---
permalink: sg6000/automating-configuration-of-storagegrid.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, automate, automating, automation, automatic, configuration, configure 
summary: グリッドノードを導入したら、 StorageGRID システムの設定を自動化できます。 
---
= StorageGRID の設定を自動化
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッドノードを導入したら、 StorageGRID システムの設定を自動化できます。

.必要なもの
* インストールアーカイブにある次のファイルの場所を確認しておきます。
+
|===
| ファイル名 | 説明 


 a| 
「 configure -storagegrid.py 」があります
 a| 
設定を自動化するための Python スクリプト



 a| 
「 configure -storagegrid-sample.json
 a| 
スクリプトで使用するサンプル構成ファイル



 a| 
「 configure -storagegrid-bank.json 」
 a| 
スクリプトで使用する空の構成ファイルです

|===
* 構成ファイル configure -storagegrid.json を作成しました。このファイルを作成するには、サンプル構成ファイル（「 configure -storagegrid-sample.json 」）または空の構成ファイル（「 configure -storagegridBlank.json 」）を変更します。


configure -storagegrid.py Python スクリプトと、 configure -storagegrid.json 構成ファイルを使用して、 StorageGRID システムの設定を自動化できます。


NOTE: また、 Grid Manager またはインストール API を使用してシステムを設定することもできます。

.手順
. Python スクリプトを実行するために使用する Linux マシンにログインします。
. インストールアーカイブを展開したディレクトリに移動します。
+
例： +`cd StorageGRID -Webscale --_version/platform_`

+
ここで '_platform_` は 'debs'rps`'vSphere' です

. Python スクリプトを実行し、作成した構成ファイルを使用します。
+
例：

+
[listing]
----
./configure-storagegrid.py ./configure-storagegrid.json --start-install
----


リカバリ・パッケージの .zip ファイルは ' 構成プロセス中に生成され ' インストールおよび構成プロセスを実行しているディレクトリにダウンロードされますグリッドノードで障害が発生した場合に StorageGRID システムをリカバリできるようにするために、リカバリパッケージファイルをバックアップする必要があります。たとえば、バックアップされたセキュアなネットワーク上の場所や、安全なクラウドストレージ上の場所にコピーします。


IMPORTANT: リカバリパッケージファイルには StorageGRID システムからデータを取得するための暗号キーとパスワードが含まれているため、安全に保管する必要があります。

ランダムなパスワードを生成するように指定した場合は、「 passwords.txt 」ファイルを抽出し、 StorageGRID システムへのアクセスに必要なパスワードを探す必要があります。

[listing]
----
######################################################################
##### The StorageGRID "recovery package" has been downloaded as: #####
#####           ./sgws-recovery-package-994078-rev1.zip          #####
#####   Safeguard this file as it will be needed in case of a    #####
#####                 StorageGRID node recovery.                 #####
######################################################################
----
StorageGRID システムがインストールおよび設定されると、確認メッセージが表示されます。

[listing]
----
StorageGRID has been configured and installed.
----