---
permalink: sg6000/configuring-snmp-settings-for-sg6000-cn-controller.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, SNMP, configure, setup, set up, sg6000-cn 
summary: ハードウェアの SNMP の設定に精通している場合は、 BMC インターフェイスを使用して SG6000-CN コントローラの SNMP 設定を行うことができます。セキュリティで保護されたコミュニティストリングを指定し、 SNMP トラップを有効にし、 SNMP の送信先を最大 5 つ指定できます。 
---
= SG6000-CN コントローラの SNMP を設定します
:icons: font
:imagesdir: ../media/


[role="lead"]
ハードウェアの SNMP の設定に精通している場合は、 BMC インターフェイスを使用して SG6000-CN コントローラの SNMP 設定を行うことができます。セキュリティで保護されたコミュニティストリングを指定し、 SNMP トラップを有効にし、 SNMP の送信先を最大 5 つ指定できます。

.必要なもの
* BMC ダッシュボードへのアクセス方法を確認しておく必要があります。
* SNMPv1-v2c 機器の SNMP 設定経験が必要です。



NOTE: この手順 で作成された BMC 設定は、 SG6000-CN に障害が発生して交換する必要がある場合は保持されないことがあります。適用したすべての設定を記録し、必要に応じてハードウェアの交換後に簡単に再適用できるようにします。

.手順
. BMC ダッシュボードで、 * Settings * > * SNMP Settings * を選択します。
. SNMP 設定ページで、 * SNMP V1/V2* を有効にするを選択し、読み取り専用コミュニティストリングと読み取り / 書き込みコミュニティストリングを指定します。
+
読み取り専用コミュニティストリングは、ユーザ ID やパスワードのようなものです。侵入者がネットワーク設定に関する情報を取得できないようにするには、この値を変更する必要があります。読み取り / 書き込みコミュニティストリングは、不正な変更からデバイスを保護します。

. 必要に応じて、 * トラップを有効にする * を選択し、必要な情報を入力します。
+

IMPORTANT: IP アドレスを使用して、各 SNMP トラップの送信先 IP を入力します。完全修飾ドメイン名はサポートされません。

+
SG6000-CN コントローラが異常な状態になったときに SNMP コンソールにすぐに通知を送信するには、トラップを有効にします。トラップは、さまざまなコンポーネントや温度のしきい値のハードウェア障害を示している場合があります。

. 必要に応じて、 [ テストトラップの送信 ] をクリックして設定をテストします。
. 設定が正しい場合は、 * 保存 * をクリックします。

