---
permalink: sg6000/index.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, overview, models, features 
summary: StorageGRID SG6000 アプライアンスは、 StorageGRID システムにおいてストレージノードとして機能する、ストレージとコンピューティングを統合したプラットフォームです。これらのアプライアンスは、アプライアンスストレージノードと仮想ストレージノードを組み合わせたハイブリッドグリッド環境で使用できます（ソフトウェアベース）。 
---
= SG6000 アプライアンス：概要
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID SG6000 アプライアンスは、 StorageGRID システムにおいてストレージノードとして機能する、ストレージとコンピューティングを統合したプラットフォームです。これらのアプライアンスは、アプライアンスストレージノードと仮想（ソフトウェアベース）ストレージノードを組み合わせたハイブリッドグリッド環境で使用できます。

SG6000 アプライアンスには次の機能があります。

* 次の 2 つのモデルがあります。
+
** SG6060 には 60 本のドライブが含まれ、拡張シェルフをサポートします。
** SGF6024 は、 24 本のソリッドステートドライブ（ SSD ）を提供します。


* StorageGRID ストレージノードのストレージ要素とコンピューティング要素を統合します。
* ストレージノードの導入と設定を簡易化するために、 StorageGRID アプライアンスインストーラが搭載されています。
* ストレージコントローラとドライブを管理および監視するための SANtricity System Manager が搭載されています。
* コンピューティングコントローラのハードウェアを監視および診断するためのベースボード管理コントローラ（ BMC ）が搭載されています。
* StorageGRID のグリッドネットワークとクライアントネットワークとの 10GbE または 25GbE 接続を最大 4 つサポートします。
* 連邦情報処理標準（ FIPS ）ドライブに対応しています。これらのドライブを SANtricity System Manager のドライブセキュリティ機能と併用すると、データへの不正アクセスを防止できます。

