---
permalink: sg6000/installation-and-deployment-overview.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, Installation, deployment, Install, deploy, Installing, deploying 
summary: StorageGRID ストレージアプライアンスは StorageGRID の初回導入時に設置することも、後日拡張の一環として追加することもできます。リカバリ処理の一環としてアプライアンスストレージノードの設置が必要となる場合もあります。 
---
= インストールと導入の概要
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID ストレージアプライアンスは StorageGRID の初回導入時に設置することも、後日拡張の一環として追加することもできます。リカバリ処理の一環としてアプライアンスストレージノードの設置が必要となる場合もあります。

StorageGRID システムが、必要なバージョンの StorageGRID ソフトウェアを使用している。

|===
| アプライアンス | 必要な StorageGRID のバージョン 


 a| 
SG6060 に拡張シェルフがない
 a| 
11.1.1 以降



 a| 
拡張シェルフを備えた SG6060 （ 1 台または 2 台）
 a| 
11.3 以降

* 注： * 初期導入後に拡張シェルフを追加する場合は、バージョン 11.4 以降を使用する必要があります。



 a| 
SGF6024
 a| 
11.3 以降

|===


== インストールと導入のタスク

StorageGRID システムに StorageGRID ストレージアプライアンスを追加するには、主に次の 4 つの手順を実行します。

. 設置の準備：
+
** 設置場所の準備
** 開梱と内容の確認
** 追加機器および工具の入手方法
** IP アドレスとネットワーク情報を収集しています
** オプション：すべてのアプライアンスデータを暗号化する場合は、外部キー管理サーバ（ KMS ）を設定します。外部キー管理の詳細については、 StorageGRID の管理手順を参照してください。


. ハードウェアの設置
+
** ハードウェアの登録
** キャビネットまたはラックへのアプライアンスの設置
** ドライブを取り付けます
** オプションの拡張シェルフの設置（モデル SG6060 のみ、最大 2 台の拡張シェルフ）
** アプライアンスのケーブル接続
** 電源コードの接続と電源の投入
** ブート時のステータスコードの確認


. ハードウェアの設定
+
** SANtricity System Manager にアクセスして、 SANtricity システムマネージャを設定します
** StorageGRID アプライアンスインストーラへのアクセス、ストレージコントローラの管理ポート 1 の静的 IP アドレスの設定、および StorageGRID ネットワークへの接続に必要なリンクとネットワーク IP の設定を行います
** SG6000-CN コントローラのベースボード管理コントローラ（ BMC ）インターフェイスへのアクセス
** オプション：外部 KMS を使用してアプライアンスデータを暗号化する場合は、ノード暗号化を有効にします。
** オプション： RAID モードを変更する


. アプライアンスをストレージノードとして導入する：
+
|===
| タスク | 手順 


 a| 
新しい StorageGRID システムにアプライアンスストレージノードを導入する
 a| 
xref:deploying-appliance-storage-node.adoc[アプライアンスストレージノードを導入する]



 a| 
既存の StorageGRID システムへのアプライアンスストレージノードの追加
 a| 
StorageGRID システムの拡張手順



 a| 
ストレージノードのリカバリ処理の一環としてアプライアンスストレージノードを導入する
 a| 
リカバリとメンテナンスの手順

|===


xref:preparing-for-installation.adoc[設置を準備（ SG6000 ）]

xref:installing-hardware.adoc[ハードウェア（ SG6000 ）を設置]

xref:configuring-hardware.adoc[ハードウェア（ SG6000 ）の設定]

xref:../expand/index.adoc[グリッドを展開します]

xref:../maintain/index.adoc[リカバリとメンテナンス]

xref:../admin/index.adoc[StorageGRID の管理]
