---
permalink: sg6000/optional-changing-raid-mode-sg6000-only.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, raid, raid mode, change, changing, modify, DDP, ddp16, raid6 
summary: アプライアンスでは、ストレージとリカバリの要件に応じて別の RAID モードに変更できます。モードを変更できるのは、アプライアンスストレージノードを導入する前だけです。 
---
= オプション： RAID モードを変更（ SG6000 のみ）
:icons: font
:imagesdir: ../media/


[role="lead"]
アプライアンスでは、ストレージとリカバリの要件に応じて別の RAID モードに変更できます。モードを変更できるのは、アプライアンスストレージノードを導入する前だけです。

.必要なもの
* StorageGRID に接続できるクライアントを使用している必要があります。
* クライアントにはがあります xref:../admin/web-browser-requirements.adoc[サポートされている Web ブラウザ]。


アプライアンスをストレージノードとして導入する前に、次のいずれかのボリューム設定オプションを選択できます。

* * DDP * ：データドライブ 8 本につきパリティドライブを 2 本使用します。すべてのアプライアンスに推奨されるデフォルトのモードです。RAID6 よりもシステムパフォーマンスに優れ、ドライブ障害が発生したあとのリビルド時間も短く、管理も簡単です。
* * DDP16 * ：このモードはデータドライブ 16 本につきパリティドライブを 2 本使用するため、 DDP よりもストレージ効率が高くなります。RAID6 よりもシステムパフォーマンスに優れ、ドライブ障害が発生したあとのリビルド時間も短く、管理も簡単です。ストレージ効率は RAID6 と同等です。DDP16 モードを使用するには、構成にドライブが 20 本以上含まれている必要があります。ドロワー損失からの保護は提供しません。
* *RAID6 *: このモードは 16 台以上のデータドライブごとに 2 本のパリティドライブを使用します。RAID 6 モードを使用するには、構成にドライブが 20 本以上含まれている必要があります。DDP よりもアプライアンスのストレージ効率を上げることができますが、ほとんどの StorageGRID 環境では推奨されません。



IMPORTANT: ボリュームがすでに構成されている場合や StorageGRID が事前にインストールされている場合に RAID モードを変更すると、ボリュームが削除されて置き換えられます。対象となったボリュームのデータはすべて失われます。

.手順
. ブラウザを開き、アプライアンスのコンピューティングコントローラの IP アドレスのいずれかを入力します。
+
「 * https://_Controller_IP_:8443*` 」と入力します

+
「 _Controller_IP_` 」は、 3 つの StorageGRID ネットワークのいずれか上のコンピューティング・コントローラ（ストレージ・コントローラではない）の IP アドレスです。

+
StorageGRID アプライアンスインストーラのホームページが表示されます。

. 「 * アドバンスト * 」 > 「 * RAID モード * 」の順に選択します。
. [Configure RAID Mode*] ページで、 [Mode] ドロップダウンリストから目的の RAID モードを選択します。
. [ 保存（ Save ） ] をクリックします。


http://mysupport.netapp.com/info/web/ECMP1658252.html["NetApp E シリーズシステムのドキュメントのサイト"^]
