---
permalink: sg6000/replacing-sg6000-cn-controller.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, Replacing, replace, sg6000-cn, controller, remove, removing, removal, install, installing, installation 
summary: SG6000-CN コントローラが適切に機能しない場合や障害が発生した場合は、交換が必要となることがあります。 
---
= SG6000-CN コントローラを交換します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SG6000-CN コントローラが適切に機能しない場合や障害が発生した場合は、交換が必要となることがあります。

.必要なもの
* 交換するコントローラと同じパーツ番号の交換用コントローラを用意しておきます。
* コントローラに接続する各ケーブルを識別するためのラベルを用意しておきます。
* データセンター内で交換するコントローラの物理的な場所を確認しておきます。
+
xref:locating-controller-in-data-center.adoc[データセンターでコントローラを探します]



.このタスクについて
SG6000-CN コントローラを交換すると、アプライアンスストレージノードにアクセスできなくなります。SG6000-CN コントローラが十分に機能している場合は、この手順 の開始時に通常の方法でシャットダウンを実行できます。


NOTE: StorageGRID ソフトウェアをインストールする前にコントローラを交換すると、この手順 の完了後すぐに StorageGRID アプライアンスインストーラにアクセスできない場合があります。アプライアンスと同じサブネット上の他のホストから StorageGRID アプライアンスインストーラにアクセスすることはできますが、他のサブネット上のホストからはアクセスできません。この状態は 15 分以内に（元のコントローラのいずれかの ARP キャッシュエントリがタイムアウトした時点で）自動的に解消されます。あるいは、古い ARP キャッシュエントリをローカルルータまたはゲートウェイから手動でパージすれば、すぐにこの状態を解消できます。

.手順
. アプライアンスの現在の設定を表示して記録します。
+
.. 交換するアプライアンスにログインします。
+
... 次のコマンドを入力します。 ssh admin@_grid_node_name
... 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
... root に切り替えるには、次のコマンドを入力します
... 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
+
root としてログインすると、プロンプトは「 $` 」から「 #」 に変わります。



.. 入力するコマンド `*run-host-command ipmitool lan print*` をクリックして、アプライアンスの現在のBMC設定を表示します。


. SG6000-CN コントローラが動作していて通常の方法でシャットダウンできる場合は、 SG6000-CN コントローラをシャットダウンします。
+
xref:shutting-down-sg6000-cn-controller.adoc[SG6000-CN コントローラをシャットダウンします]

. このStorageGRID アプライアンスのいずれかのネットワークインターフェイスがDHCP用に設定されている場合は、交換用アプライアンスのMACアドレスを参照するために、DHCPサーバの永続的なDHCPリース割り当てを更新する必要があります。この更新により、アプライアンスに想定されるIPアドレスが割り当てられます。
+
.. SG6000-CN コントローラの前面にある MAC アドレスラベルを確認し、管理ネットワークポートの MAC アドレスを特定します。
+
[NOTE]
====
MAC アドレスラベルには、 BMC 管理ポートの MAC アドレスが記載されています。

管理ネットワークポートの MAC アドレスを特定するには、ラベルに記載された 16 進数に * 2 * を追加する必要があります。たとえば、ラベルに記載されている MAC アドレスの末尾が * 09 * の場合、管理ポートの MAC アドレスの末尾は * 0B * となります。ラベルに記載された MAC アドレスの末尾が * （ _y_） FF* の場合、管理ポートの MAC アドレスの末尾は * （ _y_+1 ） 01 * となります。この計算を簡単に行うには、 Windows で Calculator を開き、 Programmer モードに設定して Hex を選択し、 MAC アドレスを入力してから、 *+2=* と入力します。

====
.. 取り外したコントローラの DNS / ネットワークおよび IP アドレスを交換用コントローラの MAC アドレスと関連付けるよう、ネットワーク管理者に依頼します。
+

IMPORTANT: 交換用コントローラに電源を投入する前に、元のコントローラのすべての IP アドレスが更新されたことを確認する必要があります。そうしないと、コントローラのブート時に新しい DHCP IP アドレスが取得されて、 StorageGRID に再接続できなくなることがあります。この手順では、コントローラに接続されているすべての StorageGRID ネットワークを環境 接続します。

+

NOTE: 元のコントローラが静的 IP アドレスを使用していた場合は、取り外したコントローラの IP アドレスが自動的に新しいコントローラで使用されます。



. SG6000-CN コントローラを取り外して交換します。
+
.. ケーブルにラベルを付けてから、ケーブルと SFP+ または SFP28 トランシーバを取り外します。
+

IMPORTANT: パフォーマンスの低下を防ぐために、ケーブルをねじったり、折り曲げたり、はさんだり、踏みつけたりしないでください。

.. 障害が発生したコントローラをキャビネットまたはラックから取り外します。
.. 交換用コントローラをキャビネットまたはラックに取り付けます。
.. ケーブルと SFP+ または SFP28 トランシーバを交換します。
.. コントローラの電源を入れ、コントローラの LED とブート時のコードを監視します。


. コントローラを交換したアプライアンスでキー管理サーバ（KMS）を使用してデータを暗号化していた場合は、ノードをグリッドに追加する前に追加の設定が必要になることがあります。ノードが自動的にグリッドに追加されない場合は、次の設定が新しいコントローラに転送されたことを確認し、想定される設定と異なる設定があれば手動で設定します。
+
** link:../sg6000/configuring-storagegrid-connections.html["StorageGRID 接続を設定します"]
** link:../admin/kms-overview-of-kms-and-appliance-configuration.html#set-up-the-appliance["アプライアンスのノード暗号化を設定します"]


. コントローラを交換したアプライアンスにログインします。
+
.. 次のコマンドを入力します。 ssh admin@_grid_node_name
.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
.. root に切り替えるには、次のコマンドを入力します
.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。


. アプライアンスのBMCネットワーク接続をリストアします。次の 2 つのオプションがあります。
+
** 静的IP、ネットマスク、およびゲートウェイを使用します
** DHCPを使用して、IP、ネットマスク、およびゲートウェイを取得します
+
... 静的IP、ネットマスク、およびゲートウェイを使用するようにBMCの設定をリストアするには、次のコマンドを入力します。
+
`*run-host-command ipmitool lan set 1 ipsrc static*`

+
`*run-host-command ipmitool lan set 1 ipaddr _Appliance_IP_*`

+
`*run-host-command ipmitool lan set 1 netmask _Netmask_IP_*`

+
`*run-host-command ipmitool lan set 1 defgw ipaddr _Default_gateway_*`

... DHCPを使用してIP、ネットマスク、およびゲートウェイを取得するようにBMCの設定を復元するには、次のコマンドを入力します。
+
`*run-host-command ipmitool lan set 1 ipsrc dhcp*`





. BMCネットワーク接続をリストアしたら、BMCインターフェイスに接続して監査し、追加で適用したBMCのカスタム設定をリストアします。たとえば、SNMPトラップの送信先やEメール通知の設定を確認する必要があります。を参照してください link:configuring-bmc-interface-sg6000.html["BMCインターフェイスの設定"]。
. アプライアンスノードが Grid Manager に表示され、アラートが表示されていないことを確認します。


.関連情報
xref:sg6000-cn-installing-into-cabinet-or-rack.adoc[SG6000-CN ：キャビネットまたはラックに設置します]

xref:viewing-status-indicators-and-buttons-on-sg6000-cn-controller.adoc[SG6000-CN コントローラのステータスインジケータとボタンを表示します]

xref:viewing-boot-up-codes-for-sg6000-cn-controller.adoc[SG6000-CN コントローラのブート時のコードを確認します]
