---
permalink: sg6000/replacing-hardware-components-in-storage-controller-shelf.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, Replacing, replace, hardware, components, remove, removing, removal, install, installing, installation, storage controller shelf, Battery, Drive, Power canister, power supply, Fan canister, fan, Drive drawer 
summary: ハードウェアの問題が発生した場合は、ストレージコントローラシェルフのコンポーネントの交換が必要となることがあります。 
---
= ストレージコントローラシェルフのハードウェアコンポーネントを交換します
:icons: font
:imagesdir: ../media/


[role="lead"]
ハードウェアの問題が発生した場合は、ストレージコントローラシェルフのコンポーネントの交換が必要となることがあります。

.必要なもの
* E シリーズハードウェアの交換用手順 を用意しておきます。
* データセンターでストレージシェルフのハードウェアコンポーネントを交換するストレージアプライアンスを物理的に配置しておきます。
+
xref:locating-controller-in-data-center.adoc[データセンターでコントローラを探します]



ストレージコントローラのバッテリを交換するには、ストレージコントローラの交換手順の説明を参照してください。これらの手順では、アプライアンスからのコントローラの取り外し、コントローラからのバッテリの取り外し、バッテリの取り付け、およびコントローラの交換の方法について説明します。

コントローラシェルフの他の Field Replaceable Unit （ FRU ；フィールド交換可能ユニット）に関する手順については、システムメンテナンスに関する E シリーズの手順書を参照してください。

|===
| FRU | 手順を参照してください 


 a| 
バッテリー
 a| 
StorageGRID （以下の手順）：ストレージコントローラの交換



 a| 
ドライブ
 a| 
E シリーズ：

* ドライブの交換（ 60 ドライブ）
* ドライブの交換（ 12 ドライブまたは 24 ドライブ）




 a| 
電源キャニスター
 a| 
E シリーズ

* 電源キャニスターの交換（ 60 ドライブ）
* 電源装置の交換（ 12 ドライブまたは 24 ドライブ）




 a| 
ファンキャニスター（ 60 ドライブシェルフのみ）
 a| 
E シリーズ：ファンキャニスターの交換（ 60 ドライブ）



 a| 
ドライブドロワー（ 60 ドライブシェルフのみ）
 a| 
E シリーズ：ドライブドロワーの交換（ 60 ドライブ）

|===
http://mysupport.netapp.com/info/web/ECMP1658252.html["NetApp E シリーズシステムのドキュメントのサイト"^]

xref:replacing-storage-controller-sg6000.adoc[ストレージコントローラを交換します]
