---
permalink: sg6000/replacing-sg6000-cn-controller.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, Replacing, replace, sg6000-cn, controller, remove, removing, removal, install, installing, installation 
summary: SG6000-CN コントローラが適切に機能しない場合や障害が発生した場合は、交換が必要となることがあります。 
---
= SG6000-CN コントローラを交換します
:icons: font
:imagesdir: ../media/


[role="lead"]
SG6000-CN コントローラが適切に機能しない場合や障害が発生した場合は、交換が必要となることがあります。

.必要なもの
* 交換するコントローラと同じパーツ番号の交換用コントローラを用意しておきます。
* コントローラに接続する各ケーブルを識別するためのラベルを用意しておきます。
* データセンター内で交換するコントローラの物理的な場所を確認しておきます。
+
xref:locating-controller-in-data-center.adoc[データセンターでコントローラを探します]



SG6000-CN コントローラを交換すると、アプライアンスストレージノードにアクセスできなくなります。SG6000-CN コントローラが十分に機能している場合は、この手順 の開始時に通常の方法でシャットダウンを実行できます。


NOTE: StorageGRID ソフトウェアをインストールする前にコントローラを交換すると、この手順 の完了後すぐに StorageGRID アプライアンスインストーラにアクセスできない場合があります。アプライアンスと同じサブネット上の他のホストから StorageGRID アプライアンスインストーラにアクセスすることはできますが、他のサブネット上のホストからはアクセスできません。この状態は 15 分以内に（元のコントローラのいずれかの ARP キャッシュエントリがタイムアウトした時点で）自動的に解消されます。あるいは、古い ARP キャッシュエントリをローカルルータまたはゲートウェイから手動でパージすれば、すぐにこの状態を解消できます。

.手順
. SG6000-CN コントローラが動作していて通常の方法でシャットダウンできる場合は、 SG6000-CN コントローラをシャットダウンします。
+
xref:shutting-down-sg6000-cn-controller.adoc[SG6000-CN コントローラをシャットダウンします]

. 次のどちらかの方法を使用して、 SG6000-CN コントローラの電源がオフになっていることを確認します。
+
** コントローラ前面の電源 LED が消灯している。
** BMC インターフェイスの電源制御ページに、コントローラがオフになっていることが示されます。


. コントローラに接続されている StorageGRID ネットワークが DHCP サーバを使用している場合は、 DNS / ネットワークと IP アドレスの設定を更新します。
+
.. SG6000-CN コントローラの前面にある MAC アドレスラベルを確認し、管理ネットワークポートの MAC アドレスを特定します。
+

NOTE: MAC アドレスラベルには、 BMC 管理ポートの MAC アドレスが記載されています。+ 管理ネットワークポートの MAC アドレスを特定するには、ラベルに記載された 16 進数に * 2 * を追加する必要があります。たとえば、ラベルに記載されている MAC アドレスの末尾が * 09 * の場合、管理ポートの MAC アドレスの末尾は * 0B * となります。ラベルに記載された MAC アドレスの末尾が * （ _y_） FF* の場合、管理ポートの MAC アドレスの末尾は * （ _y_+1 ） 01 * となります。この計算を簡単に行うには、 Windows で Calculator を開き、 Programmer モードに設定して Hex を選択し、 MAC アドレスを入力してから、 *+2=* と入力します。

.. 取り外したコントローラの DNS / ネットワークおよび IP アドレスを交換用コントローラの MAC アドレスと関連付けるよう、ネットワーク管理者に依頼します。
+

IMPORTANT: 交換用コントローラに電源を投入する前に、元のコントローラのすべての IP アドレスが更新されたことを確認する必要があります。そうしないと、コントローラのブート時に新しい DHCP IP アドレスが取得されて、 StorageGRID に再接続できなくなることがあります。この手順では、コントローラに接続されているすべての StorageGRID ネットワークを環境 接続します。

+

NOTE: 元のコントローラが静的 IP アドレスを使用していた場合は、取り外したコントローラの IP アドレスが自動的に新しいコントローラで使用されます。



. SG6000-CN コントローラを取り外して交換します。
+
.. ケーブルにラベルを付けてから、ケーブルと SFP+ または SFP28 トランシーバを取り外します。
+

IMPORTANT: パフォーマンスの低下を防ぐために、ケーブルをねじったり、折り曲げたり、はさんだり、踏みつけたりしないでください。

.. 障害が発生したコントローラをキャビネットまたはラックから取り外します。
.. 交換用コントローラをキャビネットまたはラックに取り付けます。
.. ケーブルと SFP+ または SFP28 トランシーバを交換します。
.. コントローラの電源を入れ、コントローラの LED とブート時のコードを監視します。


. アプライアンスストレージノードが Grid Manager に表示され、アラームが表示されていないことを確認します。
. Grid Manager で * nodes * を選択し、ノードコントローラの BMC IP アドレスが正しいことを確認します。
+
ノードコントローラの IP アドレスが無効であるか、想定範囲に含まれていない場合は、リカバリおよびメンテナンスの手順に従って IP アドレスを再設定します。

+

NOTE: SNMP トラップの送信先や E メール通知の設定など、元のインストール時に追加のカスタマイズを適用した場合は、設定を記録して検証し、必要に応じて再適用する必要があります。

+
xref:../maintain/index.adoc[リカバリとメンテナンス]



xref:sg6000-cn-installing-into-cabinet-or-rack.adoc[SG6000-CN ：キャビネットまたはラックに設置します]

xref:viewing-status-indicators-and-buttons-on-sg6000-cn-controller.adoc[SG6000-CN コントローラのステータスインジケータとボタンを表示します]

xref:viewing-boot-up-codes-for-sg6000-cn-controller.adoc[SG6000-CN コントローラのブート時のコードを確認します]
