---
permalink: audit/audit-message-format.html 
sidebar: sidebar 
keywords: storagegrid, audit, message formats, message format 
summary: StorageGRID システム内でやり取りされる監査メッセージには、すべてのメッセージに共通の標準情報と、報告対象のイベントまたはアクティビティを説明する固有のコンテンツが含まれます。 
---
= 監査メッセージの形式
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID システム内でやり取りされる監査メッセージには、すべてのメッセージに共通の標準情報と、報告対象のイベントまたはアクティビティを説明する固有のコンテンツが含まれます。

「 audit-explain 」および「 audit-sum 」ツールで提供されるサマリー情報が不十分な場合は、このセクションを参照して、すべての監査メッセージの一般的な形式を理解してください。

以下は、監査ログファイルに記録されている監査メッセージの例です。

[listing]
----
2014-07-17T03:50:47.484627
[AUDT:[RSLT(FC32):VRGN][AVER(UI32):10][ATIM(UI64):1405569047484627][ATYP(FC32):SYSU][ANID(UI32):11627225][AMID(FC32):ARNI][ATID(UI64):9445736326500603516]]
----
各監査メッセージには、一連の属性要素で構成されます。文字列全体が括弧 (`[]') で囲まれ、文字列内の各属性要素には次の特性があります。

* 角かっこ [] で囲まれています
* 監査メッセージを示す文字列「 AUDT 」で始まる
* 前後に区切り記号（カンマやスペース）がない
* 改行文字で終了しました \n


各要素には、次の形式で報告される属性コード、データ型、および値が含まれます。

[listing]
----
[ATTR(type):value][ATTR(type):value]...
[ATTR(type):value]\n
----
メッセージ内の属性要素の数は、メッセージのイベントタイプによって異なります。属性要素は特定の順序でリストされません。

次に、属性要素について説明します。

* 「 ATTR' 」は報告される属性の 4 文字のコードです。すべての監査メッセージに共通する属性とイベント固有の属性があります。
* 「 type 」は、 UI64 、 FC32 など、値のプログラミング・データ・タイプの 4 文字の識別子です。型は括弧で囲まれます
* 「 value 」は属性の内容で、通常は数値またはテキスト値です。値は常にコロン (`:') の後に続きます。データ型 CSTR の値は二重引用符で囲まれます。


xref:using-audit-explain-tool.adoc[audit-explain ツールを使用してください]

xref:using-audit-sum-tool.adoc[audit-sum ツールを使用します]

xref:audit-messages-main.adoc[監査メッセージ]

xref:common-elements-in-audit-messages.adoc[監査メッセージの共通要素]

xref:data-types.adoc[データ型]

xref:audit-message-examples.adoc[監査メッセージの例]
