---
permalink: audit/llst-location-lost.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, LLST, Location Lost 
summary: このメッセージは、オブジェクトコピーの場所（レプリケートまたはイレイジャーコーディング）が見つからない場合に生成されます。 
---
= LLST ：ロケーションが失われました
:icons: font
:imagesdir: ../media/


[role="lead"]
このメッセージは、オブジェクトをコピー（レプリケートまたはイレイジャーコーディング）する場所が見つからない場合に生成されます。

|===
| コード | フィールド | 説明 


 a| 
CBIL
 a| 
CBID
 a| 
影響を受ける CBID 。



 a| 
NOID
 a| 
ソースノード ID
 a| 
場所が失われたノード ID 。



 a| 
UUID
 a| 
Universally Unique ID の略
 a| 
StorageGRID システムでの該当オブジェクトの識別子。



 a| 
ECPR
 a| 
イレイジャーコーディングプロファイル
 a| 
イレイジャーコーディングされたオブジェクトデータ用。使用されているイレイジャーコーディングプロファイルの ID です。



 a| 
LTYP
 a| 
保管場所タイプ
 a| 
CLDI （ Online ）：レプリケートされたオブジェクトデータ用

CLEC （ Online ）：イレイジャーコーディングされたオブジェクトデータ用

CLNL （ Nearline ）：アーカイブされたレプリケートオブジェクトデータ用



 a| 
PCLD
 a| 
レプリケートオブジェクトへのパス
 a| 
損失オブジェクトデータのディスクの場所への完全なパス。LTYP の値が CLDI （つまりレプリケートオブジェクトの場合）の場合にのみ返されます。

/var/local/rangedb/2/p/13/13/00oJs6X% ｛ h ｛ u ） SeUFxE@ の形式をとります



 a| 
RSLT
 a| 
結果
 a| 
常に NONE 。RSLT は必須のメッセージフィールドですが、このメッセージには該当しません。このメッセージがフィルタリングされないように、 SUCS ではなく NONE が使用されます。



 a| 
TsRC
 a| 
トリガ元
 a| 
USER ：ユーザがトリガーしました

SYST ：システムがトリガーされました

|===