---
permalink: audit/sput-s3-put.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SPUT, S3 PUT 
summary: S3 クライアントが PUT トランザクションを実行すると、新しいオブジェクトまたはバケットを作成する要求が送信されます。このメッセージは、トランザクションが成功した場合にサーバによって出力されます。 
---
= SPUT ： S3 PUT
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 クライアントが PUT トランザクションを実行すると、新しいオブジェクトまたはバケットを作成する要求が送信されます。このメッセージは、トランザクションが成功した場合にサーバによって出力されます。

|===
| コード | フィールド | 説明 


 a| 
CBID
 a| 
Content Block Identifier の略
 a| 
要求されたコンテンツブロックの一意の識別子。CBID が不明な場合、このフィールドは 0 に設定されます。バケットに対する処理ではこのフィールドは記録されません。



 a| 
CMP
 a| 
コンプライアンス設定
 a| 
バケットを作成する際に使用された準拠設定（ PUT Bucket 要求にこの設定がある場合、最初の 1024 文字に切り詰められます）。



 a| 
CNCH
 a| 
整合性制御ヘッダー
 a| 
要求に Consistency-Control HTTP 要求ヘッダーが存在する場合は、その値。



 a| 
CNID
 a| 
接続識別子
 a| 
TCP / IP 接続の一意のシステム識別子。



 a| 
CSIZ
 a| 
コンテンツサイズ（ Content Size ）
 a| 
読み出されたオブジェクトのサイズ（バイト単位）。バケットに対する処理ではこのフィールドは記録されません。



 a| 
HTRH
 a| 
HTTP 要求ヘッダー
 a| 
設定時に選択した、ログに記録される HTTP 要求ヘッダーの名前と値のリスト。

* 注意 :*`X-Forwarded-For` は、要求に存在し、 'X-Forwarded-For' 値が要求送信者の IP アドレス (SAIP 監査フィールド ) と異なる場合に自動的に含められます。



 a| 
LKEN
 a| 
オブジェクトロックが有効になりました
 a| 
PUT Bucket 要求に要求ヘッダー「 x-amz-bucketobject-lock-enabled 」が存在する場合、その値



 a| 
LKLH
 a| 
オブジェクトロックリーガルホールド
 a| 
PUT Object 要求に要求ヘッダーの「 x-amz-object-lock-legal hold' 」の値が存在する場合



 a| 
LKMD
 a| 
オブジェクトロック保持モード
 a| 
PUT Object 要求に要求ヘッダーの「 x-amz-object-lock-mode 」が存在する場合は、その値。



 a| 
LKRU
 a| 
オブジェクトロック終了日まで保持
 a| 
PUT Object 要求に要求ヘッダーの「 x-amz-object-lock-retain-date 」の値が存在する場合



 a| 
MTME
 a| 
最終変更時刻
 a| 
オブジェクトが最後に変更された日時を示す Unix タイムスタンプ（マイクロ秒）。



 a| 
RSLT
 a| 
結果コード
 a| 
PUT トランザクションの結果。常に次の結果になります。

SUCS ：成功しました



 a| 
S3AI
 a| 
S3 テナントアカウント ID （要求の送信者）
 a| 
要求を送信したユーザのテナントアカウント ID 。空の値は匿名アクセスであることを示します。



 a| 
S3AK
 a| 
S3 アクセスキー ID （要求の送信者）
 a| 
要求を送信したユーザのハッシュ済み S3 アクセスキー ID 。空の値は匿名アクセスであることを示します。



 a| 
S3BK
 a| 
S3 バケット
 a| 
S3 バケット名。



 a| 
S3KY
 a| 
S3KY
 a| 
バケット名を除く S3 キーの名前。バケットに対する処理ではこのフィールドは記録されません。



 a| 
S3SR
 a| 
S3 サブリソース
 a| 
必要に応じて、処理対象のバケットまたはオブジェクトサブリソース。



 a| 
SACC
 a| 
S3 テナントアカウント名（要求の送信者）
 a| 
要求を送信したユーザのテナントアカウントの名前。匿名の要求の場合は空です。



 a| 
saip
 a| 
IP アドレス（要求送信者）
 a| 
要求を送信したクライアントアプリケーションの IP アドレス。



 a| 
SBAC
 a| 
S3 テナントアカウント名（バケット所有者）
 a| 
バケット所有者のテナントアカウント名。クロスアカウントアクセスまたは匿名アクセスの識別に使用します。



 a| 
SBAI
 a| 
S3 テナントアカウント ID （バケット所有者）
 a| 
ターゲットバケットの所有者のテナントアカウント ID 。クロスアカウントアクセスまたは匿名アクセスの識別に使用します。



 a| 
SRCF
 a| 
サブリソースの設定
 a| 
新しいサブリソース設定（最初の 1024 文字に切り詰められます）。



 a| 
サスペンション
 a| 
S3 ユーザの URN （要求の送信者）
 a| 
要求を送信しているユーザのテナントアカウント ID とユーザ名。ローカルユーザまたは LDAP ユーザです。例： `urn:sgws ： identity ：：： 03393893651506583485 ： root

匿名の要求の場合は空です。



 a| 
時間
 a| 
時間
 a| 
要求の合計処理時間（マイクロ秒）。



 a| 
TLIP
 a| 
信頼できるロードバランサの IP アドレス
 a| 
要求が信頼できるレイヤ 7 ロードバランサによってルーティングされた場合は、ロードバランサの IP アドレス。



 a| 
ULID
 a| 
ID をアップロードします
 a| 
Complete Multipart Upload 処理の SPUT メッセージのみに含まれます。すべてのパーツがアップロードされ、アセンブルされたことを示します。



 a| 
UUID
 a| 
Universally Unique Identifier の略
 a| 
StorageGRID システム内でのオブジェクトの識別子。



 a| 
VSID
 a| 
バージョン ID
 a| 
バージョン管理されたバケットで作成された新しいオブジェクトのバージョン ID 。バージョン管理されていないバケット内のバケットやオブジェクトに対する処理には、このフィールドは含まれません。



 a| 
VSST
 a| 
バージョン管理の状態
 a| 
バケットの新しいバージョン管理状態。「 enabled 」または「 suspended 」のどちらかです。 オブジェクトに関する処理ではこのフィールドは記録されません。

|===