---
permalink: audit/wdel-swift-delete.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, WDEL, Swift DELETE 
summary: Swift クライアントが DELETE トランザクションを実行すると、指定したオブジェクトまたはコンテナを削除する要求が送信されます。このメッセージは、トランザクションが成功した場合にサーバによって出力されます。 
---
= WDEL ： Swift の削除
:icons: font
:imagesdir: ../media/


[role="lead"]
Swift クライアントが DELETE トランザクションを実行すると、指定したオブジェクトまたはコンテナを削除する要求が送信されます。このメッセージは、トランザクションが成功した場合にサーバによって出力されます。

[cols="1a,1a,4a"]
|===
| コード | フィールド | 説明 


 a| 
CBID
 a| 
Content Block Identifier の略
 a| 
要求されたコンテンツブロックの一意の識別子。CBID が不明な場合、このフィールドは 0 に設定されます。コンテナに関する処理ではこのフィールドは記録されません。



 a| 
CSIZ
 a| 
コンテンツサイズ（ Content Size ）
 a| 
削除されたオブジェクトのサイズ（バイト単位）。コンテナに関する処理ではこのフィールドは記録されません。



 a| 
HTRH
 a| 
HTTP 要求ヘッダー
 a| 
設定時に選択した、ログに記録される HTTP 要求ヘッダーの名前と値のリスト。

* 注意 :*`X-Forwarded-For` は、要求に存在し、 'X-Forwarded-For' 値が要求送信者の IP アドレス (SAIP 監査フィールド ) と異なる場合に自動的に含められます。



 a| 
MTME
 a| 
最終変更時刻
 a| 
オブジェクトが最後に変更された日時を示す Unix タイムスタンプ（マイクロ秒）。



 a| 
RSLT
 a| 
結果コード
 a| 
DELETE トランザクションの結果。常に次の結果になります。

SUCS ：成功しました



 a| 
saip
 a| 
要求元クライアントの IP アドレス
 a| 
要求を送信したクライアントアプリケーションの IP アドレス。



 a| 
SgRP
 a| 
サイト（グループ）
 a| 
オブジェクトが存在する場合は、指定したサイトで削除されています。このサイトは、オブジェクトが取り込まれたサイトではありません。



 a| 
時間
 a| 
時間
 a| 
要求の合計処理時間（マイクロ秒）。



 a| 
TLIP
 a| 
信頼できるロードバランサの IP アドレス
 a| 
要求が信頼できるレイヤ 7 ロードバランサによってルーティングされた場合は、ロードバランサの IP アドレス。



 a| 
UUID
 a| 
Universally Unique Identifier の略
 a| 
StorageGRID システム内でのオブジェクトの識別子。



 a| 
WACC
 a| 
Swift アカウント ID
 a| 
StorageGRID システムによって指定された一意のアカウント ID 。



 a| 
WCON
 a| 
Swift コンテナ
 a| 
Swift コンテナ名。



 a| 
WOBJ
 a| 
Swift オブジェクト
 a| 
Swift オブジェクトの識別子。コンテナに関する処理ではこのフィールドは記録されません。



 a| 
WUSR
 a| 
Swift アカウントユーザ
 a| 
トランザクションを実行するクライアントを一意に識別する Swift アカウントのユーザ名。

|===