---
permalink: audit/wget-swift-get.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, WGET, Swift GET 
summary: Swift クライアントが GET トランザクションを実行すると、オブジェクトを読み出す、コンテナ内のオブジェクトを一覧表示する、またはアカウント内のコンテナを一覧表示する要求が送信されます。このメッセージは、トランザクションが成功した場合にサーバによって出力されます。 
---
= wget ： Swift GET
:icons: font
:imagesdir: ../media/


[role="lead"]
Swift クライアントが GET トランザクションを実行すると、オブジェクトを読み出す、コンテナ内のオブジェクトを一覧表示する、またはアカウント内のコンテナを一覧表示する要求が送信されます。このメッセージは、トランザクションが成功した場合にサーバによって出力されます。

|===
| コード | フィールド | 説明 


 a| 
CBID
 a| 
Content Block Identifier の略
 a| 
要求されたコンテンツブロックの一意の識別子。CBID が不明な場合、このフィールドは 0 に設定されます。アカウントおよびコンテナに関する処理ではこのフィールドは記録されません。



 a| 
CSIZ
 a| 
コンテンツサイズ（ Content Size ）
 a| 
読み出されたオブジェクトのサイズ（バイト単位）。アカウントおよびコンテナに関する処理ではこのフィールドは記録されません。



 a| 
HTRH
 a| 
HTTP 要求ヘッダー
 a| 
設定時に選択した、ログに記録される HTTP 要求ヘッダーの名前と値のリスト。

* 注意 :*`X-Forwarded-For` は、要求に存在し、 'X-Forwarded-For' 値が要求送信者の IP アドレス (SAIP 監査フィールド ) と異なる場合に自動的に含められます。



 a| 
RSLT
 a| 
結果コード
 a| 
GET トランザクションの結果。結果は常にです

SUCS ：成功しました



 a| 
saip
 a| 
要求元クライアントの IP アドレス
 a| 
要求を送信したクライアントアプリケーションの IP アドレス。



 a| 
時間
 a| 
時間
 a| 
要求の合計処理時間（マイクロ秒）。



 a| 
TLIP
 a| 
信頼できるロードバランサの IP アドレス
 a| 
要求が信頼できるレイヤ 7 ロードバランサによってルーティングされた場合は、ロードバランサの IP アドレス。



 a| 
UUID
 a| 
Universally Unique Identifier の略
 a| 
StorageGRID システム内でのオブジェクトの識別子。



 a| 
WACC
 a| 
Swift アカウント ID
 a| 
StorageGRID システムによって指定された一意のアカウント ID 。



 a| 
WCON
 a| 
Swift コンテナ
 a| 
Swift コンテナ名。アカウントに関する処理ではこのフィールドは記録されません。



 a| 
WOBJ
 a| 
Swift オブジェクト
 a| 
Swift オブジェクトの識別子。アカウントおよびコンテナに関する処理ではこのフィールドは記録されません。



 a| 
WUSR
 a| 
Swift アカウントユーザ
 a| 
トランザクションを実行するクライアントを一意に識別する Swift アカウントのユーザ名。

|===