---
settings:
  name: StorageGRID
  downlevel: true
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: false
  langs: ja-jp,us-en,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: StorageGRID 11.6 ドキュメント
    url: "/index.html"
  - section: release-notes
  - title: はじめに
    entries:
    - section: primer
    - section: network
  - title: アプライアンスハードウェアを設置して保守します
    entries:
    - section: sg100-1000
    - section: sg6000
    - section: sg5700
    - section: sg5600
  - title: ソフトウェアをインストールしてアップグレードする
    entries:
    - section: upgrade
    - section: rhel
    - section: ubuntu
    - section: vmware
  - title: システム管理を実行する
    entries:
    - section: admin
    - section: ilm
    - section: harden
    - section: fabricpool
  - title: StorageGRID を使用します
    entries:
    - section: tenant
    - section: s3
    - section: swift
  - title: StorageGRID を監視および保守します
    entries:
    - section: monitor
    - section: expand
    - section: maintain
    - section: audit
  - title: StorageGRID を有効にします
    url: "/storagegrid-enable.html"
  - title: その他のバージョン
    url: "/earlier-versions.html"
  - title: 法的通知
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: はじめに
    links:
    - title: リリースノート
      url: "/release-notes/index.html"
    - title: 新機能
      url: "/upgrade/whats-new.html"
    - title: グリッド入門
      url: "/primer/index.html"
    - title: ネットワークガイドライン
      url: "/network/index.html"
  - title: ハードウェアのメンテナンスをインストールします
    links:
    - title: SG100 および SG1000 サービスアプライアンス
      url: "/sg100-1000/index.html"
    - title: SG6000 ストレージアプライアンス
      url: "/sg6000/index.html"
    - title: SG5700 ストレージアプライアンス
      url: "/sg5700/index.html"
    - title: SG5600 ストレージアプライアンス
      url: "/sg5600/index.html"
  - title: アップグレードソフトウェアをインストールします
    links:
    - title: Red Hat Enterprise Linux または CentOS をインストールします
      url: "/rhel/index.html"
    - title: Ubuntu または Debian をインストールします
      url: "/ubuntu/index.html"
    - title: VMware をインストールする
      url: "/vmware/index.html"
    - title: ソフトウェアをアップグレードする
      url: "/upgrade/index.html"
  - title: グリッドを設定します
    links:
    - title: StorageGRID の管理
      url: "/admin/index.html"
    - title: ILM を使用してオブジェクトを管理する
      url: "/ilm/index.html"
    - title: システムの保護対策
      url: "/harden/index.html"
    - title: StorageGRID for FabricPool を設定します
      url: "/fabricpool/index.html"
  - title: オブジェクトを管理します
    links:
    - title: テナントアカウントを使用する
      url: "/tenant/index.html"
    - title: S3 を使用する
      url: "/s3/index.html"
    - title: Swift を使用します
      url: "/swift/index.html"
  - title: モニタメンテナンス
    links:
    - title: トラブルシューティングを監視する
      url: "/monitor/index.html"
    - title: グリッドを展開します
      url: "/expand/index.html"
    - title: リカバリメンテナンス
      url: "/maintain/index.html"
    - title: 監査ログを確認します
      url: "/audit/index.html"
  - title: デモチュートリアル
    links:
    - title: StorageGRID を有効にする方法について説明します
      url: https://docs.netapp.com/us-en/storagegrid-enable/index.html
    - title: StorageGRID ビデオライブラリ
      url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7nh2wGRA65iulXhtXwLiqrY
    - title: ネットアップラーニングサービス
      url: https://www.netapp.com/support-and-training/netapp-university/
  - title: リソースの追加
    links:
    - title: StorageGRID のサポートページ
      url: https://mysupport.netapp.com/site/products/all/details/5d9f1107e01d9c0001ee50f6/downloads-tab
    - title: ネットアップの Interoperability Matrix Tool （ IMT ）
      url: https://mysupport.netapp.com/matrix
    - title: StorageGRID ナレッジベース
      url: https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID
    - title: ネットアップのブログ
      url: https://netapp.com/blog/
    - title: ネットアップコミュニティ
      url: https://community.netapp.com/
  - title: その他のバージョン
    links:
    - title: StorageGRID 11.7ドキュメント
      url: https://docs.netapp.com/us-en/storagegrid-117/index.html
    - title: StorageGRID 11.5 のドキュメント
      url: https://docs.netapp.com/us-en/storagegrid-115/index.html
    - title: StorageGRID 11.4 ドキュメント
      url: https://docs.netapp.com/sgws-114/index.jsp
    - title: StorageGRID 11.3 のドキュメント
      url: https://docs.netapp.com/sgws-113/index.jsp
    - title: StorageGRID 11.2 のドキュメント
      url: https://docs.netapp.com/sgws-112/index.jsp
