---
permalink: upgrade/checking-systems-condition-before-upgrading-software.html 
sidebar: sidebar 
keywords: upgrade, grid tasks, firewall, ports 
summary: StorageGRID システムをアップグレードする前に、システムがアップグレードできる状態にあることを確認する必要があります。システムが正常に稼働し、すべてのグリッドノードが動作している必要があります。 
---
= システムの状態を確認します
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID システムをアップグレードする前に、システムがアップグレードできる状態にあることを確認する必要があります。システムが正常に稼働し、すべてのグリッドノードが動作している必要があります。

.手順
. を使用して Grid Manager にサインインします xref:../admin/web-browser-requirements.adoc[サポートされている Web ブラウザ]。
. アクティブなアラートがないかを確認し、ある場合は解決します。
+
特定のアラートの詳細については、を参照してください xref:../monitor/alerts-reference.adoc[アラート一覧]。

. 競合するグリッドタスクがアクティブまたは保留中でないことを確認します。
+
.. サポート * > * ツール * > * グリッドトポロジ * を選択します。
.. _site * > * _primary Admin Node_* > * CMN * > * Grid Tasks * > * Configuration * を選択します。
+
情報ライフサイクル管理評価（ ILME ）タスクは、ソフトウェアのアップグレードと同時に実行できる唯一のグリッドタスクです。

.. 他のグリッドタスクがアクティブまたは保留中の場合は、それらが終了するまで、またはロックが解放されるまで待ちます。
+

NOTE: タスクが終了しない、またはロックが解放されない場合は、テクニカルサポートにお問い合わせください。



. を参照してください xref:../network/internal-grid-node-communications.adoc[内部でのグリッドノードの通信] および xref:../network/external-communications.adoc[外部との通信] アップグレードの前に、 StorageGRID 11.6 に必要なすべてのポートを開いておく必要があります。
+

IMPORTANT: カスタムのファイアウォールポートが開いている場合は、アップグレードの事前確認中に通知されます。アップグレードを続行する前に、テクニカルサポートに連絡する必要があります。


