---
permalink: upgrade/docker-image-availability-check-error-messages.html 
sidebar: sidebar 
keywords: upgrade, error message, docker image availability 
summary: アップグレードプロセスを開始しようとすると、「 The following issues were identified by the Docker image availability check validation suite 」というエラーメッセージが表示される場合があります。 アップグレードを完了する前に、すべての問題を解決しておく必要があります。 
---
= 「 Docker image availability check 」というエラーメッセージが表示される
:icons: font
:imagesdir: ../media/


[role="lead"]
アップグレードプロセスを開始しようとすると、「 The following issues were identified by the Docker image availability check validation suite 」というエラーメッセージが表示される場合があります。 アップグレードを完了する前に、すべての問題を解決しておく必要があります。

見つかった問題の解決に必要な変更内容がわからない場合は、テクニカルサポートにお問い合わせください。

[cols="1a,1a,1a"]
|===
| メッセージ | 原因 | 解決策 


 a| 
アップグレードバージョンを特定できません。アップグレード・バージョン情報ファイル '{file.PATH}' が予期された形式と一致しませんでした
 a| 
アップグレードパッケージが破損しています。
 a| 
アップグレードパッケージを再度アップロードしてやり直してください。問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
アップグレード・バージョン情報ファイル '{file.PATH}' が見つかりませんでしたアップグレードバージョンを特定できません。
 a| 
アップグレードパッケージが破損しています。
 a| 
アップグレードパッケージを再度アップロードしてやり直してください。問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
'{node_name }' に現在インストールされているリリースバージョンを判別できません
 a| 
ノード上の重要なファイルが破損しています。
 a| 
テクニカルサポートにお問い合わせください。



 a| 
'{node_name }' のバージョンをリストしようとしたときに接続エラーが発生しました
 a| 
ノードがオフラインであるか、接続が中断されました。
 a| 
すべてのノードがオンラインで、プライマリ管理ノードからアクセスできることを確認して、操作をやり直します。



 a| 
ノード '{node_name }' のホストには StorageGRID '{upgrade_version}' イメージがロードされていませんアップグレードを続行するには、イメージとサービスがホストにインストールされている必要があります。
 a| 
ノードを実行しているホストにアップグレード用の RPM パッケージまたは DEB パッケージがインストールされていないか、イメージのインポートがまだ終了していません。

* 注：このエラーは、 Linux でコンテナとして実行されている環境 ノードのみに該当します。
 a| 
RPM パッケージまたは DEB パッケージが、ノードが実行されているすべての Linux ホストにインストールされていることを確認します。サービスとイメージファイルの両方について、バージョンが正しいことを確認します。数分待ってから再試行してください。

を参照してください xref:../upgrade/linux-installing-rpm-or-deb-package-on-all-hosts.adoc[Linux ：すべてのホストに RPM パッケージまたは DEB パッケージをインストールします]。



 a| 
ノード '{node_name }' のチェック中にエラーが発生しました
 a| 
予期しないエラーが発生しました。
 a| 
数分待ってから再試行してください。



 a| 
事前確認の実行時に不明なエラーが発生する。'{error_string}`
 a| 
予期しないエラーが発生しました。
 a| 
数分待ってから再試行してください。

|===