---
permalink: upgrade/estimating-time-to-complete-upgrade.html 
sidebar: sidebar 
keywords: upgrade, time estimate, duration, cassandra upgrade 
summary: StorageGRID 11.6 へのアップグレードを計画する場合は、アップグレードにかかる時間に基づいてアップグレードのタイミングを検討する必要があります。また、アップグレードの各ステージ中に実行できる処理と実行できない処理についても把握しておく必要があります。 
---
= アップグレードが完了するまでの推定時間
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 11.6 へのアップグレードを計画する場合は、アップグレードにかかる時間に基づいてアップグレードのタイミングを検討する必要があります。また、アップグレードの各ステージ中に実行できる処理と実行できない処理についても把握しておく必要があります。

StorageGRID のアップグレード完了までに必要な時間は、クライアントの負荷やハードウェアのパフォーマンスなどのさまざまな要因によって異なります。

次の表に、アップグレードの主なタスクをまとめ、各タスクに必要なおおよその時間を示します。表に続いて、システムのアップグレード時間を見積もる手順を記載します。

[cols="1a,1a,1a,a"]
|===
| アップグレードタスク | 説明 | おおよその所要時間です | このタスクの実行中です 


 a| 
アップグレードサービスを開始します
 a| 
アップグレードの事前確認が実行され、ソフトウェアファイルが配布されて、アップグレードサービスが開始されます。
 a| 
検証エラーが報告されないかぎり、グリッドノードあたり 3 分
 a| 
必要に応じて、スケジュールされたアップグレードのメンテナンス時間の前に、アップグレードの事前確認を手動で実行できます。



 a| 
Grid ノード（プライマリ管理ノード）をアップグレード
 a| 
プライマリ管理ノードが停止されてアップグレードされ、再起動されます。
 a| 
SG100 および SG1000 アプライアンスのノードが最も時間がかかる場合は、 30 分から 1 時間かかります。
 a| 
プライマリ管理ノードにはアクセスできません。接続エラーが報告されますが、無視してかまいません。



 a| 
Grid ノード（他のすべてのノード）をアップグレード
 a| 
他のすべてのグリッドノードのソフトウェアが、ノードを承認した順序でアップグレードされます。システムの各ノードが一度に 1 つずつ数分間停止されます。
 a| 
ノードあたり 15~1 時間。アプライアンスノードで最も時間が必要です

* 注： * アプライアンスノードの場合、 StorageGRID アプライアンスインストーラは自動的に最新リリースに更新されます。
 a| 
* グリッド設定は変更しないでください。
* 監査レベルの設定は変更しないでください。
* ILM 設定を更新しないでください。
* ホットフィックス、運用停止、拡張など、他のメンテナンス手順を実行することはできません。
+
* 注： * リカバリを実行する必要がある場合は、テクニカル・サポートにお問い合わせください。





 a| 
機能を有効にします
 a| 
新しいバージョンの新機能が有効になります。
 a| 
5 分未満
 a| 
* グリッド設定は変更しないでください。
* 監査レベルの設定は変更しないでください。
* ILM 設定を更新しないでください。
* 別のメンテナンス手順 は実行できません。




 a| 
データベースをアップグレードします
 a| 
アップグレードプロセスによって各ノードがチェックされ、 Cassandra データベースの更新が不要であることが確認されます。
 a| 
ノードあたり 10 秒、またはグリッド全体で数分
 a| 
StorageGRID 11.5 から 11.6 へのアップグレードでは、 Cassandra データベースをアップグレードする必要はありません。ただし、各ストレージノードの Cassandra サービスは停止したあとに再起動します。

StorageGRID の今後の機能リリースでは、 Cassandra データベースの更新処理が完了するまでに数日かかることがあります。



 a| 
最終アップグレード手順
 a| 
一時ファイルが削除され、新しいリリースへのアップグレードが完了します。
 a| 
5 分
 a| 
[* 最終アップグレードステップ * ] タスクが完了すると、すべてのメンテナンス手順を実行できます。

|===
.手順
. すべてのグリッドノードをアップグレードするために必要な推定時間。
+
.. StorageGRID システムのノード数に 1 時間を掛けます。
+
原則として、アプライアンスノードのアップグレードにはソフトウェアベースのノードよりも時間がかかります。

.. この時間に '.upgrade ファイルのダウンロード ' 事前確認の実行 ' 最終アップグレード手順の完了に必要な時間を考慮して '1 時間を加えます


. Linux ノードがある場合は、 RPM パッケージまたは DEB パッケージをダウンロードしてインストールするために必要な時間として、各ノードに 15 分を追加します。
. 手順 1 および 2 の結果を追加して、アップグレードの合計推定時間を計算します。




== 例： StorageGRID 11.6 にアップグレードする推定時間

システムにグリッドノードが 14 個あり、そのうち 8 個が Linux ノードであるとします。

. 14 に 1 時間を掛けます。
. ダウンロード、事前確認、および最終手順に 1 時間を足します。
+
すべてのノードのアップグレードにかかる推定時間は 15 時間です。

. Linux ノードに RPM パッケージまたは DEB パッケージをインストールする時間を、 8 に 15 分 / ノードを掛けます。
+
この手順の推定時間は 2 時間です。

. 値をまとめて追加します。
+
システムを StorageGRID 11.6.1 にアップグレードするには、最大 17 時間かかります。


