---
permalink: upgrade/how-your-system-is-affected-during-upgrade.html 
sidebar: sidebar 
keywords: upgrade, firmware, appliance, alert 
summary: アップグレード中に StorageGRID システムがどのような影響を受けるかを理解しておく必要があります。 
---
= アップグレード中にシステムが受ける影響
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アップグレード中に StorageGRID システムがどのような影響を受けるかを理解しておく必要があります。



== StorageGRID のアップグレードは無停止で実行されます

StorageGRID システムは、アップグレードプロセス中もクライアントアプリケーションからデータを取り込み、読み出すことができます。アップグレード中に一度に 1 つずつグリッドノードが停止されるため、すべてのグリッドノードが使用できなくなることはありません。

継続的な可用性を確保するには、オブジェクトが適切な ILM ポリシーを使用して冗長に格納されていることを確認する必要があります。また、次のいずれかに要求を送信するようにすべての外部の S3 または Swift クライアントを設定する必要があります。

* ハイアベイラビリティ（ HA ）グループとして設定された StorageGRID エンドポイント
* 高可用性のサードパーティ製ロードバランサ
* 各クライアントに複数のゲートウェイノードが必要
* クライアントごとに複数のストレージノード




== アプライアンスファームウェアがアップグレードされている

StorageGRID 11.6 アップグレード中は、次の点に注意

* すべての StorageGRID アプライアンスノードは、 StorageGRID アプライアンスインストーラファームウェアバージョン 3.6 に自動的にアップグレードされます。
* SG6060 と SGF6024 アプライアンスは、 BIOS ファームウェアバージョン 3B07.EX および BMC ファームウェアバージョン BMC 3.93.07 に自動的にアップグレードされます。
* SG100 および SG1000 アプライアンスは、自動的に BIOS ファームウェアバージョン 3B12.EC および BMC ファームウェアバージョン 4.67.07 にアップグレードされます。




== アラートがトリガーされる可能性があります

アラートは、サービスの開始と停止、および StorageGRID システムを複数バージョンが混在した環境で使用している場合（一部のグリッドノードで以前のバージョンを実行し、その他のノードはより新しいバージョンにアップグレードしている場合）にトリガーされることがあります。アップグレードの完了後にその他のアラートがトリガーされることがあります。

たとえば、サービスが停止しているときに * Unable to communicate with node * アラートが表示されたり、一部のノードが StorageGRID 11.6 にアップグレードされても、他のノードが StorageGRID 11.5 を実行している場合に * Cassandra communication error * アラートが表示されることがあります。通常、これらのアラートはアップグレードが完了するとクリアされます。

StorageGRID 11.6 へのアップグレード中にストレージノードが停止すると、「 ILM placement unAchievable * 」アラートがトリガーされることがあります。このアラートは、アップグレードの完了後 1 日続く場合があります。

ストレージボリュームのウォーターマークにカスタム値を使用すると、アップグレードの完了後に * 読み取り専用のウォーターマーク上書き * アラートがトリガーされることがあります。を参照してください xref:../monitor/troubleshoot-low-watermark-alert.adoc[読み取り専用のローウォーターマーク上書きアラートのトラブルシューティング] を参照してください。

アップグレードが完了したら、 Grid Manager ダッシュボードで「 Recently Resolved alerts 」または「 * Current alerts 」を選択することで、アップグレード関連のアラートを確認できます。



== 多数の SNMP 通知が生成されます

アップグレード中にグリッドノードが停止および再起動されると、多数の SNMP 通知が生成される場合があります。過剰な通知を避けるには、 [ * SNMP エージェント通知を有効にする * ] チェックボックス（ * configuration * > * Monitoring * > * SNMP agent * ）をオフにして、アップグレードを開始する前に SNMP 通知を無効にします。その後、アップグレードの完了後に通知を再度有効にします。



== 設定の変更は制限されています


NOTE: 制限された設定変更のリストは、リリースによって変わる可能性があります。別の StorageGRID リリースにアップグレードする場合は、該当するアップグレード手順のリストを参照してください。

[ 新しい機能を有効にする *] タスクが完了するまで :

* グリッドの設定は変更しないでください。
* 監査レベルの設定を変更したり、外部 syslog サーバを設定したりしないでください。
* 新しい機能を有効または無効にしないでください。
* ILM 設定を更新しないでください。ILM の動作が不安定になり、正常に動作しない場合があります。
* ホットフィックスの適用やグリッドノードのリカバリは行わないでください。
* StorageGRID 11.6 へのアップグレード中は、 HA グループ、 VLAN インターフェイス、またはロードバランサエンドポイントを管理できません。


[* Final Upgrade Steps * （最終アップグレード手順 * ） ] タスクが完了するまで：

* 拡張手順 は実行しないでください。
* 手順 の運用停止は実行しないでください。




== Tenant Manager でバケットの詳細を表示したりバケットを管理したりすることはできません

StorageGRID 11.6 へのアップグレード（つまり、システムは複数バージョンが混在する環境として動作している）中は、バケットの詳細を表示したり、テナントマネージャを使用してバケットを管理したりすることはできません。Tenant Manager のバケットページには、次のいずれかのエラーが表示されます。

* "'11.6 にアップグレードしている間は、この API を使用できません。 "
* "'11.6 にアップグレードしている間は 'Tenant Manager でバケットのバージョン管理の詳細を表示できません "


このエラーは、 11.6 へのアップグレードが完了すると解決します。

.回避策
11.6 アップグレードの実行中は、 Tenant Manager ではなく、次のツールを使用してバケットの詳細を表示したりバケットを管理したりします。

* バケットに対して標準の S3 処理を実行するには、 S3 REST API またはテナント管理 API を使用します。
* バケットに対して StorageGRID のカスタム処理（バケットの整合性レベルの表示と変更、最終アクセス日時の更新の有効化と無効化、検索統合の設定など）を実行するには、テナント管理 API を使用します。


を参照してください xref:../tenant/understanding-tenant-management-api.adoc[テナント管理 API について理解する] および xref:../s3/index.adoc[S3 を使用する] 手順については、を参照し
