---
permalink: upgrade/troubleshooting-upgrade-issues.html 
sidebar: sidebar 
keywords: upgrade, troubleshoot, troubleshooting, errors, upgrade precheck 
summary: アップグレードが正常に完了しない場合は、問題 を自分で解決できることがあります。問題 を解決できない場合は、テクニカルサポートに連絡する前に、必要な情報を収集する必要があります。 
---
= アップグレードが完了しない
:icons: font
:imagesdir: ../media/


[role="lead"]
アップグレードが正常に完了しない場合は、問題 を自分で解決できることがあります。問題 を解決できない場合は、テクニカルサポートに連絡する前に、必要な情報を収集する必要があります。

次のセクションでは、アップグレードが部分的に失敗した場合のリカバリ方法について説明します。アップグレード問題 を解決できない場合は、テクニカルサポートにお問い合わせください。



== アップグレードの事前確認エラー

問題を検出して解決するために、実際のアップグレードを開始する前にアップグレードの事前確認を手動で実行できます。事前確認で報告されるほとんどのエラーには、問題 の解決方法が表示されます。サポートが必要な場合は、テクニカルサポートにお問い合わせください。



== プロビジョニングに失敗しました

自動プロビジョニングプロセスが失敗する場合は、テクニカルサポートにお問い合わせください。



== グリッドノードがクラッシュするか起動しない

アップグレードプロセス中にグリッドノードがクラッシュする、またはアップグレードの終了後に正常に起動しない場合は、テクニカルサポートに調査を依頼して、根本的な問題を修正してください。



== データの取り込みまたは読み出しが中断される

グリッドノードをアップグレードしていないときにデータの取り込みまたは読み出しが突然中断する場合は、テクニカルサポートにお問い合わせください。



== データベースのアップグレードエラーです

データベースのアップグレードがエラーで失敗した場合は、アップグレードを再試行します。それでも失敗する場合は、テクニカルサポートにお問い合わせください。

xref:checking-systems-condition-before-upgrading-software.adoc[ソフトウェアのアップグレード前のシステム状態の確認]
