---
permalink: upgrade/verifying-installed-version-of-storagegrid.html 
sidebar: sidebar 
keywords: storagegrid, version, current version, previous version 
summary: アップグレードを開始する前に、利用可能な最新のホットフィックスを適用して以前のバージョンの StorageGRID が現在インストールされていることを確認する必要があります。 
---
= インストールされている StorageGRID のバージョンを確認します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アップグレードを開始する前に、利用可能な最新のホットフィックスを適用して以前のバージョンの StorageGRID が現在インストールされていることを確認する必要があります。

StorageGRID 11.6 にアップグレードする前に、グリッドに StorageGRID 11.5 がインストールされている必要があります。以前のバージョンの StorageGRID を現在使用している場合は、グリッドの現在のバージョンが StorageGRID 11.5._x.y_x になるまで、以前のすべてのアップグレードファイルと最新のホットフィックスをインストールする必要があります（強く推奨）。

に、アップグレード可能なパスの 1 つを示します  Upgrade to StorageGRID 11.5 from version 11.3.0.8,例。


IMPORTANT: StorageGRID の各バージョンに最新のホットフィックスを適用してから次のバージョンにアップグレードすることを強く推奨します。また、インストールした新しいバージョンごとに最新のホットフィックスも適用します。場合によっては、データ損失のリスクを回避するためにホットフィックスを適用する必要があります。を参照してください https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["ネットアップのダウンロード： StorageGRID"^] 各ホットフィックスのリリースノートで詳細を確認できます。

11.3.0.13+ から 11.2.0._y_in へのアップデートを 1 つの手順で実行し、 11.2.0.7+ から 11.5.0.0._y_in へのアップデートを 1 つの手順で実行できることに注意してください。を参照してください https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_run_combined_major_upgrade_and_hotfix_script_for_StorageGRID["ネットアップのナレッジベース：「 How to run combined Major upgrade and hotfix script for StorageGRID"^]。

.手順
. を使用して Grid Manager にサインインします xref:../admin/web-browser-requirements.adoc[サポートされている Web ブラウザ]。
. Grid Manager の上部から * ヘルプ * > * バージョン情報 * を選択します。
. バージョン * が 11.5._x.y_. であることを確認します。
+
StorageGRID 11.5._x.y_version の番号で、次の手順を実行します。

+
** メジャーリリース * の _x_value は 0 （ 11.5.0 ）です。
** * ホットフィックス * が適用されている場合は、 _y_value （例： 11.5.0.1 ）が適用されています。


. バージョン * が 11.5._x.y__ でない場合は、に進みます https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["ネットアップのダウンロード： StorageGRID"^] 各リリースの最新のホットフィックスを含めて、以前の各リリースのファイルをダウンロードします。
. ダウンロードした各リリースのアップグレード手順を入手します。次に、そのリリースのソフトウェアアップグレード手順 を実行し、そのリリースの最新のホットフィックスを適用します（強く推奨）。
+
を参照してください xref:../maintain/storagegrid-hotfix-procedure.adoc[StorageGRID ホットフィックス手順]。





== 例：バージョン 11.3.0.8 から StorageGRID 11.5 にアップグレードします

次の例は、 StorageGRID 11.6 アップグレードに備えて StorageGRID バージョン 11.3.0.8 からバージョン 11.5 にアップグレードする手順を示しています。


IMPORTANT: 必要に応じて、手順 2 と 3 を組み合わせて（ 11.3.0.13+ から 11.4.0_y__ に更新）、手順 4 と 5 を組み合わせて（ 11.4.0.7 以降から 11.5.0_y_y _ に更新）、スクリプトを実行することもできます。を参照してください https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_run_combined_major_upgrade_and_hotfix_script_for_StorageGRID["ネットアップのナレッジベース：「 How to run combined Major upgrade and hotfix script for StorageGRID"^]。

次の順序でソフトウェアをダウンロードしてインストールし、システムをアップグレードする準備をします。

. 最新の StorageGRID 11.3.0 ._y_hotfix を適用します。
. StorageGRID 11.4.0 メジャーリリースにアップグレードします。
. 最新の StorageGRID 11.11.0._y_hotfix を適用します。
. StorageGRID 11.5.0 メジャーリリースにアップグレードします。
. 最新の StorageGRID 11.5.0_y_hotfix を適用します。

