---
permalink: sg100-1000/configuring-snmp-settings-for-sg1000.html 
sidebar: sidebar 
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, SNMP, configure, setup, set up 
summary: ハードウェアの SNMP の設定に精通している場合は、 BMC インターフェイスを使用してサービスアプライアンスの SNMP 設定を行うことができます。セキュリティで保護されたコミュニティストリングを指定し、 SNMP トラップを有効にし、 SNMP の送信先を最大 5 つ指定できます。 
---
= サービスアプライアンスの SNMP を設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ハードウェアの SNMP の設定に精通している場合は、 BMC インターフェイスを使用してサービスアプライアンスの SNMP 設定を行うことができます。セキュリティで保護されたコミュニティストリングを指定し、 SNMP トラップを有効にし、 SNMP の送信先を最大 5 つ指定できます。

.必要なもの
* BMC ダッシュボードへのアクセス方法を確認しておく必要があります。
* SNMPv1-v2c 機器の SNMP 設定経験が必要です。



NOTE: この手順 で作成された BMC 設定は、アプライアンスに障害が発生して交換が必要な場合に、保持されないことがあります。適用したすべての設定を記録し、必要に応じてハードウェアの交換後に簡単に再適用できるようにします。

.手順
. BMC ダッシュボードで、 * Settings * > * SNMP Settings * を選択します。
. SNMP 設定ページで、 * SNMP V1/V2* を有効にするを選択し、読み取り専用コミュニティストリングと読み取り / 書き込みコミュニティストリングを指定します。
+
読み取り専用コミュニティストリングは、ユーザ ID やパスワードのようなものです。侵入者がネットワーク設定に関する情報を取得できないようにするには、この値を変更する必要があります。読み取り / 書き込みコミュニティストリングは、不正な変更からデバイスを保護します。

. 必要に応じて、 * トラップを有効にする * を選択し、必要な情報を入力します。
+

IMPORTANT: IP アドレスを使用して、各 SNMP トラップの送信先 IP を入力します。完全修飾ドメイン名はサポートされません。

+
サービスアプライアンスから SNMP コンソールが異常な状態になったときに通知をすぐに送信するには、トラップを有効にします。トラップは、リンクの稼働 / 停止状態、しきい値を超えた温度、トラフィックの増加を示している場合があります。

. 必要に応じて、 [ テストトラップの送信 ] をクリックして設定をテストします。
. 設定が正しい場合は、 * 保存 * をクリックします。

