---
permalink: sg100-1000/replacing-services-appliance.html 
sidebar: sidebar 
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, Replacing, replace, remove, removing, removal, install, installing, installation 
summary: アプライアンスが適切に機能しない場合や障害が発生した場合は、交換が必要となることがあります。 
---
= サービスアプライアンスを交換します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アプライアンスが適切に機能しない場合や障害が発生した場合は、交換が必要となることがあります。

.必要なもの
* 交換するアプライアンスと同じパーツ番号の交換用アプライアンスを用意しておきます。
* アプライアンスに接続する各ケーブルを識別するためのラベルを用意しておきます。
* これで完了です xref:locating-controller-in-data-center.adoc[アプライアンスを物理的に設置します]。
* アプライアンスは次のようになりました xref:placing-appliance-into-maintenance-mode.adoc[メンテナンスモードにしました]。


アプライアンスの交換中は、 StorageGRID ノードにアクセスできなくなります。アプライアンスが動作している場合は、この手順 の起動時に通常の方法でシャットダウンを実行できます。


NOTE: StorageGRID ソフトウェアをインストールする前にアプライアンスを交換すると、この手順 の完了後すぐに StorageGRID アプライアンスインストーラにアクセスできない場合があります。アプライアンスと同じサブネット上の他のホストから StorageGRID アプライアンスインストーラにアクセスすることはできますが、他のサブネット上のホストからはアクセスできません。この状態は 15 分以内に（元のアプライアンスのいずれかの ARP キャッシュエントリがタイムアウトした時点で）自動的に解消されます。あるいは、古い ARP キャッシュエントリをローカルルータまたはゲートウェイから手動でパージすれば、すぐにこの状態を解消できます。

.手順
. アプライアンスをメンテナンスモードにしたら、アプライアンスをシャットダウンします。
+
.. グリッドノードにログインします。
+
... 次のコマンドを入力します。 ssh admin@_grid_node_name
... 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
... root に切り替えるには、次のコマンドを入力します
... 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
+
root としてログインすると、プロンプトは「 $` 」から「 #」 に変わります。



.. アプライアンスをシャットダウンします :+`*shutdown-h now *`


. アプライアンスの電源がオフになっていることを確認するには、次のいずれかの方法を使用します。
+
** アプライアンスの前面にある電源 LED が消灯している。
** BMC インターフェイスの電源制御ページに、アプライアンスがオフになっていることが示されます。


. アプライアンスに接続されている StorageGRID ネットワークが DHCP サーバを使用している場合は、 DNS / ネットワークおよび IP アドレスの設定を更新します。
+
.. アプライアンス前面の MAC アドレスラベルを確認し、管理ネットワークポートの MAC アドレスを特定します。
+

NOTE: MAC アドレスラベルには、 BMC 管理ポートの MAC アドレスが記載されています。

+
管理ネットワークポートの MAC アドレスを特定するには、ラベルに記載された 16 進数に * 2 * を追加する必要があります。たとえば、ラベルに記載されている MAC アドレスの末尾が * 09 * の場合、管理ポートの MAC アドレスの末尾は * 0B * となります。ラベルに記載された MAC アドレスの末尾が * （ _y_） FF* の場合、管理ポートの MAC アドレスの末尾は * （ _y_+1 ） 01 * となります。この計算を簡単に行うには、 Windows で Calculator を開き、 Programmer モードに設定して Hex を選択し、 MAC アドレスを入力してから、 *+2=* と入力します。

.. 取り外したアプライアンスの DNS / ネットワークおよび IP アドレスを交換用アプライアンスの MAC アドレスと関連付けるよう、ネットワーク管理者に依頼します。
+

IMPORTANT: 交換用アプライアンスに電源を投入する前に、元のアプライアンスのすべての IP アドレスが更新されたことを確認する必要があります。そうしないと、アプライアンスのブート時に新しい DHCP IP アドレスが取得されて、 StorageGRID に再接続できなくなることがあります。この手順では、アプライアンスに接続されているすべての StorageGRID ネットワークを環境 接続します。

+

NOTE: 元のアプライアンスが静的 IP アドレスを使用していた場合は、取り外したアプライアンスの IP アドレスが自動的に新しいアプライアンスで使用されます。



. アプライアンスを取り外して交換します。
+
.. ケーブルにラベルを付け、ケーブルとネットワークトランシーバを取り外します。
+

IMPORTANT: パフォーマンスの低下を防ぐために、ケーブルをねじったり、折り曲げたり、はさんだり、踏みつけたりしないでください。

.. 障害が発生したアプライアンスをキャビネットまたはラックから取り外します。
.. 電源装置 2 台、冷却ファン 8 台、および SSD 2 台を障害が発生したアプライアンスから交換用アプライアンスに移します。
+
これらのコンポーネントの交換手順に従ってください。

.. 交換用アプライアンスをキャビネットまたはラックに設置します。
.. ケーブルと光トランシーバを交換してください。
.. アプライアンスの電源を入れ、アプライアンスの LED とブート時のコードを監視します。
+
BMC インターフェイスを使用して、ブート時のステータスを監視します。



. アプライアンスノードが Grid Manager に表示され、アラートが表示されていないことを確認します。


xref:installing-appliance-in-cabinet-or-rack-sg100-and-sg1000.adoc[キャビネットまたはラックへのアプライアンスの設置（ SG100 および SG1000 ）]

xref:viewing-status-indicators-on-sg100-and-sg1000-appliances.adoc[SG100 および SG1000 アプライアンスのステータスインジケータを表示します]

xref:viewing-boot-up-codes-for-appliance-sg100-and-sg1000.adoc[アプライアンスのブート時のコードを確認します]
