---
permalink: sg100-1000/sg100-and-sg1000-applications.html 
sidebar: sidebar 
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, applications, how to use, services 
summary: StorageGRID サービスアプライアンスは、ゲートウェイサービスおよび一部のグリッド管理サービスの冗長性を提供するためにさまざまな方法で設定できます。 
---
= SG100 および SG1000 アプリケーション
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID サービスアプライアンスは、ゲートウェイサービスおよび一部のグリッド管理サービスの冗長性を提供するためにさまざまな方法で設定できます。

アプライアンスは、次の方法で導入できます。

* ゲートウェイノードとして新規または既存のグリッドに追加します
* プライマリまたは非プライマリ管理ノードとして新しいグリッドに追加するか、非プライマリ管理ノードとして既存のグリッドに追加します
* ゲートウェイノードと管理ノード（プライマリまたは非プライマリ）として同時に動作します


アプライアンスでは、 S3 または Swift データパス接続に対し、ハイアベイラビリティ（ HA ）グループとインテリジェントなロードバランシングを実装できます。

次に、アプライアンスの機能を最大限に活用する例を示します。

* 2 台の SG1000 アプライアンスをゲートウェイノードとして設定して、ゲートウェイサービスを提供するには、 2 台の SG100 または 2 台の SG1000 アプライアンスを使用します。
+

IMPORTANT: SG100 と SG1000 サービスアプライアンスは同じサイトに導入しないでください。パフォーマンスが予測不能になる可能性があります

* 一部のグリッド管理サービスの冗長性を確保するには、 2 台の SG100 または 2 台の SG1000 アプライアンスを使用します。そのためには、各アプライアンスを管理ノードとして設定します。
* 2 台の SG1000 アプライアンスを使用して、 1 つ以上の仮想 IP アドレス経由でアクセスする可用性の高いロードバランシングサービスとトラフィックシェーピングサービスを提供します。そのためには、アプライアンスを管理ノードまたはゲートウェイノードの任意の組み合わせとして設定し、両方のノードを同じ HA グループに追加します。
+

IMPORTANT: 同じ HA グループ内の管理ノードとゲートウェイノードを使用する場合、 CLB （ Connection Load Balancer ）ポートと管理ノードのみのポートはフェイルオーバーされません。HA グループを設定する手順については、 StorageGRID の管理手順を参照してください。

+

NOTE: CLB サービスは廃止されました。



StorageGRID ストレージアプライアンスとともに使用すると、 SG100 と SG1000 サービスアプライアンスの両方で、外部のハイパーバイザーやコンピューティングハードウェアに依存しないアプライアンスのみのグリッドを導入できます。

xref:../admin/index.adoc[StorageGRID の管理]
