---
permalink: sg100-1000/troubleshooting-connection-issues-sg100-and-sg1000.html 
sidebar: sidebar 
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, troubleshoot, troubleshooting, connection 
summary: StorageGRID アプライアンスのインストール時に接続の問題が発生した場合は、以下に記載する対処策を実施する必要があります。 
---
= 接続の問題（ SG100 および SG1000 ）のトラブルシューティング
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID アプライアンスのインストール時に接続の問題が発生した場合は、以下に記載する対処策を実施する必要があります。



== アプライアンスに接続できません

サービスアプライアンスに接続できない場合は、ネットワーク問題 があるか、またはハードウェアの設置が正常に完了していない可能性があります。

.手順
. アプライアンスの IP アドレスを使用してアプライアンスに ping を送信してみます： +`*ping_services_apply_ip_*`
. ping からの応答がない場合は、正しい IP アドレスを使用していることを確認します。
+
グリッドネットワーク、管理ネットワーク、またはクライアントネットワークでのアプライアンスの IP アドレスを使用できます。

. IP アドレスが正しい場合は、アプライアンスのケーブル接続、 QSFP または SFP トランシーバ、およびネットワークのセットアップを確認します。
. アプライアンスへの物理的なアクセスが可能な場合は ' 恒久的なリンクローカル IP 169.254.0.1 への直接接続を使用して ' コントローラのネットワーク構成を確認し ' 必要に応じて更新できます詳細な手順については、のステップ 2 を参照してください xref:..//sg100-1000/accessing-storagegrid-appliance-installer-sg100-and-sg1000.adoc[StorageGRID アプライアンスインストーラにアクセスします]。
+
この手順で問題 が解決しない場合は、テクニカルサポートにお問い合わせください。

. ping が成功した場合は、 Web ブラウザを開きます。
. StorageGRID アプライアンスインストーラの URL を入力します :+`*https://_appliances_controller_IP_:8443*`
+
ホームページが表示されます。


