---
permalink: sg100-1000/verifying-and-upgrading-storagegrid-appliance-installer-version.html 
sidebar: sidebar 
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, Verifying, verify, upgrading, upgrade, update, updating, Appliance Installer, version, release 
summary: StorageGRID のすべての機能がサポートされるようにするには、アプライアンスの StorageGRID アプライアンスインストーラのバージョンと StorageGRID システムにインストールされているソフトウェアのバージョンが一致している必要があります。 
---
= StorageGRID アプライアンスインストーラのバージョンを確認してアップグレードします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID のすべての機能がサポートされるようにするには、アプライアンスの StorageGRID アプライアンスインストーラのバージョンと StorageGRID システムにインストールされているソフトウェアのバージョンが一致している必要があります。

StorageGRID アプライアンスインストーラにアクセスしておきます。

StorageGRID アプライアンスは、 StorageGRID アプライアンスインストーラがプリインストールされた状態で出荷されます。最近アップグレードした StorageGRID システムにアプライアンスを追加する場合は、そのアプライアンスを新しいノードとしてインストールする前に、 StorageGRID アプライアンスインストーラの手動アップグレードが必要になることがあります。

新しい StorageGRID バージョンにアップグレードすると、 StorageGRID アプライアンスインストーラが自動的にアップグレードされます。インストールされているアプライアンスノードでは、 StorageGRID アプライアンスインストーラをアップグレードする必要はありません。この手順 が必要になるのは、以前のバージョンの StorageGRID アプライアンスインストーラを搭載したアプライアンスをインストールする場合のみです。

.手順
. StorageGRID アプライアンス・インストーラから、 * アドバンスト * > * アップグレード・ファームウェア * を選択します。
. 現在のファームウェアバージョンと StorageGRID システムにインストールされているソフトウェアバージョンを比較します。（ Grid Manager の上部からヘルプアイコンを選択し、 * バージョン情報 * を選択します）。
+
2 つのバージョンの 2 桁目の数字が一致している必要があります。たとえば、 StorageGRID システムでバージョン 11.* 6 * 。 _x_.y_y__ を実行している場合、 StorageGRID アプライアンスインストーラのバージョンは 3.* 6 * ._z_ である必要があります。

. アプライアンスの StorageGRID アプライアンスインストーラの下位バージョンがある場合は、に進みます https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["ネットアップの StorageGRID ダウンロードページ"^]。
+
ネットアップアカウントのユーザ名とパスワードを使用してサインインします。

. StorageGRID アプライアンス * 対応するバージョンのサポート・ファイルと対応するチェックサム・ファイルをダウンロードします。
+
StorageGRID アプライアンス・ファイルのサポート・ファイルは '.zip アーカイブであり ' すべての StorageGRID アプライアンス・モデルの最新および以前のファームウェア・バージョンが ' 各コントローラ・タイプのサブディレクトリに格納されています

+
StorageGRID アプライアンス・ファイルのサポート・ファイルをダウンロードした後 '.zip アーカイブを展開し 'README ファイルを参照して StorageGRID アプライアンス・インストーラのインストールに関する重要な情報を入手してください

. StorageGRID アプライアンスインストーラのファームウェアのアップグレードページの手順に従って、次の手順を実行します。
+
.. コントローラタイプとチェックサムファイルに適したサポートファイル（ファームウェアイメージ）をアップロードします。
.. 非アクティブなパーティションをアップグレードします。
.. パーティションを再起動してスワップします。
.. 2 つ目の（非アクティブな）パーティションをアップグレードします。




xref:accessing-storagegrid-appliance-installer-sg100-and-sg1000.adoc[StorageGRID アプライアンスインストーラにアクセスします]
