---
permalink: ubuntu/automating-installation.html 
sidebar: sidebar 
keywords: how to automate ubuntu or debian installation 
summary: StorageGRID ホストサービスのインストールおよびグリッドノードの設定を自動化することができます。 
---
= インストールの自動化（ Ubuntu または Debian ）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID ホストサービスのインストールおよびグリッドノードの設定を自動化することができます。

.このタスクについて
導入を自動化すると、次のいずれかの場合に役立ちます。

* 物理ホストや仮想ホストの導入と設定に Ansible 、 Puppet 、 Chef などの標準のオーケストレーションフレームワークをすでに使用している場合。
* 複数の StorageGRID インスタンスを導入する場合。
* 大規模で複雑な StorageGRID インスタンスを導入する場合。


StorageGRID ホストサービスはパッケージでインストールされ、構成ファイルで制御されます。構成ファイルは、手動インストール時に対話形式で作成できるほか、あらかじめ用意して（またはプログラム化して）標準のオーケストレーションフレームワークを使用した自動インストールに使用できます。StorageGRID には、 StorageGRID アプライアンスと StorageGRID システム全体（「グリッド」）の設定を自動化するためのオプションの Python スクリプトが用意されています。これらのスクリプトは直接使用することも、 StorageGRID インストール REST API の使用方法を調べることもできます。グリッドの導入ツールや設定ツールを独自に開発する際の参考としても使用できます。



== StorageGRID ホストサービスのインストールと設定を自動化する

StorageGRID ホストサービスのインストールは、 Ansible 、 Puppet 、 Chef 、 Fabric 、 SaltStack などの標準のオーケストレーションフレームワークを使用して自動化できます。

StorageGRID ホストサービスは、 DEB 形式でパッケージ化されており、あらかじめ構成ファイルを用意して（またはプログラム化して）おくことで自動インストールが可能です。すでに Ubuntu または Debian のインストールおよび設定に標準的なオーケストレーションフレームワークを使用している場合は、プレイブックやレシピに StorageGRID を追加する方が簡単です。

次のタスクを自動化できます。

. Linux をインストールしています
. Linux の設定
. StorageGRID の要件を満たすホストネットワークインターフェイスを設定する
. StorageGRID の要件を満たすホストストレージを構成する
. Docker をインストールする
. StorageGRID ホストサービスをインストールしています
. StorageGRID ノード構成ファイルを /etc/storagegrid/nodes に作成しています
. StorageGRID ノード構成ファイルを検証しています
. StorageGRID ホストサービスを開始しています




=== サンプルの Ansible のロールとプレイブック

サンプルの Ansible のロールとプレイブックは、 /extras フォルダに含まれるインストールアーカイブに含まれています。Ansible プレイブックは 'Ansible StorageGRID の役割がホストを準備し ' ターゲット・サーバに StorageGRID をインストールする方法を示しています必要に応じて、ロールまたはプレイブックをカスタマイズできます。



== StorageGRID の設定を自動化

グリッドノードを導入したら、 StorageGRID システムの設定を自動化できます。

.必要なもの
* インストールアーカイブにある次のファイルの場所を確認しておきます。


[cols="1a,1a"]
|===
| ファイル名 | 説明 


| configure-storagegrid.py  a| 
設定を自動化するための Python スクリプト



| storagegrid-sample.json を設定します  a| 
スクリプトで使用するサンプル構成ファイル



| storagegrid-bank.json を設定する  a| 
スクリプトで使用する空の構成ファイルです

|===
* 構成ファイル configure -storagegrid.json を作成しました。このファイルを作成するには、サンプル構成ファイル（「 configure -storagegrid-sample.json 」）または空の構成ファイル（「 configure -storagegridBlank.json 」）を変更します。


.このタスクについて
configure -storagegrid.py Python スクリプトと、 configure -storagegrid.json 構成ファイルを使用して、 StorageGRID システムの設定を自動化できます。


NOTE: また、 Grid Manager またはインストール API を使用してシステムを設定することもできます。

.手順
. Python スクリプトを実行するために使用する Linux マシンにログインします。
. インストールアーカイブを展開したディレクトリに移動します。
+
例：

+
[listing]
----
cd StorageGRID-Webscale-version/platform
----
+
ここで 'platform` は `debs`, `rps`, または「 vsphere 」です。

. Python スクリプトを実行し、作成した構成ファイルを使用します。
+
例：

+
[listing]
----
./configure-storagegrid.py ./configure-storagegrid.json --start-install
----


.結果
リカバリ・パッケージの .zip ファイルは ' 構成プロセス中に生成され ' インストールおよび構成プロセスを実行しているディレクトリにダウンロードされますグリッドノードで障害が発生した場合に StorageGRID システムをリカバリできるようにするために、リカバリパッケージファイルをバックアップする必要があります。たとえば、バックアップされたセキュアなネットワーク上の場所や、安全なクラウドストレージ上の場所にコピーします。


IMPORTANT: リカバリパッケージファイルには StorageGRID システムからデータを取得するための暗号キーとパスワードが含まれているため、安全に保管する必要があります。

ランダムなパスワードを生成するように指定した場合は、「 passwords.txt 」ファイルを抽出し、 StorageGRID システムへのアクセスに必要なパスワードを探す必要があります。

[listing]
----
######################################################################
##### The StorageGRID "recovery package" has been downloaded as: #####
#####           ./sgws-recovery-package-994078-rev1.zip          #####
#####   Safeguard this file as it will be needed in case of a    #####
#####                 StorageGRID node recovery.                 #####
######################################################################
----
StorageGRID システムがインストールおよび設定されると、確認メッセージが表示されます。

[listing]
----
StorageGRID has been configured and installed.
----
.関連情報
xref:overview-of-installation-rest-api.adoc[インストール REST API の概要]
