---
permalink: ubuntu/planning-and-preparation.html 
sidebar: sidebar 
keywords: how to prepare for ubuntu or debian installation 
summary: グリッドノードの導入および StorageGRID グリッドの設定を行う前に、手順 を完了するためのステップと要件を把握しておく必要があります。 
---
= インストールする前に（ Ubuntu または Debian ）
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッドノードの導入および StorageGRID グリッドの設定を行う前に、手順 を完了するためのステップと要件を把握しておく必要があります。

StorageGRID の導入手順と設定手順を実行するには、 StorageGRID システムのアーキテクチャと運用に関する十分な知識が必要です。

一度に 1 つ以上のサイトを導入できますが、ストレージノードが少なくとも 3 つ必要であるという最小要件をすべてのサイトが満たしている必要があります。

StorageGRID のインストールを開始する前に、次の作業を実行する必要があります

* ノードごとの CPU や RAM の最小要件など、 StorageGRID のコンピューティング要件を確認します。
* トラフィックの分離、セキュリティ、および管理性の向上のために複数のネットワークをサポートする StorageGRID の仕組みについて理解し、 StorageGRID の各ノードに接続するネットワークを決めます。
+
StorageGRID のネットワークに関するガイドラインを参照してください。

* 各タイプのグリッドノードのストレージ要件とパフォーマンス要件を把握します。
* 導入予定の StorageGRID ノードの数とタイプに応じて、それらをサポートできる十分なリソースを備えた一連のサーバ（物理、仮想、またはその両方）を特定します。
* 物理ホストに対して、サービスを中断することなく定期的なメンテナンスを実行する場合は、ノード移行の要件を確認します。
* すべてのネットワーク情報を事前に収集します。DHCP を使用している場合を除き、各グリッドノードに割り当てる IP アドレス、および使用される Domain Name System （ DNS ；ドメインネームシステム）サーバと Network Time Protocol （ NTP ；ネットワークタイムプロトコル）サーバの IP アドレスを収集してください。
* StorageGRID アプライアンスを含む必要なすべてのハードウェアを仕様に従って設置、接続、設定します。
+

NOTE: ハードウェア固有の設置と統合の手順は、 StorageGRID インストール手順 には含まれていません。StorageGRID アプライアンスのインストール方法については、使用するアプライアンスのインストールとメンテナンスの手順を参照してください。

* 使用する導入ツールと設定ツールを決定します。


xref:../network/index.adoc[ネットワークのガイドライン]

xref:../sg100-1000/index.adoc[SG100 および SG1000 サービスアプライアンス]

xref:../sg6000/index.adoc[SG6000 ストレージアプライアンス]

xref:../sg5700/index.adoc[SG5700 ストレージアプライアンス]

xref:../sg5600/index.adoc[SG5600 ストレージアプライアンス]

xref:node-container-migration-requirements.adoc[ノードコンテナの移行要件]
