---
permalink: harden/hardening-guidelines-for-software-upgrades.html 
sidebar: sidebar 
keywords: Hardening guidelines, upgrades 
summary: 攻撃を防御するには、 StorageGRID システムおよび関連サービスを最新の状態に保つ必要があります。 
---
= ソフトウェアアップグレードの強化に関するガイドライン
:icons: font
:imagesdir: ../media/


[role="lead"]
攻撃を防御するには、 StorageGRID システムおよび関連サービスを最新の状態に保つ必要があります。



== StorageGRID ソフトウェアへのアップグレード

StorageGRID ソフトウェアは、可能なかぎり、最新のメジャーリリースまたは以前のメジャーリリースにアップグレードする必要があります。StorageGRID を最新の状態に保つことで、既知の脆弱性がアクティブになる時間を短縮し、攻撃対象領域全体を削減できます。また、 StorageGRID の最新リリースには、以前のリリースには含まれていないセキュリティ強化機能が含まれていることがよくあります。

ホットフィックスが必要になったときに、ネットアップは最新リリースの更新プログラムの作成に優先順位を付けます。一部のパッチは、以前のリリースと互換性がない場合があります。

StorageGRID の最新のリリースやホットフィックスをダウンロードするには、 StorageGRID のソフトウェアダウンロードページにアクセスします。StorageGRID ソフトウェアのアップグレード手順については、 StorageGRID のアップグレード手順を参照してください。ホットフィックスの適用手順については、リカバリとメンテナンスの手順を参照してください。



== 外部サービスへのアップグレード

外部サービスには、 StorageGRID に間接的に影響する脆弱性が存在する場合がありますStorageGRID が依存するサービスが最新の状態に保たれていることを確認してください。LDAP 、 KMS （ KMIP サーバ）、 DNS 、 NTP などのサービスを利用できます。

サポートされているバージョンの一覧については、 NetApp Interoperability Matrix Tool を参照してください。



== ハイパーバイザーのアップグレード

StorageGRID ノードが VMware または別のハイパーバイザーで実行されている場合は、ハイパーバイザーのソフトウェアとファームウェアが最新であることを確認する必要があります。

サポートされているバージョンの一覧については、 NetApp Interoperability Matrix Tool を参照してください。



== Linux ノードにアップグレードします

StorageGRID ノードで Linux ホストプラットフォームを使用している場合は、セキュリティ更新とカーネル更新がホスト OS に適用されていることを確認する必要があります。また、これらの更新プログラムが利用可能になった場合は、脆弱なハードウェアにファームウェアの更新プログラムを適用する必要があります。

サポートされているバージョンの一覧については、 NetApp Interoperability Matrix Tool を参照してください。

https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["ネットアップのダウンロード： StorageGRID"^]

xref:../upgrade/index.adoc[ソフトウェアをアップグレードする]

xref:../maintain/index.adoc[リカバリとメンテナンス]

https://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool で確認できます"^]
