---
permalink: harden/other-hardening-guidelines.html 
sidebar: sidebar 
keywords: Hardening guidelines, security 
summary: StorageGRID ネットワークおよびノードに対する強化ガイドラインに加えて、 StorageGRID システムの他の領域に対する強化ガイドラインに従う必要があります。 
---
= その他のセキュリティ強化に関するガイドライン
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID ネットワークおよびノードに対する強化ガイドラインに加えて、 StorageGRID システムの他の領域に対する強化ガイドラインに従う必要があります。



== ログと監査メッセージ

StorageGRID ログおよび監査メッセージ出力は必ず安全な方法で保護してください。StorageGRID のログと監査メッセージは、サポートやシステム可用性の観点から非常に重要な情報を提供します。また、 StorageGRID のログおよび監査メッセージの出力に含まれる情報や詳細情報は、一般に機密性が高いため、

セキュリティイベントを外部 syslog サーバに送信するように StorageGRID を設定します。syslog エクスポートを使用する場合は、トランスポートプロトコルに対して TLS と RELP/TLS を選択します。

StorageGRID ログの詳細については、監視とトラブルシューティングの手順を参照してください。StorageGRID 監査メッセージの詳細については、監査メッセージに関する手順を参照してください。



== NetApp AutoSupport

StorageGRID の AutoSupport 機能を使用すると、システムの状態をプロアクティブに監視し、ネットアップテクニカルサポート、組織の社内サポートチーム、またはサポートパートナーにメッセージと詳細を自動的に送信できます。デフォルトでは、 StorageGRID を初めて設定した場合、ネットアップテクニカルサポートへの AutoSupport メッセージが有効になります。

AutoSupport 機能は無効にすることができます。ただし、 StorageGRID システムで問題 に障害が発生した場合には、 AutoSupport を使用して迅速に問題を識別し解決できるため、ネットアップではこの機能を有効にすることを推奨してい

AutoSupport は、転送プロトコルとして HTTPS 、 HTTP 、 SMTP をサポートしています。AutoSupport メッセージは機密性が高いため、ネットアップでは、 AutoSupport メッセージをネットアップサポートに送信する際のデフォルト転送プロトコルとして HTTPS を使用することを強く推奨しています。

必要に応じて、管理ノードからネットアップテクニカルサポートへの AutoSupport 通信をより細かく制御するための管理プロキシを設定できます。StorageGRID の管理手順の管理プロキシの作成手順を参照してください。



== Cross-Origin Resource Sharing （ CORS ）

S3 バケットとバケット内のオブジェクトに他のドメインにある Web アプリケーションからアクセスできるようにする必要がある場合は、そのバケットに Cross-Origin Resource Sharing （ CORS ）を設定できます。一般に、 CORS は必要でないかぎり有効にしないでください。CORS が必要な場合は、信頼できるオリジンに制限します。

テナントアカウントの使用手順の Cross-Origin Resource Sharing （ CORS ）の設定手順を参照してください。



== 外部セキュリティデバイス

完全なセキュリティ強化解決策 は、 StorageGRID 以外のセキュリティメカニズムに対応する必要があります。StorageGRID へのアクセスをフィルタリングおよび制限するために追加のインフラデバイスを使用すると、厳格なセキュリティ体制を確立し、維持するための効果的な方法となります。これらの外部セキュリティデバイスには、ファイアウォール、 Intrusion Prevention System （ IPS ；侵入防御システム）、およびその他のセキュリティデバイスが含まれます。

信頼されないクライアントトラフィックには、サードパーティのロードバランサを使用することを推奨します。サードパーティ製のロードバランシングにより、攻撃に対する制御性が向上し、追加の保護レイヤが提供されます。

.関連情報
xref:../monitor/index.adoc[監視とトラブルシューティング]

xref:../audit/index.adoc[監査ログを確認します]

xref:../tenant/index.adoc[テナントアカウントを使用する]

xref:../admin/index.adoc[StorageGRID の管理]
