---
permalink: swift/container-operations.html 
sidebar: sidebar 
keywords: swift container operations 
summary: StorageGRID では、 Swift アカウントあたり最大で 1 、 000 個のコンテナがサポートされます。コンテナに対して実行する Swift API 処理を次に示します。 
---
= コンテナの処理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID では、 Swift アカウントあたり最大で 1 、 000 個のコンテナがサポートされます。コンテナに対して実行する Swift API 処理を次に示します。



== コンテナを削除します

この処理は、 StorageGRID システムの Swift アカウントから空のコンテナを削除します。

次の要求パラメータが必要です。

* 「アカウント」
* 「コンテナ」


次の要求ヘッダーが必要です。

* 「 X-Auth-Token 」


実行が成功すると、「 HTTP/1.1 204 No Content 」の応答とともに次のヘッダーが返されます。

* 「 Content-Length 」
* 「 Content-Type 」
* 「日付」
* 「 X-Trans-ID 」




== GET コンテナ

この処理は、コンテナに関連付けられているオブジェクトリストを、 StorageGRID システム内のコンテナの統計情報およびメタデータとともに読み出します。

次の要求パラメータが必要です。

* 「アカウント」
* 「コンテナ」


次の要求ヘッダーが必要です。

* 「 X-Auth-Token 」


次のサポートされている要求クエリパラメータはオプションです。

* 「デリミタ」
* 「 End_marker 」のように入力します
* 「フォーマット」
* 「制限」
* 「マーカー」
* 「パス」
* 「接頭辞」


実行が成功すると、「 HTTP/1.1 200 Success 」または「 HTTP/1.1 204 No Content 」の応答とともに次のヘッダーが返されます。

* 「 Accept-Ranges 」を参照してください
* 「 Content-Length 」
* 「 Content-Type 」
* 「日付」
* 「 X-Container-Bytes - Used 」
* 「 X-Container-Object-Count 」
* 「 X - タイムスタンプ」
* 「 X-Trans-ID 」




== HEAD コンテナ

この処理は、 StorageGRID システムからコンテナの統計情報とメタデータを読み出します。

次の要求パラメータが必要です。

* 「アカウント」
* 「コンテナ」


次の要求ヘッダーが必要です。

* 「 X-Auth-Token 」


実行が成功すると、「 HTTP/1.1 204 No Content 」の応答とともに次のヘッダーが返されます。

* 「 Accept-Ranges 」を参照してください
* 「 Content-Length 」
* 「日付」
* 「 X-Container-Bytes - Used 」
* 「 X-Container-Object-Count 」
* 「 X - タイムスタンプ」
* 「 X-Trans-ID 」




== PUT コンテナ

この処理は、 StorageGRID システムのアカウントにコンテナを作成します。

次の要求パラメータが必要です。

* 「アカウント」
* 「コンテナ」


次の要求ヘッダーが必要です。

* 「 X-Auth-Token 」


実行が成功すると、「 HTTP/1.1 201 Created 」または「 HTTP/1.1 202 Accepted 」の応答（このアカウントにコンテナがすでに存在する場合）とともに次のヘッダーが返されます。

* 「 Content-Length 」
* 「日付」
* 「 X - タイムスタンプ」
* 「 X-Trans-ID 」


コンテナ名は StorageGRID ネームスペース内で一意である必要があります。このコンテナが別のアカウントの下に存在する場合は、ヘッダー「 HTTP/1.1 409 Conflict 」が返されます。

.関連情報
xref:monitoring-and-auditing-operations.adoc[監視と監査の処理]
