---
permalink: network/general-networking-requirements.html 
sidebar: sidebar 
keywords: networking requirements, storagegrid networks 
summary: すべての StorageGRID 環境で次の接続がサポートされている必要があります。 
---
= 一般的なネットワーク要件
:icons: font
:imagesdir: ../media/


[role="lead"]
すべての StorageGRID 環境で次の接続がサポートされている必要があります。

これらの接続は、ネットワークトポロジの例に示すように、グリッドネットワーク、管理ネットワーク、クライアントネットワーク、またはこれらのネットワークの組み合わせを介して発生します。

* * 管理接続 * ：通常は SSH 経由で、管理者からノードへのインバウンド接続。Grid Manager 、テナントマネージャ、および StorageGRID アプライアンスインストーラへの Web ブラウザアクセス
* *NTP サーバ接続 *: 受信 UDP 応答を受信するアウトバウンド UDP 接続。
+
プライマリ管理ノードが、少なくとも 1 つの NTP サーバにアクセスできる必要があります。

* *DNS サーバ接続 *: 受信 UDP 応答を受信するアウトバウンド UDP 接続。
* *LDAP/Active Directory サーバ接続 *: ストレージノード上のアイデンティティサービスからのアウトバウンド TCP 接続。
* *TCP*: 管理ノードからの AutoSupport 接続を、 support.netapp.com` またはお客様が設定したプロキシのいずれかに送信します。
* * 外部キー管理サーバ * ：ノード暗号化が有効な各アプライアンスノードからのアウトバウンド TCP 接続。
* S3 および Swift クライアントからのインバウンド TCP 接続。
* CloudMirror レプリケーションやクラウドストレージプールなどの StorageGRID プラットフォームサービスからのアウトバウンド要求。


デフォルトのルーティングルールを使用して、プロビジョニングされた NTP サーバや DNS サーバと StorageGRID が通信できない場合は、 DNS サーバと NTP サーバの IP アドレスが指定されていれば、すべてのネットワーク（グリッド、管理、クライアント）で自動的に接続が試行されます。NTP サーバまたは DNS サーバにネットワーク経由でアクセスできる場合は、 StorageGRID によって追加のルーティングルールが自動的に作成され、以降のすべてのネットワーク接続試行に使用されるようになります。


IMPORTANT: これらの自動検出されたホストルートは使用できますが、通常は、自動検出が失敗した場合に接続を確保するために、 DNS ルートと NTP ルートを手動で設定する必要があります。

導入時にオプションの管理ネットワークとクライアントネットワークを設定する準備ができていなかった場合は、設定手順でグリッドノードを承認する際にこれらのネットワークを設定できます。また、インストールが完了したら、 IP 変更ツールを使用してこれらのネットワークを設定することもできます（を参照） xref:../maintain/configuring-ip-addresses.adoc[IP アドレスを設定する]）。



== 管理ノードとゲートウェイノードの接続

管理ノードは、開いているインターネット上のノードなど、信頼されていないクライアントから常に保護する必要があります。グリッドネットワーク上、管理ネットワーク上、またはクライアントネットワーク上のどの管理ノードにも、信頼されていないクライアントがアクセスできないようにする必要があります。

ハイアベイラビリティグループに追加する管理ノードとゲートウェイノードには静的 IP アドレスを設定する必要があります。を参照してください xref:../admin/managing-high-availability-groups.adoc[ハイアベイラビリティグループを管理します]。



== ネットワークアドレス変換（ NAT ）の使用

グリッドノード間または StorageGRID サイト間のグリッドネットワークでは、ネットワークアドレス変換（ NAT ）を使用しないでください。グリッドネットワークにプライベート IPv4 アドレスを使用する場合は、使用するアドレスに各サイトのすべてのグリッドノードから直接ルーティングできる必要があります。ただし、必要に応じて、ゲートウェイノードにパブリック IP アドレスを指定するなど、外部クライアントとグリッドノードの間で NAT を使用できます。NAT を使用してパブリックネットワークセグメントをブリッジする方法は、グリッド内のすべてのノードに対して透過的なトンネリングアプリケーションを採用する場合、つまりグリッドノードがパブリック IP アドレスを認識する必要がない場合にのみサポートされます。
