---
permalink: network/index.html 
sidebar: sidebar 
keywords: storagegrid, network, networking, ethernet, subnet, routing 
summary: これらのガイドラインを使用して、 StorageGRID アーキテクチャとネットワークトポロジについて学び、ネットワークの設定とプロビジョニングの要件を確認してください。 
---
= ネットワークガイドライン：概要
:icons: font
:imagesdir: ../media/


[role="lead"]
これらのガイドラインを使用して、 StorageGRID アーキテクチャとネットワークトポロジについて学び、ネットワークの設定とプロビジョニングの要件を確認してください。



== これらの手順について

これらのガイドラインは、 StorageGRID ノードを導入して設定する前に、 StorageGRID ネットワークインフラの作成に使用できる情報を示しています。これらのガイドラインを使用して、グリッド内のすべてのノード間、およびグリッドと外部のクライアントとサービス間で通信を確実に行うことができます。

外部クライアントや外部サービスは、次のような機能を実行するために StorageGRID ネットワークに接続する必要があります。

* オブジェクトデータを格納し、読み出す
* E メール通知を受信
* StorageGRID 管理インターフェイス（ Grid Manager およびテナントマネージャ）へのアクセス
* 監査共有へのアクセス（オプション）
* 次のようなサービスを提供します。
+
** ネットワークタイムプロトコル NTP
** Domain Name System （ DNS ；ドメインネームシステム）
** キー管理サーバ（ KMS ）




これらの機能を使用するトラフィックなどを処理するには、 StorageGRID ネットワークが適切に設定されている必要があります。



== 作業を開始する前に

StorageGRID システムのネットワークを設定するには、イーサネットスイッチング、 TCP/IP ネットワーク、サブネット、ネットワークルーティング、およびファイアウォールに関する高度な経験が必要です。

ネットワークを設定する前に、『』の説明に従って StorageGRID アーキテクチャを理解しておいてください xref:../primer/index.adoc[グリッド入門]。

使用する StorageGRID ネットワークとその設定を決定したら、該当する手順に従って StorageGRID ノードを設置および設定できます。

.ソフトウェアベースのノードをインストール
* xref:../rhel/index.adoc[Red Hat Enterprise Linux または CentOS をインストールします]
* xref:../ubuntu/index.adoc[Ubuntu または Debian をインストールします]
* xref:../vmware/index.adoc[VMware をインストールする]


.アプライアンスノードを設置
* xref:../sg100-1000/index.adoc[SG100 および SG1000 サービスアプライアンス]
* xref:../sg6000/index.adoc[SG6000 ストレージアプライアンス]
* xref:../sg5700/index.adoc[SG5700 ストレージアプライアンス]
* xref:../sg5600/index.adoc[SG5600 ストレージアプライアンス]


.StorageGRID ソフトウェアを設定および管理する
* xref:../admin/index.adoc[StorageGRID の管理]
* xref:../release-notes/index.adoc[リリースノート]

