---
permalink: network/internal-grid-node-communications.html 
sidebar: sidebar 
keywords: storagegrid, network port, internal communications, ports, TCP, UDP, grid communications 
summary: StorageGRID の内部ファイアウォールは、ポート 22 、 80 、 123 、 443 を除き、グリッドネットワーク上の特定のポートへの受信接続のみを許可します（外部通信に関する情報を参照）。ロードバランサエンドポイントで定義されたポートにも接続が許可されます。 
---
= 内部でのグリッドノードの通信
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID の内部ファイアウォールは、ポート 22 、 80 、 123 、 443 を除き、グリッドネットワーク上の特定のポートへの受信接続のみを許可します（外部通信に関する情報を参照）。ロードバランサエンドポイントで定義されたポートにも接続が許可されます。


NOTE: グリッドノード間で Internet Control Message Protocol （ ICMP ）トラフィックを有効にすることを推奨します。ICMP トラフィックを許可すると、グリッドノードに到達できない場合のフェイルオーバーパフォーマンスを向上させることができます。

StorageGRID では、 ICMP と表に記載されているポートに加えて、 Virtual Router Redundancy Protocol （ VRRP; 仮想ルータ冗長プロトコル）を使用します。VRRP は、 IP プロトコル番号 112 を使用するインターネットプロトコルです。StorageGRID は、ユニキャストモードでのみ VRRP を使用します。VRRP が必要なのは、の場合だけです xref:../admin/managing-high-availability-groups.adoc[ハイアベイラビリティグループ] が設定されている。



== Linux ベースのノードについてはガイドラインを参照してください

これらのいずれかのポートへのアクセスがエンタープライズネットワークポリシーで制限されている場合は、導入設定パラメータを使用して導入時にポートを再マッピングできます。ポートの再マッピングおよび導入設定パラメータの詳細については、次のサイトを参照してください。

* xref:../rhel/index.adoc[Red Hat Enterprise Linux または CentOS をインストールします]
* xref:../ubuntu/index.adoc[Ubuntu または Debian をインストールします]




== VMware ベースのノードについてのガイドラインを参照してください

次のポートは、 VMware ネットワーク外部のファイアウォール制限を定義する必要がある場合にのみ設定してください。

これらのいずれかのポートへのアクセスがエンタープライズネットワークポリシーによって制限される場合は、ノードを導入する際に VMware vSphere Web Client を使用してポートを再マッピングするか、またはグリッドノードの導入を自動化する際に構成ファイルの設定を使用してポートを再マッピングできます。ポートの再マッピングおよび導入設定パラメータの詳細については、を参照してくださいxref:../vmware/index.adoc[VMware をインストールする]。



== アプライアンスノードのガイドライン

これらのいずれかのポートへのアクセスがエンタープライズネットワークポリシーで制限されている場合は、 StorageGRID アプライアンスインストーラを使用してポートを再マッピングできます。アプライアンスのポート再マッピングの詳細については、次のサイトを参照してください。

* xref:../sg100-1000/index.adoc[SG100 および SG1000 サービスアプライアンス]
* xref:../sg6000/index.adoc[SG6000 ストレージアプライアンス]
* xref:../sg5700/index.adoc[SG5700 ストレージアプライアンス]
* xref:../sg5600/index.adoc[SG5600 ストレージアプライアンス]




== StorageGRID の内部ポート

|===


| ポート | tcp または udp です | 移動元 | 終了： | 詳細 


 a| 
22
 a| 
TCP
 a| 
プライマリ管理ノード
 a| 
すべてのノード
 a| 
メンテナンス手順では、プライマリ管理ノードがポート 22 で SSH を使用して他のすべてのノードと通信できる必要があります。他のノードからの SSH トラフィックの許可は任意です。



 a| 
80
 a| 
TCP
 a| 
アプライアンス
 a| 
プライマリ管理ノード
 a| 
StorageGRID アプライアンスが、インストールを開始する目的でプライマリ管理ノードと通信するために使用します。



 a| 
123
 a| 
UDP
 a| 
すべてのノード
 a| 
すべてのノード
 a| 
ネットワークタイムプロトコルサービス。すべてのノードは、 NTP を使用して他のすべてのノードと時間を同期します。



 a| 
443
 a| 
TCP
 a| 
すべてのノード
 a| 
プライマリ管理ノード
 a| 
インストールおよびその他のメンテナンス手順の実行中に、プライマリ管理ノードにステータスを通知するために使用します。



 a| 
1139
 a| 
TCP
 a| 
ストレージノード
 a| 
ストレージノード
 a| 
ストレージノード間の内部トラフィック。



 a| 
1501 年
 a| 
TCP
 a| 
すべてのノード
 a| 
ADC を採用するストレージノード
 a| 
レポート、監査、および設定の内部トラフィック。



 a| 
1502
 a| 
TCP
 a| 
すべてのノード
 a| 
ストレージノード
 a| 
S3 および Swift 関連の内部トラフィック。



 a| 
1504.
 a| 
TCP
 a| 
すべてのノード
 a| 
管理ノード
 a| 
NMS サービスのレポートおよび設定の内部トラフィック。



 a| 
1505.
 a| 
TCP
 a| 
すべてのノード
 a| 
管理ノード
 a| 
AMS サービスの内部トラフィック。



 a| 
1506.
 a| 
TCP
 a| 
すべてのノード
 a| 
すべてのノード
 a| 
サーバステータスの内部トラフィック。



 a| 
1507
 a| 
TCP
 a| 
すべてのノード
 a| 
ゲートウェイノード
 a| 
ロードバランサの内部トラフィック。



 a| 
1508
 a| 
TCP
 a| 
すべてのノード
 a| 
プライマリ管理ノード
 a| 
設定管理の内部トラフィック。



 a| 
1509.
 a| 
TCP
 a| 
すべてのノード
 a| 
アーカイブノード
 a| 
アーカイブノードの内部トラフィック。



 a| 
1511.
 a| 
TCP
 a| 
すべてのノード
 a| 
ストレージノード
 a| 
メタデータの内部トラフィック。



 a| 
5353
 a| 
UDP
 a| 
すべてのノード
 a| 
すべてのノード
 a| 
必要に応じて、フルグリッドの IP 変更、およびインストール、拡張、リカバリ時のプライマリ管理ノードの検出に使用します。



 a| 
7001
 a| 
TCP
 a| 
ストレージノード
 a| 
ストレージノード
 a| 
Cassandra TLS ノード間クラスタ通信。



 a| 
7443
 a| 
TCP
 a| 
すべてのノード
 a| 
管理ノード
 a| 
メンテナンス手順およびエラーレポート用の内部トラフィック。



| 8443 | TCP | プライマリ管理ノード | アプライアンスノード | メンテナンスモードの手順 に関連する内部トラフィック。 


 a| 
9042
 a| 
TCP
 a| 
ストレージノード
 a| 
ストレージノード
 a| 
Cassandra クライアントポート。



 a| 
9999
 a| 
TCP
 a| 
すべてのノード
 a| 
すべてのノード
 a| 
複数のサービスの内部トラフィック。メンテナンス手順、指標、およびネットワークの更新が含まれます。



 a| 
10226
 a| 
TCP
 a| 
ストレージノード
 a| 
プライマリ管理ノード
 a| 
StorageGRID アプライアンスが、 E シリーズの SANtricity System Manager からプライマリ管理ノードに AutoSupport メッセージを転送するために使用します。



 a| 
11139
 a| 
TCP
 a| 
アーカイブ / ストレージノード
 a| 
アーカイブ / ストレージノード
 a| 
ストレージノードとアーカイブノード間の内部トラフィック。



 a| 
18000 年
 a| 
TCP
 a| 
管理 / ストレージノード
 a| 
ADC を採用するストレージノード
 a| 
アカウントサービスの内部トラフィック。



 a| 
18001
 a| 
TCP
 a| 
管理 / ストレージノード
 a| 
ADC を採用するストレージノード
 a| 
アイデンティティフェデレーションの内部トラフィック。



 a| 
18002
 a| 
TCP
 a| 
管理 / ストレージノード
 a| 
ストレージノード
 a| 
オブジェクトプロトコルに関連する内部 API トラフィック。



 a| 
18003 年
 a| 
TCP
 a| 
管理 / ストレージノード
 a| 
ADC を採用するストレージノード
 a| 
プラットフォームサービスの内部トラフィック。



 a| 
18017 年
 a| 
TCP
 a| 
管理 / ストレージノード
 a| 
ストレージノード
 a| 
クラウドストレージプールの Data Mover サービスの内部トラフィック。



 a| 
18019 年になります
 a| 
TCP
 a| 
ストレージノード
 a| 
ストレージノード
 a| 
イレイジャーコーディング用のチャンクサービスの内部トラフィック。



 a| 
18082 年
 a| 
TCP
 a| 
管理 / ストレージノード
 a| 
ストレージノード
 a| 
S3 関連の内部トラフィック。



 a| 
18083 年
 a| 
TCP
 a| 
すべてのノード
 a| 
ストレージノード
 a| 
Swift 関連の内部トラフィック。



 a| 
18200 年
 a| 
TCP
 a| 
管理 / ストレージノード
 a| 
ストレージノード
 a| 
クライアント要求に関する追加の統計。



 a| 
19000 年
 a| 
TCP
 a| 
管理 / ストレージノード
 a| 
ADC を採用するストレージノード
 a| 
Keystone サービスの内部トラフィック。

|===
* 関連情報 *

xref:external-communications.adoc[外部との通信]
