---
permalink: network/networking-and-ports-for-platform-services-and-cloud-storage-pools.html 
sidebar: sidebar 
keywords: networking for platform services, networking for cloud storage pools 
summary: StorageGRID プラットフォームサービスまたはクラウドストレージプールを使用する場合は、デスティネーションエンドポイントに到達できるようにグリッドネットワークとファイアウォールを設定する必要があります。 
---
= プラットフォームサービスとクラウドストレージプール用のネットワークとポート
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID プラットフォームサービスまたはクラウドストレージプールを使用する場合は、デスティネーションエンドポイントに到達できるようにグリッドネットワークとファイアウォールを設定する必要があります。



== プラットフォームサービス用のネットワーク

を参照してください xref:../admin/manage-platform-services-for-tenants.adoc[テナントのプラットフォームサービスを管理する] および xref:../tenant/what-platform-services-are.adoc[プラットフォームサービスとは]プラットフォームサービスには、検索統合、イベント通知、 CloudMirror レプリケーションを提供する外部サービスが含まれます。

プラットフォームサービスには、 StorageGRID ADC サービスをホストするストレージノードから外部サービスエンドポイントへのアクセスが必要です。アクセスの提供例は次のとおりです。

* ADC サービスがあるストレージノードで、ターゲットエンドポイントにルーティングする AESL エントリを使用して一意の管理ネットワークを設定します。
* クライアントネットワークが提供するデフォルトルートを使用します。デフォルトルートを使用する場合は、を使用できます xref:../admin/managing-untrusted-client-networks.adoc[信頼されていないクライアントネットワーク機能] インバウンド接続を制限する。




== クラウドストレージプールのネットワーク

また、クラウドストレージプールは、ストレージノードから、 Amazon S3 Glacier や Microsoft Azure BLOB ストレージなどの使用する外部サービスが提供するエンドポイントへのアクセスを必要とします。詳細については、を参照してください xref:../ilm/what-cloud-storage-pool-is.adoc[クラウドストレージプールとは]。



== プラットフォームサービスとクラウドストレージプールのポート

デフォルトでは、プラットフォームサービスとクラウドストレージプールの通信には次のポートが使用されます。

* *80*: エンドポイント URI の場合 'http' で始まります
* *442*: エンドポイント URI の場合は 'https' で始まります


エンドポイントの作成時または編集時に別のポートを指定できます。を参照してください xref:network-port-reference.adoc[ネットワークポートのリファレンス]。

非透過型プロキシサーバを使用する場合は、も使用する必要があります xref:../admin/configuring-storage-proxy-settings.adoc[ストレージプロキシを設定します] インターネット上のエンドポイントなどの外部エンドポイントへのメッセージの送信を許可します。



== VLAN およびプラットフォームサービスとクラウドストレージプール

プラットフォームサービスやクラウドストレージプールに VLAN ネットワークを使用することはできません。デスティネーションエンドポイントには、グリッドネットワーク、管理ネットワーク、またはクライアントネットワーク経由でアクセスできる必要があります。
