---
permalink: sg5600/gathering-installation-information-sg5600.html 
sidebar: sidebar 
keywords: storagegrid, sg5600, storage node, storage appliance, install, information, site, pre-install, preparing, prepare, preinstall, info, preparation 
summary: StorageGRID アプライアンスを設置および設定する際に、イーサネットスイッチポート、 IP アドレス、およびポートとネットワークのボンディングモードについて決定し、関連情報を収集する必要があります。 
---
= 設置情報の収集（ SG5600 ）
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID アプライアンスを設置および設定する際に、イーサネットスイッチポート、 IP アドレス、およびポートとネットワークのボンディングモードについて決定し、関連情報を収集する必要があります。

次の表を使用して、アプライアンスに接続する各ネットワークの情報を記録できます。これらの値は、ハードウェアの設置と設定に必要です。



== E2700 コントローラを SANtricity Storage Manager に接続するために必要な情報

SANtricity Storage Manager で使用する管理ネットワークに E2700 コントローラを接続する必要があります。

|===
| 必要な情報 | あなたの価値 


 a| 
管理ポート 1 に接続するイーサネットスイッチポート
 a| 



 a| 
管理ポート 1 の MAC アドレス（ポート P1 のラベルに記載）
 a| 



 a| 
DHCP によって管理ポート 1 に割り当てられた IP アドレス（電源投入後に使用可能な場合）

* 注： * E2700 コントローラに接続するネットワークに DHCP サーバがある場合、ネットワーク管理者は、 MAC アドレスを使用して DHCP サーバによって割り当てられた IP アドレスを特定できます。
 a| 



 a| 
速度と二重モード

* 注： SANtricity Storage Manager 管理ネットワークのイーサネットスイッチが自動ネゴシエーションに設定されていることを確認する必要があります。
 a| 
次の値でなければなりません

* Autonegotiate （デフォルト）




 a| 
IP アドレスの形式
 a| 
1 つ選択してください：

* IPv4
* IPv6




 a| 
管理ネットワークでアプライアンスに使用する静的 IP アドレス
 a| 
IPv4 の場合：

* IPv4 アドレス：
* サブネットマスク：
* ゲートウェイ


IPv6 の場合：

* IPv6 アドレス：
* ルーティング可能な IP アドレス：
* E2700 コントローラルータの IP アドレス：


|===


== E5600SG コントローラを管理ネットワークに接続するために必要な情報

StorageGRID の管理ネットワークは、システムの管理とメンテナンスに使用するオプションのネットワークです。アプライアンスは、 E5600SG コントローラの 1GbE 管理ポートを使用して管理ネットワークに接続します。

|===
| 必要な情報 | あなたの価値 


 a| 
管理ネットワークが有効になりました
 a| 
1 つ選択してください：

* いいえ
* ○（デフォルト）




 a| 
ネットワークボンディングモード
 a| 
1 つ選択してください：

* 独立
* アクティブ / バックアップ




 a| 
管理ポート 1 （ P1 ）のスイッチポート
 a| 



 a| 
管理ポート 2 のスイッチポート（ P2 、アクティブ / バックアップネットワークボンディングモードのみ）
 a| 



 a| 
管理ポート 1 の MAC アドレス（ポート P1 のラベルに記載）
 a| 



 a| 
DHCP によって管理ポート 1 に割り当てられた IP アドレス（電源投入後に使用可能な場合）

* 注： * 管理ネットワークに DHCP サーバが含まれている場合、 E5600SG コントローラのブート後はデジタル表示ディスプレイに DHCP によって割り当てられた IP アドレスが表示されます。DHCP によって割り当てられた IP アドレスは、 MAC アドレスを使用して IP アドレスを調べる方法でも確認できます。
 a| 
* IPv4 アドレス（ CIDR ）：
* ゲートウェイ




 a| 
管理ネットワークでアプライアンスストレージノードに使用する静的 IP アドレス

* 注： * ネットワークにゲートウェイがない場合は、同じ静的 IPv4 アドレスをゲートウェイに指定してください。
 a| 
* IPv4 アドレス（ CIDR ）：
* ゲートウェイ




 a| 
管理ネットワークのサブネット（ CIDR ）
 a| 

|===


== E5600SG コントローラで 10GbE ポートの接続と設定に必要な情報

E5600SG コントローラの 4 つの 10GbE ポートは、 StorageGRID のグリッドネットワークとクライアントネットワークに接続します。


NOTE: これらのポートのオプションの詳細については、「 E5600SG コントローラでの 10GbE ポート接続」を参照してください。

|===
| 必要な情報 | あなたの価値 


 a| 
ポートボンディングモード
 a| 
1 つ選択してください：

* Fixed （デフォルト）
* アグリゲート




 a| 
ポート 1 のスイッチポート（固定モードのクライアントネットワーク）
 a| 



 a| 
ポート 2 のスイッチポート（ Fixed モードのグリッドネットワーク）
 a| 



 a| 
ポート 3 のスイッチポート（固定モードのクライアントネットワーク）
 a| 



 a| 
ポート 4 のスイッチポート（ Fixed モードのグリッドネットワーク）
 a| 

|===


== E5600SG コントローラをグリッドネットワークに接続するために必要な情報

StorageGRID のグリッドネットワークは、内部のすべての StorageGRID トラフィックに使用される必須のネットワークです。アプライアンスは、 E5600SG コントローラの 10GbE ポートを使用してグリッドネットワークに接続します。


NOTE: これらのポートのオプションの詳細については、「 E5600SG コントローラでの 10GbE ポート接続」を参照してください。

|===
| 必要な情報 | あなたの価値 


 a| 
ネットワークボンディングモード
 a| 
1 つ選択してください：

* Active-Backup （デフォルト）
* LACP （ 802.3ad ）




 a| 
VLAN タギングが有効です
 a| 
1 つ選択してください：

* いいえ（デフォルト）
* はい。




 a| 
VLAN タグ（ VLAN タギングが有効な場合）
 a| 
0~4095 の値を入力してください：



 a| 
電源投入後に使用可能な場合、 DHCP によってグリッドネットワークに割り当てられた IP アドレス

* 注： * グリッドネットワークに DHCP サーバが含まれている場合、 E5600SG コントローラのブート後にデジタル表示ディスプレイにグリッドネットワークに対して DHCP によって割り当てられた IP アドレスが表示されます。
 a| 
* IPv4 アドレス（ CIDR ）：
* ゲートウェイ




 a| 
グリッドネットワークでアプライアンスストレージノードに使用する静的 IP アドレス

* 注： * ネットワークにゲートウェイがない場合は、同じ静的 IPv4 アドレスをゲートウェイに指定してください。
 a| 
* IPv4 アドレス（ CIDR ）：
* ゲートウェイ




 a| 
グリッドネットワークのサブネット（ CIDR ）

* 注： * クライアントネットワークが有効になっていない場合、コントローラのデフォルトルートではここで指定したゲートウェイが使用されます。
 a| 

|===


== E5600SG コントローラをクライアントネットワークに接続するために必要な情報

StorageGRID のクライアントネットワークは、グリッドへのクライアントプロトコルアクセスを可能にするオプションのネットワークです。アプライアンスは、 E5600SG コントローラの 10GbE ポートを使用してクライアントネットワークに接続します。


NOTE: これらのポートのオプションの詳細については、「 E5600SG コントローラでの 10GbE ポート接続」を参照してください。

|===
| 必要な情報 | あなたの価値 


 a| 
クライアントネットワークが有効になりました
 a| 
1 つ選択してください：

* いいえ（デフォルト）
* はい。




 a| 
ネットワークボンディングモード
 a| 
1 つ選択してください：

* Active-Backup （デフォルト）
* LACP （ 802.3ad ）




 a| 
VLAN タギングが有効です
 a| 
1 つ選択してください：

* いいえ（デフォルト）
* はい。




 a| 
VLAN タグ（ VLAN タギングが有効な場合）
 a| 
0~4095 の値を入力してください：



 a| 
電源投入後に DHCP によってクライアントネットワークに割り当てられた IP アドレスがある場合は
 a| 
* IPv4 アドレス（ CIDR ）：
* ゲートウェイ




 a| 
クライアントネットワークでアプライアンスストレージノードに使用する静的 IP アドレス

* 注： * クライアントネットワークが有効になっている場合、コントローラのデフォルトルートではここで指定したゲートウェイが使用されます。
 a| 
* IPv4 アドレス（ CIDR ）：
* ゲートウェイ


|===
xref:reviewing-appliance-network-connections-sg5600.adoc[SG5600 アプライアンスのネットワーク接続の確認]

xref:configuring-hardware.adoc[ハードウェアの設定（ SG5600 ）]

xref:port-bond-modes-for-e5600sg-controller-ports.adoc[E5600SG コントローラポートのポートボンディングモード]
