---
permalink: sg5600/hardware-setup-progress-appears-to-hang.html 
sidebar: sidebar 
keywords: storagegrid, sg5600, storage node, storage appliance, troubleshoot, troubleshooting, hardware, setup, hang, hangs, fails, failure, stop, terminate, terminates, stuck 
summary: ハードウェア障害やケーブル接続エラーによって E5600SG コントローラのブート処理が完了しなかった場合は、 StorageGRID アプライアンスインストーラを使用できないことがあります。 
---
= ハードウェアのセットアップがハングした場合（ SG5600 ）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ハードウェア障害やケーブル接続エラーによって E5600SG コントローラのブート処理が完了しなかった場合は、 StorageGRID アプライアンスインストーラを使用できないことがあります。

.手順
. いずれかのコントローラの警告 LED を確認し、点滅しているエラーコードを探します。
+
電源投入時は、ハードウェアの初期化が完了するまで、保守操作可能を示す LED と保守操作要を示す LED が点灯した状態になります。また、 _diagnostic LED_ という名前の下の桁の上の小数点も点灯します。デジタル表示ディスプレイには、両方のコントローラに共通のコードが順番に表示されます。これは正常な状態であり、エラーを示すものではありません。ハードウェアのブートが完了すると、保守操作の LED は消灯し、ディスプレイの制御がファームウェアに切り替わります。

. E5600SG コントローラのデジタル表示ディスプレイのコードを確認します。
+

NOTE: インストールとプロビジョニングには時間がかかります。フェーズによっては、 StorageGRID アプライアンスインストーラの更新が数分間報告されないこともあります。

+
エラーが発生すると、デジタル表示ディスプレイに HE などの一連のコードが点滅します。

. これらのコードの意味については、次のリソースを参照してください。
+
|===
| コントローラ | 参照 


 a| 
E5600SG コントローラ
 a| 
** "`he error:Error synchronizing with SANtricity OS Software`" （エラー： OS ソフトウェアとの同期エラー）
** "E5600SG コントローラのデジタル表示ディスプレイ・コード "




 a| 
E2700 コントローラ
 a| 
E シリーズのドキュメント

* 注： * E シリーズ E5600 コントローラに関するコードは、アプライアンスの E5600SG コントローラには適用されません。

|===
. この方法で問題 が解決しない場合は、テクニカルサポートにお問い合わせください。


xref:e5600sg-controller-seven-segment-display-codes.adoc[E5600SG コントローラのデジタル表示ディスプレイのコード]

xref:he-error-error-synchronizing-with-santricity-os-software.adoc[HE エラー： SANtricity OS ソフトウェアとの同期エラー]

https://library.netapp.com/ecm/ecm_download_file/ECMLP2344477["E2700 コントローラドライブトレイおよび関連ドライブトレイ設置ガイド"^]

http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61765["ネットアップのマニュアル： E2700 シリーズ"^]
