---
permalink: sg5600/index.html 
sidebar: sidebar 
keywords: storagegrid, sg5600, storage node, storage appliance, overview, models, features 
summary: StorageGRID SG5600 アプライアンスは、 StorageGRID グリッドにおいてストレージノードとして機能する、ストレージとコンピューティングを統合したプラットフォームです。 
---
= SG5600 アプライアンス：概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID SG5600 アプライアンスは、 StorageGRID グリッドにおいてストレージノードとして機能する、ストレージとコンピューティングを統合したプラットフォームです。

StorageGRID SG5600 アプライアンスには、次のコンポーネントが含まれています。

|===
| コンポーネント | 説明 


 a| 
E5600SG コントローラ
 a| 
コンピューティングサーバ E5600SG コントローラは Linux オペレーティングシステムと StorageGRID ソフトウェアを実行します。

このコントローラは次のものに接続されています。

* StorageGRID システムの管理、グリッド、クライアントネットワーク
* E2700 コントローラ。 E5600SG コントローラがイニシエータとして動作しているデュアル SAS パス（アクティブ / アクティブ）を使用します




 a| 
E2700 コントローラ
 a| 
ストレージコントローラ E2700 コントローラは、シンプレックスモードで標準の E シリーズストレージアレイとして動作し、 SANtricity オペレーティングシステム（コントローラファームウェア）を実行します。

このコントローラは次のものに接続されています。

* SANtricity Storage Manager がインストールされている管理ネットワーク
* E5600SG コントローラは、 E2700 コントローラがターゲットとして動作しているデュアル SAS パス（アクティブ / アクティブ）を使用する


|===
SG5600 アプライアンスには、モデルに応じて次のコンポーネントも含まれています。

|===
| コンポーネント | モデル SG5612 | モデル SG5660 


 a| 
ドライブ
 a| 
12 本の NL-SAS ドライブ
 a| 
NL-SAS ドライブ × 60



 a| 
エンクロージャ
 a| 
DE1600 エンクロージャ：ドライブとコントローラを収容する 2 ラックユニット（ 2U ）シャーシ
 a| 
DE6600 エンクロージャは、ドライブとコントローラを収納する 4 ラックユニット（ 4U ）シャーシです



 a| 
電源装置とファン
 a| 
電源 / ファンキャニスター × 2
 a| 
電源装置 × 2 、ファン × 2

|===

NOTE: E5600SG コントローラは、 StorageGRID アプライアンスで使用するために高度にカスタマイズされています。それ以外のコンポーネントは、それぞれの手順に記載されている点を除いて、 E シリーズのドキュメントで説明されているとおりに動作します。

各 StorageGRID アプライアンスストレージノードで使用可能な最大物理容量は固定であり、アプライアンスのモデルと構成に基づいて決まります。ドライブを増設したシェルフを追加してストレージを拡張することはできません。
