---
permalink: sg5600/replacing-e5600sg-controller.html 
sidebar: sidebar 
keywords: storagegrid, sg5600, storage node, storage appliance, hardware, Replacing, replace, E5600sg, controller, remove, removing, removal, install, installing, installation 
summary: E5600SG コントローラの交換が必要となる場合があります。 
---
= E5600SG コントローラの交換
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
E5600SG コントローラの交換が必要となる場合があります。

.必要なもの
次のリソースにアクセスできる必要があります。

* E シリーズハードウェアの交換に関する the NetApp Support Site at + の情報http://["mysupport.netapp.com"^]
* E5600 に関するサポートサイトのドキュメント
* アプライアンスは次のようになりました xref:placing-appliance-into-maintenance-mode.adoc[メンテナンスモードにしました]。


.このタスクについて
両方のコントローラが動作していて通常の方法でシャットダウンできる場合は、まず E5600SG コントローラをシャットダウンして E2700 コントローラへの接続を中断できます。


NOTE: StorageGRID ソフトウェアをインストールする前にコントローラを交換すると、この手順 の完了後すぐに StorageGRID アプライアンスインストーラにアクセスできない場合があります。アプライアンスと同じサブネット上の他のホストから StorageGRID アプライアンスインストーラにアクセスすることはできますが、他のサブネット上のホストからはアクセスできません。この状態は 15 分以内に（元のコントローラのいずれかの ARP キャッシュエントリがタイムアウトした時点で）自動的に解消されます。あるいは、古い ARP キャッシュエントリをローカルルータまたはゲートウェイから手動でパージすれば、すぐにこの状態を解消できます。

.手順
. 静電気防止処置を施します。
. 再接続するときにわかるように、 E5600SG コントローラに接続されている各ケーブルにラベルを付けます。
+

IMPORTANT: パフォーマンスの低下を防ぐために、ケーブルをねじったり、折り曲げたり、はさんだり、踏みつけたりしないでください。ケーブルを曲げないでください。半径が 5cm 以上になるようにしてください。

. アプライアンスがメンテナンスモードになったら、 E5600SG コントローラをシャットダウンします。
+
.. グリッドノードにログインします。
+
... 次のコマンドを入力します。 ssh admin@_grid_node_name
... 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
... root に切り替えるには、次のコマンドを入力します
... 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
+
root としてログインすると、プロンプトは「 $` 」から「 #」 に変わります。



.. E5600SG コントローラをシャットダウンします。 +`*shutdown-h now *`


. エンクロージャの電源をオフにし、コントローラの背面にあるすべての LED とデジタル表示ディスプレイの動作が停止するまで待ちます。
. ケーブルを取り外します。
. E5600SG コントローラのドキュメントの説明に従って、コントローラを取り外します。
. E5600SG コントローラのドキュメントの説明に従って、新しいコントローラを挿入します。
. すべてのケーブルを交換します。
. エンクロージャの電源を再度オンにします。
. デジタル表示のコードを監視します。
+
** E2700 コントローラ：
+
LED の最終状態は '99' です

** E5600SG コントローラ：
+
最後の LED の状態は「 ha 」です。



. Grid Manager で、アプライアンスストレージノードのステータスを監視します。
+
アプライアンスストレージノードが想定されるステータスに戻ったことを確認します。



.関連情報
https://["NetApp E シリーズおよび EF シリーズでのハードウェアの交換手順"^]

http://["ネットアップのマニュアル： E5600 シリーズ"^]
