---
permalink: sg5600/replacing-other-hardware-components-sg5600.html 
sidebar: sidebar 
keywords: storagegrid, sg5600, storage node, storage appliance, Replacing, replace, hardware, components, remove, removing, removal, install, installing, installation, drive, fan, power supply, battery 
summary: StorageGRID アプライアンスのドライブ、ファン、電源装置、またはバッテリの交換が必要になることがあります。 
---
= 他のハードウェアコンポーネントを交換します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID アプライアンスのドライブ、ファン、電源装置、またはバッテリの交換が必要になることがあります。

.必要なもの
* E シリーズハードウェアの交換用手順 を用意しておきます。
* アプライアンスは次のようになりました xref:placing-appliance-into-maintenance-mode.adoc[メンテナンスモードに切り替えられます] コンポーネントの交換用手順 でアプライアンスをシャットダウンする必要がある場合。


.このタスクについて
ドライブ、電源 / ファンキャニスター、ファンキャニスター、電源キャニスター、バッテリを交換する方法 またはドライブドロワーについては、 E2700 および E5600 ストレージアレイでの標準的な手順を参照してください。ハードウェア自体の取り外しや交換についてのステップバイステップの手順をよくお読みください。 SANtricity Storage Manager の手順の多くは、アプライアンスには当てはまりません。



== SG5612 コンポーネントの交換手順

|===
| FRU | を参照してください 


 a| 
ドライブ
 a| 
E2600 、 E2700 、 E5400 、 E5500 、 E5600 、 12 ドライブまたは 24 ドライブトレイのドライブを交換する場合は、 E シリーズの手順に従ってください。



 a| 
電源 / ファンキャニスター
 a| 
E シリーズの手順に従い、 E5612 または E5624 コントローラドライブトレイの電源 / ファンキャニスターで障害が発生した場合は交換します



 a| 
E2700 コントローラのバッテリ（コントローラの取り外しが必要）
 a| 
の手順に従います xref:replacing-e2700-controller.adoc[E2700 コントローラを交換します]をクリックします。ただし、既存のコントローラに新しいバッテリを取り付けます。

|===


== SG5660 コンポーネントの交換手順

|===
| FRU | を参照してください 


 a| 
ドライブ
 a| 
E シリーズの手順に従って、 E2660 、 E2760 、 E5460 、 E5560 、または E5660 トレイのドライブを交換します。



 a| 
電源キャニスター
 a| 
E シリーズの手順に従って、 E5660 コントローラドライブトレイの電源キャニスターに障害が発生した場合の交換を行ってください



 a| 
ファンキャニスター
 a| 
E シリーズの手順に従って、 E5660 コントローラドライブトレイのファンキャニスターで障害が発生した場合の交換を行ってください



 a| 
E2700 コントローラのバッテリ（コントローラの取り外しが必要）
 a| 
の手順に従います xref:replacing-e2700-controller.adoc[E2700 コントローラを交換します]をクリックします。ただし、既存のコントローラに新しいバッテリを取り付けます。

|===
.関連情報
https://["NetApp E シリーズおよび EF シリーズでのハードウェアの交換手順"^]

http://["ネットアップのマニュアル： E2700 シリーズ"^]

http://["ネットアップのマニュアル： E5600 シリーズ"^]
