---
permalink: sg5600/turning-power-on-sg5600.html 
sidebar: sidebar 
keywords: storagegrid, sg5600, storage node, storage appliance, power on, power, start 
summary: エンクロージャの電源を入れると、両方のコントローラの電源がオンになります。 
---
= 電源オン（ SG5600 ）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
エンクロージャの電源を入れると、両方のコントローラの電源がオンになります。

.手順
. エンクロージャの背面にある 2 つの電源スイッチをオンにします。
+
電源が投入されている間、コントローラの LED が断続的に点灯または消灯します。

+
電源投入プロセスが完了するまでに最大 10 分かかることがあります。最初の起動時にコントローラが数回リブートすると、ファンの速度が低下し、 LED が点滅します。

. 各コントローラの電源 LED とホストリンクアクティブ LED で、電源がオンになっていることを確認します。
. すべてのドライブが緑の永続的 LED で点灯し、オンラインになったことが示されるまで待ちます。
. エンクロージャの前面と背面に緑の LED があることを確認します。
+
オレンジ色の LED がある場合は、その場所をメモします。

. E5600SG コントローラのデジタル表示ディスプレイを確認します。
+
このディスプレイには * HO * が表示され、続いて 2 桁の数字が順番に表示されます。

+
[listing]
----
HO -- IP address for Admin Network -- IP address for Grid Network HO
----
+
最初に表示される数字は、コントローラの管理ポート 1 に対して DHCP によって割り当てられた IP アドレスです。このアドレスは、コントローラを StorageGRID の管理ネットワークに接続するときに使用されます。2 番目に表示される数字は、 StorageGRID のグリッドネットワークにアプライアンスを接続するときに使用される DHCP によって割り当てられた IP アドレスです。

+

NOTE: DHCP を使用して IP アドレスを割り当てることができなかった場合は、 0.0.0.0 と表示されます。


