= ストレージノードのホスト名を探します
:allow-uri-read: 




== ストレージノードのホスト名を探します

. プライマリ管理ノードにログインします。
+
.. 次のコマンドを入力します。 ssh admin@_primary_Admin_Node_IP_`
.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
.. root に切り替えるには、次のコマンドを入力します
.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
+
root としてログインすると、プロンプトは「 $` 」から「 #」 に変わります。



. 「 /etc/hosts 」ファイルを使用して、リストアされたストレージボリュームのストレージノードのホスト名を検索します。グリッド内のすべてのノードのリストを表示するには、「 cat /etc/hosts 」と入力します。




== すべてのボリュームで障害が発生した場合はデータを修復します

すべてのストレージボリュームで障害が発生した場合は、ノード全体を修復します。レプリケートデータ、イレイジャーコーディング（ EC ）データ、またはその両方を使用するかどうかに応じて、 * レプリケートデータ * 、 * イレイジャーコーディング（ EC ）データ * 、またはその両方の手順を実行します。

一部のボリュームだけで障害が発生した場合は、に進みます <<一部のボリュームのみで障害が発生した場合はデータを修復します>>。


IMPORTANT: 複数のノードに対して同時に「 repair-data 」操作を実行することはできません。複数のノードをリカバリする場合は、テクニカルサポートにお問い合わせください。

[role="tabbed-block"]
====
.レプリケートデータ
--
グリッドに複製データが含まれている場合は、「 --nodes 」オプションを指定して「 repair-data start-replicated-node-repair 」コマンドを使用し、ストレージノード全体を修復します。

次のコマンドは、 SG-DC-SN3 というストレージノードにあるレプリケートデータを修復します。

「 repair-data start-replicated-node-repair --nodes SG-DC-SN3 」を参照してください


NOTE: オブジェクトデータのリストア時、 StorageGRID システムがレプリケートされたオブジェクトデータを見つけられない場合は、 * Objects lost * アラートがトリガーされます。システム全体のストレージノードでアラートがトリガーされることがあります。損失の原因 と、リカバリが可能かどうかを確認する必要があります。を参照してください xref:../monitor/index.adoc[監視とトラブルシューティング]。

--
.イレイジャーコーディング（ EC ）データ
--
グリッドにイレイジャーコーディングされたデータがある場合は、「 --nodes 」オプションを指定して「 repair-data start-ec-node-repair 」コマンドを使用し、ストレージノード全体を修復します。

次のコマンドは、 SG-DC-SN3 というストレージノードにあるイレイジャーコーディングデータを修復します。

「 repair-data start-ec-node-repair -- ノード SG-DC-SN3 」

この「 repair_data 」操作を識別する一意の「 repair ID 」が返されます。この「修理 ID 」を使用して、「 repair_data 」操作の進行状況と結果を追跡します。リカバリプロセスが完了しても、それ以外のフィードバックは返されません。


NOTE: イレイジャーコーディングデータの修復は、一部のストレージノードがオフライン状態で開始できます。修復はすべてのノードが使用可能になったあとに完了します。

--
====


== 一部のボリュームのみで障害が発生した場合はデータを修復します

一部のボリュームだけで障害が発生した場合は、影響を受けたボリュームを修復します。レプリケートデータ、イレイジャーコーディング（ EC ）データ、またはその両方を使用するかどうかに応じて、 * レプリケートデータ * 、 * イレイジャーコーディング（ EC ）データ * 、またはその両方の手順を実行します。

すべてのボリュームで障害が発生した場合は、に進みます <<すべてのボリュームで障害が発生した場合はデータを修復します>>。

ボリューム ID を 16 進数で入力します。例えば、「 0000 」は最初のボリュームで、「 000F 」は 16 番目のボリュームです。1 つのボリューム、一連のボリューム、または連続していない複数のボリュームを指定できます。

すべてのボリュームが同じストレージノードにある必要があります。複数のストレージノードのボリュームをリストアする必要がある場合は、テクニカルサポートにお問い合わせください。

[role="tabbed-block"]
====
.レプリケートデータ
--
グリッドにレプリケートされたデータが含まれている場合は 'start-replicated-volume-repair コマンドに --nodes オプションを指定して ' ノードを識別します次に ' 次の例に示すように '--volums' または --volume-range オプションを追加します

* 単一ボリューム * ：次のコマンドは、 SG-DC-SN3 というストレージノードのボリューム「 0002 」にレプリケートデータをリストアします。

「 repair-data start-replicated-volume-repair -- nodes SG-DC-SN3 -- volumes 0002

* ボリューム範囲 *: 次のコマンドは 'SG-DC-SN3 というストレージノードの 0003' ～ 0009' の範囲のすべてのボリュームにレプリケートデータをリストアします

`repair-data start-replicated-volume-repair --nodes SG-DC-SN3 --volume-range 0003,0009`

* 複数のボリュームが連続していません * ：このコマンドは 'SG-DC-SN3 というストレージノードのボリューム 0001' 0005' および 0008' にレプリケートデータをリストアします

「 repair-data start-replicated-volume-repair -- ノード SG-DC-SN3 -- ボリューム 0001,0005,0008`


NOTE: オブジェクトデータのリストア時、 StorageGRID システムがレプリケートされたオブジェクトデータを見つけられない場合は、 * Objects lost * アラートがトリガーされます。システム全体のストレージノードでアラートがトリガーされることがあります。損失の原因 と、リカバリが可能かどうかを確認する必要があります。StorageGRID の監視とトラブルシューティングの手順を参照してください。

--
.イレイジャーコーディング（ EC ）データ
--
グリッドにイレイジャーコーディングされたデータが含まれている場合は 'start-ec-volume-repair コマンドに --nodes オプションを指定して ' ノードを識別します次に ' 次の例に示すように '--volums' または --volume-range オプションを追加します

* 単一ボリューム * ：次のコマンドは、 SG-DC-SN3 というストレージノード上のボリューム 0007` にイレイジャーコーディングデータをリストアします。

「 repair-data start-ec-volume-repair -- nodes SG-DC-SN3 -- volumes 0007`

* ボリュームの範囲 * ：次のコマンドは、 SG-DC-SN3 というストレージノードの「 0004 」の範囲にあるすべてのボリュームにイレイジャーコーディングデータをリストアします。

`repair-data start-ec-volume-repair --nodes SG-DC-SN3 --volume-range 0004,0006`

* 複数のボリュームがシーケンスに含まれていない場合 *: 次のコマンドは 'SG-DC-SN3 というストレージノードのボリューム 000A'000C'000E' にイレイジャーコーディングデータをリストアします

「 repair-data start-ec-volume-repair -- ノード SG-DC-SN3 -- ボリューム 000A 、 000C 、 000E 」

「 repair-data 」操作は、この「 repair_data 」操作を識別する一意の「 repair ID 」を返します。この「修理 ID 」を使用して、「 repair_data 」操作の進行状況と結果を追跡します。リカバリプロセスが完了しても、それ以外のフィードバックは返されません。


NOTE: イレイジャーコーディングデータの修復は、一部のストレージノードがオフライン状態で開始できます。修復はすべてのノードが使用可能になったあとに完了します。

--
====