---
permalink: tenant/changing-consistency-level.html 
sidebar: sidebar 
keywords: how to change tenant consistency level, read after new write, read-after-new-write, strong site, strong-site, strong global, strong-global 
summary: S3 テナントを使用している場合は、テナントマネージャまたはテナント管理 API を使用して、 S3 バケット内のオブジェクトに対して実行される処理の整合性制御レベルを変更できます。 
---
= 整合性レベルを変更します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 テナントを使用している場合は、テナントマネージャまたはテナント管理 API を使用して、 S3 バケット内のオブジェクトに対して実行される処理の整合性制御レベルを変更できます。

.必要なもの
* Tenant Manager にはを使用してサインインする必要があります xref:../admin/web-browser-requirements.adoc[サポートされている Web ブラウザ]。
* Manage All Buckets 権限または Root Access 権限のあるユーザグループに属している必要があります。これらの権限は、グループまたはバケットポリシーの権限の設定よりも優先されます。を参照してください xref:tenant-management-permissions.adoc[テナント管理権限]。


整合性レベルを設定する場合は、オブジェクトの可用性と、異なるストレージノードおよびサイト間におけるオブジェクトの整合性のどちらかを犠牲にしなければなりません。通常は、バケットに * Read-after-new-write * 整合性レベルを使用してください。リードアフターニューライトの * コンシステンシ・レベルがクライアント・アプリケーションの要件を満たしていない場合は ' バケット・コンシステンシ・レベルを設定するか 'Consistency-Control ヘッダーを使用してコンシステンシ・レベルを変更できます「 Consistency-Control 」ヘッダーは、バケットの整合性レベルよりも優先されます。


NOTE: バケットの整合性レベルを変更した場合、変更後のレベルを満たすことが保証されるのは、変更後に取り込まれたオブジェクトのみです。

.手順
. ストレージ（ S3 ） * > * バケット * を選択します。
. リストからバケット名を選択します。
+
バケットの詳細ページが表示されます。

. * Bucket options * > * Consistency level * を選択します。
. このバケット内のオブジェクトに対して実行される処理の整合性レベルを選択します。
+
[cols="1a,3a"]
|===
| 整合性レベル | 説明 


 a| 
すべて
 a| 
すべてのノードが即座にデータを受け取り、受け取れない場合は要求が失敗します。



 a| 
strong-global
 a| 
すべてのサイトのすべてのクライアント要求について、リードアフターライト整合性が保証されます。



 a| 
strong-site
 a| 
1 つのサイト内のすべてのクライアント要求について、リードアフターライト整合性が保証されます。



 a| 
read-after-new-write （デフォルト）
 a| 
新規オブジェクトにはリードアフターライト整合性を、オブジェクトの更新には結果整合性を提供します。高可用性が確保され、データ保護が保証されます。Amazon S3 の整合性の保証に最も近い機能です。

* 注： Amazon S3 の整合性保証が必要な場合を除き、アプリケーションが存在しないキーに対して HEAD 処理または GET 処理を実行しようとする場合は、整合性レベルを * Available * に設定してください。そうしないと、使用できないストレージノードがある場合に「 500 Internal Server Error 」が大量に発生する可能性があります。



 a| 
available （ HEAD 処理または GET 処理は結果整合性）
 a| 
read-after-new-write * 整合性レベルと動作は同じですが、 HEAD 処理と GET 処理については結果整合性を提供します。ストレージノードを使用できない場合に、 HEAD 処理と GET 処理に対して「 Read-after-new-write 」よりも高い可用性が提供される。Amazon S3 の整合性とは異なり、 HEAD 処理と GET 処理は保証されません。

|===
. 「変更を保存」を選択します。

