---
permalink: tenant/index.html 
sidebar: sidebar 
keywords: use tenant account 
summary: テナントアカウントでは、 Simple Storage Service （ S3 ） REST API または Swift REST API を使用して、 StorageGRID システムでオブジェクトの格納や読み出しを行うことができます。 
---
= テナントアカウントを使用する：概要
:icons: font
:imagesdir: ../media/


[role="lead"]
テナントアカウントでは、 Simple Storage Service （ S3 ） REST API または Swift REST API を使用して、 StorageGRID システムでオブジェクトの格納や読み出しを行うことができます。



== テナントアカウントとは何ですか？

各テナントアカウントには、フェデレーテッド / ローカルグループ、ユーザ、 S3 バケットまたは Swift コンテナ、オブジェクトがあります。

必要に応じて、テナントアカウントを使用して、格納されているオブジェクトをエンティティごとに分離できます。たとえば、次のようなユースケースでは複数のテナントアカウントを使用できます。

* * エンタープライズのユースケース： StorageGRID システムがエンタープライズ内で使用されている場合は、組織の部門ごとにグリッドのオブジェクトストレージを分けることができます。たとえば、マーケティング部門、カスタマーサポート部門、人事部門などのテナントアカウントが存在する場合があります。
+

NOTE: S3 クライアントプロトコルを使用する場合は、 S3 バケットとバケットポリシーを使用してエンタープライズ内の部門間でオブジェクトを分離することもできます。個別のテナントアカウントを作成する必要はありません。を参照してください xref:../s3/index.adoc[S3 クライアントアプリケーションを実装するための手順]。

* * サービスプロバイダのユースケース： * StorageGRID システムがサービスプロバイダによって使用されている場合は、ストレージをリースするエンティティごとにグリッドのオブジェクトストレージを分けることができます。たとえば、会社 A 、会社 B 、会社 C などのテナントアカウントを作成できます。




== テナントアカウントを作成する方法

テナントアカウントは、によって作成されます xref:../admin/managing-tenants.adoc[グリッドマネージャを使用した StorageGRID のグリッド管理者]。グリッド管理者は、テナントアカウントを作成する際に次の情報を指定します。

* テナントの表示名（テナントのアカウント ID は自動的に割り当てられ、変更できません）。
* テナントアカウントが S3 と Swift のどちらを使用するか。
* S3 テナントアカウントの場合：テナントアカウントにプラットフォームサービスの使用を許可するかどうか。プラットフォームサービスの使用が許可されている場合は、グリッドがその使用をサポートするように設定されている必要があります。
* 必要に応じて、テナントアカウントのストレージクォータ -- テナントのオブジェクトで使用可能な最大ギガバイト数、テラバイト数、ペタバイト数。テナントのストレージクォータは、物理容量（ディスクのサイズ）ではなく、論理容量（オブジェクトのサイズ）を表します。
* StorageGRID システムでアイデンティティフェデレーションが有効になっている場合は、テナントアカウントを設定するための Root Access 権限が割り当てられているフェデレーテッドグループ。
* StorageGRID システムでシングルサインオン（ SSO ）が使用されていない場合は、テナントアカウントが独自のアイデンティティソースを使用するか、グリッドのアイデンティティソースを共有するか、およびテナントのローカル root ユーザの初期パスワード。


また、 S3 テナントアカウントが規制要件に準拠する必要がある場合は、グリッド管理者が StorageGRID システムに対して S3 オブジェクトロック設定を有効にすることができます。S3 オブジェクトのロックを有効にすると、すべての S3 テナントアカウントで準拠バケットを作成、管理できます。



=== S3 テナントを設定する

の後 xref:../admin/creating-tenant-account.adoc[S3 テナントアカウントが作成されます]では、 Tenant Manager にアクセスして次のようなタスクを実行できます。

* アイデンティティフェデレーションの設定（グリッドとアイデンティティソースを共有する場合を除く）、またはローカルグループおよびユーザの作成
* S3 アクセスキーの管理
* 準拠バケットを含む S3 バケットを作成、管理します
* プラットフォームサービスの使用（有効な場合）
* ストレージ使用状況を監視しています



IMPORTANT: Tenant Manager を使用して S3 バケットを作成および管理できますが、が必要です xref:../s3/index.adoc[S3 アクセスキーと S3 REST API を使用してオブジェクトを取り込み、管理します]。



=== Swift テナントを設定します

の後 xref:../admin/creating-tenant-account.adoc[Swift テナントアカウントが作成される]では、 Tenant Manager にアクセスして次のようなタスクを実行できます。

* アイデンティティフェデレーションの設定（グリッドとアイデンティティソースを共有する場合を除く）、およびローカルグループとユーザの作成
* ストレージ使用状況を監視しています



IMPORTANT: Swift ユーザが Tenant Manager にアクセスするには、 Root Access 権限が必要です。ただし、 Root Access 権限では、ユーザがに認証することはできません xref:../swift/index.adoc[Swift REST API] コンテナを作成してオブジェクトを取り込むため。Swift REST API に認証するには、 Swift 管理者の権限が必要です。



== Tenant Manager を使用します

Tenant Manager では、 StorageGRID テナントアカウントのすべての要素を管理できます。

Tenant Manager を使用して、テナントアカウントのストレージ使用率を監視したり、アイデンティティフェデレーションを使用するかローカルのグループとユーザを作成してユーザを管理したりできます。S3 テナントアカウントの場合は、 S3 キーの管理、 S3 バケットの管理、プラットフォームサービスの設定も行うことができます。
