---
permalink: tenant/managing-groups.html 
sidebar: sidebar 
keywords: how to manage groups 
summary: テナントユーザが実行できるタスクを制御するには、ユーザグループに権限を割り当てます。Active Directory や OpenLDAP などのアイデンティティソースからフェデレーテッドグループをインポートすることも、ローカルグループを作成することもできます。 
---
= グループを管理します
:icons: font
:imagesdir: ../media/


[role="lead"]
テナントユーザが実行できるタスクを制御するには、ユーザグループに権限を割り当てます。Active Directory や OpenLDAP などのアイデンティティソースからフェデレーテッドグループをインポートすることも、ローカルグループを作成することもできます。


IMPORTANT: StorageGRID システムでシングルサインオン（ SSO ）が有効になっている場合、ローカルユーザはテナントマネージャにサインインできません。ただし、グループの権限に基づいて S3 リソースと Swift リソースにアクセスすることはできます。



== テナント管理権限

テナントグループを作成する前に、そのグループに割り当てる権限を検討してください。テナント管理権限は、 Tenant Manager またはテナント管理 API を使用してユーザが実行できるタスクを決定します。ユーザは 1 つ以上のグループに属することができます。権限は、ユーザが複数のグループに属している場合に累積されます。

Tenant Manager にサインインするには、またはテナント管理 API を使用するには、少なくとも 1 つの権限が割り当てられたグループにユーザが属している必要があります。サインインできるすべてのユーザは、次のタスクを実行できます。

* ダッシュボードを表示します
* 自分のパスワードを変更する（ローカルユーザの場合）


すべての権限について、グループのアクセスモード設定によって、ユーザが設定を変更して処理を実行できるかどうか、またはユーザが関連する設定と機能のみを表示できるかどうかが決まります。


NOTE: ユーザが複数のグループに属していて、いずれかのグループが読み取り専用に設定されている場合、選択したすべての設定と機能に読み取り専用でアクセスできます。

グループには次の権限を割り当てることができます。S3 テナントと Swift テナントではグループの権限が異なるので注意してください。キャッシングに時間がかかるため変更には最大で 15 分を要します。

[cols="1a,3a"]
|===
| アクセス権 | 説明 


 a| 
ルートアクセス（ Root Access ）
 a| 
Tenant Manager とテナント管理 API へのフルアクセスを提供します。

* 注： * Swift ユーザがテナントアカウントにサインインするには、 Root Access 権限が必要です。



 a| 
管理者
 a| 
Swift テナントのみ。このテナントアカウントの Swift コンテナとオブジェクトへのフルアクセスを提供します

* 注： * Swift ユーザが Swift REST API を使用して処理を実行するには、 Swift 管理者の権限が必要です。



 a| 
自分の S3 クレデンシャルを管理します
 a| 
S3 テナントのみ。ユーザに自分の S3 アクセスキーの作成および削除を許可します。この権限を持たないユーザには、「 * storage （ S3 ） * > * My S3 access keys * 」メニューオプションは表示されません。



 a| 
すべてのバケットを管理します
 a| 
* S3 テナント： S3 のバケットまたはグループポリシーに関係なく、ユーザに Tenant Manager とテナント管理 API を使用して S3 バケットの作成と削除を許可し、テナントアカウント内のすべての S3 バケットの設定を管理することを許可します。
+
この権限を持たないユーザには、 *Bucket* メニューオプションは表示されません。

* Swift テナント： Swift ユーザにテナント管理 API を使用して Swift コンテナの整合性レベルを制御することを許可します。


* 注： * テナント管理 API から Swift グループに割り当てることができるのは、 Manage All Buckets 権限だけです。この権限は、 Tenant Manager を使用して Swift グループに割り当てることはできません。



 a| 
エンドポイントを管理します
 a| 
S3 テナントのみ。ユーザが Tenant Manager またはテナント管理 API を使用して、 StorageGRID プラットフォームサービスのデスティネーションとして使用するエンドポイントを作成または編集できるようにします。

この権限を持たないユーザーには、 * プラットフォームサービスエンドポイント * メニューオプションは表示されません。

|===
xref:../s3/index.adoc[S3 を使用する]

xref:../swift/index.adoc[Swift を使用します]
