---
permalink: tenant/using-search-integration-service.html 
sidebar: sidebar 
keywords: how to use search integration service 
summary: 検索統合サービスは、 3 つの StorageGRID プラットフォームサービスのうちの 1 つです。このサービスを有効にすると、オブジェクトが作成、削除されたとき、またはそのメタデータやタグが更新されたときに、デスティネーションの検索インデックスにオブジェクトメタデータを送信できます。 
---
= 検索統合サービスを使用する
:icons: font
:imagesdir: ../media/


[role="lead"]
検索統合サービスは、 3 つの StorageGRID プラットフォームサービスのうちの 1 つです。このサービスを有効にすると、オブジェクトが作成、削除されたとき、またはそのメタデータやタグが更新されたときに、デスティネーションの検索インデックスにオブジェクトメタデータを送信できます。

テナントマネージャを使用して検索統合を設定し、カスタム StorageGRID 設定 XML をバケットに適用できます。


NOTE: 検索統合サービスではオブジェクトメタデータがデスティネーションに送信されるため、その設定 XML は _ メタデータ通知設定 xml_ と呼ばれます。この設定 XML は、イベント通知を有効にするための _ 通知設定 xml_ とは異なります。

を参照してください xref:../s3/index.adoc[S3 クライアントアプリケーションを実装するための手順] 次のカスタムの StorageGRID S3 REST API 処理の詳細については、以下を参照してください。

* DELETE Bucket metadata notification configuration 要求
* GET Bucket metadata notification configuration 要求
* PUT Bucket metadata notification configuration 要求


xref:configuration-xml-for-search-configuration.adoc[検索統合用の XML を設定します]

xref:object-metadata-included-in-metadata-notifications.adoc[メタデータ通知に含まれているオブジェクトメタデータ]

xref:json-generated-by-search-integration-service.adoc[検索統合サービスで生成される JSON]

xref:configuring-search-integration-service.adoc[検索統合サービスを設定する]

xref:../s3/index.adoc[S3 を使用する]
