---
permalink: vmware/automating-grid-node-deployment-in-vmware-vsphere.html 
sidebar: sidebar 
keywords: how to automate installation 
summary: VMware vSphere を使用して、グリッドノードの導入を自動化できます。StorageGRID の設定を自動化することもできます。 
---
= インストールの自動化（ VMware ）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere を使用して、グリッドノードの導入を自動化できます。StorageGRID の設定を自動化することもできます。



== グリッドノードの導入を自動化

VMware vSphere を使用してグリッドノードの導入を自動化する。

.必要なもの
* Bash 3.2 以降が搭載された Linux / UNIX システムにアクセスできるようにしておきます。
* VMware OVF Tool 4.1 をインストールし、正しく設定しておきます。
* OVF Tool を使用して VMware vSphere にアクセスするために必要なユーザ名とパスワードを確認しておきます。
* StorageGRID 仮想マシンを導入する vSphere 内の場所の仮想インフラ（ VI ） URL を確認しておきます。この URL は通常、 vApp またはリソースプールです。例： vi ： // vcenter.example.com/vi/sgws`
+

NOTE: この値は 'VMware'ovftool' ユーティリティを使用して確認できます（詳細については 'ovftool' のマニュアルを参照してください）

+

NOTE: vApp に導入する場合、初回は仮想マシンが自動的に起動されないため、手動で電源をオンにする必要があります。

* 構成ファイルに必要なすべての情報を収集しておきます。を参照してください xref:collecting-information-about-your-deployment-environment.adoc[導入環境に関する情報を収集します] を参照してください。
* VMware 用インストールアーカイブに含まれている次のファイルに StorageGRID からアクセスできるようにしておきます。


[cols="1a,1a"]
|===
| ファイル名 | 説明 


| NetApp-SG-version-sha.vmdk  a| 
グリッドノード仮想マシンを作成するためのテンプレートとして使用される仮想マシンディスクファイル。

* 注意 : このファイルは '.ovf ファイルおよび .mf ファイルと同じフォルダにある必要があります



| vsphere-primary-admin.ovf vsphere-primary-admin.mf  a| 
プライマリ管理ノードを導入するための Open Virtualization Format テンプレートファイル (`.ovf ') およびマニフェストファイル (`.mf ') 。



| vsphere-non-primary-admin.ovf vsphere-non-primary-admin.mf  a| 
非プライマリ管理ノードを導入するためのテンプレートファイル (`.ovf ') およびマニフェストファイル (`.mf ') 。



| vsphere-archive.ovf vsphere-archive.mf  a| 
アーカイブノードを導入するためのテンプレートファイル (`.ovf ') およびマニフェストファイル (`.mf ')



| vsphere-gateway.ovf vsphere-gateway.mf  a| 
ゲートウェイノードを導入するためのテンプレートファイル (`.ovf ') およびマニフェストファイル (`.mf ') 。



| vsphere-storage.ovf vsphere-storage.mf  a| 
仮想マシンベースのストレージノードを導入するためのテンプレートファイル (`.ovf ') およびマニフェストファイル (`.mf ') 。



| deploy-vsphere-ovftool.sh  a| 
仮想グリッドノードの導入を自動化するための Bash シェルスクリプト。



| deploy-vsphere-ovftool-sample.ini  a| 
「 deploy-vsphere-ovftool.sh 」スクリプトで使用するサンプル構成ファイル。

|===


=== 導入環境に応じた構成ファイルを定義します

StorageGRID の仮想グリッドノードを導入するために必要な情報を構成ファイルで指定します。このファイルは、「 deploy-vsphere-ovftool.sh 」スクリプトで使用します。サンプル構成ファイルを変更して、ファイルをゼロから作成する必要がないようにすることができます。

.手順
. サンプル構成ファイル (`deploy-vsphere-ovftool.sample.ini` ) のコピーを作成します新しいファイルを「 deploy-vsphere-ovftool.ini` 」として「 deploy-vsphere-ovftool.sh 」と同じディレクトリに保存します。
. deploy-vsphere-ovftool.ini` を開きます
. VMware 仮想グリッドノードを導入するために必要なすべての情報を入力します。
+
を参照してください ,構成ファイルの設定 を参照してください。

. 必要な情報をすべて入力して確認したら、ファイルを保存して閉じます。




=== 構成ファイルの設定

「 deploy-vsphere-ovftool.ini` 」構成ファイルには、仮想グリッドノードを導入するために必要な設定が含まれています。

構成ファイルでは、最初にグローバルパラメータがリストされ、そのあとにノード名で定義されるセクションにノード固有のパラメータがリストされます。ファイルの使用状況：

* _Global parameters_ は、すべてのグリッドノードに適用されます。
* _Node-specific parameters_override グローバルパラメータ。




==== グローバルパラメータ

グローバルパラメータは、個々のセクションの設定で上書きされないかぎり、すべてのグリッドノードに適用されます。複数のノードに適用するパラメータをグローバルパラメータセクションに配置し、個々のノードのセクションで必要に応じてこれらの設定を上書きします。

* * OVFTOOL_ARGUMENTS * ： OVFTOOL_ARGUMENTS をグローバル設定として指定するか、または特定のノードに個別に引数を適用できます。例：
+
[listing, subs="specialcharacters,quotes"]
----
OVFTOOL_ARGUMENTS = --powerOn --noSSLVerify --diskMode=eagerZeroedThick --datastore='_datastore_name_'
----
+
--powerOffTarget' および --overwrite オプションを使用して ' 既存の仮想マシンをシャットダウンし ' 置き換えることができます

+

IMPORTANT: ノードを別々のデータストアに導入し、 OVFTOOL_ARGUMENTS をグローバルに指定するのではなくノードごとに指定する必要があります。

* * source * ： StorageGRID 仮想マシン・テンプレート（ .vmdk ）ファイルおよび個々のグリッド・ノードの「 .ovf 」ファイルおよび「 .mf 」ファイルのパス。デフォルトでは現在のディレクトリに設定されます。
+
[listing, subs="specialcharacters,quotes"]
----
SOURCE = /downloads/StorageGRID-Webscale-_version_/vsphere
----
* * target * ： StorageGRID の導入先となる VMware vSphere 仮想インフラ（ vi ）の URL 。例：
+
[listing]
----
TARGET = vi://vcenter.example.com/vm/sgws
----
* * GRID_NETWORK_CONFIG * ：静的または DHCP のいずれかの IP アドレスの取得に使用される方法。デフォルトは「 STATIC 」です。全ノードまたはほとんどのノードが IP アドレスの取得に同じ方法を使用する場合は、ここでその方法を指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
GRID_NETWORK_CONFIG = DHCP
----
* * GRID_NETWORK_TARGET * ：グリッドネットワークに使用される既存の VMware ネットワークの名前。全ノードまたはほとんどのノードが同じネットワーク名を使用する場合は、ここでその名前を指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
GRID_NETWORK_TARGET = SG-Admin-Network
----
* * GRID_NETWORK_MASK * ：グリッドネットワークのネットワークマスク。全ノードまたはほとんどのノードが同じネットワークマスクを使用する場合は、ここでそのネットワークマスクを指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
GRID_NETWORK_MASK = 255.255.255.0
----
* * GRID_NETWORK_GATEWAY * ：グリッドネットワークのネットワークゲートウェイ。全ノードまたはほとんどのノードが同じネットワークゲートウェイを使用する場合は、ここでそのネットワークゲートウェイを指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
GRID_NETWORK_GATEWAY = 10.1.0.1
----
* * GRID_NETWORK_MTU * ：オプション。グリッドネットワークでの最大伝送ユニット（ MTU ）です。この値を指定する場合、 1280 ～ 9216 の範囲で指定する必要があります。例：
+
[listing]
----
GRID_NETWORK_MTU = 8192
----
+
省略すると 1400 に設定されます。

+
ジャンボフレームを使用する場合は、 MTU を 9000 などのジャンボフレームに適した値に設定します。それ以外の場合は、デフォルト値のままにします。

+

IMPORTANT: ネットワークの MTU 値は、ノードが接続されているスイッチポートに設定されている値と同じである必要があります。そうしないと、ネットワークパフォーマンスの問題やパケット損失が発生する可能性があります。

+

IMPORTANT: ネットワークのパフォーマンスを最大限に高めるには、すべてのノードのグリッドネットワークインターフェイスで MTU 値がほぼ同じになるように設定する必要があります。個々のノードのグリッドネットワークの MTU 設定に大きな違いがある場合は、 * Grid Network MTU mismatch * アラートがトリガーされます。MTU 値はすべてのネットワークタイプで同じである必要はありません。

* * ADMIN_NETWORK_CONFIG * ： IP アドレスの取得に使用された方法。無効、静的、または DHCP のいずれかです。デフォルトは disabled です。全ノードまたはほとんどのノードが IP アドレスの取得に同じ方法を使用する場合は、ここでその方法を指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
ADMIN_NETWORK_CONFIG = STATIC
----
* * ADMIN_NETWORK_TARGET * ：管理ネットワークに使用する既存の VMware ネットワークの名前。この設定は、管理ネットワークが無効になっていない場合に必要となります。全ノードまたはほとんどのノードが同じネットワーク名を使用する場合は、ここでその名前を指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
ADMIN_NETWORK_TARGET = SG-Admin-Network
----
* * ADMIN_NETWORK_MASK * ：管理ネットワークのネットワークマスク。この設定は、静的 IP アドレスを使用する場合に必要となります。全ノードまたはほとんどのノードが同じネットワークマスクを使用する場合は、ここでそのネットワークマスクを指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
ADMIN_NETWORK_MASK = 255.255.255.0
----
* * ADMIN_NETWORK_GATEWAY * ：管理ネットワークのネットワークゲートウェイ。この設定は、 IP アドレスを静的に指定し、かつ ADMIN_NETWORK_ESL 設定で外部サブネットを指定する場合に必要となります（ ADMIN_NETWORK_ESL が空の場合は不要です）。 全ノードまたはほとんどのノードが同じネットワークゲートウェイを使用する場合は、ここでそのネットワークゲートウェイを指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
ADMIN_NETWORK_GATEWAY = 10.3.0.1
----
* * ADMIN_NETWORK_ESL * ：管理ネットワークの外部サブネットリスト（ルート）。 CIDR ルートのデスティネーションをカンマで区切ったリストとして指定します。全ノードまたはほとんどのノードが同じ外部サブネットリストを使用する場合は、ここでそのリストを指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
ADMIN_NETWORK_ESL = 172.16.0.0/21,172.17.0.0/21
----
* * ADMIN_NETWORK_MTU * ：オプション。管理ネットワークでの最大伝送ユニット（ MTU ）です。ADMIN_NETWORK_CONFIG = DHCP の場合は指定しないでください。この値を指定する場合、 1280 ～ 9216 の範囲で指定する必要があります。省略すると 1400 に設定されます。ジャンボフレームを使用する場合は、 MTU を 9000 などのジャンボフレームに適した値に設定します。それ以外の場合は、デフォルト値のままにします。全ノードまたはほとんどのノードが管理ネットワークに同じ MTU を使用する場合は、ここでその MTU を指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
ADMIN_NETWORK_MTU = 8192
----
* * CLIENT_NETWORK_CONFIG * ： IP アドレスの取得に使用する方法。無効、静的、または DHCP のいずれかになります。デフォルトは disabled です。全ノードまたはほとんどのノードが IP アドレスの取得に同じ方法を使用する場合は、ここでその方法を指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
CLIENT_NETWORK_CONFIG = STATIC
----
* * client_network_target * ：クライアントネットワークに使用する既存の VMware ネットワークの名前。この設定は、クライアントネットワークが無効になっていない場合に必要となります。全ノードまたはほとんどのノードが同じネットワーク名を使用する場合は、ここでその名前を指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
CLIENT_NETWORK_TARGET = SG-Client-Network
----
* * CLIENT_NETWORK_MASK * ：クライアントネットワークのネットワークマスク。この設定は、静的 IP アドレスを使用する場合に必要となります。全ノードまたはほとんどのノードが同じネットワークマスクを使用する場合は、ここでそのネットワークマスクを指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
CLIENT_NETWORK_MASK = 255.255.255.0
----
* * client_network_gateway * ：クライアントネットワークのネットワークゲートウェイ。この設定は、静的 IP アドレスを使用する場合に必要となります。全ノードまたはほとんどのノードが同じネットワークゲートウェイを使用する場合は、ここでそのネットワークゲートウェイを指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
CLIENT_NETWORK_GATEWAY = 10.4.0.1
----
* * CLIENT_NETWORK_MTU * ：オプション。クライアントネットワークでの最大伝送ユニット（ MTU ）です。CLIENT_NETWORK_CONFIG = DHCP の場合は指定しないでください。この値を指定する場合、 1280 ～ 9216 の範囲で指定する必要があります。省略すると 1400 に設定されます。ジャンボフレームを使用する場合は、 MTU を 9000 などのジャンボフレームに適した値に設定します。それ以外の場合は、デフォルト値のままにします。全ノードまたはほとんどのノードがクライアントネットワークに同じ MTU を使用する場合は、ここでその MTU を指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
CLIENT_NETWORK_MTU = 8192
----
* * PORT_REMAP * ：ノードが内部でのグリッドノードの通信または外部との通信に使用するポートを再マッピングします。StorageGRID で使用される 1 つ以上のポートがエンタープライズネットワークポリシーによって制限される場合は、ポートの再マッピングが必要です。StorageGRID で使用されるポートのリストについては、で内部でのグリッドノードの通信および外部との通信を参照してください xref:../network/index.adoc[ネットワークのガイドライン]。
+

IMPORTANT: ロードバランサエンドポイントの設定に使用する予定のポートは再マッピングしないでください。

+

NOTE: PORT_REMAP のみを設定すると、指定したマッピングがインバウンド通信とアウトバウンド通信の両方に使用されます。PORT_REMAP_INBOUND を併せて指定した場合は、 PORT_REMAP がアウトバウンド通信のみに適用されます。



使用される形式は、「 _network type/protocol/default port used by grid node/new port_」 です。ここで、ネットワークの種類は grid 、 admin 、 client 、 protocol は tcp または udp です。

例：

[listing]
----
PORT_REMAP = client/tcp/18082/443
----
この例の設定だけを使用した場合は、グリッドノードのインバウンド通信とアウトバウンド通信の両方が、ポート 18082 からポート 443 へと対称的にマッピングされます。この例の設定を PORT_REMAP_INBOUND とともに使用した場合は、アウトバウンド通信がポート 18082 からポート 443 にマッピングされます。

* * port_remap_inbound * ：指定したポートのインバウンド通信を再マッピングします。PORT_REMAP_INBOUND を指定して PORT_REMAP に値を指定しなかった場合は、ポートのアウトバウンド通信が変更されません。
+

IMPORTANT: ロードバランサエンドポイントの設定に使用する予定のポートは再マッピングしないでください。



使用される形式は、「 _network type_/_protocol/_default port 」です。グリッドノードで使用されるデフォルトポートは、 grid 、 admin 、 client のいずれかで、 protocol は tcp または udp です。

例：

[listing]
----
PORT_REMAP_INBOUND = client/tcp/443/18082
----
次の例は、ポート 443 に送信されたトラフィックを内部ファイアウォールを通過させ、グリッドノードが S3 要求をリスンしているポート 18082 に転送します。



==== ノード固有のパラメータ

構成ファイルには、各ノード専用のセクションがあります。各ノードには次の設定が必要です。

* セクションヘッドでは、 Grid Manager に表示されるノード名を定義します。この値を無視するには、ノードに対してオプションの node_name パラメータを指定します。
* * node_name * ： VM_Admin_Node 、 VM_Storage_Node 、 VM_Archive_Node 、 VM_API_Gateway_Node のいずれか
* * GRID_NETWORK_IP * ：グリッドネットワークでのノードの IP アドレス。
* * ADMIN_NETWORK_IP * ：管理ネットワークでのノードの IP アドレス。ノードが管理ネットワークに接続され、かつ ADMIN_NETWORK_CONFIG が STATIC に設定されている場合にのみ必要です。
* * client_network_ip * ：クライアントネットワーク上のノードの IP アドレス。ノードがクライアントネットワークに接続され、かつノードの CLIENT_NETWORK_CONFIG が STATIC に設定されている場合にのみ必要です。
* * ADMIN_IP * ：グリッドネットワークでのプライマリ管理ノードの IP アドレス。プライマリ管理ノードの GRID_NETWORK_IP で指定した値を使用します。このパラメータを省略すると、ノードは mDNS を使用してプライマリ管理ノードの IP を検出しようとします。詳細については、を参照してください xref:how-grid-nodes-discover-primary-admin-node.adoc[グリッドノードによるプライマリ管理ノードの検出]。
+

NOTE: プライマリ管理ノードでは ADMIN_IP パラメータが無視されます。

* グローバルに設定されていないすべてのパラメータ。たとえば、ノードが管理ネットワークに接続されていて、 ADMIN_NETWORK_NETWORK パラメータをグローバルに指定していない場合は、ノードに対してそれらのパラメータを指定する必要があります。


プライマリ管理ノードには次の設定を追加する必要があります。

* * node_type * ： VM_Admin_Node
* * Admin_role * ：プライマリ


次のエントリ例は、プライマリ管理ノードが 3 つのネットワークすべてに接続される場合を示しています。

[listing]
----
[DC1-ADM1]
  ADMIN_ROLE = Primary
  NODE_TYPE = VM_Admin_Node

  GRID_NETWORK_IP = 10.1.0.2
  ADMIN_NETWORK_IP = 10.3.0.2
  CLIENT_NETWORK_IP = 10.4.0.2
----
プライマリ管理ノードにオプションで追加できる設定は次のとおりです。

* * DISK * ：デフォルトでは、管理ノードに対して監査用とデータベース用の 2 つの 200GB ハードディスクが追加で割り当てられます。DISK パラメータを使用して、この容量を増やすことができます。例：
+
[listing]
----
DISK = INSTANCES=2, CAPACITY=300
----



NOTE: 管理ノードの場合は、 INSTANCES を必ず 2 にする必要があります。

ストレージノードには次の設定を追加する必要があります。

* * node_name * ： VM_Storage_Node
+
次のエントリ例は、ストレージノードがグリッドネットワークと管理ネットワークに接続され、クライアントネットワークに接続されない場合を示しています。このノードでは、 ADMIN_IP 設定を使用してグリッドネットワークでのプライマリ管理ノードの IP アドレスを指定しています。

+
[listing]
----
[DC1-S1]
  NODE_TYPE = VM_Storage_Node

  GRID_NETWORK_IP = 10.1.0.3
  ADMIN_NETWORK_IP = 10.3.0.3

  ADMIN_IP = 10.1.0.2
----
+
2 番目のエントリ例は、ストレージノードがクライアントネットワークに接続される場合を示しています。ここでは、 S3 クライアントアプリケーションがストレージノードへのアクセスに使用できるポートが、ユーザのエンタープライズネットワークポリシーによって 80 または 443 に制限されています。この例の構成ファイルでは、 PORT_REMAP を使用して、ストレージノードがポート 443 で S3 メッセージを送受信できるようにしています。

+
[listing]
----
[DC2-S1]
  NODE_TYPE = VM_Storage_Node

  GRID_NETWORK_IP = 10.1.1.3
  CLIENT_NETWORK_IP = 10.4.1.3
  PORT_REMAP = client/tcp/18082/443

  ADMIN_IP = 10.1.0.2
----
+
最後の例では、 ssh トラフィックに対してポート 22 からポート 3022 への対称的な再マッピングが作成されますが、インバウンドとアウトバウンドの両方のトラフィックに明示的に値が設定されます。

+
[listing]
----
[DC1-S3]
  NODE_TYPE = VM_Storage_Node

  GRID_NETWORK_IP = 10.1.1.3

  PORT_REMAP = grid/tcp/22/3022
  PORT_REMAP_INBOUND = grid/tcp/3022/22

  ADMIN_IP = 10.1.0.2
----


ストレージノードにオプションで追加できる設定は次のとおりです。

* * DISK * ：デフォルトでは、ストレージノードに対して RangeDB 用に 3 つの 4TB ディスクが割り当てられます。DISK パラメータを使用して、この容量を増やすことができます。例：
+
[listing]
----
DISK = INSTANCES=16, CAPACITY=4096
----


アーカイブノードには次の設定を追加する必要があります。

* * node_name * ： VM_Archive_Node


次のエントリ例は、アーカイブノードがグリッドネットワークと管理ネットワークに接続され、クライアントネットワークに接続されない場合を示しています。

[listing]
----
[DC1-ARC1]
  NODE_TYPE = VM_Archive_Node

  GRID_NETWORK_IP = 10.1.0.4
  ADMIN_NETWORK_IP = 10.3.0.4

  ADMIN_IP = 10.1.0.2
----
ゲートウェイノードには次の設定を追加する必要があります。

* * node_name * ： VM_API_Gateway


次のエントリ例は、ゲートウェイノードが 3 つのネットワークすべてに接続される場合を示しています。この例では、構成ファイルのグローバルセクションでクライアントネットワークのパラメータが指定されていないため、ノードに対してそれらのパラメータを指定する必要があります。

[listing]
----
[DC1-G1]
  NODE_TYPE = VM_API_Gateway

  GRID_NETWORK_IP = 10.1.0.5
  ADMIN_NETWORK_IP = 10.3.0.5

  CLIENT_NETWORK_CONFIG = STATIC
  CLIENT_NETWORK_TARGET = SG-Client-Network
  CLIENT_NETWORK_MASK = 255.255.255.0
  CLIENT_NETWORK_GATEWAY = 10.4.0.1
  CLIENT_NETWORK_IP = 10.4.0.5

  ADMIN_IP = 10.1.0.2
----
非プライマリ管理ノードには次の設定を追加する必要があります。

* * node_type * ： VM_Admin_Node
* * Admin_role * ：非プライマリ


次のエントリ例は、非プライマリ管理ノードがクライアントネットワークに接続されない場合を示しています。

[listing]
----
[DC2-ADM1]
  ADMIN_ROLE = Non-Primary
  NODE_TYPE = VM_Admin_Node

  GRID_NETWORK_TARGET = SG-Grid-Network
  GRID_NETWORK_IP = 10.1.0.6
  ADMIN_NETWORK_IP = 10.3.0.6

  ADMIN_IP = 10.1.0.2
----
非プライマリ管理ノードにオプションで追加できる設定は次のとおりです。

* * DISK * ：デフォルトでは、管理ノードに対して監査用とデータベース用の 2 つの 200GB ハードディスクが追加で割り当てられます。DISK パラメータを使用して、この容量を増やすことができます。例：
+
[listing]
----
DISK = INSTANCES=2, CAPACITY=300
----



NOTE: 管理ノードの場合は、 INSTANCES を必ず 2 にする必要があります。



== Bash スクリプトを実行します

VMware vSphere への StorageGRID グリッドノードの導入を自動化するために 'deploy-vsphere-ovftool.sh スクリプトおよび変更した deploy-vsphere-ovftool.ini 構成ファイルを使用できます

.必要なもの
* 環境に対応した deploy-vsphere-ovftool.ini 構成ファイルを作成しておきます。


Bash スクリプトのヘルプを参照するには、ヘルプコマンド（「 -h / --help 」）を入力します。例：

[listing]
----
./deploy-vsphere-ovftool.sh -h
----
または

[listing]
----
./deploy-vsphere-ovftool.sh --help
----
.手順
. Bash スクリプトの実行に使用する Linux マシンにログインします。
. インストールアーカイブを展開したディレクトリに移動します。
+
例：

+
[listing]
----
cd StorageGRID-Webscale-version/vsphere
----
. グリッドノードをすべて導入する場合は、使用する環境に適したオプションを指定して Bash スクリプトを実行します。
+
例：

+
[listing]
----
./deploy-vsphere-ovftool.sh --username=user --password=pwd ./deploy-vsphere-ovftool.ini
----
. エラーのために導入できなかったグリッドノードがある場合は、エラーを解決し、そのノードだけを対象に Bash スクリプトを再実行します。
+
例：

+
[listing]
----
./deploy-vsphere-ovftool.sh --username=user --password=pwd --single-node="DC1-S3" ./deploy-vsphere-ovftool.ini
----


各ノードのステータスが Passed になると ' 配備は完了します

[listing]
----
Deployment Summary
+-----------------------------+----------+----------------------+
| node                        | attempts | status               |
+-----------------------------+----------+----------------------+
| DC1-ADM1                    |        1 | Passed               |
| DC1-G1                      |        1 | Passed               |
| DC1-S1                      |        1 | Passed               |
| DC1-S2                      |        1 | Passed               |
| DC1-S3                      |        1 | Passed               |
+-----------------------------+----------+----------------------+
----


== StorageGRID の設定を自動化

グリッドノードを導入したら、 StorageGRID システムの設定を自動化できます。

.必要なもの
* インストールアーカイブにある次のファイルの場所を確認しておきます。


[cols="1a,1a"]
|===
| ファイル名 | 説明 


| configure-storagegrid.py  a| 
設定を自動化するための Python スクリプト



| storagegrid-sample.json を設定します  a| 
スクリプトで使用するサンプル構成ファイル



| storagegrid-bank.json を設定する  a| 
スクリプトで使用する空の構成ファイルです

|===
* 構成ファイル configure -storagegrid.json を作成しました。このファイルを作成するには、サンプル構成ファイル（「 configure -storagegrid-sample.json 」）または空の構成ファイル（「 configure -storagegridBlank.json 」）を変更します。


configure -storagegrid.py Python スクリプトと、 configure -storagegrid.json 構成ファイルを使用して、 StorageGRID システムの設定を自動化できます。


NOTE: また、 Grid Manager またはインストール API を使用してシステムを設定することもできます。

.手順
. Python スクリプトを実行するために使用する Linux マシンにログインします。
. インストールアーカイブを展開したディレクトリに移動します。
+
例：

+
[listing]
----
cd StorageGRID-Webscale-version/platform
----
+
ここで 'platform' は debs'rpms ' または vsphere です

. Python スクリプトを実行し、作成した構成ファイルを使用します。
+
例：

+
[listing]
----
./configure-storagegrid.py ./configure-storagegrid.json --start-install
----


設定プロセスでリカバリパッケージの .zip ファイルが生成され、インストールと設定を実行するディレクトリにダウンロードされます。グリッドノードで障害が発生した場合に StorageGRID システムをリカバリできるようにするために、リカバリパッケージファイルをバックアップする必要があります。たとえば、バックアップされたセキュアなネットワーク上の場所や、安全なクラウドストレージ上の場所にコピーします。


IMPORTANT: リカバリパッケージファイルには StorageGRID システムからデータを取得するための暗号キーとパスワードが含まれているため、安全に保管する必要があります。

ランダムパスワードを生成するように指定した場合は、 Passwords.txt ファイルを展開し、 StorageGRID システムへのアクセスに必要なパスワードを探す必要があります。

[listing]
----
######################################################################
##### The StorageGRID "recovery package" has been downloaded as: #####
#####           ./sgws-recovery-package-994078-rev1.zip          #####
#####   Safeguard this file as it will be needed in case of a    #####
#####                 StorageGRID node recovery.                 #####
######################################################################
----
StorageGRID システムがインストールおよび設定されると、確認メッセージが表示されます。

[listing]
----
StorageGRID has been configured and installed.
----
xref:navigating-to-grid-manager.adoc[Grid Manager に移動します]

xref:overview-of-installation-rest-api.adoc[インストール REST API の概要]
