---
permalink: vmware/downloading-and-extracting-storagegrid-installation-files.html 
sidebar: sidebar 
keywords: how to download vmware installation files 
summary: StorageGRID インストールアーカイブをダウンロードし、ファイルを展開する必要があります。 
---
= StorageGRID インストールファイルをダウンロードして展開します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID インストールアーカイブをダウンロードし、ファイルを展開する必要があります。

.手順
. にアクセスします https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["ネットアップの StorageGRID ダウンロードページ"^]。
. 最新のリリースをダウンロードするボタンを選択するか、ドロップダウンメニューから別のバージョンを選択して、「 * Go * 」を選択します。
. ネットアップアカウントのユーザ名とパスワードを使用してサインインします。
. 「注意 / 必ずお読みください」という記述が表示されたら、それを読んでチェックボックスを選択してください。
+

IMPORTANT: StorageGRID リリースのインストール後に、必要な修正プログラムを適用する必要があります。詳細については、を参照してください xref:../maintain/storagegrid-hotfix-procedure.adoc[リカバリとメンテナンスの手順の Hotfix 手順]

. エンドユーザライセンス契約を読み、チェックボックスをオンにして、「 * 同意して続行 * 」を選択します。
. Install StorageGRID * 列で、 VMware 用の .tgz ファイルまたは .zip ファイルを選択します。
+

NOTE: サービスラップトップで Windows を実行している場合は '.zip ファイルを使用します

. アーカイブファイルを保存して展開します。
. 次のリストから必要なファイルを選択します。
+
必要なファイルは、計画したグリッドトポロジおよび StorageGRID システムの導入方法によって異なります。




NOTE: 次の表に示すパスは、展開されたインストールアーカイブによってインストールされた最上位ディレクトリに対する相対パスです。

[cols="1a,1a"]
|===
| パスとファイル名 | 説明 


| ./vsphere/README （ ./vsphere/README  a| 
StorageGRID ダウンロードファイルに含まれているすべてのファイルについて説明するテキストファイル。



| ./vsphere/NLF000000.txt にアクセスします  a| 
製品サポートのない無償ライセンス。



| ./vsphere/NetApp-SG-version-sha.vmdk  a| 
グリッドノード仮想マシンを作成するためのテンプレートとして使用される仮想マシンディスクファイル。



| ./vsphere/vsphere-primary-admin.ovf ./vsphere-primary-admin.mf  a| 
プライマリ管理ノードを導入するための Open Virtualization Format テンプレートファイル (`.ovf ') およびマニフェストファイル (`.mf ') 。



| ./vsphere/vsphere-non-primary-admin.ovf ./vsphere/vsphere-non-primary-admin.mf  a| 
非プライマリ管理ノードを導入するためのテンプレートファイル (`.ovf ') およびマニフェストファイル (`.mf ') 。



| ./vsphere/vsphere-archive.ovf ./vsphere-archive.mf  a| 
アーカイブノードを導入するためのテンプレートファイル (`.ovf ') およびマニフェストファイル (`.mf ')



| ./vsphere/vsphere-gateway.ovf ./vsphere/vsphere-gateway.mf  a| 
ゲートウェイノードを導入するためのテンプレートファイル (`.ovf ') およびマニフェストファイル (`.mf ') 。



| ./vsphere/vsphere-storage.OVF ./vsphere/vsphere-storage.mf  a| 
仮想マシンベースのストレージノードを導入するためのテンプレートファイル (`.ovf ') およびマニフェストファイル (`.mf ') 。



| 導入スクリプトツール | 説明 


| ./vsphere/deploy-vsphere-ovftool.sh にアクセスします  a| 
仮想グリッドノードの導入を自動化するための Bash シェルスクリプト。



| ./vsphere/deploy-vsphere-ovftool-sample.ini にアクセスします  a| 
「 deploy-vsphere-ovftool.sh 」スクリプトで使用する構成ファイルの例。



| ./vsphere/configure-storagegrid.py にアクセスします  a| 
StorageGRID システムの設定を自動化するための Python スクリプト。



| ./vsphere/configure-sga.py にアクセスします  a| 
StorageGRID アプライアンスの設定を自動化するための Python スクリプト。



| ./vsphere/storagegrid-ssoauth.py にアクセスします  a| 
シングルサインオンが有効な場合にグリッド管理 API にサインインするために使用できる Python スクリプトの例。



| ./vsphere/configure -storagegrid-sample.json という形式で実行します  a| 
configure -storagegrid.py スクリプトで使用される設定ファイルの例。



| ./vsphere/configure -storagegrid-bank.json （ページ構成  a| 
configure -storagegrid.py スクリプトで使用する空の構成ファイル。



| ./vsphere/extra/api-schemas  a| 
StorageGRID の API スキーマ

* 注 * ：アップグレードを実行する前に、これらのスキーマを使用して、 StorageGRID 管理 API を使用するように記述したコードが、アップグレード互換性テスト用の非本番環境の StorageGRID 環境を持たない場合、新しい StorageGRID リリースと互換性があることを確認できます。

|===
xref:../maintain/index.adoc[リカバリとメンテナンス]
