---
permalink: vmware/planning-and-preparation.html 
sidebar: sidebar 
keywords: how to plan before installation 
summary: グリッドノードの導入および StorageGRID グリッドの設定を行う前に、手順 を完了するためのステップと要件を把握しておく必要があります。 
---
= インストールの前に（ VMware ）
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッドノードの導入および StorageGRID グリッドの設定を行う前に、手順 を完了するためのステップと要件を把握しておく必要があります。

StorageGRID の導入手順と設定手順を実行するには、 StorageGRID システムのアーキテクチャと運用機能に関する十分な知識が必要です。

一度に 1 つ以上のサイトを導入できますが、ストレージノードが少なくとも 3 つ必要であるという最小要件をすべてのサイトが満たしている必要があります。


IMPORTANT: 基盤となるディスク保護はハードウェア RAID ではないため、 StorageGRID では Virtual Storage Area Network （ VSAN ；仮想ストレージエリアネットワーク）の使用はサポートされていません。

ノード導入とグリッド設定の手順 を開始する前に、次の作業を完了しておく必要があります。

* StorageGRID の導入を計画します。
* StorageGRID アプライアンスを含む必要なすべてのハードウェアを仕様に従って設置、接続、設定します。
+

NOTE: ハードウェア固有の設置と統合の手順は、 StorageGRID インストール手順 には含まれていません。StorageGRID アプライアンスのインストール方法については、使用するアプライアンスのインストールとメンテナンスの手順を参照してください。

* を理解します xref:../network/index.adoc[使用可能なネットワークオプションおよび各ネットワークオプションをグリッドノードで実装する方法]。
* すべてのネットワーク情報を事前に収集します。DHCP を使用している場合を除き、各グリッドノードに割り当てる IP アドレス、および使用される Domain Name System （ DNS ；ドメインネームシステム）サーバと Network Time Protocol （ NTP ；ネットワークタイムプロトコル）サーバの IP アドレスを収集してください。
* 使用する導入ツールと設定ツールを決定します。


xref:../sg100-1000/index.adoc[SG100 および SG1000 サービスアプライアンス]

xref:../sg6000/index.adoc[SG6000 ストレージアプライアンス]

xref:../sg5700/index.adoc[SG5700 ストレージアプライアンス]

xref:../sg5600/index.adoc[SG5600 ストレージアプライアンス]
