---
permalink: vmware/troubleshooting-installation-issues.html 
sidebar: sidebar 
keywords: how to troubleshoot installation issues 
summary: StorageGRID システムのインストール中に問題が発生した場合は、インストールログファイルにアクセスできます。 
---
= インストールに関する問題のトラブルシューティング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID システムのインストール中に問題が発生した場合は、インストールログファイルにアクセスできます。

次のファイルは、テクニカルサポートが問題の解決に必要とする場合があるメインのインストールログファイルです。

* /var/local/log/install.log （すべてのグリッドノードに存在）
* /var/local/log/gdu-server.log （プライマリ管理ノードに存在）


ログファイルへのアクセス方法については、を参照してください xref:../monitor/index.adoc[StorageGRID の監視とトラブルシューティングの手順]。アプライアンスの設置に関する問題のトラブルシューティングについては、使用しているアプライアンスの設置とメンテナンスの手順を参照してください。その他のサポートが必要な場合は、テクニカルサポートにお問い合わせください。

xref:../sg100-1000/index.adoc[SG100 および SG1000 サービスアプライアンス]

xref:../sg6000/index.adoc[SG6000 ストレージアプライアンス]

xref:../sg5700/index.adoc[SG5700 ストレージアプライアンス]

xref:../sg5600/index.adoc[SG5600 ストレージアプライアンス]

https://mysupport.netapp.com/site/global/dashboard["ネットアップサポート"^]



== 仮想マシンのリソースリザベーションの調整が必要です

OVF ファイルでは、各グリッドノードが十分な RAM と CPU を確保して効率よく動作できるようにするためのリソースリザベーションが設定されています。VMware で OVF ファイルを導入して仮想マシンを作成する場合、事前に定義された数のリソースを使用できないと、仮想マシンは起動されません。

.このタスクについて
VM ホストに各グリッドノード用の十分なリソースがあることがわかっている場合は、各仮想マシンに割り当てられているリソースを手動で調整し、仮想マシンの起動を試みます。

.手順
. VMware vSphere ハイパーバイザーのクライアントツリーで、起動されていない仮想マシンを選択します。
. 仮想マシンを右クリックし、 * 設定の編集 * を選択します。
. [ 仮想マシンのプロパティ ] ウィンドウで、 [ * リソース * ] タブを選択します。
. 仮想マシンに割り当てられているリソースを調整します。
+
.. [*CPU*] を選択し、 [ 予約 ] スライダを使用して、この仮想マシン用に予約されている MHz を調整します。
.. [* Memory] を選択し、 [Reservation （予約） ] スライダを使用してこの仮想マシン用に予約されている MB を調整します。


. [OK] をクリックします。
. 必要に応じて、同じ VM ホストでホストされている他の仮想マシンに対して同じ手順を繰り返します。

