---
permalink: vmware/where-to-go-next.html 
sidebar: sidebar 
keywords: after installation 
summary: インストールが完了したら、統合と設定のための一連の手順を実行する必要があります。手順には必須のものとオプションのものがあります。 
---
= 次の手順
:icons: font
:imagesdir: ../media/


[role="lead"]
インストールが完了したら、統合と設定のための一連の手順を実行する必要があります。手順には必須のものとオプションのものがあります。



== 必要な作業

* VMware vSphere ハイパーバイザーで自動再起動を設定する。
+
サーバの再起動時に仮想マシンを再起動するようにハイパーバイザーを設定する必要があります。自動再起動を有効にしないと、サーバが再起動したあとも仮想マシンとグリッドノードがシャットダウンされたままになります。詳細については、 VMware vSphere ハイパーバイザーのドキュメントを参照してください。

* StorageGRID システムにオブジェクトを格納するために使用されるクライアントプロトコル（ Swift または S3 ）ごとに、テナントアカウントを作成します。
* グループとユーザアカウントを設定してシステムアクセスを制御します。管理者グループおよびユーザをインポートできるように、必要に応じて、フェデレーテッドアイデンティティソース（ Active Directory や OpenLDAP など）を設定できます。または、ローカルグループやユーザを作成することもできます。
* StorageGRID システムにオブジェクトをアップロードするために使用する S3 または Swift API クライアントアプリケーションを統合し、テストします。
* 準備ができたら、オブジェクトデータの保護に使用する情報ライフサイクル管理（ ILM ）ルールと ILM ポリシーを設定します。
+

NOTE: StorageGRID をインストールすると、デフォルトの ILM ポリシーである Baseline 2 Copies Policy がアクティブになります。このポリシーには組み込みの ILM ルール（ Make 2 Copies ）が含まれており、他のポリシーがアクティブ化されていない場合に適用されます。

* インストール環境にアプライアンスストレージノードが含まれている場合は、 SANtricity ソフトウェアを使用して次の作業を実行します。
+
** 各 StorageGRID アプライアンスに接続します。
** AutoSupport データの受信を確認します。


* StorageGRID システムにアーカイブノードが含まれている場合は、アーカイブノードからターゲットの外部アーカイブストレージシステムへの接続を設定します。



NOTE: アーカイブノードが Tivoli Storage Manager を外部アーカイブストレージシステムとして使用する場合は、 Tivoli Storage Manager を設定する必要もあります。

* StorageGRID システムのセキュリティ設定ガイドラインに従ってセキュリティリスクを排除します。
* システムアラートの E メール通知を設定します。




== 任意のタスク

* （レガシー）アラームシステムから通知を受信するには、アラーム用のメーリングリストおよび E メール通知を設定します。
* 導入を計画し、リカバリパッケージを生成したあとにグリッドノードの IP アドレスが変わった場合は、それらの IP アドレスを更新します。リカバリとメンテナンスの手順の IP アドレスの変更に関する情報を参照してください。
* 必要に応じて、ストレージ暗号化を設定します。
* 必要に応じて、ストレージの圧縮を設定し、格納されているオブジェクトのサイズを削減します。
* 監査クライアントアクセスを設定します。NFS または CIFS ファイル共有を通じて、監査を目的としたシステムへのアクセスを設定できます。StorageGRID の管理手順を参照してください。



NOTE: CIFS / Samba を使用した監査エクスポートは廃止されており、 StorageGRID の今後のリリースで削除される予定です。

xref:../admin/index.adoc[StorageGRID の管理]

xref:../s3/index.adoc[S3 を使用する]

xref:../swift/index.adoc[Swift を使用します]

xref:../ilm/index.adoc[ILM を使用してオブジェクトを管理する]

xref:../monitor/index.adoc[監視とトラブルシューティング]

xref:../maintain/index.adoc[リカバリとメンテナンス]

xref:../sg100-1000/index.adoc[SG100 および SG1000 サービスアプライアンス]

xref:../sg5600/index.adoc[SG5600 ストレージアプライアンス]

xref:../sg5700/index.adoc[SG5700 ストレージアプライアンス]

xref:../sg6000/index.adoc[SG6000 ストレージアプライアンス]

xref:../release-notes/index.adoc[リリースノート]

xref:../harden/index.adoc[システムの保護対策]

xref:../audit/index.adoc[監査ログを確認します]

xref:../upgrade/index.adoc[ソフトウェアをアップグレードする]
