---
permalink: rhel/automating-installation.html 
sidebar: sidebar 
keywords: how to automate red hat linux installation 
summary: StorageGRID ホストサービスのインストールおよびグリッドノードの設定を自動化することができます。 
---
= インストールの自動化（ Red Hat Enterprise Linux または CentOS ）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID ホストサービスのインストールおよびグリッドノードの設定を自動化することができます。

導入を自動化すると、次のいずれかの場合に役立ちます。

* 物理ホストや仮想ホストの導入と設定に Ansible 、 Puppet 、 Chef などの標準のオーケストレーションフレームワークをすでに使用している場合。
* 複数の StorageGRID インスタンスを導入する場合。
* 大規模で複雑な StorageGRID インスタンスを導入する場合。


StorageGRID ホストサービスはパッケージによってインストールされ、構成ファイルによって制御されます。次のいずれかの方法で構成ファイルを作成できます。

* xref:creating-node-configuration-files.adoc[構成ファイルを作成します] 手動インストール中の対話的な操作。
* 構成ファイルを事前に準備し（またはプログラム化して）、この資料で説明するように、標準のオーケストレーションフレームワークを使用した自動インストールを可能にします。
+
StorageGRID には、 StorageGRID アプライアンスと StorageGRID システム全体（「グリッド」）の設定を自動化するためのオプションの Python スクリプトが用意されています。これらのスクリプトは直接使用することも、 StorageGRID インストール REST API の使用方法を調べることもできます。グリッドの導入ツールや設定ツールを独自に開発する際の参考としても使用できます。





== StorageGRID ホストサービスのインストールと設定を自動化する

StorageGRID ホストサービスのインストールは、 Ansible 、 Puppet 、 Chef 、 Fabric 、 SaltStack などの標準のオーケストレーションフレームワークを使用して自動化できます。

StorageGRID ホストサービスは RPM 形式でパッケージ化されており、あらかじめ構成ファイルを用意して（またはプログラム化して）おくことで自動インストールが可能です。すでに RHEL または CentOS のインストールおよび設定に標準的なオーケストレーションフレームワークを使用している場合は、プレイブックやレシピに StorageGRID を追加する方が簡単です。

インストールアーカイブに付属の「 /extras 」フォルダにあるサンプルの Ansible のロールとプレイブックを参照してください。Ansible プレイブックは 'Ansible StorageGRID のロールがホストを準備し ' ターゲット・サーバに StorageGRID をインストールする方法を示しています必要に応じて、ロールまたはプレイブックをカスタマイズできます。


NOTE: サンプルのプレイブックには、 StorageGRID ホストサービスを開始する前にネットワークデバイスを作成するために必要な手順は含まれていません。これらの手順は、最終的な確認と使用の前に追加してください。

ホストの準備と仮想グリッドノードの導入の手順をすべて自動化することができます。



== StorageGRID の設定を自動化

グリッドノードを導入したら、 StorageGRID システムの設定を自動化できます。

.必要なもの
* インストールアーカイブにある次のファイルの場所を確認しておきます。
+
[cols="1a,1a"]
|===
| ファイル名 | 説明 


| configure-storagegrid.py  a| 
設定を自動化するための Python スクリプト



| storagegrid-sample.json を設定します  a| 
スクリプトで使用するサンプル構成ファイル



| storagegrid-bank.json を設定する  a| 
スクリプトで使用する空の構成ファイルです

|===
* 構成ファイル configure -storagegrid.json を作成しました。このファイルを作成するには、サンプル構成ファイル（「 configure -storagegrid-sample.json 」）または空の構成ファイル（「 configure -storagegridBlank.json 」）を変更します。


.このタスクについて
configure -storagegrid.py Python スクリプトと、 configure -storagegrid.json 構成ファイルを使用して、 StorageGRID システムの設定を自動化できます。


NOTE: また、 Grid Manager またはインストール API を使用してシステムを設定することもできます。

.手順
. Python スクリプトを実行するために使用する Linux マシンにログインします。
. インストールアーカイブを展開したディレクトリに移動します。
+
例：

+
[listing]
----
cd StorageGRID-Webscale-version/platform
----
+
ここで 'platform` は `debs`, `rps`, または「 vsphere 」です。

. Python スクリプトを実行し、作成した構成ファイルを使用します。
+
例：

+
[listing]
----
./configure-storagegrid.py ./configure-storagegrid.json --start-install
----


.結果
リカバリ・パッケージの .zip ファイルは ' 構成プロセス中に生成され ' インストールおよび構成プロセスを実行しているディレクトリにダウンロードされますグリッドノードで障害が発生した場合に StorageGRID システムをリカバリできるようにするために、リカバリパッケージファイルをバックアップする必要があります。たとえば、バックアップされたセキュアなネットワーク上の場所や、安全なクラウドストレージ上の場所にコピーします。


IMPORTANT: リカバリパッケージファイルには StorageGRID システムからデータを取得するための暗号キーとパスワードが含まれているため、安全に保管する必要があります。

ランダムなパスワードを生成するように指定した場合は、「 passwords.txt 」ファイルを抽出し、 StorageGRID システムへのアクセスに必要なパスワードを探す必要があります。

[listing]
----
######################################################################
##### The StorageGRID "recovery package" has been downloaded as: #####
#####           ./sgws-recovery-package-994078-rev1.zip          #####
#####   Safeguard this file as it will be needed in case of a    #####
#####                 StorageGRID node recovery.                 #####
######################################################################
----
StorageGRID システムがインストールおよび設定されると、確認メッセージが表示されます。

[listing]
----
StorageGRID has been configured and installed.
----
.関連情報
xref:overview-of-installation-rest-api.adoc[インストール REST API の概要]
