---
permalink: rhel/creating-node-configuration-files.html 
sidebar: sidebar 
keywords: how to create red hat linux node configuration files 
summary: ノード構成ファイルは、ノードを起動して適切なネットワークおよびブロックストレージリソースに接続するために StorageGRID ホストサービスで必要となる情報をまとめた小さいテキストファイルです。ノード構成ファイルは仮想ノードに使用され、アプライアンスノードには使用されません。 
---
= Red Hat Enterprise Linux または CentOS 環境のノード構成ファイルを作成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ノード構成ファイルは、ノードを起動して適切なネットワークおよびブロックストレージリソースに接続するために StorageGRID ホストサービスで必要となる情報をまとめた小さいテキストファイルです。ノード構成ファイルは仮想ノードに使用され、アプライアンスノードには使用されません。



== ノード構成ファイルの配置場所

ノードを実行するホストの「 /etc/storagegrid/nodes 」ディレクトリに各 StorageGRID ノードの構成ファイルを配置する必要があります。たとえば、 HostA で管理ノード、ゲートウェイノード、およびストレージノードを 1 つずつ実行する場合は、 3 つのノード構成ファイルを HostA の「 /etc/storagegrid/nodes 」に配置する必要があります。構成ファイルは、 vim や nano などのテキストエディタを使用して各ホストで直接作成することも、別の場所で作成して各ホストに移動することもできます。



== ノード構成ファイルの名前

構成ファイルの名前は、形式は 'node-name.conf ですここで 'node-name' はノードに割り当てる名前ですこの名前は StorageGRID インストーラに表示され、ノード移行などのノードのメンテナンス処理で使用されます。

ノード名は次のルールに従って付ける必要があります。

* 一意である必要があります
* 1 文字目はアルファベットにする必要があります
* A~Z と a~z のアルファベットを使用できます
* 0~9 の数字を使用できます
* 1 つまたは複数のハイフン（ - ）を含めることができます。
* 拡張子「 .conf 」を含めない 32 文字以内である必要があります


これらの命名規則に従っていない /etc/storagegrid/nodes 内のファイルはホスト・サービスで解析されません。

グリッドでマルチサイトトポロジを使用する場合の一般的なノード名は次のようになります。

[listing]
----
site-nodetype-nodenumber.conf
----
たとえば、データセンター 1 の最初の管理ノードには「 dc1-adm1.conf 」を、データセンター 2 の 3 番目のストレージノードには「 dc2-SN1.conf 」を使用できます。ただし、すべてのノード名がルールに従っていれば、別の名前にしてもかまいません。



== ノード構成ファイルの内容

構成ファイルには、キーと値のペアが 1 行に 1 つずつ含まれています。キーと値のペアごとに、次のルールに従う必要があります。

* キーと値は等号 (`=') と省略可能な空白で区切る必要があります
* キーにスペースを含めることはできません。
* 値にはスペースを含めることができます。
* 先頭または末尾の空白は無視されます。


キーの種類に応じて、すべてのノードで必要なものと省略可能なもの、特定のノードタイプでのみ必要なものがあります。

次の表に、サポートされているすべてのキーについて、使用可能な値を示します。中央の列：

* R * ：必須 + BP ：ベストプラクティス + O ：オプション

[cols="2a,1a,4a"]
|===
| キーを押します | R 、 BP 、または O | 価値 


 a| 
ADMIN_IP を指定します
 a| 
BP
 a| 
このノードが属するグリッドのプライマリ管理ノードのグリッドネットワークの IPv4 アドレス。GRID_NETWORK_IP で指定した値を Node_type=VM_Admin_Node および ADMIN_NETWORK_role = Primary のグリッドノードに使用します。このパラメータを省略すると、 mDNS を使用してプライマリ管理ノードの検出が試行されます。

xref:how-grid-nodes-discover-primary-admin-node.adoc[グリッドノードによるプライマリ管理ノードの検出]

* 注 * ：この値は無視されます。また、プライマリ管理ノードでは禁止される場合があります。



 a| 
ADMIN_NETWORK_CONFIG
 a| 
o
 a| 
DHCP 、 STATIC 、または DISABLED



 a| 
ADMIN_NETWORK_ESL
 a| 
o
 a| 
このノードが管理ネットワークゲートウェイ経由で通信する CIDR 表記のサブネットをカンマで区切ったリスト。

例 : '172.16.0.0/21 、 172.17.0.0/21



 a| 
ADMIN_NETWORK_GATEWAY
 a| 
O （ * R * ）
 a| 
このノードのローカルの管理ネットワークゲートウェイの IPv4 アドレス。ADMIN_NETWORK_IP および ADMIN_NETWORK_MASK で定義されるサブネットに属している必要があります。この値は、 DHCP によって設定されたネットワークでは無視されます。

* 注 * ：このパラメータは、 ADMIN_NETWORK_ESL が指定されている場合は必須です。

例

'1.1.1'

「 10.224.4.81.



 a| 
ADMIN_NETWORK_IP
 a| 
o
 a| 
このノードの管理ネットワークにおける IPv4 アドレス。このキーが必要なのは、 ADMIN_NETWORK_CONFIG = STATIC の場合だけです。それ以外の値の場合は指定しないでください。

例

'1.1.1'

「 10.224.4.81.



 a| 
ADMIN_NETWORK_MAC
 a| 
o
 a| 
コンテナ内の管理ネットワークインターフェイスの MAC アドレス。

このフィールドはオプションです。省略すると、 MAC アドレスが自動的に生成されます。

6 つの 16 進数値をコロンで区切って指定する必要があります。

例 : 'B2:9C:02:C2:27:10`



 a| 
ADMIN_NETWORK_MASK
 a| 
o
 a| 
このノードの管理ネットワークにおける IPv4 ネットマスク。このキーが必要なのは、 ADMIN_NETWORK_CONFIG = STATIC の場合だけです。それ以外の値の場合は指定しないでください。

例

「 255.255.255.0 」

「 255.255.248.0 」と入力します



 a| 
ADMIN_NETWORK_MTU を指定します
 a| 
o
 a| 
このノードの管理ネットワークでの最大伝送ユニット（ MTU ）。ADMIN_NETWORK_CONFIG = DHCP の場合は指定しないでください。この値を指定する場合、 1280 ～ 9216 の範囲で指定する必要があります。省略すると、 1500 が使用されます。

ジャンボフレームを使用する場合は、 MTU を 9000 などのジャンボフレームに適した値に設定します。それ以外の場合は、デフォルト値のままにします。

* 重要 * ：ネットワークの MTU 値は、ノードが接続されているスイッチポートに設定された値と一致する必要があります。そうしないと、ネットワークパフォーマンスの問題やパケット損失が発生する可能性があります。

例

「 1500 」

「 8192 」



 a| 
ADMIN_NETWORK_TARGET
 a| 
BP
 a| 
StorageGRID ノードで管理ネットワークのアクセスに使用するホストデバイスの名前。ネットワークインターフェイス名のみがサポートされています。通常、 GRID_NETWORK_TARGET または CLIENT_NETWORK _TARGET に指定したインターフェイス名とは別のインターフェイス名を使用します。

* 注：ボンドデバイスやブリッジデバイスをネットワークターゲットとして使用しないでください。ボンドデバイスの上に VLAN （または他の仮想インターフェイス）を設定するか、ブリッジと仮想イーサネット（ veth ）のペアを使用します。

* ベストプラクティス * ：管理ネットワークの IP アドレスは、このノードで最初は使用しない場合でも値を指定します。そうすることで、ホストでノードの設定を再度行わなくても、管理ネットワークの IP アドレスをあとから追加することができます。

例

「 bond0.1002`

「 ens256 」



 a| 
ADMIN_NETWORK_TARGET タイプ
 a| 
o
 a| 
インターフェイス

（サポートされている値はこれだけです）。



 a| 
ADMIN_NETWORK_TARGET _TYPE_interface_clone_MAC
 a| 
BP
 a| 
正しいか間違っているか

StorageGRID コンテナで管理ネットワークのホストターゲットインターフェイスの MAC アドレスを使用するには、キーを「 true 」に設定して原因 に設定します。

* ベストプラクティス：プロミスキャスモードが必要なネットワークでは、「 ADMIN_NETWORK_TARGET_TYPE_interface_clone_MAC 」キーを使用してください。

MAC クローニングの詳細については、次の URL を参照してください

xref:../rhel/configuring-host-network.adoc#considerations-and-recommendations-for-mac-address-cloning[MAC アドレスのクローニングに関する考慮事項と推奨事項（ Red Hat Enterprise Linux または CentOS ）]

xref:../ubuntu/configuring-host-network.adoc#considerations-and-recommendations-for-mac-address-cloning[MAC アドレスのクローニングに関する考慮事項と推奨事項（ Ubuntu または Debian ）]



 a| 
ADMIN_NETWORK_ROLE
 a| 
* R *
 a| 
Primary または Non-Primary

このキーが必要なのは、 node_type が VM_Admin_Node の場合だけです。それ以外のタイプのノードの場合は指定しないでください。



 a| 
BLOBK_DEVICE_AUDIT_logs
 a| 
* R *
 a| 
このノードで監査ログの永続的なストレージに使用するブロックデバイススペシャルファイルのパスと名前。このキーが必要なのは、 node_type が VM_Admin_Node のノードだけです。それ以外のタイプのノードの場合は指定しないでください。

例

/dev/disk/by-path/pci-0000:03:000-scsi-0:0:0:0

/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd

/dev/mapper/sgws-adm1-audit-logs



 a| 
BLOCK_DEVICE_RANGEDB_000

BLOCK_DEVICE_RANGEDB_001

BLOCK_DEVICE_RANGEDB_002

BLOCK_DEVICE_RANGEDB_003

BLOCK_DEVICE_RANGEDB_004

BLOCK_DEVICE_RANGEDB_005

BLOCK_DEVICE_RANGEDB_006

BLOCK_DEVICE_RANGEDB_007

BLOCK_DEVICE_RANGEDB_008

BLOCK_DEVICE_RANGEDB_009

BLOCK_DEVICE_RANGEDB_010

BLOCK_DEVICE_RANGEDB_011

BLOCK_DEVICE_RANGEDB_012

BLOCK_DEVICE_RANGEDB_013

BLOCK_DEVICE_RANGEDB_014

BLOCK_DEVICE_RANGEDB_015
 a| 
* R *
 a| 
このノードでオブジェクトの永続的なストレージに使用するブロックデバイススペシャルファイルのパスと名前。このキーが必要なのは、 node_type が VM_Storage_Node のノードだけです。それ以外のタイプのノードの場合は指定しないでください。

BLOCK_DEVICE_RANGEDB_000 のみが必須で、それ以外は省略可能です。BLOCK_DEVICE_RANGEDB_000 に指定するブロックデバイスは 4TB 以上である必要があります。それ以外は 4TB 未満でもかまいません。

間は空けずに続けて指定してくださいBLOCK_DEVICE_RANGEDB_005 を指定する場合は、 BLOCK_DEVICE_RANGEDB_004 も指定されている必要があります。

* 注 * ：既存の環境との互換性を確保するため、アップグレードされたノードでは 2 桁のキーがサポートされています。

例

/dev/disk/by-path/pci-0000:03:000-scsi-0:0:0:0

/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd

/dev/mapper/sgws-sn1-rangedb/000



 a| 
BLOBK_DEVICE_tables
 a| 
* R *
 a| 
このノードでデータベーステーブルの永続的なストレージに使用するブロックデバイススペシャルファイルのパスと名前。このキーが必要なのは、 node_type が VM_Admin_Node のノードだけです。それ以外のタイプのノードの場合は指定しないでください。

例

/dev/disk/by-path/pci-0000:03:000-scsi-0:0:0:0

/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd

/dev/mapper/sgws-adm1-tables



 a| 
BLOBK_DEVICE_VAR_LOCAL です
 a| 
* R *
 a| 
このノードが /var/local の永続的ストレージに使用するブロックデバイススペシャルファイルのパスと名前。

例

/dev/disk/by-path/pci-0000:03:000-scsi-0:0:0:0

/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd

/dev/mapper/sgws-sn1-var-local



 a| 
CLIENT_NETWORK_CONFIG
 a| 
o
 a| 
DHCP 、 STATIC 、または DISABLED



 a| 
CLIENT_NETWORK_GATEWAY
 a| 
o
 a| 
このノードのローカルのクライアントネットワークゲートウェイの IPv4 アドレス。 CLIENT_NETWORK_IP および CLIENT_NETWORK_MASK で定義されるサブネットに属している必要があります。この値は、 DHCP によって設定されたネットワークでは無視されます。

例

'1.1.1'

「 10.224.4.81.



 a| 
CLIENT_NETWORK_IP
 a| 
o
 a| 
このノードのクライアントネットワークにおける IPv4 アドレス。このキーが必要なのは、 CLIENT_NETWORK_CONFIG = STATIC の場合だけです。それ以外の値の場合は指定しないでください。

例

'1.1.1'

「 10.224.4.81.



 a| 
CLIENT_NETWORK_MAC
 a| 
o
 a| 
コンテナ内のクライアントネットワークインターフェイスの MAC アドレス。

このフィールドはオプションです。省略すると、 MAC アドレスが自動的に生成されます。

6 つの 16 進数値をコロンで区切って指定する必要があります。

例 : 'B2:9C:02:C2:27:20`



 a| 
CLIENT_NETWORK_MASK
 a| 
o
 a| 
このノードのクライアントネットワークにおける IPv4 ネットマスク。このキーが必要なのは、 CLIENT_NETWORK_CONFIG = STATIC の場合だけです。それ以外の値の場合は指定しないでください。

例

「 255.255.255.0 」

「 255.255.248.0 」と入力します



 a| 
CLIENT_NETWORK_MTU
 a| 
o
 a| 
このノードのクライアントネットワークでの最大伝送ユニット（ MTU ）。CLIENT_NETWORK_CONFIG = DHCP の場合は指定しないでください。この値を指定する場合、 1280 ～ 9216 の範囲で指定する必要があります。省略すると、 1500 が使用されます。

ジャンボフレームを使用する場合は、 MTU を 9000 などのジャンボフレームに適した値に設定します。それ以外の場合は、デフォルト値のままにします。

* 重要 * ：ネットワークの MTU 値は、ノードが接続されているスイッチポートに設定された値と一致する必要があります。そうしないと、ネットワークパフォーマンスの問題やパケット損失が発生する可能性があります。

例

「 1500 」

「 8192 」



 a| 
client_network_target です
 a| 
BP
 a| 
StorageGRID ノードでクライアントネットワークのアクセスに使用するホストデバイスの名前。ネットワークインターフェイス名のみがサポートされています。通常、 GRID_NETWORK_TARGET または ADMIN_NETWORK_TARGET に指定したインターフェイス名とは別のインターフェイス名を使用します。

* 注：ボンドデバイスやブリッジデバイスをネットワークターゲットとして使用しないでください。ボンドデバイスの上に VLAN （または他の仮想インターフェイス）を設定するか、ブリッジと仮想イーサネット（ veth ）のペアを使用します。

* ベストプラクティス： * クライアントネットワークの IP アドレスは、このノードで最初は使用しない場合でも値を指定してください。そうすることで、ホストでノードの設定を再度行わなくても、クライアントネットワークの IP アドレスをあとから追加することができます。

例

「 bond0.1003`

ens423`



 a| 
client_network_target_type
 a| 
o
 a| 
インターフェイス

（この値のみがサポートされています）。



 a| 
client_network_target_type _interface_clone_MAC
 a| 
BP
 a| 
正しいか間違っているか

クライアントネットワークでホストターゲットインターフェイスの MAC アドレスを使用するには、キーを「 true 」に設定して StorageGRID コンテナを原因 します。

* ベストプラクティス：プロミスキャスモードが必要なネットワークでは、 client_network_target_type _interface_clone_MAC キーを使用してください。

MAC クローニングの詳細については、次の URL を参照してください

xref:../rhel/configuring-host-network.adoc#considerations-and-recommendations-for-mac-address-cloning[MAC アドレスのクローニングに関する考慮事項と推奨事項（ Red Hat Enterprise Linux または CentOS ）]

xref:../ubuntu/configuring-host-network.adoc#considerations-and-recommendations-for-mac-address-cloning[MAC アドレスのクローニングに関する考慮事項と推奨事項（ Ubuntu または Debian ）]



 a| 
GRID_NETWORK_CONFIG
 a| 
BP
 a| 
STATIC または DHCP

（指定しない場合のデフォルトは STATIC ）



 a| 
GRID_NETWORK_GATEWAY
 a| 
* R *
 a| 
このノードのローカルのグリッドネットワークゲートウェイの IPv4 アドレス。 GRID_NETWORK_IP および GRID_NETWORK_MASK で定義されるサブネットに属している必要があります。この値は、 DHCP によって設定されたネットワークでは無視されます。

グリッドネットワークのサブネットが 1 つだけでゲートウェイがない場合は、サブネットの標準のゲートウェイアドレス（ X.Y.Z.1 ）か、このノードの GRID_NETWORK_IP の値を使用します。このどちらかの値にしておけば、以降にグリッドネットワークを拡張するときに処理が簡単になります。



 a| 
GRID_NETWORK_IP
 a| 
* R *
 a| 
このノードのグリッドネットワークにおける IPv4 アドレス。このキーが必要なのは、 GRID_NETWORK_CONFIG = STATIC の場合だけです。それ以外の値の場合は指定しないでください。

例

'1.1.1'

「 10.224.4.81.



 a| 
GRID_NETWORK_MAC
 a| 
o
 a| 
コンテナ内のグリッドネットワークインターフェイスの MAC アドレス。

このフィールドはオプションです。省略すると、 MAC アドレスが自動的に生成されます。

6 つの 16 進数値をコロンで区切って指定する必要があります。

例 : 'B2:9C:02:C2:27:30



 a| 
GRID_NETWORK_MASK
 a| 
o
 a| 
このノードのグリッドネットワークにおける IPv4 ネットマスク。このキーが必要なのは、 GRID_NETWORK_CONFIG = STATIC の場合だけです。それ以外の値の場合は指定しないでください。

例

「 255.255.255.0 」

「 255.255.248.0 」と入力します



 a| 
GRID_NETWORK_MTU
 a| 
o
 a| 
このノードのグリッドネットワークでの最大伝送ユニット（ MTU ）。GRID_NETWORK_CONFIG = DHCP の場合は指定しないでください。この値を指定する場合、 1280 ～ 9216 の範囲で指定する必要があります。省略すると、 1500 が使用されます。

ジャンボフレームを使用する場合は、 MTU を 9000 などのジャンボフレームに適した値に設定します。それ以外の場合は、デフォルト値のままにします。

* 重要 * ：ネットワークの MTU 値は、ノードが接続されているスイッチポートに設定された値と一致する必要があります。そうしないと、ネットワークパフォーマンスの問題やパケット損失が発生する可能性があります。

* 重要 * ：ネットワークパフォーマンスを最大限に高めるには、すべてのノードのグリッドネットワークインターフェイスで MTU 値がほぼ同じになるように設定する必要があります。個々のノードのグリッドネットワークの MTU 設定に大きな違いがある場合は、 * Grid Network MTU mismatch * アラートがトリガーされます。MTU 値はすべてのネットワークタイプで同じである必要はありません。

例

1 、 500 、 8192



 a| 
GRID_NETWORK_TARGET
 a| 
* R *
 a| 
StorageGRID ノードでグリッドネットワークのアクセスに使用するホストデバイスの名前。ネットワークインターフェイス名のみがサポートされています。通常、 ADMIN_NETWORK_TARGET または ADMIN_NETWORK_TARGET に指定したインターフェイス名とは別のインターフェイス名を使用します。

* 注：ボンドデバイスやブリッジデバイスをネットワークターゲットとして使用しないでください。ボンドデバイスの上に VLAN （または他の仮想インターフェイス）を設定するか、ブリッジと仮想イーサネット（ veth ）のペアを使用します。

例

「 bond0.1001 」と入力します

「 ens192 」



 a| 
GRID_NETWORK_TARGET タイプ
 a| 
o
 a| 
インターフェイス

（サポートされている値はこれだけです）。



 a| 
GRID_NETWORK_TARGET _TYPE_interface_clone_MAC
 a| 
* BP *
 a| 
正しいか間違っているか

グリッドネットワーク上のホストターゲットインターフェイスの MAC アドレスを使用するには、キーの値を「 true 」に設定して StorageGRID コンテナを原因 に設定します。

* ベストプラクティス：プロミスキャスモードが必要なネットワークでは、 GRID_NETWORK_TARGET _TYPE_interface_clone_MAC キーを使用してください。

MAC クローニングの詳細については、次の URL を参照してください

xref:../rhel/configuring-host-network.adoc#considerations-and-recommendations-for-mac-address-cloning[MAC アドレスのクローニングに関する考慮事項と推奨事項（ Red Hat Enterprise Linux または CentOS ）]

xref:../ubuntu/configuring-host-network.adoc#considerations-and-recommendations-for-mac-address-cloning[MAC アドレスのクローニングに関する考慮事項と推奨事項（ Ubuntu または Debian ）]



 a| 
Interfaces_target_nnnn
 a| 
o
 a| 
このノードに追加するインターフェイスの名前とオプションの概要 。各ノードに複数のインターフェイスを追加できます。

「 _nnnnnn _ 」には、追加する各 interfaces _ target エントリの一意の番号を指定します。

値には、ベアメタルホスト上の物理インターフェイスの名前を指定します。その後、必要に応じて、カンマを追加してインターフェイスの概要 を指定します。このインターフェイスは、 VLAN インターフェイスのページと HA グループのページに表示されます。

たとえば 'interfaces_target_01= ens256'Trunk' のようになります

トランクインターフェイスを追加する場合は、 StorageGRID で VLAN インターフェイスを設定する必要があります。アクセスインターフェイスを追加する場合は、 HA グループに直接追加できます。 VLAN インターフェイスを設定する必要はありません。



 a| 
MAXIMUM_RAM
 a| 
o
 a| 
このノードに使用を許可する RAM の最大容量。このキーを省略した場合、ノードでメモリは制限されません。本番用のノードについて設定するときは、システム RAM の合計容量よりも 24GB 以上、 16~32GB 以上小さい値を指定してください。

* 注 * ： RAM 値は、ノードの実際のメタデータ用リザーブスペースに影響します。を参照してください xref:../admin/index.adoc[StorageGRID の管理手順] 概要 の場合： Metadata Reserved Space とは

このフィールドの形式は '<number><unit>` ですここで '<unit>` には 'b`'k`'`'m`''g` を指定できます

例

「 24g 」と入力します

38654705664b'

* 注：このオプションを使用する場合は、 memory cgroups のカーネルサポートを有効にする必要があります。



 a| 
Node_type のように指定します
 a| 
* R *
 a| 
ノードのタイプ：

VM_Admin_Node VM_Storage_Node VM_Archive_Node VM_API_Gateway



 a| 
PORT_REMAP を参照してください
 a| 
o
 a| 
ノードが内部でのグリッドノードの通信または外部との通信に使用するポートを再マッピングします。ポートの再マッピングが必要になるのは、 StorageGRID で使用される 1 つ以上のポートがエンタープライズネットワークポリシーで制限されている場合です。詳細については、「内部グリッドノードの通信」または「外部通信」を参照してください。

* 重要 * ：ロードバランサエンドポイントの設定に使用する予定のポートを再マッピングしないでください。

* 注： PORT_REMAP のみを設定すると、指定したマッピングがインバウンド通信とアウトバウンド通信の両方に使用されます。PORT_REMAP_INBOUND を併せて指定した場合は、 PORT_REMAP がアウトバウンド通信のみに適用されます。

使用される形式は「 <network type>/<protocol>/< Grid ノードで使用されるデフォルトポート >/< 新しいポート >` です。ここで、「 <network type> 」は grid 、 admin 、 client のいずれかです。プロトコルは tcp または udp です。

例：

`port_remap=client/TCP/18082/443`



 a| 
PORT_REMAP_INBOUND
 a| 
o
 a| 
指定したポートのインバウンド通信を再マッピングします。PORT_REMAP_INBOUND を指定して PORT_REMAP に値を指定しなかった場合は、ポートのアウトバウンド通信が変更されません。

* 重要 * ：ロードバランサエンドポイントの設定に使用する予定のポートを再マッピングしないでください。

使用される形式は、「 <network type> 」 / 「 <protocol:>/< 再マッピングされたポート >/< グリッドノードで使用されるデフォルトポート >` です。「 <network type> 」は grid 、 admin 、 client のいずれかです。プロトコルは TCP または UDP です。

例：

`port_remap_inbound=grid/tcp/3022/22`

|===
.関連情報
xref:../network/index.adoc[ネットワークのガイドライン]
