---
permalink: admin/adding-nfs-audit-client-to-audit-share.html 
sidebar: sidebar 
keywords: nfs, audit client, audit share 
summary: NFS 監査クライアントは、 IP アドレスに基づいて監査共有へのアクセスが許可されます。新しい NFS 監査クライアントに監査共有へのアクセスを許可するには、そのクライアントの IP アドレスを監査共有に追加します。 
---
= 監査共有に NFS 監査クライアントを追加します
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS 監査クライアントは、 IP アドレスに基づいて監査共有へのアクセスが許可されます。新しい NFS 監査クライアントに監査共有へのアクセスを許可するには、そのクライアントの IP アドレスを監査共有に追加します。

.必要なもの
* root/admin アカウントのパスワードを持つ「 passwords.txt 」ファイルがあります（ SAID パッケージ内にあります）。
* 「 Configuration.txt 」ファイルがあります（ SAID パッケージ内にあります）。
* 監査クライアントが NFS バージョン 3 （ NFSv3 ）を使用している。


.手順
. プライマリ管理ノードにログインします。
+
.. 次のコマンドを入力します。 ssh admin@_primary_Admin_Node_IP_`
.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
.. root に切り替えるには、次のコマンドを入力します
.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
+
root としてログインすると、プロンプトは「 $` 」から「 #」 に変わります。



. NFS 構成ユーティリティを起動します :'config_nfs.rb
+
[listing]
----

-----------------------------------------------------------------
| Shares               | Clients              | Config          |
-----------------------------------------------------------------
| add-audit-share      | add-ip-to-share      | validate-config |
| enable-disable-share | remove-ip-from-share | refresh-config  |
|                      |                      | help            |
|                      |                      | exit            |
-----------------------------------------------------------------
----
. 「 add-ip-to-share 」と入力します
+
管理ノードで有効になっている NFS 監査共有のリストが表示されます。監査共有は '/var/local/audit/export' として表示されます

. 監査共有の番号として '_audit_share_number_' を入力します
. プロンプトが表示されたら、監査共有の監査クライアントの IP アドレスまたは IP アドレス範囲を入力します
+
監査クライアントが監査共有に追加されます。

. プロンプトが表示されたら、 * Enter * を押します。
+
NFS 設定ユーティリティが表示されます。

. 監査共有に追加する監査クライアントごとに、この手順を繰り返します。
. オプションで、構成を確認します。「 validate-config 」
+
サービスがチェックされて表示されます。

+
.. プロンプトが表示されたら、 * Enter * を押します。
+
NFS 設定ユーティリティが表示されます。



. NFS 設定ユーティリティを閉じます
. StorageGRID 環境が単一サイトの場合は、次の手順に進みます。
+
StorageGRID 環境で他のサイトに管理ノードが含まれている場合は、必要に応じてこれらの監査共有を有効にします。

+
.. サイトの管理ノードにリモートからログインします。
+
... 次のコマンドを入力します。 ssh admin@_grid_node_name
... 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
... root に切り替えるには、次のコマンドを入力します
... 「 passwords.txt 」ファイルに記載されたパスワードを入力します。


.. 同じ手順を繰り返して、管理ノードごとに監査共有を設定します。
.. リモート管理ノードへのリモートの Secure Shell ログインを終了します。「 exit


. コマンドシェルからログアウトします :exit

