---
permalink: admin/change-node-console-password.html 
sidebar: sidebar 
keywords: node console password, console password, change password, password 
summary: グリッド内の各ノードには、一意のノードコンソールパスワードが設定されています。このパスワードを使用してノードにログインする必要があります。グリッド内の各ノードのノードコンソールパスワードを変更するには、次の手順を実行します。パスワードはリカバリパッケージに格納されます。 
---
= ノードのコンソールパスワードを変更します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッド内の各ノードには、一意のノードコンソールパスワードが設定されています。このパスワードを使用してノードにログインする必要があります。次の手順に従って、グリッド内のノードごとに一意のノードコンソールパスワードを変更します。

.必要なもの
* を使用して Grid Manager にサインインします link:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* Maintenance または Root アクセス権限が必要です。
* 現在のプロビジョニングパスフレーズを用意します。


.このタスクについて
ノードのコンソールパスワードを使用して、 SSH を使用して「 admin 」としてノードにログインするか、または VM/ 物理コンソール接続のルートユーザにログインします。ノードコンソールパスワードの変更プロセスでは、グリッド内の各ノードに対して新しいパスワードが作成され、更新されたに格納されます `Passwords.txt` リカバリパッケージ内のファイル。の[Password]列にパスワードが表示されます `Passwords.txt` ファイル。


NOTE: ノード間の通信に使用する SSH キー用に、個別の SSH アクセスパスワードがあります。SSH アクセスパスワードはこの手順 によって変更されません。



== ウィザードにアクセスします

.手順
. * 設定 * > * アクセス制御 * > * Grid パスワード * を選択します。
. [ノードコンソールパスワードの変更]*で、*[変更する]*を選択します。




== プロビジョニングパスフレーズを入力します

.手順
. グリッドのプロビジョニングパスフレーズを入力します。
. 「 * Continue * 」を選択します。




== [[download-current]]現在のリカバリパッケージをダウンロードします

ノードコンソールのパスワードを変更する前に、現在のリカバリパッケージをダウンロードしてください。いずれかのノードでパスワードの変更プロセスが失敗した場合は、このファイルのパスワードを使用できます。

.手順
. [ リカバリパッケージのダウンロード ] を選択します。
. リカバリパッケージファイルをコピーします (`.zip`)を2箇所に安全に、安全に、そして別 々 の場所に移動します。
+

CAUTION: リカバリパッケージファイルには StorageGRID システムからデータを取得するための暗号キーとパスワードが含まれているため、安全に保管する必要があります。

. 「 * Continue * 」を選択します。
. 確認ダイアログが表示されたら、ノードコンソールのパスワードの変更を開始する準備ができている場合は*[はい]*を選択します。
+
このプロセスは開始後にキャンセルすることはできません。





== ノードのコンソールパスワードを変更します

ノードのコンソールパスワードのプロセスが開始されると、新しいパスワードを含む新しいリカバリパッケージが生成されます。その後、各ノードでパスワードが更新されます。

.手順
. 新しいリカバリパッケージが生成されるまで待ちます。これには数分かかることがあります。
. [ 新しいリカバリパッケージのダウンロード ] を選択します。
. ダウンロードが完了したら、次の手順を実行
+
.. 「 .zip 」ファイルを開きます。
.. などのコンテンツにアクセスできることを確認します `Passwords.txt` ファイル。ノードコンソールの新しいパスワードを格納します。
.. 新しいリカバリパッケージファイルをコピーします (`.zip`)を2箇所に安全に、安全に、そして別 々 の場所に移動します。
+

CAUTION: 古いリカバリパッケージは上書きしないでください。

+
リカバリパッケージファイルには StorageGRID システムからデータを取得するための暗号キーとパスワードが含まれているため、安全に保管する必要があります。



. 新しいリカバリパッケージをダウンロードしてコンテンツを検証したことを示すチェックボックスを選択します。
. [ノードコンソールパスワードの変更]*を選択し、すべてのノードが新しいパスワードで更新されるまで待ちます。この処理には数分かかることがあります。
+
すべてのノードでパスワードを変更した場合は、成功を示す緑のバナーが表示されます。次の手順に進みます。

+
更新プロセスでエラーが発生した場合は、バナーメッセージにパスワードを変更できなかったノードの数が表示されます。パスワードを変更できなかったノードに対して、処理が自動的に再試行されます。プロセスが終了してもパスワードが変更されていないノードがある場合は、「 * Retry * 」ボタンが表示されます。

+
1 つ以上のノードでパスワードの更新に失敗した場合：

+
.. 表に表示されたエラーメッセージを確認します。
.. 問題を解決します。
.. [* Retry* ] を選択します。
+

NOTE: 再試行すると、前回のパスワード変更で失敗したノード上のノードコンソールパスワードのみが変更されます。



. すべてのノードのノードコンソールパスワードを変更したら、を削除します <<download-current,最初にダウンロードしたリカバリパッケージ>>。
. 必要に応じて、 * Recovery パッケージ * リンクを使用して、新しいリカバリパッケージの追加コピーをダウンロードできます。

