---
permalink: admin/configuring-client-connections.html 
sidebar: sidebar 
keywords: s3 connection, swift connection, connect to storagegrid 
summary: グリッド管理者は設定オプションを管理して、 S3 および Swift テナントがクライアントアプリケーションを StorageGRID システムに接続してデータの格納と読み出しを行う方法を制御します。クライアントとテナントのさまざまな要件を満たすために、多数のオプションが用意されています。 
---
= S3 および Swift クライアント接続について
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッド管理者は設定オプションを管理して、 S3 および Swift テナントがクライアントアプリケーションを StorageGRID システムに接続してデータの格納と読み出しを行う方法を制御します。クライアントとテナントのさまざまな要件を満たすために、多数のオプションが用意されています。

クライアントアプリケーションは、次のいずれかに接続することで、オブジェクトを格納または読み出すことができます。

* 管理ノードまたはゲートウェイノード上のロードバランササービス、または必要に応じて、管理ノードまたはゲートウェイノードのハイアベイラビリティ（ HA ）グループの仮想 IP アドレス
* ゲートウェイノード上の CLB サービス、または必要に応じて、ゲートウェイノードのハイアベイラビリティグループの仮想 IP アドレス
+

NOTE: CLB サービスは廃止されました。StorageGRID 11.3 より前に設定されたクライアントは、ゲートウェイノード上の CLB サービスを引き続き使用できます。ロードバランシングに StorageGRID を使用する他のすべてのクライアントアプリケーションは、ロードバランササービスを使用して接続する必要があります。

* 外部ロードバランサを使用するかどうかに関係なく、ストレージノードに追加されます


StorageGRID システムには、必要に応じて次の機能も設定できます。

* * VLAN インターフェイス * ：管理ノードとゲートウェイノードに仮想 LAN （ VLAN ）インターフェイスを作成してクライアントトラフィックとテナントトラフィックを分離し、パーティション化することで、セキュリティ、柔軟性、パフォーマンスを向上させることができます。VLAN インターフェイスを作成したら、ハイアベイラビリティ（ HA ）グループに追加します。
* * ハイアベイラビリティグループ * ：ゲートウェイノードまたは管理ノードのインターフェイスの HA グループを作成してアクティブ / バックアップ構成を作成できます。また、ラウンドロビン DNS やサードパーティ製ロードバランサと複数の HA グループを使用してアクティブ / アクティブ構成を実現することもできます。クライアント接続は、 HA グループの仮想 IP アドレスを使用して確立されます。
* * ロードバランササービス * ：クライアントがロードバランササービスを使用できるようにするには、クライアント接続用のロードバランサエンドポイントを作成します。ロードバランサエンドポイントを作成する際には、ポート番号、エンドポイントで HTTP / HTTPS 接続を許可するかどうか、エンドポイントを使用するクライアントのタイプ（ S3 または Swift ）、 HTTPS 接続に使用する証明書（該当する場合）を指定します。
* * 信頼されていないクライアントネットワーク * ：信頼されていないクライアントネットワークとして設定することで、クライアントネットワークのセキュリティを強化できます。クライアントネットワークが信頼されていない場合、クライアントはロードバランサエンドポイントを使用して接続する必要があります。


ストレージノードに直接接続するか、 CLB サービス（廃止予定）を使用して StorageGRID に接続するクライアントに対しては、 HTTP の使用を有効にし、 S3 クライアントには S3 API エンドポイントのドメイン名を設定できます。
