---
permalink: admin/configuring-audit-client-for-nfs.html 
sidebar: sidebar 
keywords: audit client for NFS 
summary: 監査共有は読み取り専用の共有として自動的に有効になります。 
---
= NFS の監査クライアントを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
監査共有は読み取り専用の共有として自動的に有効になります。

.必要なもの
* root/admin パスワードを持つ「 passwords.txt 」ファイルがあります（ SAID パッケージ内にあります）。
* 「 Configuration.txt 」ファイルがあります（ SAID パッケージ内にあります）。
* 監査クライアントが NFS バージョン 3 （ NFSv3 ）を使用している。


この手順 は、監査メッセージの取得先である StorageGRID 環境内の管理ノードごとに実行します。

.手順
. プライマリ管理ノードにログインします。
+
.. 次のコマンドを入力します。 ssh admin@_primary_Admin_Node_IP_`
.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
.. root に切り替えるには、次のコマンドを入力します
.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
+
root としてログインすると、プロンプトは「 $` 」から「 #」 に変わります。



. すべてのサービスの状態が「 Running 」または「 Verified 」であることを確認します。「 storagegrid-status 」と入力します
+
「 Running 」または「 Verified 」でないサービスがある場合は、問題を解決してから続行してください。

. コマンドラインに戻ります。Ctrl キーを押しながら * C キーを押します。
. NFS 設定ユーティリティを起動します。「 config_nfs.rb 」と入力します
+
[listing]
----

-----------------------------------------------------------------
| Shares               | Clients              | Config          |
-----------------------------------------------------------------
| add-audit-share      | add-ip-to-share      | validate-config |
| enable-disable-share | remove-ip-from-share | refresh-config  |
|                      |                      | help            |
|                      |                      | exit            |
-----------------------------------------------------------------
----
. 監査クライアント「 add-audit-share 」を追加します
+
.. プロンプトが表示されたら、監査共有の監査クライアントの IP アドレスまたは IP アドレス範囲を入力します。「 client_ip_address
.. プロンプトが表示されたら、 * Enter * を押します。


. 複数の監査クライアントが監査共有へのアクセスを許可されている場合は、追加ユーザ「 add-ip-to-share 」の IP アドレスを追加します
+
.. 監査共有の番号として '_audit_share_number_' を入力します
.. プロンプトが表示されたら、監査共有の監査クライアントの IP アドレスまたは IP アドレス範囲を入力します
.. プロンプトが表示されたら、 * Enter * を押します。
+
NFS 設定ユーティリティが表示されます。

.. 監査共有に追加する監査クライアントごとに、上記の手順を繰り返します。


. 必要に応じて、設定を確認します。
+
.. 「 validate-config 」と入力します
+
サービスがチェックされて表示されます。

.. プロンプトが表示されたら、 * Enter * を押します。
+
NFS 設定ユーティリティが表示されます。

.. NFS 設定ユーティリティを閉じます


. 他のサイトで監査共有を有効にする必要があるかどうかを確認します。
+
** StorageGRID 環境が単一サイトの場合は、次の手順に進みます。
** StorageGRID 環境で他のサイトに管理ノードが含まれている場合は、必要に応じてこれらの監査共有を有効にします。
+
... サイトの管理ノードにリモートからログインします。
+
.... 次のコマンドを入力します。 ssh admin@_grid_node_name
.... 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
.... root に切り替えるには、次のコマンドを入力します
.... 「 passwords.txt 」ファイルに記載されたパスワードを入力します。


... 同じ手順を繰り返して、追加の管理ノードごとに監査共有を設定します。
... リモート管理ノードへのリモートの Secure Shell ログインを終了します。「 exit 」と入力します




. コマンドシェルからログアウトします :exit
+
NFS 監査クライアントは、 IP アドレスに基づいて監査共有へのアクセスが許可されます。新しい NFS 監査クライアントに共有に IP アドレスを追加して監査共有へのアクセスを許可するか、または IP アドレスを削除して既存の監査クライアントを削除します。


