---
permalink: admin/defining-tsm-tape-and-disk-storage-pools.html 
sidebar: sidebar 
keywords: archive node, tsm, tape storage pool, tivoli storage manager 
summary: アーカイブノードはディスクストレージプールに書き込みます。コンテンツをテープにアーカイブするには、コンテンツをテープストレージプールに移動するようにディスクストレージプールを設定する必要があります。 
---
= TSM テープストレージプールとディスクストレージプールを定義します
:icons: font
:imagesdir: ../media/


[role="lead"]
アーカイブノードはディスクストレージプールに書き込みます。コンテンツをテープにアーカイブするには、コンテンツをテープストレージプールに移動するようにディスクストレージプールを設定する必要があります。

1 台の TSM サーバに対し、 Tivoli Storage Manager でテープストレージプールとディスクストレージプールを定義する必要があります。ディスクプールを定義したら、ディスクボリュームを作成してディスクプールに割り当てます。TSM サーバでディスクのみのストレージを使用する場合、テーププールは必要ありません。

テープストレージプールを作成する前に、 TSM サーバでいくつかの手順を完了しておく必要があります。（テープライブラリを作成し、テープライブラリにドライブを少なくとも 1 本作成します。サーバからライブラリへのパスとサーバからドライブへのパスを定義し、ドライブのデバイスクラスを定義します）。 これらの手順の詳細は、サイトのハードウェア構成とストレージ要件によって異なります。詳細については、 TSM のドキュメントを参照してください。

以下に、このプロセスの手順を示します。サイトの要件は導入の要件によって異なることに注意してください。設定の詳細および手順については、 TSM のドキュメントを参照してください。


NOTE: 以下のコマンドを実行するには、管理者権限を使用してサーバにログオンし、 dsmadmc ツールを使用する必要があります。

.手順
. テープライブラリを作成します。
+
「 define library_tapellibrary_libtype=_scsi_ 」を入力します

+
ここで '_tapellibrary_` はテープ・ライブラリ用に選択された任意の名前であり 'libtype' の値はテープ・ライブラリのタイプによって異なります

. サーバからテープライブラリへのパスを定義します。
+
「 define path_servername tapelible_srctype=server desttype=library device=_lib-devicename_`

+
** `_ servername _` は TSM サーバの名前です
** `_tapellibrary_` は ' 定義したテープ・ライブラリ名です
** `_lib-devicename_` はテープ・ライブラリのデバイス名です


. ライブラリのドライブを定義します。
+
'define drive_tapelLIVEY_drivenname_ 」のように入力します

+
** `_drivenname_ はドライブに指定する名前です
** `_tapellibrary_` は ' 定義したテープ・ライブラリ名です
+
ハードウェア構成によっては、追加のドライブを設定することが必要になる場合があります。（たとえば、 1 つのテープライブラリからの入力が 2 つあるファイバチャネルスイッチに TSM サーバが接続されている場合は、入力ごとにドライブを定義します）。



. サーバから定義したドライブへのパスを定義します。
+
'define path_servername_drivenname srctype=server desttype=drive library=_tapelLIBRARY_device=_drive-dname_`

+
** `_drive-dname_` はドライブのデバイス名です
** `_tapellibrary_` は ' 定義したテープ・ライブラリ名です
+
テープ・ライブラリ用に定義したドライブごとに ' ドライブごとに個別の `_drivenname_ と `_drive-dname_` を使用して ' この手順を繰り返します



. ドライブのデバイスクラスを定義します。
+
「 define devclass_DeviceClassName_devtype=_LTO_library=_tapellibrary_format=_tapetype_`

+
** 「 _DeviceClassName_ 」はデバイスクラスの名前です
** 「 _LTO_ 」は、サーバに接続されているドライブのタイプです
** `_tapellibrary_` は ' 定義したテープ・ライブラリ名です
** `_tapetype_` はテープのタイプ、例えば ultrium3 である


. ライブラリのインベントリにテープボリュームを追加します。
+
'checkin libvolume_tapelible_`

+
`_tapellibrary_` は ' 定義したテープ・ライブラリ名です

. プライマリテープストレージプールを作成します。
+
'define stgpool_SGWSTapePool__ DeviceClassName_description=_description=filespace_maxscratch=_XX_ ’

+
** `_SGWSTapePool_` はアーカイブノードのテープストレージプールの名前ですテープストレージプールには（ TSM サーバが想定する命名規則に沿ってさえいれば）任意の名前を選択できます。
** `_DeviceClassName_ はテープ・ライブラリのデバイス・クラス名です
** `_TSM_ 概要 は 'query stgpool' コマンドを使用して TSM サーバに表示できるストレージ・プールの概要 ですたとえば ' アーカイブ・ノード用のテープ・ストレージ・プールなどです
** `_collocate = filespace_ は 'TSM サーバが同じファイル・スペースのオブジェクトを 1 つのテープに書き込む必要があることを指定します
** 「 XX 」は次のいずれかです。
+
*** テープライブラリ内の空のテープの数（アーカイブノードだけがライブラリを使用している場合）。
*** StorageGRID システム用に割り当てられているテープの数（テープライブラリが共有されている場合）。




. TSM サーバで、ディスクストレージプールを作成します。TSM サーバの管理コンソールで、と入力します
+
`define stgpool_SGWSDiskPool_disk description=_descript_maxsize=_maximum_file_size nextstgpool=SGWSTapePool_highmig=_percent_high_lowg=_percent_low_`

+
** `_SGWSDiskPool_` は ' アーカイブ・ノードのディスク・プールの名前ですディスクストレージプールには（ TSM が想定する命名規則に沿ってさえいれば）任意の名前を選択できます。
** `_TSM_ 概要 は 'query stgpool' コマンドを使用して TSM サーバに表示できるストレージ・プールの概要 ですたとえば ' アーカイブ・ノード用のディスク・ストレージ・プールなどです
** `_maximum_file_size_` は ' ディスク・プールにキャッシュされるのではなく ' このサイズより大きいオブジェクトを直接テープに書き込むように強制します_maximum_file_size_' を 10 GB に設定することをお勧めします
** `_nextstgpool=SGWSTapePool_` はディスクストレージプールをアーカイブノード用に定義されたテープストレージプールと参照します
** `_percent_high_` は ' ディスク・プールがテープ・プールへのコンテンツの移行を開始するときの値を設定しますデータ移行がすぐに開始されるように '_percent_high_' を 0 に設定することをお勧めします
** `_percent_low_` はテープ・プールへの移行を停止する値を設定しますディスク・プールをクリアするには '_percent_low_' を 0 に設定することをお勧めします


. TSM サーバで、 1 つ以上のディスクボリュームを作成してディスクプールに割り当てます。
+
'define volume_SGWSDiskPool__ volume_name_formatsize=_size_`

+
** `_SGWSDiskPool_` はディスク・プール名です
** `_volume_name_` は TSM サーバ上のボリュームの場所へのフルパスです ( 例 : /var/local/arc/stage6.dsm ) テープへの転送に備えてディスクプールの内容を書き込む
** `_size_ は ' ディスク・ボリュームのサイズ（ MB 単位）です
+
たとえば、テープボリュームの容量が 200GB の場合、ディスクプールのコンテンツで 1 つのテープを使い切るようなディスクボリュームを 1 個作成するには、 size の値を 200000 に設定します。

+
ただし、 TSM サーバがディスクプール内の各ボリュームに書き込むことができるため、小さいサイズのディスクボリュームを複数作成する方がよい場合もあります。たとえばテープサイズが 250GB の場合、 10GB （ 10000 ）のディスクボリュームを 25 個作成します。

+
TSM サーバは、ディスクボリューム用にディレクトリ内のスペースを事前に割り当てます。この処理には、完了までに時間がかかることがあります（ 200GB のディスクボリュームの場合は 3 時間以上）。




