---
permalink: admin/determining-ilm-policy-for-migrated-data.html 
sidebar: sidebar 
keywords: determing ilm policy, ilm for migrated data 
summary: StorageGRID システムの ILM ポリシーは、作成されるコピーの数、コピーの格納先、およびコピーの保持期間を決定します。ILM ポリシーは、オブジェクトをフィルタリングする方法、および一定の期間にわたってオブジェクトデータを管理する方法を記述した一連の ILM ルールで構成されます。 
---
= 移行データの ILM ポリシーを決定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID システムの ILM ポリシーは、作成されるコピーの数とその格納先、および保持期間を決定します。ILM ポリシーは、オブジェクトをフィルタリングする方法、および一定の期間にわたってオブジェクトデータを管理する方法を記述した一連の ILM ルールで構成されます。

移行データの使用方法およびその要件によっては、日常業務に使用する ILM ルールとは別の、移行データに固有の ILM ルールを定義することができます。たとえば、日常的なデータ管理と移行対象のデータに異なる規制要件が適用される場合、異なるグレードのストレージに異なる数の移行データのコピーが必要となる可能性があります。

移行データと日常業務で保存されるオブジェクトデータを一意に区別できる場合は、移行データにのみ適用されるルールを設定できます。

いずれかのメタデータ条件を使用してデータのタイプを確実に識別できる場合は、この条件を使用して移行データにのみ適用される ILM ルールを定義できます。

データ移行を開始する前に、 StorageGRID システムの ILM ポリシーとそのポリシーが移行データにどのように適用されるかを確認し、 ILM ポリシーへの変更があればテストしておく必要があります。を参照してください xref:../ilm/index.adoc[ILM を使用してオブジェクトを管理する]。


CAUTION: ILM ポリシーが正しく指定されていないと、原因 によるリカバリ不能なデータ損失が発生する可能性があります。ポリシーを想定どおりに機能させるには、 ILM ポリシーをアクティブ化する前に、 ILM ポリシーに加えたすべての変更をよく確認してください。
