---
permalink: admin/impact-of-migration-on-operations.html 
sidebar: sidebar 
keywords: how data migration affects operations 
summary: StorageGRID システムは、オブジェクトを効率的に格納して読み出せるようにすること、およびオブジェクトデータとメタデータの冗長コピーをシームレスに作成することでデータ損失に対する優れた保護を提供することを目的に設計されています。 
---
= 移行が処理に及ぼす影響
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID システムは、オブジェクトを効率的に格納して読み出せるようにすること、およびオブジェクトデータとメタデータの冗長コピーをシームレスに作成することでデータ損失に対する優れた保護を提供することを目的に設計されています。

ただし、日常的なシステム運用に影響が及ばないように、または極端なケースでは StorageGRID システムに障害が発生してデータが失われないように、この章の手順に従ってデータ移行を慎重に管理する必要があります。

大量のデータを移行すると、システムに新たな負荷がかかります。StorageGRID システムの負荷が高い場合は、オブジェクトの格納および読み出し要求への応答が遅くなります。その結果、日常業務に不可欠な格納および読み出し要求が影響を受ける可能性があります。移行は、原因 のその他の運用上の問題にもなります。たとえば、ストレージノードの容量が上限に近づい原因 ている場合は、一括取り込みによって断続的に大きな負荷がかかると、ストレージノードが読み取り専用と読み書き可能の間で何度も切り替わり、そのたびに通知が生成されます。

負荷の高い状態が続く場合、オブジェクトデータとメタデータの完全な冗長性を確保するために StorageGRID システムが実行する必要のあるさまざまな処理がキューに溜まっていきます。

移行中に StorageGRID システムを安全かつ効率的に運用するためには、本書のガイドラインに従ってデータ移行を慎重に管理する必要があります。データの移行にあたっては、オブジェクトを複数のバッチで取り込むか、または取り込み量を常に調整します。そのうえで、 StorageGRID システムを常時監視し、さまざまな属性値が超えようにします。
