---
permalink: admin/managing-tenants.html 
sidebar: sidebar 
keywords: manage tenants, tenant account, what is a tenant 
summary: グリッド管理者は、 S3 および Swift クライアントがオブジェクトの格納と読み出し、ストレージ使用状況の監視、および StorageGRID システムを使用してクライアントが実行できる操作の管理に使用するテナントアカウントを作成して管理します。 
---
= テナントを管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッド管理者は、 S3 および Swift クライアントがオブジェクトの格納と読み出し、ストレージ使用状況の監視、および StorageGRID システムを使用してクライアントが実行できる操作の管理に使用するテナントアカウントを作成して管理します。



== テナントアカウントとは

テナントアカウントは、 Simple Storage Service （ S3 ） REST API または Swift REST API を使用するクライアントアプリケーションが、 StorageGRID でオブジェクトの格納や読み出しを行うことを可能にします。

各テナントアカウントで使用できるプロトコルは 1 つで、アカウントの作成時に指定します。両方のプロトコルを使用して StorageGRID システムにオブジェクトの格納や読み出しを行うには、テナントアカウントを 2 つ作成する必要があります。 1 つは S3 バケットとオブジェクト用、もう 1 つは Swift コンテナとオブジェクト用です。各テナントアカウントには、専用のアカウント ID 、許可されたグループとユーザ、バケットまたはコンテナ、およびオブジェクトがあります。

必要に応じて、システムに格納されているオブジェクトをエンティティごとに分ける場合は、追加のテナントアカウントを作成します。たとえば、次のようなユースケースでは複数のテナントアカウントをセットアップできます。

* * エンタープライズのユースケース：エンタープライズアプリケーションで StorageGRID システムを管理する場合は、組織内の部門ごとにグリッドのオブジェクトストレージを分離する必要があります。この場合は、マーケティング部門、カスタマーサポート部門、人事部門などのテナントアカウントを作成できます。
+

NOTE: S3 クライアントプロトコルを使用する場合は、 S3 バケットとバケットポリシーを使用してエンタープライズ内の部門間でオブジェクトを分離できます。テナントアカウントを使用する必要はありません。詳細については、 S3 クライアントアプリケーションを実装する手順を参照してください。

* * サービスプロバイダのユースケース：サービスプロバイダとして StorageGRID システムを管理する場合は、グリッド上のストレージをリースするエンティティごとにグリッドのオブジェクトストレージを分離できます。この場合は、 A 社、 B 社、 C 社などのテナントアカウントを作成します。




== テナントアカウントを作成および設定します

テナントアカウントを作成する際には次の情報を指定します。

* テナントアカウントの表示名。
* テナントアカウントで使用されるクライアントプロトコル（ S3 または Swift ）。
* S3 テナントアカウントの場合：テナントアカウントに S3 バケットでプラットフォームサービスを使用する権限があるかどうか。テナントアカウントにプラットフォームサービスの使用を許可する場合は、プラットフォームサービスを使用できるようグリッドを設定する必要があります。「プラットフォームサービスの管理」を参照してください。
* 必要に応じて、テナントアカウントのストレージクォータ -- テナントのオブジェクトで使用可能な最大ギガバイト数、テラバイト数、ペタバイト数。クォータを超過すると、テナントは新しいオブジェクトを作成できなくなります。
+

NOTE: テナントのストレージクォータは、物理容量（ディスクのサイズ）ではなく、論理容量（オブジェクトのサイズ）を表します。

* StorageGRID システムでアイデンティティフェデレーションが有効になっている場合は、テナントアカウントを設定するための Root アクセス権限が割り当てられているフェデレーテッドグループ。
* StorageGRID システムでシングルサインオン（ SSO ）が使用されていない場合は、テナントアカウントが独自のアイデンティティソースを使用するか、グリッドのアイデンティティソースを共有するか、およびテナントのローカル root ユーザの初期パスワード。


テナントアカウントが作成されたら、次のタスクを実行できます。

* * グリッドのプラットフォームサービスの管理 * ：テナントアカウントでプラットフォームサービスを有効にする場合は、プラットフォームサービスメッセージの配信方法と、 StorageGRID 環境でプラットフォームサービスを使用する際のネットワーク要件を理解しておく必要があります。
* * テナントアカウントのストレージ使用状況を監視 * ：テナントがアカウントの使用を開始したら、 Grid Manager を使用して各テナントが消費するストレージ容量を監視できます。
+

NOTE: ノードがグリッド内の他のノードから切断されていると、テナントのストレージ使用状況の値が最新ではなくなる場合があります。合計はネットワーク接続が回復すると更新されます。

+
テナントにクォータを設定している場合は、「テナントクォータ使用率が高い * 」アラートを有効にして、テナントがクォータを消費しているかどうかを確認できます。有効にすると、テナントのクォータの 90% が使用されたときにこのアラートがトリガーされます。詳細については、 StorageGRID の監視とトラブルシューティングの手順にあるアラートリファレンスを参照してください。

* * クライアント処理の設定 * ：一部のタイプのクライアント処理が禁止されているかどうかを設定できます。




== S3 テナントを設定する

S3 テナントアカウントが作成されたら、テナントユーザは Tenant Manager にアクセスして次のようなタスクを実行できます。

* アイデンティティフェデレーションの設定（グリッドとアイデンティティソースを共有する場合を除く）、およびローカルグループとユーザの作成
* S3 アクセスキーの管理
* S3 バケットの作成と管理を行う
* ストレージ使用状況を監視しています
* プラットフォームサービスの使用（有効な場合）



IMPORTANT: S3 テナントユーザは、 Tenant Manager を使用して S3 アクセスキーとバケットを作成および管理できますが、オブジェクトを取り込みおよび管理するには S3 クライアントアプリケーションを使用する必要があります。



== Swift テナントを設定します

Swift テナントアカウントが作成されたら、テナントの root ユーザは Tenant Manager にアクセスして次のようなタスクを実行できます。

* アイデンティティフェデレーションの設定（グリッドとアイデンティティソースを共有する場合を除く）、およびローカルグループとユーザの作成
* ストレージ使用状況を監視しています



IMPORTANT: Swift ユーザが Tenant Manager にアクセスするには、 Root Access 権限が必要です。ただし Root Access 権限では、 Swift REST API に認証してコンテナを作成したりオブジェクトを取り込んだりすることはできません。Swift REST API に認証するには、 Swift 管理者の権限が必要です。

xref:../tenant/index.adoc[テナントアカウントを使用する]
