---
permalink: admin/migrating-objects-from-cloud-tiering-s3-to-cloud-storage-pool.html 
sidebar: sidebar 
keywords: cloud tiering 
summary: 現在 Cloud Tiering - Simple Storage Service （ S3 \ ）機能を使用してオブジェクトデータを S3 バケットに階層化している場合は、代わりにクラウドストレージプールへのオブジェクトの移行を検討してください。クラウドストレージプールは拡張性に優れたアプローチを提供し、 StorageGRID システム内のすべてのストレージノードを活用します。 
---
= 「 Cloud Tiering - S3 」からクラウドストレージプールにオブジェクトを移行します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
現在 Cloud Tiering - Simple Storage Service （ S3 ） * 機能を使用してオブジェクトデータを S3 バケットに階層化している場合は、代わりにクラウドストレージプールへのオブジェクトの移行を検討してください。クラウドストレージプールは拡張性に優れたアプローチを提供し、 StorageGRID システム内のすべてのストレージノードを活用します。

.必要なもの
* を使用して Grid Manager にサインインします xref:../admin/web-browser-requirements.adoc[サポートされている Web ブラウザ]。
* 特定のアクセス権限が必要です。
* クラウド階層化用に設定された S3 バケットにオブジェクトが格納済みである。



NOTE: オブジェクトデータを移行する前に、ネットアップのアカウント担当者に問い合わせて関連するコストについて把握してください。

ILM から見た場合、クラウドストレージプールはストレージプールに似ています。ただし、ストレージプールは StorageGRID システム内のストレージノードまたはアーカイブノードで構成されますが、クラウドストレージプールは外部の S3 バケットで構成されます。

オブジェクトを「 Cloud Tiering - S3 」からクラウドストレージプールに移行する前に、 S3 バケットを作成し、 StorageGRID にクラウドストレージプールを作成する必要があります。次に、新しい ILM ポリシーを作成し、クラウド階層化バケットにオブジェクトを格納するために使用していた ILM ルールをコピーし、同じオブジェクトをクラウドストレージプールに格納するように変更します。


NOTE: オブジェクトがクラウドストレージプールに格納されている場合、それらのオブジェクトのコピーを StorageGRID にも格納することはできません。現在クラウド階層化に使用している ILM ルールが複数の場所に同時にオブジェクトを格納するように設定されている場合は、その機能が失われるため、このオプションの移行を引き続き実行するかどうかを検討してください。移行を続行する場合は、既存のルールをコピーするのではなく、新しいルールを作成する必要があります。

.手順
. クラウドストレージプールを作成
+
クラウドストレージプールに新しい S3 バケットを使用して、クラウドストレージプールで管理されるデータのみが含まれるようにします。

. クラウド階層化バケットに格納する原因 オブジェクトをアクティブな ILM ポリシーで特定します。
. 該当するルールをコピーします。
. コピーしたルールで、配置場所を新しいクラウドストレージプールに変更します。
. コピーしたルールを保存します。
. 新しいルールを使用する新しいポリシーを作成します。
. 新しいポリシーをシミュレートしてアクティブ化します。
+
新しいポリシーがアクティブ化されて ILM 評価が実行されると、クラウド階層化用に設定された S3 バケットからクラウドストレージプール用に設定された S3 バケットにオブジェクトが移動します。グリッド上の使用可能なスペースに影響はありません。クラウドストレージプールに移動されたオブジェクトは、クラウド階層化バケットから削除されます。



xref:../ilm/index.adoc[ILM を使用してオブジェクトを管理する]
