---
permalink: admin/removing-nfs-audit-client-from-audit-share.html 
sidebar: sidebar 
keywords: nfs audit client, remove audit client 
summary: NFS 監査クライアントは、 IP アドレスに基づいて監査共有へのアクセスが許可されます。既存の監査クライアントを削除するには、その IP アドレスを削除します。 
---
= 監査共有から NFS 監査クライアントを削除します
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS 監査クライアントは、 IP アドレスに基づいて監査共有へのアクセスが許可されます。既存の監査クライアントを削除するには、その IP アドレスを削除します。

.必要なもの
* root/admin アカウントのパスワードを持つ「 passwords.txt 」ファイルがあります（ SAID パッケージ内にあります）。
* 「 Configuration.txt 」ファイルがあります（ SAID パッケージ内にあります）。


監査共有にアクセス可能な最後の IP アドレスを削除することはできません。

.手順
. プライマリ管理ノードにログインします。
+
.. 次のコマンドを入力します。 ssh admin@_primary_Admin_Node_IP_`
.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
.. root に切り替えるには、次のコマンドを入力します
.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
+
root としてログインすると、プロンプトは「 $` 」から「 #」 に変わります。



. NFS 構成ユーティリティを起動します :'config_nfs.rb
+
[listing]
----

-----------------------------------------------------------------
| Shares               | Clients              | Config          |
-----------------------------------------------------------------
| add-audit-share      | add-ip-to-share      | validate-config |
| enable-disable-share | remove-ip-from-share | refresh-config  |
|                      |                      | help            |
|                      |                      | exit            |
-----------------------------------------------------------------
----
. 監査共有から IP アドレス「 remove-ip-from-share 」を削除します
+
サーバで設定されている監査共有に番号が振られ、リストに表示されます。監査共有は '/var/local/audit/export' として表示されます

. 監査共有に対応する番号として '_audit_share_number_' を入力します
+
監査共有へのアクセスを許可している IP アドレスに番号が振られ、リストに表示されます。

. 削除する IP アドレスに対応する番号を入力します。
+
監査共有が更新され、この IP アドレスの監査クライアントからのアクセスは許可されなくなります。

. プロンプトが表示されたら、 * Enter * を押します。
+
NFS 設定ユーティリティが表示されます。

. NFS 設定ユーティリティを閉じます
. StorageGRID 環境が複数データセンターサイトの環境であり、他のサイトにも管理ノードが含まれている場合は、必要に応じてこれらの監査共有を無効にします。
+
.. 各サイトの管理ノードにリモートからログインします。
+
... 次のコマンドを入力します。 ssh admin@_grid_node_name
... 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
... root に切り替えるには、次のコマンドを入力します
... 「 passwords.txt 」ファイルに記載されたパスワードを入力します。


.. 同じ手順を繰り返して、追加の管理ノードごとに監査共有を設定します。
.. リモート管理ノードへのリモートの Secure Shell ログインを終了します。「 exit


. コマンドシェルからログアウトします :exit

