---
permalink: admin/summary-ip-addresses-and-ports-for-client-connections.html 
sidebar: sidebar 
keywords: ip addresses for client, how to connect to storagegrid, ports, vip 
summary: クライアントアプリケーションは、グリッドノードの IP アドレスおよびそのノード上のサービスのポート番号を使用して StorageGRID に接続できます。ハイアベイラビリティ（ HA\ ）グループが設定されている場合、クライアントアプリケーションは HA グループの仮想 IP アドレスを使用して接続できます。 
---
= Summary ：クライアント接続の IP アドレスとポート
:icons: font
:imagesdir: ../media/


[role="lead"]
クライアントアプリケーションは、グリッドノードの IP アドレスおよびそのノード上のサービスのポート番号を使用して StorageGRID に接続できます。ハイアベイラビリティ（ HA ）グループが設定されている場合は、 HA グループの仮想 IP アドレスを使用してクライアントアプリケーションを接続できます。

次の表に、クライアントが StorageGRID に接続できるさまざまな方法、および接続のタイプごとに使用される IP アドレスとポートを示します。以下の手順では、ロードバランサエンドポイントとハイアベイラビリティ（ HA ）グループがすでに設定されている場合に Grid Manager でこの情報を検索する方法について説明します。

[cols="1a,1a,1a,1a"]
|===
| 接続が確立される場所 | クライアントが接続するサービス | IP アドレス | ポート 


 a| 
HA グループ
 a| 
ロードバランサ
 a| 
HA グループの仮想 IP アドレス
 a| 
* ロードバランサエンドポイントのポート




 a| 
HA グループ
 a| 
CLB の機能です

* 注： * CLB サービスは廃止されました。
 a| 
HA グループの仮想 IP アドレス
 a| 
デフォルトの S3 ポート：

* HTTPS ： 8082
* HTTP ： 8084


デフォルトの Swift ポート：

* HTTPS ： 8083
* HTTP ： 8085




 a| 
管理ノード
 a| 
ロードバランサ
 a| 
管理ノードの IP アドレス
 a| 
* ロードバランサエンドポイントのポート




 a| 
ゲートウェイノード
 a| 
ロードバランサ
 a| 
ゲートウェイノードの IP アドレス
 a| 
* ロードバランサエンドポイントのポート




 a| 
ゲートウェイノード
 a| 
CLB の機能です

* 注： * CLB サービスは廃止されました。
 a| 
ゲートウェイノードの IP アドレス

* 注：デフォルトでは、 CLB および LDR の HTTP ポートは有効になっていません。
 a| 
デフォルトの S3 ポート：

* HTTPS ： 8082
* HTTP ： 8084


デフォルトの Swift ポート：

* HTTPS ： 8083
* HTTP ： 8085




 a| 
ストレージノード
 a| 
LDR
 a| 
ストレージノードの IP アドレス
 a| 
デフォルトの S3 ポート：

* HTTPS ： 18082
* HTTP ： 18084


デフォルトの Swift ポート：

* HTTPS ： 18083
* HTTP ： 18085


|===
ゲートウェイノードの HA グループのロードバランサエンドポイントに S3 クライアントを接続するには、次のように構造化された URL を使用します。

* https://_VIP-of-HA-group:LB-endpoint-port_`


たとえば、 HA グループの仮想 IP アドレスが 192.0.2.5 で S3 ロードバランサエンドポイントのポート番号が 10443 の場合、 S3 クライアントは次の URL を使用して StorageGRID に接続できます。

* https://192.0.2.5:10443` にアクセスします


Swift クライアントをゲートウェイノードの HA グループのロードバランサエンドポイントに接続するには、次のように構造化された URL を使用します。

* https://_VIP-of-HA-group:LB-endpoint-port_`


たとえば、 HA グループの仮想 IP アドレスが 192.0.2.6 で、 Swift ロードバランサエンドポイントのポート番号が 10444 の場合、 Swift クライアントは次の URL を使用して StorageGRID に接続できます。

* https://192.0.2.6:10444` にアクセスします


クライアントが StorageGRID への接続に使用する IP アドレスに DNS 名を設定できます。ローカルネットワーク管理者にお問い合わせください。

.手順
. を使用して Grid Manager にサインインします xref:../admin/web-browser-requirements.adoc[サポートされている Web ブラウザ]。
. グリッドノードの IP アドレスを確認するには、次の手順を実行します。
+
.. [* nodes （ノード） ] を選択します
.. 接続する管理ノード、ゲートウェイノード、またはストレージノードを選択します。
.. [* Overview * （概要 * ） ] タブを選択します。
.. Node Information セクションで、ノードの IP アドレスを確認します。
.. IPv6 アドレスとインターフェイスマッピングを表示するには、 * Show More * を選択します。
+
クライアントアプリケーションから、リスト内の任意の IP アドレスへの接続を確立できます。

+
*** * eth0 ： * グリッドネットワーク
*** * eth1 ： * 管理ネットワーク（オプション）
*** * eth2 ： * クライアントネットワーク（オプション）
+

NOTE: 表示されている管理ノードまたはゲートウェイノードがハイアベイラビリティグループのアクティブノードである場合は、 HA グループの仮想 IP アドレスが eth2 に表示されます。





. ハイアベイラビリティグループの仮想 IP アドレスを検索するには、次の手順を実行します。
+
.. 構成 * > * ネットワーク * > * ハイアベイラビリティグループ * を選択します。
.. HA グループの仮想 IP アドレスを表で確認します。


. ロードバランサエンドポイントのポート番号を確認するには、次の手順を実行します。
+
.. [ * configuration * > * Network * > * Load Balancer Endpoints * ] を選択します。
+
Load Balancer Endpoints ページが表示され、設定済みのエンドポイントのリストが表示されます。

.. エンドポイントを選択し、 * エンドポイントの編集 * を選択します。
+
[Edit Endpoint] ウィンドウが開き、エンドポイントに関する追加の詳細が表示されます。

.. 選択したエンドポイントが正しいプロトコル（ S3 または Swift ）で使用するように設定されていることを確認し、 * Cancel * を選択します。
.. クライアント接続に使用するエンドポイントのポート番号をメモします。
+

NOTE: ポート番号が 80 または 443 の場合は、管理ノードで予約されているため、エンドポイントはゲートウェイノードにのみ設定されます。それ以外のポートはすべて、ゲートウェイノードと管理ノードの両方に設定されます。




