---
permalink: admin/supported-ciphers-for-outgoing-tls-connections.html 
sidebar: sidebar 
keywords: tls cipher suites, transport layer security connections 
summary: StorageGRID システムでは、アイデンティティフェデレーションとクラウドストレージプールに使用される外部システムへの Transport Layer Security （ TLS ）接続でサポートされる暗号スイートに制限があります。 
---
= 発信 TLS 接続でサポートされる暗号
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID システムでは、アイデンティティフェデレーションとクラウドストレージプールに使用される外部システムへの Transport Layer Security （ TLS ）接続でサポートされる暗号スイートに制限があります。



== サポートされる TLS のバージョン

StorageGRID では、アイデンティティフェデレーションとクラウドストレージプールに使用される外部システムへの接続で TLS 1.2 と TLS 1.3 がサポートされます。

外部システムとの互換性を確保するために、外部システムとの使用がサポートされている TLS 暗号が選択されています。S3 または Swift クライアントアプリケーションで使用できる暗号のリストは、このリストよりも大容量です。


NOTE: プロトコルのバージョン、暗号、鍵交換アルゴリズム、 MAC アルゴリズムなどの TLS 設定オプションは、 StorageGRID では設定できません。これらの設定について具体的なご要望がある場合は、ネットアップのアカウント担当者にお問い合わせください。



== サポートされている TLS 1.2 暗号スイート

次の TLS 1.2 暗号スイートがサポートされています。

* TLS_ECDHE_RSA_With _AES_128_GCM_SHA256
* TLS_ECDHE_RSA_with _AES_256_GCM_SHA384
* TLS_ECDHE_ECDSA_With _AES_128_GG_SHA256
* TLS_ECDHE_ECDSA_With _AES_256_GCM_SHA384
* TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
* TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
* TLS_RSA_With _AES_128_GCM _SHA256
* TLS_RSA_With _AES_256_GCM_SHA384




== サポートされている TLS 1.3 暗号スイート

次の TLS 1.3 暗号スイートがサポートされています。

* TLS_AES_256_GCM_SHA384
* TLS_CHACHA20_POLY1305_SHA256
* TLS_AES_128_GCM _SHA256

