---
permalink: admin/what-admin-node-is.html 
sidebar: sidebar 
keywords: admin nodes 
summary: 管理ノードは、システムの設定、監視、ロギングなどの管理サービスを提供します。各グリッドにはプライマリ管理ノードが 1 つ必要で、冗長性を確保するために任意の数の非プライマリ管理ノードを設定できます。 
---
= 管理ノードとは
:icons: font
:imagesdir: ../media/


[role="lead"]
管理ノードは、システムの設定、監視、ロギングなどの管理サービスを提供します。各グリッドにはプライマリ管理ノードが 1 つ必要で、冗長性を確保するために任意の数の非プライマリ管理ノードを設定できます。

Grid Manager または Tenant Manager にサインインすると、管理ノードに接続されます。どの管理ノードにも接続が可能で、各管理ノードに表示される StorageGRID システムのビューもほぼ同じです。ただし、メンテナンス手順はプライマリ管理ノードを使用して実行する必要があります。

管理ノードを使用して、 S3 および Swift クライアントトラフィックの負荷を分散することもできます。

管理ノードは次のサービスをホストします。

* AMS サービス
* CMN サービス
* NMS サービス
* Prometheus サービス
* ロードバランササービスとハイアベイラビリティサービス（ S3 および Swift クライアントトラフィックをサポート）


管理ノードは、グリッド管理 API とテナント管理 API からの要求を処理する管理アプリケーションプログラムインターフェイス（ mgmt-api ）もサポートします。を参照してください xref:using-grid-management-api.adoc[グリッド管理 API を使用します]。



== AMS サービスとは

Audit Management System （ AMS ）サービスは、システムアクティビティとイベントを追跡します。



== CMN サービスとは

Configuration Management Node （ CMN ）サービスは、すべてのサービスで必要とされる接続およびプロトコルの機能について、システム全体での設定を管理します。CMN サービスはグリッドタスクの実行および監視にも使用されます。StorageGRID 環境ごとに CMN サービスは 1 つだけです。CMN サービスをホストする管理ノードをプライマリ管理ノードと呼びます。



== NMS サービスとは

Network Management System （ NMS ）サービスは、 StorageGRID システムのブラウザベースのインターフェイスであるグリッドマネージャに表示される、監視、レポート、および設定のオプションを提供します。



== Prometheus サービスとは

Prometheus サービスは、すべてのノードのサービスから時系列の指標を収集します。
