---
permalink: s3/benefits-of-active-http-connections.html 
sidebar: sidebar 
keywords: active http connection benefits 
summary: ストレージノードへの直接接続、またはゲートウェイノード上の CLB サービスへの直接接続を行う場合は、 HTTP 接続でトランザクションを継続的に実行する場合でも、アクティブ HTTP 接続の継続時間を 10 分までに制限することを推奨します。 
---
= アクティブ HTTP 接続のメリット
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージノードへの直接接続、またはゲートウェイノード上の CLB サービス（廃止）への直接接続を行う場合は、 HTTP 接続でトランザクションを継続的に実行する場合でも、アクティブ HTTP 接続の継続時間を 10 分までに制限することを推奨します。

接続を開いておく最大継続時間は、接続を維持することで得られるメリットと内部システムリソースへの理想的な接続の割り当てとのバランスによって決まります。

ストレージノードまたは CLB サービスへのクライアント接続でアクティブ HTTP 接続を制限する利点は次のとおりです。

* StorageGRID システム全体で負荷を最適に分散できます。
+
CLB サービスを使用する場合に StorageGRID システム全体で負荷を最適に分散するには、 TCP / IP 接続を長時間維持しないようにすることが重要です。それぞれの HTTP 接続の継続時間をクライアントアプリケーションで追跡し、設定した時間が経過したら HTTP 接続を閉じるように設定します。これにより、 HTTP 接続を再確立して負荷を再分散できます。

+
CLB サービスは、クライアントアプリケーションが HTTP 接続を確立したときに、 StorageGRID システム全体で負荷を分散します。時間の経過とともに負荷分散の要件が変わったため、 HTTP 接続が最適な状態でなくなることがあります。クライアントアプリケーションでトランザクションごとに別の HTTP 接続を確立すれば、システムによる負荷分散は最適になりますが、この場合、接続を維持することで得られるより大きなメリットを失うことになります。

+

NOTE: CLB サービスは廃止されました。

* クライアントアプリケーションからの HTTP トランザクションを使用可能な空きスペースがある LDR サービスに転送できる
* メンテナンス手順を開始できます。
+
メンテナンス手順の中には、実行中のすべての HTTP 接続が完了してからでないと開始されないものがあります。



ロードバランササービスへのクライアント接続では、接続時間を制限することで一部のメンテナンス手順をすぐに開始できます。クライアント接続の継続時間が制限されていない場合は、アクティブな接続が自動的に終了するまでに数分かかることがあります。
