---
permalink: s3/get-object.html 
sidebar: sidebar 
keywords: get object 
summary: S3 GET Object 要求を使用して、 S3 バケットからオブジェクトを読み出すことができます。 
---
= オブジェクトの取得
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 GET Object 要求を使用して、 S3 バケットからオブジェクトを読み出すことができます。



== オブジェクトとマルチパートオブジェクトを取得する

「 PartNumber 」要求パラメータを使用すると、マルチパートオブジェクトまたはセグメント化されたオブジェクトの特定の部分を取得できます。「 x-amz-mp-parts-count 」応答要素は、オブジェクトのパーツ数を示します。

セグメント化された / マルチパートオブジェクトとセグメント化されていない / 非マルチパートオブジェクトの両方に対して「 PartNumber 」を 1 に設定できますが、「 x-amz-mp-parts-count 」応答要素はセグメント化されたオブジェクトまたはマルチパートオブジェクトに対してのみ返されます。



== ユーザ指定の暗号化キーによるサーバ側の暗号化（ SSE-C ）の要求ヘッダー

指定した一意のキーでオブジェクトが暗号化されている場合は、 3 つのヘッダーをすべて使用します。

* 「 x-amz-server-side-encryption-customer-algorithm 」：「 AES256 」を指定します。
* x-amz-server-side-encryption-customer-key ：オブジェクトの暗号化キーを指定します。
* x-amz-server-side-encryption-customer-key-MD5 ：オブジェクトの暗号化キーの MD5 ダイジェストを指定します。



IMPORTANT: 指定した暗号化キーが格納されることはありません。暗号化キーを紛失すると、対応するオブジェクトが失われます。お客様提供の鍵を使用してオブジェクト・データを保護する前に ' サーバ側の暗号化を使用の考慮事項を確認してください



== ユーザメタデータ内の UTF-8 文字

StorageGRID は、ユーザ定義メタデータ内のエスケープされた UTF-8 文字を解析も解釈もしません。ユーザ定義メタデータにエスケープされた UTF-8 文字が含まれているオブジェクトに対して GET 要求を実行した場合、キーの名前または値に印刷不能文字が含まれていると、「 x-amz-missing -meta 」ヘッダーが返されません。



== サポートされない要求ヘッダーです

次の要求ヘッダーはサポートされていません。指定した場合は "XNotImplemented " が返されます。

* 「 x-amz-website redirect-location 」




== バージョン管理

versionId サブリソースが指定されていない場合、バージョン管理されたバケット内のオブジェクトの最新バージョンが取得されます。オブジェクトの現在のバージョンが削除マーカーの場合は、「 Not Found 」ステータスが返され、「 x-amz-delete-marker` 応答ヘッダーは「 true 」に設定されます。



== クラウドストレージプールオブジェクトに対する GET Object の動作

オブジェクトがクラウドストレージプールに格納されている場合（情報ライフサイクル管理を使用してオブジェクトを管理する手順を参照）、 GET Object 要求の動作はオブジェクトの状態によって異なります。詳細については、「 head Object 」を参照してください。


NOTE: オブジェクトがクラウドストレージプールに格納され、かつそのオブジェクトのコピーがグリッドに 1 つ以上存在する場合、 GET Object 要求はクラウドストレージプールからデータを読み出す前に、グリッドからデータを読み出そうとします。

|===
| オブジェクトの状態 | GET Object の動作 


 a| 
StorageGRID に取り込まれているがまだ ILM によって評価されていないオブジェクト、または従来のストレージプールに格納されているオブジェクト、またはイレイジャーコーディングを使用しているオブジェクト
 a| 
「 200 OK 」

オブジェクトのコピーが読み出されます。



 a| 
クラウドストレージプール内にあるが、まだ読み出し不可能な状態に移行していない
 a| 
「 200 OK 」

オブジェクトのコピーが読み出されます。



 a| 
オブジェクトを読み出し不可能な状態に移行した
 a| 
「 403 Forbidden 」、「 InvalidObjectState 」

POST Object restore 要求を使用して、オブジェクトを読み出し可能な状態にリストアします。



 a| 
読み出し不可能な状態からリストア中である
 a| 
「 403 Forbidden 」、「 InvalidObjectState 」

POST Object restore 要求が完了するまで待ちます。



 a| 
クラウドストレージプールへのリストアが完了している
 a| 
「 200 OK 」

オブジェクトのコピーが読み出されます。

|===


== クラウドストレージプール内のマルチパートオブジェクトまたはセグメント化されたオブジェクト

マルチパートオブジェクトをアップロードした場合や StorageGRID が大きなオブジェクトをセグメントに分割した場合、 StorageGRID はオブジェクトのパーツまたはセグメントのサブセットをサンプリングすることでクラウドストレージプール内のオブジェクトが使用可能かどうかを判断します。オブジェクトの一部の部分がすでに読み出し不可能な状態に移行されている場合、またはオブジェクトの一部がまだリストアされていない場合、 GET Object 要求が誤って「 200 OK 」を返すことがあります。

このような場合は、次のよう

* GET Object 要求がデータの一部を返し、転送の途中で停止することがあります。
* 後続の GET Object 要求では、「 403 Forbidden 」が返される場合があります。


xref:using-server-side-encryption.adoc[サーバ側の暗号化を使用します]

xref:../ilm/index.adoc[ILM を使用してオブジェクトを管理する]

xref:post-object-restore.adoc[POST Object restore の実行]

xref:s3-operations-tracked-in-audit-logs.adoc[監査ログで追跡される S3 処理]
