---
permalink: s3/get-bucket-consistency-request.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, GET bucket consistency request 
summary: GET Bucket consistency 要求を使用すると、特定のバケットに適用されている整合性レベルを確認できます。 
---
= GET Bucket consistency 要求を実行します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
GET Bucket consistency 要求を使用すると、特定のバケットに適用されている整合性レベルを確認できます。

新たに作成したオブジェクトに対しては、リードアフターライト整合性を保証するようにデフォルトの整合性制御が設定されます。

この処理を完了するには、 s3 ： GetBucketConsistency 権限または root アカウントが必要です。



== 要求例

[source, subs="specialcharacters,quotes"]
----
GET /bucket?x-ntap-sg-consistency HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


== 応答

応答 XML では、「 <Consistency> 」は次のいずれかの値を返します。

|===
| 整合性制御 | 説明 


 a| 
すべて
 a| 
すべてのノードが即座にデータを受け取り、受け取れない場合は要求が失敗します。



 a| 
strong-global
 a| 
すべてのサイトのすべてのクライアント要求について、リードアフターライト整合性が保証されます。



 a| 
strong-site
 a| 
1 つのサイト内のすべてのクライアント要求について、リードアフターライト整合性が保証されます。



 a| 
read-after-new-write の場合
 a| 
（デフォルト）新規オブジェクトにはリードアフターライト整合性を、オブジェクトの更新には結果整合性を提供します。高可用性が確保され、データ保護が保証されます。Amazon S3 の整合性の保証に最も近い機能です。

* 注：存在しないオブジェクトに対してアプリケーションが HEAD 要求を使用すると、使用できないストレージノードがあると「 500 Internal Server Error 」が大量に返される可能性があります。これらのエラーを回避するには、 Amazon S3 と同様の整合性の保証が必要でない限り、整合性制御を「 available 」に設定します。



 a| 
available （ HEAD 処理は結果整合性）
 a| 
「 read-after-new-write 」整合性レベルと動作は同じですが、 HEAD 処理については結果整合性のみを提供します。ストレージ・ノードが使用できない場合 ' リードアフター・新規ライトよりもヘッド操作の可用性が高くなりますAmazon S3 の整合性と異なるのは HEAD 処理のみです。

|===


== 応答例

[listing]
----
HTTP/1.1 200 OK
Date: Fri, 18 Sep 2020 01:02:18 GMT
Connection: CLOSE
Server: StorageGRID/11.5.0
x-amz-request-id: 12345
Content-Length: 127
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<Consistency xmlns="http://s3.storagegrid.com/doc/2015-02-01/">read-after-new-write</Consistency>
----
.関連情報
xref:consistency-controls.adoc[整合性制御]
