---
permalink: s3/how-storagegrid-ilm-rules-manage-objects.html 
sidebar: sidebar 
keywords: ilm manage object rules 
summary: グリッド管理者が情報ライフサイクル管理（ ILM ）ルールを作成して、 S3 REST API クライアントアプリケーションから StorageGRID システムに取り込まれたオブジェクトデータを管理します。これらのルールは、以降のオブジェクトデータを格納する方法と場所を指定するために、 ILM ポリシーに追加されます。 
---
= StorageGRID の ILM ルールによるオブジェクトの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッド管理者が情報ライフサイクル管理（ ILM ）ルールを作成して、 S3 REST API クライアントアプリケーションから StorageGRID システムに取り込まれたオブジェクトデータを管理します。これらのルールは、以降のオブジェクトデータを格納する方法と場所を指定するために、 ILM ポリシーに追加されます。

ILM の設定によって、オブジェクトの次の要素が決まります。

* * 地域 *
+
StorageGRID システム（ストレージプール）内またはクラウドストレージプール内のオブジェクトのデータの場所。

* * ストレージグレード *
+
フラッシュや回転式ディスクなど、オブジェクトデータの格納に使用されるストレージのタイプ。

* * 損失の保護 *
+
作成されるコピーの数と作成されるコピーのタイプ（レプリケーション、イレイジャーコーディング、またはその両方）。

* * 保持 *
+
オブジェクトのデータの管理方法、格納場所、損失からの保護方法の経過時間に応じて変更が加えられます。

* * 取り込み中の保護 *
+
取り込み時にオブジェクトデータを保護する方法。同期配置（取り込み動作に Balanced オプションまたは Strict オプションを使用）または中間コピー作成（ Dual commit オプションを使用）のいずれかです。



ILM ルールではオブジェクトをフィルタして選択できます。S3 を使用して取り込まれたオブジェクトは、 ILM ルールによって次のメタデータに基づいてフィルタできます。

* テナントアカウント
* バケット名
* 取り込み時間
* キーを押します
* 最終アクセス時間
+

NOTE: デフォルトでは、すべての S3 バケットで最終アクセス時間の更新が無効になっています。StorageGRID システムに Last Access Time オプションを使用する ILM ルールが含まれている場合は、そのルールで指定される S3 バケットで最終アクセス時間の更新を有効にする必要があります。最終アクセス時間の更新を有効にするには、 Tenant Manager の PUT Bucket last access time 要求、 * S3 * > * Buckets * > * Configure Last Access Time * チェックボックス、またはテナント管理 API を使用します。最終アクセス時間の更新を有効にする場合は、特に小さなオブジェクトを含むシステムで StorageGRID のパフォーマンスが低下する可能性があることに注意してください。

* 場所の制約
* オブジェクトサイズ
* ユーザメタデータ
* オブジェクトタグ


ILM の詳細については、情報ライフサイクル管理を使用してオブジェクトを管理する手順を参照してください。

xref:../tenant/index.adoc[テナントアカウントを使用する]

xref:../ilm/index.adoc[ILM を使用してオブジェクトを管理する]

xref:put-bucket-last-access-time-request.adoc[PUT Bucket last access time 要求の場合]
