---
permalink: s3/initiate-multipart-upload.html 
sidebar: sidebar 
keywords: initiate multipart upload, uploads 
summary: Initiate Multipart Upload 処理は、オブジェクトのマルチパートアップロードを開始し、アップロード ID を返します。 
---
= マルチパートアップロードを開始します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Initiate Multipart Upload 処理は、オブジェクトのマルチパートアップロードを開始し、アップロード ID を返します。

x-amz-storage-class' 要求ヘッダーがサポートされています。x-amz-storage-class で送信される値は StorageGRID が取り込み中にオブジェクトデータを保護する方法に影響し、 StorageGRID システムに格納されるオブジェクトの永続的コピーの数（ ILM で決定）には影響しません。

取り込まれたオブジェクトに一致する ILM ルールの取り込み動作が Strict オプションに指定されている場合、 x-amz-storage-class ヘッダーの値は無視されます。

x-amz-storage-class には次の値を使用できます。

* 'standard' （デフォルト）
+
** * Dual commit * ： ILM ルールの取り込み動作が Dual commit オプションに指定されている場合は、オブジェクトの取り込み直後にオブジェクトの 2 つ目のコピーが作成されて別のストレージノードに配置されます（デュアルコミット）。ILM が評価されると、この初期中間コピーがルールの配置手順を満たしているかどうかを StorageGRID が判断します。満たしていない場合は、新しいオブジェクトコピーを別の場所に作成し、初期中間コピーを削除することが必要になる可能性があります。
** * Balanced * ： ILM ルールで Balanced オプションが指定されていて、ルールで指定されたすべてのコピーを StorageGRID がただちに作成できない場合、 StorageGRID は 2 つの中間コピーを別々のストレージノードに作成します。
+
StorageGRID が ILM ルールで指定されたすべてのオブジェクトコピーをただちに作成できる（同期配置）場合、「 x-amz-storage-class 」ヘッダーは無視されます。



* 「 reduced_redundancy 」
+
** * Dual commit * ： ILM ルールの取り込み動作が Dual commit オプションに指定されている場合は、オブジェクトの取り込み時に StorageGRID が中間コピーを 1 つ作成します（シングルコミット）。
** * Balanced * ： ILM ルールで Balanced オプションが指定されている場合、 StorageGRID は、ルールで指定されたすべてのコピーをただちに作成できない場合にのみ、中間コピーを 1 つ作成します。StorageGRID で同期配置を実行できる場合、このヘッダーは効果がありません。オブジェクトに一致する ILM ルールが単一のレプリケートコピーを作成する場合は、「 reduced_redundancy 」オプションの使用を推奨します。この場合 'reduced_redundancy</1> を使用すると ' すべての取り込み操作で余分なオブジェクト・コピーを不要に作成および削除する必要がなくなります


+
他の状況では 'reduced_redundancy</1> オプションを使用することは推奨されません「 reduced_redundancy 」を使用すると、取り込み中にオブジェクトデータが失われるリスクが高まります。たとえば、 ILM 評価の前にコピーが 1 つだけ格納されていたストレージノードに障害が発生すると、データが失われる可能性があります。



* 注意 * ：一定期間にレプリケートされたコピーを 1 つだけ保持すると、データが永久に失われる危険があります。オブジェクトのレプリケートコピーが 1 つしかない場合、ストレージノードに障害が発生したり、重大なエラーが発生すると、そのオブジェクトは失われます。また、アップグレードなどのメンテナンス作業中は、オブジェクトへのアクセスが一時的に失われます。

「 reduced_redundancy 」を指定した場合は、オブジェクトを最初に取り込むときに作成されるコピー数のみに影響します。オブジェクトがアクティブな ILM ポリシーで評価される際に作成されるオブジェクトのコピー数には影響せず、 StorageGRID システムでデータが格納されるときの冗長性レベルが低下することもありません。

* 注 * ： S3 オブジェクトロックが有効な状態でオブジェクトをバケットに取り込む場合、「 REDUCED_REDUNDANCY 」オプションは無視されます。オブジェクトをレガシー準拠バケットに取り込む場合、「 reduced_redundancy 」オプションはエラーを返します。StorageGRID では、常にデュアルコミットの取り込みが実行され、コンプライアンス要件が満たされます。

次の要求ヘッダーがサポートされています。

* 「 Content-Type 」
* x-amz-meta- 。後ろに、ユーザ定義のメタデータを含む名前と値のペアを付加
+
ユーザ定義メタデータの名前と値のペアを指定する場合、一般的な形式は次のとおりです。

+
[listing]
----
x-amz-meta-_name_: `value`
----
+
ILM ルールの参照時間として * User Defined Creation Time * オプションを使用する場合は、オブジェクトの作成時に記録されるメタデータの名前として「 creation-time 」を使用する必要があります。例：

+
[listing]
----
x-amz-meta-creation-time: 1443399726
----
+
'creation-time' の値は '1970 年 1 月 1 日以降の秒数として評価されます

+

NOTE: レガシーコンプライアンスが有効になっているバケットにオブジェクトを追加する場合 ' ユーザー定義のメタデータとして 'creation-time' を追加することはできませんエラーが返されます。

* S3 オブジェクトロック要求のヘッダー：
+
** 「 x-amz-object-lock-mode 」です
** x-amz-object-lock-retain-until -date' のように指定します
** 「 x-amz-object-lock-legal hold' 」のようになります
+
これらのヘッダーがない状態で要求を送信した場合、バケットのデフォルトの保持設定を使用して、オブジェクトバージョンの retain-date が計算されます。

+
xref:using-s3-object-lock.adoc[S3 オブジェクトロックを使用する]



* SSE 要求ヘッダー：
+
** 「 x-amz-server-side-encryption 」です
** 「 x-amz-server-side-encryption-customer-key-MD5 」
** 「 x-amz-server-side-encryption-customer-key 」
** 「 x-amz-server-side-encryption-customer-algorithm 」を実行します
+
<<Request headers for server-side encryption>>



+

NOTE: StorageGRID での UTF-8 文字の処理については、 PUT Object に関するドキュメントを参照してください。





== サーバ側の暗号化を行うための要求ヘッダー

マルチパートオブジェクトをサーバ側の暗号化で暗号化するには、次の要求ヘッダーを使用します。SSE オプションと SSE-C オプションを同時に指定することはできません。

* * SSE * ： StorageGRID で管理される一意のキーでオブジェクトを暗号化する場合は、 Initiate Multipart Upload 要求で次のヘッダーを使用します。Upload Part 要求ではこのヘッダーを指定しないでください。
+
** 「 x-amz-server-side-encryption 」です


* * SSE-C * ：ユーザが指定および管理する一意のキーでオブジェクトを暗号化する場合は、 Initiate Multipart Upload 要求（および後続の各 Upload Part 要求）で、次の 3 つのヘッダーをすべて使用します。
+
** 「 x-amz-server-side-encryption-customer-algorithm 」：「 AES256 」を指定します。
** x-amz-server-side-encryption-customer-key ：新しいオブジェクトの暗号化キーを指定します。
** x-amz-server-side-encryption-customer-key-MD5 ：新しいオブジェクトの暗号化キーの MD5 ダイジェストを指定します。




* 注意： * 指定した暗号化キーは保存されません。暗号化キーを紛失すると、対応するオブジェクトが失われます。お客様提供の鍵を使用してオブジェクト・データを保護する前に ' サーバ側の暗号化を使用の考慮事項を確認してください



== サポートされない要求ヘッダーです

次の要求ヘッダーはサポートされていませんまた 'XNotImplemented が返されます

* 「 x-amz-website redirect-location 」




== バージョン管理

マルチパートアップロードは、アップロードの開始、アップロードのリストの表示、パートのアップロード、アップロードしたパートのアセンブル、およびアップロードの完了の個別の処理に分けられます。Complete Multipart Upload 処理が実行されると、オブジェクトが作成されます（該当する場合はバージョン管理されます）。

xref:../ilm/index.adoc[ILM を使用してオブジェクトを管理する]

xref:using-server-side-encryption.adoc[サーバ側の暗号化を使用します]

xref:put-object.adoc[PUT Object の場合]
