---
permalink: s3/put-bucket-metadata-notification-configuration-request.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, PUT bucket metadata notification configuration request 
summary: PUT Bucket metadata notification configuration 要求を使用すると、個々のバケットで検索統合サービスを有効化できます。要求の本文に含めるメタデータ通知設定 XML では、デスティネーション検索インデックスにメタデータを送信するオブジェクトを指定します。 
---
= PUT Bucket metadata notification configuration 要求
:icons: font
:imagesdir: ../media/


[role="lead"]
PUT Bucket metadata notification configuration 要求を使用すると、個々のバケットで検索統合サービスを有効化できます。要求の本文に含めるメタデータ通知設定 XML では、デスティネーション検索インデックスにメタデータを送信するオブジェクトを指定します。

この処理を完了するには、バケットの s3 ： PutBucketMetadataNotification 権限または root アカウントが必要です。



== リクエスト

要求の本文にメタデータ通知設定が含まれている必要があります。各メタデータ通知設定には、 1 つ以上のルールが含まれています。各ルールは、環境 がオブジェクトを指定し、 StorageGRID がオブジェクトメタデータを送信するデスティネーションを指定します。

オブジェクトはオブジェクト名のプレフィックスでフィルタリングできます。たとえば、プレフィックスが「 /images 」であるオブジェクトのメタデータをあるデスティネーションに送信し、プレフィックスが「 /videos 」であるオブジェクトのメタデータを別のデスティネーションに送信できます。

プレフィックスが重複している設定は無効で、送信時に拒否されます。たとえば、プレフィックスが「 test 」のオブジェクト用のルールとプレフィックスが「 test2 」のオブジェクト用のルールを含む設定は許可されません。

デスティネーションは、 StorageGRID エンドポイントの URN を使用して指定する必要があります。エンドポイントは、メタデータ通知設定が送信されたときに存在している必要があります。存在しない場合、リクエストは「 400 Bad Request 」として失敗します。エラーメッセージには、「メタデータ通知（検索）ポリシーを保存できません。指定されたエンドポイント URN は存在しません： _URN_

[listing]
----
<MetadataNotificationConfiguration>
    <Rule>
        <ID>Rule-1</ID>
        <Status>rule-status</Status>
        <Prefix>key-prefix</Prefix>
        <Destination>
           <Urn>arn:aws:es:region:account-ID:domain/mydomain/myindex/mytype</Urn>
        </Destination>
    </Rule>
    <Rule>
        <ID>Rule-2</ID>
         ...
    </Rule>
     ...
</MetadataNotificationConfiguration>
----
次の表に、メタデータ通知設定 XML の要素を示します。

|===
| 名前 | 説明 | 必須 


 a| 
MetadataNotificationConfiguration のページです
 a| 
メタデータ通知でオブジェクトとデスティネーションの指定に使用されるルール用のコンテナタグ。

1 つ以上の Rule 要素を含みます。
 a| 
はい。



 a| 
ルール
 a| 
指定したインデックスにメタデータを追加する必要があるオブジェクトを特定するルール用のコンテナタグ。

プレフィックスが重複しているルールは拒否されます。

MetadataNotificationConfiguration 要素に含まれています。
 a| 
はい。



 a| 
ID
 a| 
ルールの一意の識別子。

Rule 要素に含まれています。
 a| 
いいえ



 a| 
ステータス
 a| 
Status には「 Enabled 」または「 Disabled 」を指定できます。無効になっているルールについては操作が実行されません。

Rule 要素に含まれています。
 a| 
はい。



 a| 
プレフィックス
 a| 
プレフィックスと一致するオブジェクトにルールが適用され、そのメタデータが指定したデスティネーションに送信されます。

すべてのオブジェクトを照合するには、空のプレフィックスを指定します。

Rule 要素に含まれています。
 a| 
はい。



 a| 
宛先
 a| 
ルールのデスティネーションのコンテナタグ。

Rule 要素に含まれています。
 a| 
はい。



 a| 
URN
 a| 
オブジェクトメタデータが送信されるデスティネーションの URN 。次のプロパティを持つ StorageGRID エンドポイントの URN を指定する必要があります。

* 「 es 」は 3 番目の要素である必要があります。
* URN の末尾に、メタデータが格納されるインデックスとタイプを、「 domain-name/myindex/mytype 」の形式で指定する必要があります。


エンドポイントは、 Tenant Manager またはテナント管理 API を使用して設定します。形式は次のとおりです。

* arn ： aws ： es ： region ： account-ID ： domain/mydomain/myindex/mytype
* `urn:mysite:es::mydomain/myindex/mytype`


エンドポイントは設定 XML を送信する前に設定する必要があります。そうしないと、 404 エラーで設定が失敗します。

Urn は Destination 要素に含まれています。
 a| 
はい。

|===


== 例をリクエストする

次の例は、バケットの検索統合を有効にする方法を示しています。この例では、すべてのオブジェクトのオブジェクトメタデータが同じデスティネーションに送信されます。

[source, subs="specialcharacters,quotes"]
----
PUT /test1?x-ntap-sg-metadata-notification HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_

<MetadataNotificationConfiguration>
    <Rule>
        <ID>Rule-1</ID>
        <Status>Enabled</Status>
        <Prefix></Prefix>
        <Destination>
           <Urn>urn:sgws:es:::sgws-notifications/test1/all</Urn>
        </Destination>
    </Rule>
</MetadataNotificationConfiguration>
----
この例では、プレフィックス「 /images 」に一致するオブジェクトのオブジェクトメタデータは 1 つのデスティネーションに送信され、プレフィックス「 /videos 」に一致するオブジェクトのオブジェクトメタデータは 2 つ目のデスティネーションに送信されます。

[source, subs="specialcharacters,quotes"]
----
PUT /graphics?x-ntap-sg-metadata-notification HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_

<MetadataNotificationConfiguration>
    <Rule>
        <ID>Images-rule</ID>
        <Status>Enabled</Status>
        <Prefix>/images</Prefix>
        <Destination>
           <Urn>arn:aws:es:us-east-1:3333333:domain/es-domain/graphics/imagetype</Urn>
        </Destination>
    </Rule>
    <Rule>
        <ID>Videos-rule</ID>
        <Status>Enabled</Status>
        <Prefix>/videos</Prefix>
        <Destination>
           <Urn>arn:aws:es:us-west-1:22222222:domain/es-domain/graphics/videotype</Urn>
        </Destination>
    </Rule>
</MetadataNotificationConfiguration>
----


== 検索統合サービスで生成される JSON

バケットで検索統合サービスを有効にすると、オブジェクトのメタデータまたはタグの追加、更新、削除が行われるたびに、 JSON ドキュメントが生成されてデスティネーションエンドポイントに送信されます。

次の例は、「 test 」という名前のバケットに「 sgws / Tagging .txt 」というキーのオブジェクトが作成されたときに生成される JSON を示しています。test` バケットはバージョン管理されていないため 'versionId' タグは空です

[listing]
----
{
  "bucket": "test",
  "key": "SGWS/Tagging.txt",
  "versionId": "",
  "accountId": "86928401983529626822",
  "size": 38,
  "md5": "3d6c7634a85436eee06d43415012855",
  "region":"us-east-1"
  "metadata": {
    "age": "25"
  },
  "tags": {
    "color": "yellow"
  }
}
----


== メタデータ通知に含まれているオブジェクトメタデータ

次の表に、検索統合が有効になっている場合にデスティネーションエンドポイントに送信される JSON ドキュメント内のすべてのフィールドを示します。

ドキュメント名には、バケット名、オブジェクト名、バージョン ID （存在する場合）が含まれます。

|===
| を入力します | 項目名 | 説明 


 a| 
バケットとオブジェクトの情報
 a| 
バケット
 a| 
バケットの名前



 a| 
バケットとオブジェクトの情報
 a| 
キーを押します
 a| 
オブジェクトキーの名前



 a| 
バケットとオブジェクトの情報
 a| 
versionId
 a| 
バージョン管理されたバケット内のオブジェクトのオブジェクトバージョン



 a| 
バケットとオブジェクトの情報
 a| 
リージョン
 a| 
バケットリージョン。たとえば、「 us-east-1 」と入力します



 a| 
システムメタデータ
 a| 
サイズ
 a| 
HTTP クライアントから認識できるオブジェクトのサイズ（バイト）



 a| 
システムメタデータ
 a| 
MD5
 a| 
オブジェクトのハッシュ



 a| 
ユーザメタデータ
 a| 
metadata`_key: value_`
 a| 
オブジェクトのすべてのユーザメタデータをキーと値のペアとして格納



 a| 
タグ
 a| 
tags `_key: value_`
 a| 
オブジェクトに対して定義されたすべてのオブジェクトタグをキーと値のペアとして使用します

|===
* 注： StorageGRID は、タグとユーザメタデータに対して、文字列または S3 イベント通知として Elasticsearch に日付と番号を渡します。これらの文字列を日付または数値として解釈するように Elasticsearch を設定するには、動的フィールドマッピングおよびマッピング日付形式に関する Elasticsearch の手順に従ってください。検索統合サービスを設定する前に、インデックスの動的フィールドマッピングを有効にする必要があります。ドキュメントにインデックスを付けた後は、インデックス内のドキュメントのフィールドタイプを編集できません。

xref:../tenant/index.adoc[テナントアカウントを使用する]
