---
permalink: s3/s3-rest-api-supported-operations-and-limitations.html 
sidebar: sidebar 
keywords: s3 rest api supported operations, s3 rest api limitations 
summary: StorageGRID システムは Simple Storage Service API （ API バージョン 2006-03-01 ）を実装しており、ほとんどの処理をサポートしていますが、いくつかの制限事項があります。S3 REST API クライアントアプリケーションを統合するときは、実装の詳細を理解しておく必要があります。 
---
= S3 REST API のサポートされる処理と制限事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID システムは Simple Storage Service API （ API バージョン 2006-03-01 ）を実装しており、ほとんどの処理をサポートしていますが、いくつかの制限事項があります。S3 REST API クライアントアプリケーションを統合するときは、実装の詳細を理解しておく必要があります。

StorageGRID システムでは、仮想ホスト形式の要求とパス形式の要求の両方がサポートされます。



== 日付の処理

S3 REST API の StorageGRID 実装では、有効な HTTP の日付形式のみをサポートしています。

StorageGRID システムでは、日付の値を設定できるすべてのヘッダーで、有効な HTTP の日付形式のみがサポートされます。日付の時刻の部分は、 Greenwich Mean Time （ GMT ；グリニッジ標準時）の形式で指定するか、タイムゾーンのオフセットなし（ +0000 を指定）の Universal Coordinated Time （ UTC ；協定世界時）の形式で指定できます。要求に「 x-amz-date 」ヘッダーを含めた場合、 Date 要求ヘッダーで指定された値よりも優先されます。AWS 署名バージョン 4 を使用する場合は、 date ヘッダーはサポートされないため、署名済み要求に x-amz-date` のヘッダーを含める必要があります。



== 代表的な要求ヘッダー

StorageGRID システムでは、で定義されている代表的な要求ヘッダーがサポートされます http://["Amazon Web Services （ AWS ）ドキュメント：「 Amazon Simple Storage Service API Reference"^]1 つの例外を除いて。

|===
| 要求ヘッダー | 実装 


 a| 
承認
 a| 
AWS 署名バージョン 2 は完全にサポートされます

AWS 署名バージョン 4 は次の例外を除いてサポートされます。

* 要求の本文の SHA256 の値は計算されません。「 x-amz-content-SHA256 」ヘッダーで「 unsigned payload 」の値が指定されているかのように、ユーザが送信した値は検証なしで受け入れられます。




 a| 
x-amz-security-token を指定します
 a| 
実装されていませんXNotImplemented が返されます。

|===


== 共通の応答ヘッダー

StorageGRID システムでは、以下の例外を除き、 _Simple Storage Service API Reference_で 定義されている共通の応答ヘッダーがすべてサポートされます。

|===
| 応答ヘッダー | 実装 


 a| 
x-amz-id-2
 a| 
使用されません

|===