---
permalink: s3/storagegrid-s3-rest-api-operations.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations 
summary: StorageGRID システム固有の処理が S3 REST API に追加されています。 
---
= StorageGRID の S3 REST API の処理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID システム固有の処理が S3 REST API に追加されています。

* xref:../s3/get-bucket-consistency-request.adoc[GET Bucket consistency 要求を実行します]
+
GET Bucket consistency 要求を使用すると、特定のバケットに適用されている整合性レベルを確認できます。

* xref:../s3/put-bucket-consistency-request.adoc[PUT Bucket consistency 要求]
+
PUT Bucket consistency 要求を使用すると、バケットで実行される処理に適用する整合性レベルを指定できます。

* xref:../s3/get-bucket-last-access-time-request.adoc[GET Bucket last access time 要求]
+
GET Bucket last access time 要求を使用すると、最終アクセス時間の更新が個々のバケットで有効になっているか無効になっているかを確認できます。

* xref:../s3/put-bucket-last-access-time-request.adoc[PUT Bucket last access time 要求の場合]
+
PUT Bucket last access time 要求を使用すると、最終アクセス時間の更新を個々のバケットで有効または無効にできます。最終アクセス時間の更新を無効にするとパフォーマンスが向上します。バージョン 10.3.0 以降で作成されたバケットに対しては、いずれもデフォルトで無効になります。

* xref:../s3/delete-bucket-metadata-notification-configuration-request.adoc[DELETE Bucket metadata notification configuration 要求]
+
DELETE Bucket metadata notification configuration 要求では、設定 XML を削除することで、個々のバケットで検索統合サービスを無効化できます。

* xref:../s3/get-bucket-metadata-notification-configuration-request.adoc[GET Bucket metadata notification configuration 要求]
+
GET Bucket metadata notification configuration 要求では、個々のバケットで検索統合を設定するために使用する設定 XML を読み出すことができます。

* xref:../s3/put-bucket-metadata-notification-configuration-request.adoc[PUT Bucket metadata notification configuration 要求]
+
PUT Bucket metadata notification configuration 要求を使用すると、個々のバケットで検索統合サービスを有効化できます。要求の本文に含めるメタデータ通知設定 XML では、デスティネーション検索インデックスにメタデータを送信するオブジェクトを指定します。

* xref:../s3/get-storage-usage-request.adoc[GET Storage Usage 要求の略]
+
GET Storage Usage 要求を使用すると、アカウントで使用しているストレージの総容量とアカウントに関連付けられているバケットごとの使用容量を確認できます。

* xref:../s3/deprecated-bucket-requests-for-legacy-compliance.adoc[従来の準拠のための廃止されたバケット要求]
+
従来の準拠機能で作成されたバケットの管理には、 StorageGRID S3 REST API の使用が必要になる場合があります。


