---
permalink: s3/support-for-storagegrid-platform-services.html 
sidebar: sidebar 
keywords: platform service support 
summary: StorageGRID プラットフォームサービスでは、 StorageGRID のテナントアカウントでリモート S3 バケット、 Simple Notification Service （ SNS ）エンドポイント、 Elasticsearch クラスタなどの外部サービスを利用して、グリッドが提供するサービスを拡張できます。 
---
= StorageGRID プラットフォームサービスのサポート
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID プラットフォームサービスでは、 StorageGRID のテナントアカウントでリモート S3 バケット、 Simple Notification Service （ SNS ）エンドポイント、 Elasticsearch クラスタなどの外部サービスを利用して、グリッドが提供するサービスを拡張できます。

次の表に、使用可能なプラットフォームサービスとその設定に使用する S3 API を示します。

|===
| プラットフォームサービス | 目的 | サービスの設定に使用する S3 API 


 a| 
CloudMirror レプリケーション
 a| 
ソースの StorageGRID バケットから、設定したリモートの S3 バケットにオブジェクトをレプリケートします。
 a| 
PUT Bucket replication



 a| 
通知
 a| 
ソースの StorageGRID バケットでのイベントに関する通知を、設定した Simple Notification Service （ SNS ）エンドポイントに送信します。
 a| 
PUT Bucket notification



 a| 
検索統合
 a| 
StorageGRID バケットに格納されているオブジェクトメタデータを、設定した Elasticsearch インデックスに送信します。
 a| 
PUT Bucket metadata notification

* 注： * これは StorageGRID のカスタム S3 API です。

|===
グリッド管理者がテナントアカウントでプラットフォームサービスの使用を有効にするには、事前にプラットフォームサービスを使用できるようにする必要があります。その後、テナント管理者が、テナントアカウントのリモートサービスを表すエンドポイントを作成する必要があります。この手順は、サービスを設定する前に実行する必要があります。



== プラットフォームサービスの使用に関する推奨事項

プラットフォームサービスを使用する前に、次の推奨事項を確認してください。

* CloudMirror のレプリケーション、通知、検索統合を必要とする S3 要求ではアクティブなテナントが 100 個を超えないようにすることを推奨します。アクティブなテナントが 100 を超えると、 S3 クライアントのパフォーマンスが低下する可能性があります。
* StorageGRID システムの S3 バケットで、バージョン管理と CloudMirror レプリケーションの両方が有効になっている場合は、デスティネーションエンドポイントでも S3 バケットのバージョン管理を有効にすることを推奨します。これにより、 CloudMirror レプリケーションでエンドポイントに同様のオブジェクトバージョンを生成できます。
* ソースバケットで S3 オブジェクトのロックが有効になっている場合、 CloudMirror レプリケーションはサポートされません。
* デスティネーションバケットでレガシー準拠が有効になっていると、 CloudMirror レプリケーションは AccessDenied エラーで失敗します。


xref:../tenant/index.adoc[テナントアカウントを使用する]

xref:../admin/index.adoc[StorageGRID の管理]

xref:operations-on-buckets.adoc[バケットの処理]

xref:put-bucket-metadata-notification-configuration-request.adoc[PUT Bucket metadata notification configuration 要求]
