---
permalink: monitor/alerts-reference.html 
sidebar: sidebar 
keywords: alerts reference 
summary: 次の表に、デフォルトの StorageGRID アラートをすべて示します。必要に応じて、システムの管理方法に合わせてカスタムのアラートルールを作成できます。 
---
= アラート一覧
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
次の表に、デフォルトの StorageGRID アラートをすべて示します。必要に応じて、システムの管理方法に合わせてカスタムのアラートルールを作成できます。

の情報を参照してください xref:commonly-used-prometheus-metrics.adoc[よく使用される Prometheus 指標] 一部のアラートで使用される指標については、を参照してください。

[cols="1a,2a"]
|===
| アラート名 | 概要 および推奨される対処方法 


 a| 
アプライアンスのバッテリの有効期間が終了し
 a| 
アプライアンスのストレージコントローラのバッテリの有効期間が終了しました。

. バッテリを交換します。バッテリの取り外しと交換の手順は、ストレージコントローラを交換するための手順 に含まれています。ご使用のストレージアプライアンスの手順を参照してください。
+
** xref:../sg5600/index.adoc[SG5600 ストレージアプライアンス]
** xref:../sg5700/index.adoc[SG5700 ストレージアプライアンス]
** xref:../sg6000/index.adoc[SG6000 ストレージアプライアンス]


. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
アプライアンスのバッテリに問題があります
 a| 
アプライアンスのストレージコントローラのバッテリに障害が発生しました。

. バッテリを交換します。バッテリの取り外しと交換の手順は、ストレージコントローラを交換するための手順 に含まれています。ご使用のストレージアプライアンスの手順を参照してください。
+
** xref:../sg5600/index.adoc[SG5600 ストレージアプライアンス]
** xref:../sg5700/index.adoc[SG5700 ストレージアプライアンス]
** xref:../sg6000/index.adoc[SG6000 ストレージアプライアンス]


. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
アプライアンスバッテリの学習容量が不足しています
 a| 
アプライアンスのストレージコントローラのバッテリで学習容量が不足しています。

. バッテリを交換します。バッテリの取り外しと交換の手順は、ストレージコントローラを交換するための手順 に含まれています。ご使用のストレージアプライアンスの手順を参照してください。
+
** xref:../sg5600/index.adoc[SG5600 ストレージアプライアンス]
** xref:../sg5700/index.adoc[SG5700 ストレージアプライアンス]
** xref:../sg6000/index.adoc[SG6000 ストレージアプライアンス]


. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
アプライアンスバッテリの有効期限が近づいています
 a| 
アプライアンスのストレージコントローラのバッテリの有効期限が近づいています。

. すぐにバッテリを交換してください。バッテリの取り外しと交換の手順は、ストレージコントローラを交換するための手順 に含まれています。ご使用のストレージアプライアンスの手順を参照してください。
+
** xref:../sg5600/index.adoc[SG5600 ストレージアプライアンス]
** xref:../sg5700/index.adoc[SG5700 ストレージアプライアンス]
** xref:../sg6000/index.adoc[SG6000 ストレージアプライアンス]


. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
アプライアンスのバッテリが取り外されました
 a| 
アプライアンスのストレージコントローラのバッテリがありません。

. バッテリを取り付けます。バッテリの取り外しと交換の手順は、ストレージコントローラを交換するための手順 に含まれています。ご使用のストレージアプライアンスの手順を参照してください。
+
** xref:../sg5600/index.adoc[SG5600 ストレージアプライアンス]
** xref:../sg5700/index.adoc[SG5700 ストレージアプライアンス]
** xref:../sg6000/index.adoc[SG6000 ストレージアプライアンス]


. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
アプライアンスのバッテリが高温になっています
 a| 
アプライアンスのストレージコントローラのバッテリが過熱しています。

. このノードに影響している別のアラートがないかを確認します。他のアラートを解決することで、このアラートが解決する可能性があります。
. ファンや HVAC の故障など、温度上昇の考えられる原因を調査する。
. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
アプライアンスの BMC 通信エラー
 a| 
ベースボード管理コントローラ（ BMC ）との通信が失われました。

. BMC が正常に動作していることを確認します。ノード * を選択し、アプライアンスノードのハードウェア * タブを選択します。Compute Controller BMC IP フィールドを探し、その IP を参照します。
. ノードをメンテナンスモードにしてから、アプライアンスの電源をオフにしてオンにし、 BMC の通信をリストアします。使用しているアプライアンスの手順を参照してください。
+
** xref:../sg100-1000/index.adoc[SG100 および SG1000 サービスアプライアンス]
** xref:../sg6000/index.adoc[SG6000 ストレージアプライアンス]


. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
アプライアンスキャッシュバックアップデバイスに障害が発生しました
 a| 
永続的キャッシュバックアップデバイスで障害が発生しました。

. このノードに影響している別のアラートがないかを確認します。他のアラートを解決することで、このアラートが解決する可能性があります。
. テクニカルサポートにお問い合わせください。




 a| 
アプライアンスキャッシュバックアップデバイスに十分な容量がありません
 a| 
キャッシュバックアップデバイスに十分な容量がありません。

テクニカルサポートにお問い合わせください。



 a| 
アプライアンスのキャッシュ・バックアップ・デバイスの書き込み保護
 a| 
キャッシュバックアップデバイスは書き込み保護されています。

テクニカルサポートにお問い合わせください。



 a| 
アプライアンスのキャッシュメモリサイズが一致しません
 a| 
アプライアンスの 2 台のコントローラは、キャッシュサイズが異なります。

テクニカルサポートにお問い合わせください。



 a| 
アプライアンスコンピューティングコントローラシャーシの温度が高すぎます
 a| 
StorageGRID アプライアンスのコンピューティングコントローラの温度が公称のしきい値を超えました。

. ハードウェアコンポーネントの過熱状態を確認し、推奨される対処方法に従います。
+
** SG100 、 SG1000 、または SG6000 を使用している場合は、 BMC を使用します。
** SG5600 または SG5700 を使用している場合は、 SANtricity System Manager を使用します。


. 必要に応じて、コンポーネントを交換します。使用しているアプライアンスの手順を参照してください。
+
** xref:../sg100-1000/index.adoc[SG100 および SG1000 サービスアプライアンス]
** xref:../sg6000/index.adoc[SG6000 ストレージアプライアンス]
** xref:../sg5700/index.adoc[SG5700 ストレージアプライアンス]
** xref:../sg5600/index.adoc[SG5600 ストレージアプライアンス]






 a| 
アプライアンスのコンピューティングコントローラの CPU 温度が高すぎます
 a| 
StorageGRID アプライアンスのコンピューティングコントローラの CPU 温度が公称のしきい値を超えました。

. ハードウェアコンポーネントの過熱状態を確認し、推奨される対処方法に従います。
+
** SG100 、 SG1000 、または SG6000 を使用している場合は、 BMC を使用します。
** SG5600 または SG5700 を使用している場合は、 SANtricity System Manager を使用します。


. 必要に応じて、コンポーネントを交換します。使用しているアプライアンスの手順を参照してください。
+
** xref:../sg100-1000/index.adoc[SG100 および SG1000 サービスアプライアンス]
** xref:../sg5600/index.adoc[SG5600 ストレージアプライアンス]
** xref:../sg5700/index.adoc[SG5700 ストレージアプライアンス]
** xref:../sg6000/index.adoc[SG6000 ストレージアプライアンス]






 a| 
アプライアンスのコンピューティングコントローラを確認する必要があります
 a| 
StorageGRID アプライアンスのコンピューティングコントローラでハードウェア障害が検出されました。

. ハードウェアコンポーネントにエラーがないかどうかを確認し、推奨される対処方法に従います。
+
** SG100 、 SG1000 、または SG6000 を使用している場合は、 BMC を使用します。
** SG5600 または SG5700 を使用している場合は、 SANtricity System Manager を使用します。


. 必要に応じて、コンポーネントを交換します。使用しているアプライアンスの手順を参照してください。
+
** xref:../sg100-1000/index.adoc[SG100 および SG1000 サービスアプライアンス]
** xref:../sg5600/index.adoc[SG5600 ストレージアプライアンス]
** xref:../sg5700/index.adoc[SG5700 ストレージアプライアンス]
** xref:../sg6000/index.adoc[SG6000 ストレージアプライアンス]






 a| 
アプライアンスコンピューティングコントローラの電源装置 A に問題があります
 a| 
コンピューティングコントローラの電源装置 A に問題があります。このアラートは、電源装置に障害が発生したか、電源の供給に問題があることを示している可能性があります。

. ハードウェアコンポーネントにエラーがないかどうかを確認し、推奨される対処方法に従います。
+
** SG100 、 SG1000 、または SG6000 を使用している場合は、 BMC を使用します。
** SG5600 または SG5700 を使用している場合は、 SANtricity System Manager を使用します。


. 必要に応じて、コンポーネントを交換します。使用しているアプライアンスの手順を参照してください。
+
** xref:../sg100-1000/index.adoc[SG100 および SG1000 サービスアプライアンス]
** xref:../sg5600/index.adoc[SG5600 ストレージアプライアンス]
** xref:../sg5700/index.adoc[SG5700 ストレージアプライアンス]
** xref:../sg6000/index.adoc[SG6000 ストレージアプライアンス]






 a| 
アプライアンスコンピューティングコントローラの電源装置 B に問題があります
 a| 
コンピューティングコントローラの電源装置 B に問題があります。

このアラートは、電源装置に障害が発生したか、または電源の供給に問題があることを示している可能性があります。

. ハードウェアコンポーネントにエラーがないかどうかを確認し、推奨される対処方法に従います。
+
** SG100 、 SG1000 、または SG6000 を使用している場合は、 BMC を使用します。
** SG5600 または SG5700 を使用している場合は、 SANtricity System Manager を使用します。


. 必要に応じて、コンポーネントを交換します。使用しているアプライアンスの手順を参照してください。
+
** xref:../sg100-1000/index.adoc[SG100 および SG1000 サービスアプライアンス]
** xref:../sg5600/index.adoc[SG5600 ストレージアプライアンス]
** xref:../sg5700/index.adoc[SG5700 ストレージアプライアンス]
** xref:../sg6000/index.adoc[SG6000 ストレージアプライアンス]






 a| 
アプライアンスコンピューティングハードウェアモニタのサービスが停止する
 a| 
ストレージハードウェアのステータスを監視するサービスによってデータのレポートが停止されました。

. ベース OS の EOS-system-status サービスのステータスを確認する。
. サービスが停止またはエラー状態の場合は、サービスを再起動します。
. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
アプライアンスのファイバ・チャネル障害が検出されました
 a| 
アプライアンスストレージコントローラとコンピューティングコントローラの間で Fibre Channel リンクの問題が検出されました。

アプライアンスのストレージコントローラとコンピューティングコントローラの間の Fibre Channel 接続に問題がある可能性があります。

. ハードウェアコンポーネントにエラーがないかどうかを確認します（ * nodes * > * _appliance node_name > * Hardware * ）。いずれかのコンポーネントのステータスが「公称」でない場合は、次のアクションを実行します。
+
.. コントローラ間の Fibre Channel ケーブルが完全に接続されていることを確認します。
.. ファイバチャネルケーブルが過度に曲がっていないことを確認します。
.. SFP+ モジュールが正しく装着されていることを確認します。
+
* 注： * この問題が解決しない場合、 StorageGRID システムは問題のある接続を自動的にオフラインにすることがあります。



. 必要に応じて、コンポーネントを交換します。使用しているアプライアンスの手順を参照してください。
+
** xref:../sg5700/index.adoc[SG5700 ストレージアプライアンス]
** xref:../sg6000/index.adoc[SG6000 ストレージアプライアンス]






 a| 
アプライアンスのファイバ・チャネル HBA ポート障害
 a| 
Fibre Channel HBA ポートで障害が発生しているか、障害が発生しています。

テクニカルサポートにお問い合わせください。



 a| 
アプライアンスのフラッシュキャッシュドライブが最適な状態でありません
 a| 
SSD キャッシュに使用されているドライブが最適な状態でありません。

. SSD キャッシュドライブを交換します。使用しているアプライアンスの手順を参照してください。
+
** xref:../sg5600/index.adoc[SG5600 ストレージアプライアンス]
** xref:../sg5700/index.adoc[SG5700 ストレージアプライアンス]
** xref:../sg6000/index.adoc[SG6000 ストレージアプライアンス]


. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
アプライアンスインターコネクト / バッテリキャニスターが取り外されました
 a| 
インターコネクト / バッテリキャニスターがありません。

. バッテリを交換します。バッテリの取り外しと交換の手順は、ストレージコントローラを交換するための手順 に含まれています。使用しているストレージアプライアンスの手順を参照してください。
+
** xref:../sg5600/index.adoc[SG5600 ストレージアプライアンス]
** xref:../sg5700/index.adoc[SG5700 ストレージアプライアンス]
** xref:../sg6000/index.adoc[SG6000 ストレージアプライアンス]


. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
アプライアンスの LACP ポートがありません
 a| 
StorageGRID アプライアンスのポートが LACP ボンドに参加していません。

. スイッチの設定を確認します。インターフェイスが正しいリンクアグリゲーショングループに設定されていることを確認してください。
. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
アプライアンス全体の電源装置がデグレード状態になりました
 a| 
StorageGRID アプライアンスの電源が、推奨される動作電圧から逸脱しています。

. 電源装置 A と B のステータスを調べ、どちらの電源装置に異常があるかを確認し、推奨される対処方法に従います。
+
** SG100 、 SG1000 、または SG6000 を使用している場合は、 BMC を使用します。
** SG5600 または SG5700 を使用している場合は、 SANtricity System Manager を使用します。


. 必要に応じて、コンポーネントを交換します。使用しているアプライアンスの手順を参照してください。
+
** xref:../sg6000/index.adoc[SG6000 ストレージアプライアンス]
** xref:../sg5700/index.adoc[SG5700 ストレージアプライアンス]
** xref:../sg5600/index.adoc[SG5600 ストレージアプライアンス]
** xref:../sg100-1000/index.adoc[SG100 および SG1000 サービスアプライアンス]






 a| 
アプライアンスストレージコントローラ A の障害
 a| 
StorageGRID アプライアンスのストレージコントローラ A で障害が発生した。

. SANtricity System Manager を使用してハードウェアコンポーネントを確認し、推奨される対処方法に従います。
. 必要に応じて、コンポーネントを交換します。使用しているアプライアンスの手順を参照してください。
+
** xref:../sg6000/index.adoc[SG6000 ストレージアプライアンス]
** xref:../sg5700/index.adoc[SG5700 ストレージアプライアンス]
** xref:../sg5600/index.adoc[SG5600 ストレージアプライアンス]






 a| 
アプライアンスストレージコントローラ B の障害
 a| 
StorageGRID アプライアンスのストレージコントローラ B で障害が発生した。

. SANtricity System Manager を使用してハードウェアコンポーネントを確認し、推奨される対処方法に従います。
. 必要に応じて、コンポーネントを交換します。使用しているアプライアンスの手順を参照してください。
+
** xref:../sg6000/index.adoc[SG6000 ストレージアプライアンス]
** xref:../sg5700/index.adoc[SG5700 ストレージアプライアンス]
** xref:../sg5600/index.adoc[SG5600 ストレージアプライアンス]






 a| 
アプライアンスストレージコントローラのドライブ障害
 a| 
StorageGRID アプライアンスの 1 つ以上のドライブで障害が発生しているか、または最適な状態でありません。

. SANtricity System Manager を使用してハードウェアコンポーネントを確認し、推奨される対処方法に従います。
. 必要に応じて、コンポーネントを交換します。使用しているアプライアンスの手順を参照してください。
+
** xref:../sg6000/index.adoc[SG6000 ストレージアプライアンス]
** xref:../sg5700/index.adoc[SG5700 ストレージアプライアンス]
** xref:../sg5600/index.adoc[SG5600 ストレージアプライアンス]






 a| 
アプライアンスストレージコントローラハードウェア問題
 a| 
SANtricity ソフトウェアから、 StorageGRID アプライアンスのコンポーネントについて「 Needs Attention 」が報告されます。

. SANtricity System Manager を使用してハードウェアコンポーネントを確認し、推奨される対処方法に従います。
. 必要に応じて、コンポーネントを交換します。使用しているアプライアンスの手順を参照してください。
+
** xref:../sg6000/index.adoc[SG6000 ストレージアプライアンス]
** xref:../sg5700/index.adoc[SG5700 ストレージアプライアンス]
** xref:../sg5600/index.adoc[SG5600 ストレージアプライアンス]






 a| 
アプライアンスストレージコントローラの電源装置 A に障害が発生しました
 a| 
StorageGRID アプライアンスの電源装置 A が、推奨される動作電圧から逸脱しています。

. SANtricity System Manager を使用してハードウェアコンポーネントを確認し、推奨される対処方法に従います。
. 必要に応じて、コンポーネントを交換します。使用しているアプライアンスの手順を参照してください。
+
** xref:../sg6000/index.adoc[SG6000 ストレージアプライアンス]
** xref:../sg5700/index.adoc[SG5700 ストレージアプライアンス]
** xref:../sg5600/index.adoc[SG5600 ストレージアプライアンス]






 a| 
アプライアンスストレージコントローラの電源装置 B に障害が発生しました
 a| 
StorageGRID アプライアンスの電源装置 B が、推奨される動作電圧から逸脱しています。

. SANtricity System Manager を使用してハードウェアコンポーネントを確認し、推奨される対処方法に従います。
. 必要に応じて、コンポーネントを交換します。使用しているアプライアンスの手順を参照してください。
+
** xref:../sg6000/index.adoc[SG6000 ストレージアプライアンス]
** xref:../sg5700/index.adoc[SG5700 ストレージアプライアンス]
** xref:../sg5600/index.adoc[SG5600 ストレージアプライアンス]






 a| 
アプライアンスストレージハードウェアモニタのサービスが停止する
 a| 
ストレージハードウェアのステータスを監視するサービスによってデータのレポートが停止されました。

. ベース OS の EOS-system-status サービスのステータスを確認する。
. サービスが停止またはエラー状態の場合は、サービスを再起動します。
. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
アプライアンスストレージシェルフがデグレード状態になります
 a| 
ストレージアプライアンスのストレージシェルフのいずれかのコンポーネントのステータスがデグレードになっています。

. SANtricity System Manager を使用してハードウェアコンポーネントを確認し、推奨される対処方法に従います。
. 必要に応じて、コンポーネントを交換します。使用しているアプライアンスの手順を参照してください。
+
** xref:../sg6000/index.adoc[SG6000 ストレージアプライアンス]
** xref:../sg5700/index.adoc[SG5700 ストレージアプライアンス]
** xref:../sg5600/index.adoc[SG5600 ストレージアプライアンス]






 a| 
アプライアンスの温度が超過しました
 a| 
アプライアンスのストレージコントローラの公称温度または最大温度を超えました。

. このノードに影響している別のアラートがないかを確認します。他のアラートを解決することで、このアラートが解決する可能性があります。
. ファンや HVAC の故障など、温度上昇の考えられる原因を調査する。
. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
アプライアンスの温度センサーが取り外されました
 a| 
温度センサーが取り外されました。テクニカルサポートにお問い合わせください。



 a| 
Cassandra 自動コンパクターエラーです
 a| 
Cassandra 自動コンパクターでエラーが発生しました。

Cassandra の自動圧縮機能はすべてのストレージノードに存在し、オーバーライトや大量のワークロードの削除用に Cassandra データベースのサイズを管理します。この状態が解消されない間は、特定のワークロードでメタデータの消費量が予期せずに増加します。

. このノードに影響している別のアラートがないかを確認します。他のアラートを解決することで、このアラートが解決する可能性があります。
. テクニカルサポートにお問い合わせください。




 a| 
監査ログをメモリ内キューに追加しています
 a| 
ノードからローカル syslog サーバにログを送信できず、メモリ内キューがいっぱいになっています。

. rsyslog サービスがノードで実行されていることを確認します。
. 必要に応じて 'service rsyslog restart' コマンドを使用して ' ノード上の rsyslog サービスを再起動します
. rsyslog サービスを再起動できず、管理ノードに監査メッセージを保存しない場合は、テクニカルサポートにお問い合わせください。この状態を修正しないと、監査ログが失われます。




 a| 
Cassandra 自動コンパクターメトリックが古くなっています
 a| 
Cassandra の自動圧縮機能を説明する指標が最新ではありません。

Cassandra の自動圧縮機能はすべてのストレージノードに存在し、オーバーライトや大量のワークロードの削除用に Cassandra データベースのサイズを管理します。このアラートが解決しない間、特定のワークロードでメタデータの使用量が予期せずに増加します。

. このノードに影響している別のアラートがないかを確認します。他のアラートを解決することで、このアラートが解決する可能性があります。
. テクニカルサポートにお問い合わせください。




 a| 
Cassandra 通信エラー
 a| 
Cassandra サービスを実行するノード間の通信で問題が発生しています。

ノード間の通信に影響していることを示すアラートが表示されます。1 つ以上のストレージノードでネットワーク問題 または Cassandra サービスが停止している可能性があります。

. 1 つ以上のストレージノードに影響している別のアラートがないかを確認します。他のアラートを解決することで、このアラートが解決する可能性があります。
. 1 つ以上のストレージノードに影響している可能性のあるネットワーク問題 がないかどうかを確認します。
. サポート * > * ツール * > * グリッドトポロジ * を選択します。
. システム内のストレージノードごとに、 * SSM * > * Services * を選択します。Cassandra サービスのステータスが「 Running 」であることを確認します。
. Cassandra が実行されていない場合は、の手順を実行します xref:../maintain/starting-or-restarting-service.adoc[サービスの開始または再開]。
. Cassandra サービスのすべてのインスタンスが実行中でアラートが解決されない場合は、テクニカルサポートに連絡してください。




 a| 
Cassandra の圧縮処理が過負荷です
 a| 
Cassandra コンパクションプロセスが過負荷状態です。

コンパクションプロセスが過負荷になると、読み取りパフォーマンスが低下し、 RAM が使用される可能性があります。Cassandra サービスが応答しなくなったり、クラッシュしたりする可能性もあります。

. の手順に従って、 Cassandra サービスを再起動します xref:../maintain/starting-or-restarting-service.adoc[サービスを再開しています]。
. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
Cassandra 修復指標が最新ではありません
 a| 
Cassandra 修復ジョブを説明する指標が最新ではありません。この状況が 48 時間以上続く場合は、バケットのリストなどのクライアントクエリで削除されたデータが表示されることがあります。

. ノードをリブートします。Grid Manager から * nodes * に移動してノードを選択し、 Tasks タブを選択します。
. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
Cassandra の修復の進捗が遅い
 a| 
Cassandra データベースの修復の進捗状況が遅い。

データベースの修復が遅い場合は、 Cassandra のデータの整合性処理が中断されます。この状況が 48 時間以上続く場合は、バケットのリストなどのクライアントクエリで削除されたデータが表示されることがあります。

. すべてのストレージノードがオンラインで、ネットワーク関連のアラートがないことを確認します。
. このアラートを最大 2 日間監視して、問題 が自動的に解決するかどうかを確認します。
. データベースの修復に時間がかかる場合は、テクニカルサポートに連絡してください。




 a| 
Cassandra 修復サービスを使用できません
 a| 
Cassandra 修復サービスは使用できません。

Cassandra 修復サービスはすべてのストレージノードに存在し、 Cassandra データベースに重要な修復機能を提供します。この状況が 48 時間以上続く場合は、バケットのリストなどのクライアントクエリで削除されたデータが表示されることがあります。

. サポート * > * ツール * > * グリッドトポロジ * を選択します。
. システム内のストレージノードごとに、 * SSM * > * Services * を選択します。Cassandra Reaper サービスのステータスが「 Running 」であることを確認します。
. Cassandra Reaper が実行されていない場合は、の手順に従ってください xref:../maintain/starting-or-restarting-service.adoc[サービスの開始または再開]。
. Cassandra Reaper サービスのすべてのインスタンスが実行中で、アラートが解決されない場合は、テクニカルサポートにお問い合わせください。




 a| 
Cassandra テーブルが破損しています
 a| 
Cassandra がテーブルの破損を検出しました。

テーブルの破損が検出されると、 Cassandra が自動的に再起動します。

テクニカルサポートにお問い合わせください。



 a| 
クラウドストレージプールの接続エラー
 a| 
クラウドストレージプールの健全性チェックで、新たなエラーが 1 つ以上検出されました。

. ストレージプールページのクラウドストレージプールセクションに移動します。
. Last Error 列を確認して、エラーが発生しているクラウドストレージプールを特定します。
. の手順を参照してください xref:../ilm/index.adoc[情報ライフサイクル管理によるオブジェクトの管理]。




 a| 
DHCP リースの期限が切れました
 a| 
ネットワークインターフェイスの DHCP リースが期限切れです。DHCP リースの期限が切れている場合は、推奨される対処方法に従います。

. このノードと該当するインターフェイス上の DHCP サーバが接続されていることを確認してください。
. DHCP サーバの影響を受けるサブネットで割り当てることができる IP アドレスがあることを確認します。
. DHCP サーバで設定されている IP アドレスが永続的に予約されていることを確認します。または、 StorageGRID IP 変更ツールを使用して、 DHCP アドレスプールの外部に静的 IP アドレスを割り当てます。を参照してください xref:../maintain/index.adoc[リカバリとメンテナンスの手順]。




 a| 
DHCP リースがまもなく期限切れになります
 a| 
ネットワークインターフェイスの DHCP リースがまもなく期限切れになります。

DHCP リースが期限切れにならないようにするには、推奨される対処方法に従います。

. このノードと該当するインターフェイス上の DHCP サーバが接続されていることを確認してください。
. DHCP サーバの影響を受けるサブネットで割り当てることができる IP アドレスがあることを確認します。
. DHCP サーバで設定されている IP アドレスが永続的に予約されていることを確認します。または、 StorageGRID IP 変更ツールを使用して、 DHCP アドレスプールの外部に静的 IP アドレスを割り当てます。を参照してください xref:../maintain/index.adoc[リカバリとメンテナンスの手順]。




 a| 
DHCP サーバが使用できません
 a| 
DHCP サーバが使用できない。

StorageGRID ノードが DHCP サーバに接続できません。ノードの IP アドレスの DHCP リースを検証できません。

. このノードと該当するインターフェイス上の DHCP サーバが接続されていることを確認してください。
. DHCP サーバの影響を受けるサブネットで割り当てることができる IP アドレスがあることを確認します。
. DHCP サーバで設定されている IP アドレスが永続的に予約されていることを確認します。または、 StorageGRID IP 変更ツールを使用して、 DHCP アドレスプールの外部に静的 IP アドレスを割り当てます。を参照してください xref:../maintain/index.adoc[リカバリとメンテナンスの手順]。




 a| 
ディスク I/O が非常に遅い
 a| 
ディスク I/O が非常に遅いと、 StorageGRID のパフォーマンスに影響している可能性があります。

. 問題 がストレージアプライアンスノードに関連している場合は、 SANtricity システムマネージャを使用して、障害が発生しているドライブ、予測される障害が発生しているドライブ、または進行中のドライブの修復を確認します。また、アプライアンスのコンピューティングコントローラとストレージコントローラ間のファイバチャネルまたは SAS リンクのステータスを調べて、リンクが停止しているか、エラー率が高いリンクが表示されていないかを確認します。
. このノードのボリュームをホストしているストレージシステムを調べて、低速な I/O のルート原因 を特定して修正します
. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。


* 注： * 影響を受けるノードでは、グリッド全体のパフォーマンスへの影響を回避するために、サービスが無効になり、ノード自体がリブートされる場合があり原因となった状態が解消されて通常の I/O パフォーマンスが検出された場合は、フルサービスに自動的に戻ります。



 a| 
EC のリバランシングに失敗しました
 a| 
イレイジャーコーディングデータをストレージノード間でリバランシングするジョブが失敗したか、ユーザによって一時停止されました。

. 負荷を再分散するサイトのすべてのストレージノードがオンラインで使用可能であることを確認します。
. サイトでボリューム障害が発生していないことを確認し、負荷を再分散します。修復ジョブを実行できるように、 EC のリバランシングジョブがある場合は終了します。
+
「 'Balance - data terminate -- job-id <ID>' 」を指定します

. 負荷を再分散するサイトでサービス障害が発生していないことを確認します。サービスが実行されていない場合は、リカバリとメンテナンスの手順のサービスを開始または再開する手順を実行します。
. 問題を解決したら、プライマリ管理ノードで次のコマンドを実行してジョブを再起動します。
+
「 'Balance - data start -- job-id <ID>'` 」

. 問題を解決できない場合は、テクニカルサポートにお問い合わせください。




 a| 
EC の修復エラー
 a| 
イレイジャーコーディングデータの修復ジョブが失敗したか停止されました。

. 障害が発生したストレージノードまたはボリュームの代わりに使用できる十分な数のストレージノードまたはボリュームがあることを確認します。
. アクティブな ILM ポリシーを満たす十分な数の使用可能なストレージノードがあることを確認してください。
. ネットワーク接続に問題がないことを確認してください。
. 問題を解決したら、プライマリ管理ノードで次のコマンドを実行してジョブを再起動します。
+
「 'reply-data start-ec-node-repair -- repair-id <ID>' 」

. 問題を解決できない場合は、テクニカルサポートにお問い合わせください。




 a| 
EC の修復が停止した
 a| 
イレイジャーコーディングデータの修復ジョブが停止した。

. 障害が発生したストレージノードまたはボリュームの代わりに使用できる十分な数のストレージノードまたはボリュームがあることを確認します。
. ネットワーク接続に問題がないことを確認してください。
. 問題を解決したら、アラートが解決したかどうかを確認します。修復の進捗に関する詳細なレポートを表示するには、プライマリ管理ノードで次のコマンドを実行します。
+
「 'reply-data show-pec-repair-status --repair-id <ID>'` 」を指定します

. 問題を解決できない場合は、テクニカルサポートにお問い合わせください。




 a| 
E メール通知のエラーです
 a| 
アラートの E メール通知を送信できませんでした。

このアラートは、アラート E メール通知が失敗した場合、またはテスト E メール（ * alerts * > * Email setup * ページから送信）が配信できない場合にトリガーされます。

. アラートの「 * Site/Node * 」列に表示されている管理ノードから Grid Manager にサインインします。
. [* alerts*>* Email setup*] ページに移動し、設定を確認して、必要に応じて変更します。
. [ テストメールの送信 ] をクリックし、テスト受信者の電子メールの受信ボックスを確認します。テスト用 E メールを送信できない場合は、このアラートの新しいインスタンスがトリガーされることがあります。
. テスト用 E メールを送信できなかった場合は、 E メールサーバがオンラインであることを確認します。
. サーバが動作している場合は、 * support * > * Tools * > * Logs * を選択し、管理ノードのログを収集します。アラートの前後 15 分の期間を指定します。
. ダウンロードしたアーカイブを展開し 'prometheus.log （ ____GID<gid > <time_stamp>/<time_stamp>/<time_stamp>/metrics/prometheus.log ）の内容を確認します
. 問題を解決できない場合は、テクニカルサポートにお問い合わせください。




 a| 
[ 証明書 ] ページで設定されたクライアント証明書の有効期限
 a| 
[ 証明書 ] ページで設定されている 1 つ以上のクライアント証明書の有効期限が近づいています。

. Grid Manager で、 * configuration * > * Security * > * Certificates * を選択し、 * Client * タブを選択します。
. 有効期限が近い証明書を選択してください。
. [* 新しい証明書を * に接続 ] を選択します xref:../admin/configuring-administrator-client-certificates.adoc[新しい証明書をアップロードまたは生成する]。
. 有効期限が近い証明書ごとに、上記の手順を繰り返します。




 a| 
ロードバランサエンドポイント証明書の有効期限
 a| 
1 つ以上のロードバランサエンドポイント証明書の有効期限が近づいています。

. [ * configuration * > * Network * > * Load Balancer Endpoints * ] を選択します。
. まもなく期限切れになる証明書を含むエンドポイントを選択してください。
. 「 * エンドポイントの編集」を選択して、新しい証明書をアップロードまたは生成します。
. 証明書の有効期限が切れているエンドポイントまたはまもなく期限切れになるエンドポイントごとに、上記の手順を繰り返します。


ロードバランサエンドポイントの管理の詳細については、を参照してください xref:../admin/index.adoc[StorageGRID の管理手順]。



 a| 
管理インターフェイス用のサーバ証明書の有効期限
 a| 
管理インターフェイスで使用されるサーバ証明書の有効期限が近づいています。

. [ * configuration * > * Security * > * Certificates * ] を選択します。
. [* グローバル * ] タブで、 [* 管理インターフェイス証明書 * ] を選択します。
. xref:../admin/configuring-custom-server-certificate-for-grid-manager-tenant-manager.adoc#add-a-custom-management-interface-certificate[新しい管理インターフェイス証明書をアップロードします。]




 a| 
S3 および Swift API 用のグローバルサーバ証明書の有効期限
 a| 
ストレージ API エンドポイントへのアクセスに使用されるサーバ証明書の有効期限が近づいています。

. [ * configuration * > * Security * > * Certificates * ] を選択します。
. Global * タブで、 * S3 および Swift API 証明書 * を選択します。
. xref:../admin/configuring-custom-server-certificate-for-storage-node-or-clb.adoc#add-a-custom-s3-and-swift-api-certificate[新しい S3 および Swift API 証明書をアップロードします。]




 a| 
外部 syslog CA 証明書の有効期限
 a| 
外部 syslog サーバ証明書への署名に使用される認証局（ CA ）証明書の有効期限が近づいています。

. 外部 syslog サーバで CA 証明書を更新します。
. 更新された CA 証明書のコピーを取得します。
. Grid Manager から * configuration * > * Monitoring * > * Audit and syslog server * に移動します。
. * Edit external syslog server * を選択します。
. 新しい証明書をアップロードするには、 * Browse * を選択します。
. 設定ウィザードの手順に従って新しい証明書とキーを保存します。




 a| 
外部 syslog クライアント証明書の有効期限
 a| 
外部 syslog サーバのクライアント証明書の有効期限が近づいています。

. Grid Manager から * configuration * > * Monitoring * > * Audit and syslog server * に移動します。
. * Edit external syslog server * を選択します。
. 新しい証明書をアップロードするには、 * Browse * を選択します。
. 新しい秘密鍵をアップロードするには、 * Browse * を選択します。
. 設定ウィザードの手順に従って新しい証明書とキーを保存します。




 a| 
外部 syslog サーバ証明書の有効期限
 a| 
外部 syslog サーバから提供されるサーバ証明書の有効期限が近づいています。

. 外部 syslog サーバでサーバ証明書を更新します。
. 以前に Grid Manager API を使用して証明書の検証用のサーバ証明書を提供していた場合は、 API を使用して更新されたサーバ証明書をアップロードします。




 a| 
外部 syslog サーバの転送エラーです
 a| 
ノードから外部 syslog サーバにログを転送できません。

. Grid Manager から * configuration * > * Monitoring * > * Audit and syslog server * に移動します。
. * Edit external syslog server * を選択します。
. 「テストメッセージを送信」を選択できるようになるまで、設定ウィザードの手順に進みます。
. [ テストメッセージの送信 *] を選択して、ログを外部 syslog サーバに転送できない理由を確認します。
. 報告された問題を解決します。




 a| 
Grid ネットワーク MTU が一致しません
 a| 
グリッドネットワークインターフェイス（ eth0 ）の最大伝送ユニット（ MTU ）の設定は、グリッド内のノード間で大きく異なります。

MTU 設定の違いから、 eth0 ネットワークの一部がジャンボフレーム用に設定されているが、すべてではないことがわかります。MTU サイズが 1000 を超えると、原因 のネットワークパフォーマンスの問題が発生する可能性があります。

のグリッドネットワークの MTU 不一致アラートに関する手順を参照してください xref:troubleshooting-network-hardware-and-platform-issues.adoc[ネットワーク、ハードウェア、およびプラットフォームの問題をトラブルシューティングする]。



 a| 
Java ヒープの使用率が高い
 a| 
Java ヒープ領域の使用率が高くなっています。

Java のヒープがいっぱいになると、メタデータサービスが使用できなくなり、クライアント要求が失敗することがあります。

. ダッシュボードで ILM アクティビティを確認します。このアラートは、 ILM ワークロードが減少すると自動的に解決する場合があります。
. このノードに影響している別のアラートがないかを確認します。他のアラートを解決することで、このアラートが解決する可能性があります。
. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
メタデータクエリのレイテンシが高くなっています
 a| 
Cassandra メタデータクエリの平均時間が長すぎます。

ディスク交換などのハードウェアの変更、取り込みの急増などのワークロードの変化、ノードとサイト間の通信の問題などのネットワークの変更が原因で、クエリのレイテンシが増大することがあります。

. クエリのレイテンシが増大した時間帯に、ハードウェア、ワークロード、またはネットワークに変更がなかったかどうかを確認します。
. 問題を解決できない場合は、テクニカルサポートにお問い合わせください。




 a| 
アイデンティティフェデレーションの同期に失敗する
 a| 
アイデンティティソースからフェデレーテッドグループとフェデレーテッドユーザを同期できません。

. 設定した LDAP サーバがオンラインで使用可能であることを確認します。
. アイデンティティフェデレーションページの設定を確認します。すべての値が最新であることを確認します。を参照してください xref:../admin/using-identity-federation.adoc[アイデンティティフェデレーションを使用する] StorageGRID の管理手順を参照してください。
. ［ * 接続のテスト * ］ をクリックして、 LDAP サーバーの設定を確認します。
. 問題 を解決できない場合は、テクニカルサポートにお問い合わせください。




 a| 
テナントのアイデンティティフェデレーションの同期が失敗する
 a| 
テナントで設定されたアイデンティティソースからフェデレーテッドグループとフェデレーテッドユーザを同期できない。

. Tenant Manager にサインインします。
. テナントで設定されている LDAP サーバがオンラインで使用可能な状態になっていることを確認します。
. アイデンティティフェデレーションページの設定を確認します。すべての値が最新であることを確認します。を参照してください xref:../tenant/using-identity-federation.adoc[アイデンティティフェデレーションを使用する] テナントアカウントを使用するための手順を参照してください。
. ［ * 接続のテスト * ］ をクリックして、 LDAP サーバーの設定を確認します。
. 問題 を解決できない場合は、テクニカルサポートにお問い合わせください。




 a| 
ILM 配置を実現できません
 a| 
特定のオブジェクトについては、 ILM ルールでの配置手順を実行できません。

配置手順に必要なノードが使用できないか、 ILM ルールの設定が間違っている可能性があります。たとえば、レプリケートコピーをストレージノードよりも多く指定するルールがあるとします。

. すべてのノードがオンラインであることを確認してください。
. すべてのノードがオンラインの場合は、アクティブな ILM ポリシーを使用しているすべての ILM ルールの配置手順を確認します。すべてのオブジェクトに対して有効な手順があることを確認します。を参照してください xref:../ilm/index.adoc[情報ライフサイクル管理を使用してオブジェクトを管理するための手順]。
. 必要に応じて、ルールの設定を更新し、新しいポリシーをアクティブ化します。
+
* 注意： * 警告がクリアされるまでに最大 1 日かかる場合があります。

. 問題が解決しない場合は、テクニカルサポートにお問い合わせください。


* 注： * このアラートはアップグレード中に表示され、アップグレードが正常に完了してから 1 日後も続く場合があります。アップグレードによってこのアラートがトリガーされると、アラートは自動的にクリアされます。



 a| 
ILM のスキャン期間が長すぎます
 a| 
ILM のスキャン、オブジェクトの評価、および適用にかかる時間が長すぎます。

ILM によるすべてのオブジェクトのフルスキャンが完了するまでの推定時間が長すぎる場合（ダッシュボードの * Scan Period - Estimated * を参照）、アクティブな ILM ポリシーが新たに取り込まれたオブジェクトに適用されない可能性があります。ILM ポリシーへの変更が既存のオブジェクトに適用されない場合があります。

. このノードに影響している別のアラートがないかを確認します。他のアラートを解決することで、このアラートが解決する可能性があります。
. すべてのストレージノードがオンラインであることを確認します。
. クライアントトラフィックの量を一時的に減らします。たとえば、 Grid Manager で * configuration * > * Network * > * traffic classification * を選択し、帯域幅または要求数を制限するポリシーを作成します。
. ディスク I/O または CPU が過負荷状態の場合は、負荷を減らすか、リソースを増やしてください。
. 必要に応じて、同期配置を使用するように ILM ルールを更新します（ StorageGRID 11.3 以降に作成されたルールのデフォルト）。
. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。


xref:../admin/index.adoc[StorageGRID の管理]



 a| 
ILM のスキャン速度が低下しています
 a| 
ILM のスキャン速度は 100 オブジェクト / 秒未満に設定されます。

システムの ILM スキャン率が 100 オブジェクト / 秒未満に変更されました（デフォルト： 400 オブジェクト / 秒）。新しく取り込まれたオブジェクトにはアクティブな ILM ポリシーが適用されない場合があります。以降に ILM ポリシーに対して行われた変更は、既存のオブジェクトには適用されません。

. 継続的なサポート調査の一環として ILM スキャン率に一時的に変更が加えられたかどうかを確認します。
. テクニカルサポートにお問い合わせください。



IMPORTANT: テクニカルサポートに連絡しなくても ILM のスキャン速度を変更しないでください。



 a| 
KMS CA 証明書の有効期限
 a| 
キー管理サーバ（ KMS ）証明書への署名に使用する CA 証明書の有効期限が近づいています。

. KMS ソフトウェアを使用して、キー管理サーバの CA 証明書を更新します。
. Grid Manager から * configuration * > * Security * > * Key management server * を選択します。
. 証明書ステータスの警告がある KMS を選択します。
. 「 * 編集 * 」を選択します。
. 「 * 次へ * 」を選択して、手順 2 （サーバー証明書のアップロード）に進みます。
. 新しい証明書をアップロードするには、 * Browse * を選択します。
. [ 保存（ Save ） ] を選択します。


xref:../admin/index.adoc[StorageGRID の管理]



 a| 
KMS クライアント証明書の有効期限
 a| 
キー管理サーバのクライアント証明書の有効期限が近づいています。

. Grid Manager から * configuration * > * Security * > * Key management server * を選択します。
. 証明書ステータスの警告がある KMS を選択します。
. 「 * 編集 * 」を選択します。
. 「 * 次へ * 」を選択して、手順 3 （クライアント証明書のアップロード）に進みます。
. 新しい証明書をアップロードするには、 * Browse * を選択します。
. 新しい秘密鍵をアップロードするには、 * Browse * を選択します。
. [ 保存（ Save ） ] を選択します。


xref:../admin/index.adoc[StorageGRID の管理]



 a| 
KMS の設定をロードできませんでした
 a| 
キー管理サーバの設定は存在しますが、ロードできませんでした。

. このノードに影響している別のアラートがないかを確認します。他のアラートを解決することで、このアラートが解決する可能性があります。
. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
KMS 接続エラー
 a| 
アプライアンスノードがサイトのキー管理サーバに接続できませんでした。

. Grid Manager から * configuration * > * Security * > * Key management server * を選択します。
. ポートおよびホスト名のエントリが正しいことを確認します。
. サーバ証明書、クライアント証明書、およびクライアント証明書の秘密鍵が正しいかどうか、および有効期限が切れていないかどうかを確認します。
. ファイアウォールの設定により、アプライアンスノードが指定された KMS と通信できることを確認してください。
. ネットワークまたは DNS の問題を修正します。
. サポートが必要な場合やアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
KMS 暗号化キー名が見つかりません
 a| 
設定されているキー管理サーバに、指定した名前と一致する暗号化キーがありません。

. サイトに割り当てられている KMS が、暗号化キーと以前のバージョンに対応する正しい名前を使用していることを確認します。
. サポートが必要な場合やアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
KMS 暗号化キーのローテーションに失敗しました
 a| 
アプライアンスのすべてのボリュームが復号化されましたが、 1 つ以上のボリュームを最新のキーにローテーションできませんでした。テクニカルサポートにお問い合わせください。



 a| 
KMS は設定されていません
 a| 
このサイトにはキー管理サーバがありません。

. Grid Manager から * configuration * > * Security * > * Key management server * を選択します。
. このサイトに KMS を追加するか、デフォルトの KMS を追加します。


xref:../admin/index.adoc[StorageGRID の管理]



 a| 
KMS キーでアプライアンスボリュームを復号化できませんでした
 a| 
ノード暗号化が有効になっているアプライアンス上の 1 つ以上のボリュームを、現在の KMS キーで復号化できませんでした。

. このノードに影響している別のアラートがないかを確認します。他のアラートを解決することで、このアラートが解決する可能性があります。
. キー管理サーバ（ KMS ）に設定されている暗号化キーと以前のバージョンのキーがあることを確認します。
. サポートが必要な場合やアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
KMS サーバ証明書の有効期限
 a| 
キー管理サーバ（ KMS ）で使用されるサーバ証明書の有効期限が近づいています。

. KMS ソフトウェアを使用して、キー管理サーバのサーバ証明書を更新します。
. サポートが必要な場合やアラートが解決しない場合は、テクニカルサポートにお問い合わせください。


xref:../admin/index.adoc[StorageGRID の管理]



 a| 
大規模な監査キュー
 a| 
監査メッセージのディスクキューがいっぱいです。

. システムの負荷を確認します -- 大量のトランザクションが発生した場合は ' 時間が経過するとアラートは自動的に解決され ' このアラートは無視してかまいません
. アラートが解除されず重大度が上がった場合は、キューサイズのグラフを確認します。数時間から数日にわたって数値が増え続けている場合は、監査の負荷がシステムの監査キャパシティを超えている可能性があります。
. クライアントの書き込みとクライアントの読み取りの監査レベルを Error または Off （ * configuration * > * Monitoring * > * Audit and syslog server * ）に変更することで、クライアントの処理速度を下げるか、ログに記録される監査メッセージの数を減らします。


xref:../audit/index.adoc[監査ログを確認します]



 a| 
従来の CLB ロードバランサのアクティビティが検出されました
 a| 
一部のクライアントは、デフォルトの S3 および Swift API 証明書を使用して、廃止された CLB ロードバランササービスに接続する場合があります。

. 今後のアップグレードを簡易化するには、カスタムの S3 および Swift API 証明書を「証明書」ページの「グローバル * 」タブにインストールします。次に、従来の CLB に接続するすべての S3 または Swift クライアントに、新しい証明書が割り当てられていることを確認します。
. 1 つ以上のロードバランサエンドポイントを作成します。そのあと、既存の S3 および Swift クライアントをすべてこれらのエンドポイントに転送します。クライアントポートの再マッピングが必要な場合は、テクニカルサポートにお問い合わせください。


このアラートは、ポートスキャンなど、他のアクティビティによってトリガーされることがあります。廃止された CLB サービスが現在使用中かどうかを確認するには、「 storagegrid_private_clp_http_connection_established_successful 」 Prometheus 指標を表示します。

CLB サービスが使用されなくなった場合は、必要に応じてこのアラートルールをサイレント化または無効化します。



 a| 
ログをディスク上キューに追加しています
 a| 
ノードから外部 syslog サーバにログを転送できず、ディスク上のキューがいっぱいになっています。

. Grid Manager から * configuration * > * Monitoring * > * Audit and syslog server * に移動します。
. * Edit external syslog server * を選択します。
. 「テストメッセージを送信」を選択できるようになるまで、設定ウィザードの手順に進みます。
. [ テストメッセージの送信 *] を選択して、ログを外部 syslog サーバに転送できない理由を確認します。
. 報告された問題を解決します。




 a| 
監査ログのディスク容量が不足しています
 a| 
監査ログに使用できるスペースが少なくなっています。

. このアラートを監視して、問題 が自動的に解決し、ディスクスペースが再び使用可能になるかどうかを確認します。
. 使用可能なスペースが減少し続ける場合は、テクニカルサポートにお問い合わせください。




 a| 
利用可能なノードメモリが少なくなっています
 a| 
ノードの使用可能な RAM の容量が少なくなっています。

使用可能な RAM が少なくなった場合は、ワークロードに変化があったか、 1 つ以上のノードでメモリリークが発生している可能性があります。

. このアラートを監視して、問題 が自動的に解決するかどうかを確認します。
. 使用可能なメモリが Major アラートのしきい値を下回った場合は、テクニカルサポートに連絡してください。




 a| 
ストレージプールの空き容量が不足しています
 a| 
オブジェクトデータをストレージプールに格納できるスペースが少なくなっています。

. ILM * > * Storage pools * を選択します
. アラートに表示されたストレージプールを選択し、 * 詳細の表示 * を選択します。
. 追加のストレージ容量が必要かどうかを判断ストレージプール内の各サイトにストレージノードを追加するか、 1 つ以上の既存のストレージノードにストレージボリューム（ LUN ）を追加できます。
. 拡張手順 を実行してストレージ容量を増やします。


xref:../expand/index.adoc[グリッドを展開します]



 a| 
ノードメモリが不足しています
 a| 
ノードに搭載されているメモリの容量が少なくなっています。

仮想マシンまたは Linux ホストで使用できる RAM の容量を増やしてください。Major アラートのしきい値を確認して、 StorageGRID ノードのデフォルトの最小要件を決定します。使用しているプラットフォームに対応したインストール手順を参照してください。

* xref:../rhel/index.adoc[Red Hat Enterprise Linux または CentOS をインストールします]
* xref:../ubuntu/index.adoc[Ubuntu または Debian をインストールします]
* xref:../vmware/index.adoc[VMware をインストールする]




 a| 
メタデータストレージが不足しています
 a| 
オブジェクトメタデータを格納できるスペースが少なくなっています。

* 重大アラート *

. オブジェクトの取り込みを停止します。
. 拡張手順 にただちにストレージノードを追加します。


* 主要アラート *

拡張手順 にただちにストレージノードを追加します。

* Minor アラート *

. オブジェクトメタデータスペースの使用率を監視します。ノード * > * _Storage Node_* > * Storage * を選択し、 Storage Used - Object Metadata のグラフを表示します。
. でストレージノードを追加します xref:../expand/index.adoc[Expansion 手順 の略] できるだけ早く。


新しいストレージノードが追加されると、すべてのストレージノード間でオブジェクトメタデータが自動的にリバランシングされ、アラームが解除されます。

の Low metadata storage アラートの手順を参照してください xref:troubleshooting-metadata-issues.adoc[メタデータに関する問題のトラブルシューティング]。



 a| 
ディスク容量不足です
 a| 
指標データベースに使用できるスペースが少なくなっています。

. このアラートを監視して、問題 が自動的に解決し、ディスクスペースが再び使用可能になるかどうかを確認します。
. 使用可能なスペースが減少し続ける場合は、テクニカルサポートにお問い合わせください。




 a| 
オブジェクトデータのストレージが少ない
 a| 
オブジェクトデータを格納できるスペースが少なくなっています。

拡張手順 を実行します。既存のストレージノードにストレージボリューム（ LUN ）を追加するか、または新しいストレージノードを追加することができます。

xref:troubleshooting-low-object-data-storage-alert.adoc[Low object data storage アラートのトラブルシューティングを行います]

xref:../expand/index.adoc[グリッドを展開します]



 a| 
読み取り専用のローウォーターマークの上書き
 a| 
Storage Volume Soft Read-Only Watermark の上書きが、ストレージノードに対して最適化された最小ウォーターマークを下回っています。

このアラートの解決方法については、を参照してください xref:../monitor/troubleshoot-low-watermark-alert.html[読み取り専用のローウォーターマーク上書きアラートのトラブルシューティング]。



 a| 
ルートディスク容量が不足しています
 a| 
ルートディスクに使用できるスペースが少なくなっています。

. このアラートを監視して、問題 が自動的に解決し、ディスクスペースが再び使用可能になるかどうかを確認します。
. 使用可能なスペースが減少し続ける場合は、テクニカルサポートにお問い合わせください。




 a| 
システムのデータ容量が不足しています
 a| 
/var/local' ファイル・システム上の StorageGRID システム・データに使用できる領域が少なくなっています

. このアラートを監視して、問題 が自動的に解決し、ディスクスペースが再び使用可能になるかどうかを確認します。
. 使用可能なスペースが減少し続ける場合は、テクニカルサポートにお問い合わせください。




 a| 
tmp ディレクトリの空きスペースが不足しています
 a| 
/tmp ディレクトリのスペースが不足しています。

. このアラートを監視して、問題 が自動的に解決し、ディスクスペースが再び使用可能になるかどうかを確認します。
. 使用可能なスペースが減少し続ける場合は、テクニカルサポートにお問い合わせください。




 a| 
ノードのネットワーク接続エラー
 a| 
ノード間でデータを転送中にエラーが発生しました。

ネットワーク接続エラーは、手動操作なしに解消されることがあります。エラーが解消されない場合は、テクニカルサポートにお問い合わせください。

の Network Receive Error （ NRER ）アラームの手順を参照してください xref:troubleshooting-network-hardware-and-platform-issues.adoc[ネットワーク、ハードウェア、およびプラットフォームの問題をトラブルシューティングする]。



 a| 
ノードネットワーク受信フレームエラー
 a| 
ノードで受信したネットワークフレームの割合が高いとエラーが発生していました。

このアラートは ' ケーブルの不良や ' イーサネット接続のいずれかの端のトランシーバの不良など ' ハードウェア問題 が原因である可能性があることを示しています

. アプライアンスを使用している場合は、 SFP+ または SFP28 トランシーバとケーブルを 1 本ずつ交換し、アラートが解除されるかどうかを確認します。
. このアラートが解決しない場合は、テクニカルサポートにお問い合わせください。




 a| 
ノードが NTP サーバと同期されていません
 a| 
ノードの時刻がネットワークタイムプロトコル（ NTP ）サーバと同期されていません。

. Stratum 3 以上の外部 NTP サーバが 4 つ以上指定されていることを確認します。
. すべての NTP サーバが正常に動作していることを確認します。
. NTP サーバへの接続を確認します。ファイアウォールによってブロックされていないことを確認してください。




 a| 
NTP サーバでノードがロックされていません
 a| 
ノードがネットワークタイムプロトコル（ NTP ）サーバにロックされていません。

. Stratum 3 以上の外部 NTP サーバが 4 つ以上指定されていることを確認します。
. すべての NTP サーバが正常に動作していることを確認します。
. NTP サーバへの接続を確認します。ファイアウォールによってブロックされていないことを確認してください。




 a| 
非アプライアンスノードネットワークが停止しています
 a| 
1 つ以上のネットワークデバイスが停止しているか切断されています。仮想マシンまたは Linux ホストにインストールされているノードのネットワークインターフェイス（ eth ）にアクセスできないことを示すアラートが表示されます。

テクニカルサポートにお問い合わせください。



 a| 
オブジェクトの存在チェックに失敗しました
 a| 
オブジェクトの存在チェックジョブが失敗しました。

. [*maintenance] > [Object existence check] を選択します。
. エラーメッセージをメモします。適切な方法で対処します。
+
* 起動に失敗 * 、 * 接続が切断されました * 、 * 不明なエラー *

+
.. ジョブに含まれているストレージノードとボリュームがオンラインで使用可能であることを確認します。
.. ストレージノードでサービスまたはボリュームの障害が発生していないことを確認します。サービスが実行されていない場合は、サービスを開始または再開します。を参照してください xref:../maintain/index.adoc[リカバリとメンテナンスの手順]。
.. 選択した整合性制御を満たすことができることを確認してください。
.. 問題を解決したら、 [* 再試行 * ] を選択します。ジョブは最後の有効な状態から再開されます。


+
* ボリュームの重大なストレージエラー *

+
.. 障害ボリュームをリカバリします。を参照してください xref:../maintain/index.adoc[リカバリとメンテナンスの手順]。
.. [* Retry* ] を選択します。
.. ジョブが完了したら、ノード上の残りのボリュームに対して別のジョブを作成して、追加のエラーがないかどうかを確認します。


. 問題を解決できない場合は、テクニカルサポートにお問い合わせください。




 a| 
オブジェクトの存在チェックが停止しました
 a| 
オブジェクトの存在チェックジョブが停止しました。

オブジェクトの存在チェックジョブを続行できません。ジョブに含まれるストレージノードまたはボリュームが 1 つ以上オフラインであるか応答していないか、停止しているノードまたは使用できないノードが多すぎるために選択した整合性制御を満たすことができません。

. チェック対象のすべてのストレージノードとボリュームがオンラインで使用可能であることを確認します（ * nodes * を選択）。
. 現在のコーディネータノードが、選択した整合性制御を使用してオブジェクトメタデータを読み取れる十分な数のストレージノードがオンラインであることを確認してください。必要に応じて、サービスを開始または再開します。を参照してください xref:../maintain/index.adoc[リカバリとメンテナンスの手順]。
+
手順 1 および 2 を解決すると、ジョブは中断された場所から自動的に開始されます。

. 選択した整合性制御を満たすことができない場合は、ジョブをキャンセルし、下位の整合性制御を使用して別のジョブを開始します。
. 問題を解決できない場合は、テクニカルサポートにお問い合わせください。




 a| 
オブジェクトが失われた
 a| 
グリッドから 1 つ以上のオブジェクトが失われました。

データが永続的に失われて読み出しできなくなっている可能性があります。

. このアラートはすぐに調査してください。これ以上のデータ損失を防ぐための対処が必要になる場合があります。迅速に対処すれば、損失オブジェクトをリストアできる場合もあります。
+
xref:troubleshooting-lost-and-missing-object-data.adoc[失われたオブジェクトデータと欠落しているオブジェクトデータのトラブルシューティング]

. 原因となっている問題を解決したら、カウンタをリセットします。
+
.. サポート * > * ツール * > * グリッドトポロジ * を選択します。
.. アラートを生成したストレージノードに対して、 * _site _ * > * _grid node_name * > * LDR * > * Data Store * > * Configuration * > * Main * の順に選択します。
.. [ * Lost Objects Count * ] を選択し、 [ * Apply Changes * ] をクリックします。






 a| 
プラットフォームサービスを利用できません
 a| 
実行中または利用可能な状態の、 RSM サービスを搭載したストレージノードがサイトで不足しています。

該当するサイトで、 RSM サービスを搭載したストレージノードの大部分がエラーのない状態で稼働していることを確認します。

の「プラットフォームサービスのトラブルシューティング」を参照してください xref:../admin/index.adoc[StorageGRID の管理手順]。



 a| 
S3 PUT Object のサイズが大きすぎます
 a| 
S3 クライアントが S3 のサイズ制限を超える PUT Object 処理を実行しようとしています。

. アラートの詳細に表示されたテナント ID を使用して、テナントアカウントを特定します。
. Support * > * Tools * > * Logs * に移動し、アラートの詳細に表示されたストレージ・ノードのアプリケーション・ログを収集します。アラートの前後 15 分の期間を指定します。
. ダウンロードしたアーカイブを抽出し、「 bycast.log 」 (`/gid <grid_id>_<time_stamp>/<site_node>/<time_stamp>/grid/bycast.log ) の場所に移動します。
. 「 bycast.log 」の内容で「 method=Put 」を検索し、「 clientIP 」フィールドを参照して S3 クライアントの IP アドレスを特定します。
. PUT Object の最大サイズが 5GiB であることをすべてのクライアントユーザに通知します。
. 5GB を超えるオブジェクトではマルチパートアップロードを使用します。




 a| 
管理ネットワークポート 1 のサービスアプライアンスリンクが停止しています
 a| 
アプライアンスの管理ネットワークポート 1 が停止しているか切断されています。

. 管理ネットワークポート 1 に接続されているケーブルと物理的な接続を確認します。
. 接続の問題に対処します。使用しているアプライアンスハードウェアの設置とメンテナンスの手順を参照してください。
. このポートが目的で切断されている場合は、このルールを無効にします。Grid Manager で * alerts * > * Rules * を選択し、ルールを選択して * Edit rule * をクリックします。次に、 [*enabled*] チェックボックスをオフにします。
+
** xref:../sg100-1000/index.adoc[SG100 および SG1000 サービスアプライアンス]
** xref:disabling-alert-rules.adoc[アラートルールを無効化]






 a| 
管理ネットワーク（またはクライアントネットワーク）上のサービスアプライアンスのリンクがダウン
 a| 
管理ネットワーク（ eth1 ）またはクライアントネットワーク（ eth2 ）へのアプライアンスインターフェイスが停止しているか切断されている。

. StorageGRID ネットワークへのケーブル、 SFP 、および物理接続を確認します。
. 接続の問題に対処します。使用しているアプライアンスハードウェアの設置とメンテナンスの手順を参照してください。
. このポートが目的で切断されている場合は、このルールを無効にします。Grid Manager で * alerts * > * Rules * を選択し、ルールを選択して * Edit rule * をクリックします。次に、 [*enabled*] チェックボックスをオフにします。
+
** xref:../sg100-1000/index.adoc[SG100 および SG1000 サービスアプライアンス]
** xref:disabling-alert-rules.adoc[アラートルールを無効化]






 a| 
サービスアプライアンスは、ネットワークポート 1 、 2 、 3 、または 4 でリンクダウンします
 a| 
アプライアンスのネットワークポート 1 、 2 、 3 、または 4 が停止しているか、切断されています。

. StorageGRID ネットワークへのケーブル、 SFP 、および物理接続を確認します。
. 接続の問題に対処します。使用しているアプライアンスハードウェアの設置とメンテナンスの手順を参照してください。
. このポートが目的で切断されている場合は、このルールを無効にします。Grid Manager で * alerts * > * Rules * を選択し、ルールを選択して * Edit rule * をクリックします。次に、 [*enabled*] チェックボックスをオフにします。
+
** xref:../sg100-1000/index.adoc[SG100 および SG1000 サービスアプライアンス]
** xref:disabling-alert-rules.adoc[アラートルールを無効化]






 a| 
サービスアプライアンスストレージの接続がデグレードされました
 a| 
サービスアプライアンス内の 2 つの SSD のうちの 1 つで障害が発生したか、もう一方と同期していません。

アプライアンスの機能には影響しませんが、問題 にはすぐに対処する必要があります。両方のドライブに障害が発生すると、アプライアンスは動作しなくなります。

. Grid Manager から * nodes * > *** services apply__ を選択し、 ** Hardware * タブを選択します。
. Storage RAID Mode * フィールドでメッセージを確認します。
. メッセージに再同期処理の進捗が表示された場合は、処理が完了するのを待ってから、アラートが解決したことを確認します。再同期メッセージは、 SSD が最近交換されたこと、または別の理由で再同期中であることを示します。
. いずれかの SSD で障害が発生したことを示すメッセージが表示された場合は、障害が発生したドライブをできるだけ早く交換します。
+
サービスアプライアンスのドライブを交換する方法については、 SG100 および SG1000 アプライアンスのインストールおよびメンテナンスガイドを参照してください。

+
xref:../sg100-1000/index.adoc[SG100 および SG1000 サービスアプライアンス]





 a| 
管理ネットワークポート 1 のストレージアプライアンスのリンクが停止しています
 a| 
アプライアンスの管理ネットワークポート 1 が停止しているか切断されています。

. 管理ネットワークポート 1 に接続されているケーブルと物理的な接続を確認します。
. 接続の問題に対処します。使用しているアプライアンスハードウェアの設置とメンテナンスの手順を参照してください。
. このポートが目的で切断されている場合は、このルールを無効にします。Grid Manager で * alerts * > * Rules * を選択し、ルールを選択して * Edit rule * をクリックします。次に、 [*enabled*] チェックボックスをオフにします。
+
** xref:../sg6000/index.adoc[SG6000 ストレージアプライアンス]
** xref:../sg5700/index.adoc[SG5700 ストレージアプライアンス]
** xref:../sg5600/index.adoc[SG5600 ストレージアプライアンス]
** xref:disabling-alert-rules.adoc[アラートルールを無効化]






 a| 
管理ネットワーク（またはクライアントネットワーク）でのストレージアプライアンスのリンクが停止
 a| 
管理ネットワーク（ eth1 ）またはクライアントネットワーク（ eth2 ）へのアプライアンスインターフェイスが停止しているか切断されている。

. StorageGRID ネットワークへのケーブル、 SFP 、および物理接続を確認します。
. 接続の問題に対処します。使用しているアプライアンスハードウェアの設置とメンテナンスの手順を参照してください。
. このポートが目的で切断されている場合は、このルールを無効にします。Grid Manager で * alerts * > * Rules * を選択し、ルールを選択して * Edit rule * をクリックします。次に、 [*enabled*] チェックボックスをオフにします。
+
** xref:../sg6000/index.adoc[SG6000 ストレージアプライアンス]
** xref:../sg5700/index.adoc[SG5700 ストレージアプライアンス]
** xref:../sg5600/index.adoc[SG5600 ストレージアプライアンス]
** xref:disabling-alert-rules.adoc[アラートルールを無効化]






 a| 
ネットワークポート 1 、 2 、 3 、または 4 でストレージアプライアンスのリンクが停止しています
 a| 
アプライアンスのネットワークポート 1 、 2 、 3 、または 4 が停止しているか、切断されています。

. StorageGRID ネットワークへのケーブル、 SFP 、および物理接続を確認します。
. 接続の問題に対処します。使用しているアプライアンスハードウェアの設置とメンテナンスの手順を参照してください。
. このポートが目的で切断されている場合は、このルールを無効にします。Grid Manager で * alerts * > * Rules * を選択し、ルールを選択して * Edit rule * をクリックします。次に、 [*enabled*] チェックボックスをオフにします。
+
** xref:../sg6000/index.adoc[SG6000 ストレージアプライアンス]
** xref:../sg5700/index.adoc[SG5700 ストレージアプライアンス]
** xref:../sg5600/index.adoc[SG5600 ストレージアプライアンス]
** xref:disabling-alert-rules.adoc[アラートルールを無効化]






 a| 
ストレージアプライアンスストレージの接続がデグレードされました
 a| 
コンピューティングコントローラとストレージコントローラの間の接続に問題があります。

. アプライアンスに移動して、ポートのインジケータライトを確認します。
. ポートの LED が消灯している場合は、ケーブルが正しく接続されていることを確認します。必要に応じて、ケーブルを交換します。
. 最大 5 分待ちます。
+
* 注意： * 2 本目のケーブルを交換する必要がある場合は、 5 分以上プラグを取り外さないでください。そうしないと、ルートボリュームが読み取り専用になり、ハードウェアの再起動が必要になることがあります。

. Grid Manager から * nodes * を選択します。次に、問題があるノードの Hardware タブを選択します。アラート状態が解決したことを確認します。




 a| 
ストレージデバイスにアクセスできません
 a| 
ストレージデバイスにアクセスできません。

基盤となるストレージデバイスに問題があるため、ボリュームをマウントまたはアクセスできない可能性があります。

. ノードに使用されているすべてのストレージデバイスのステータスを確認します。
+
** ノードが仮想マシンまたは Linux ホストにインストールされている場合は、オペレーティングシステムに応じた手順に従って、ハードウェアの診断を実行するか、ファイルシステムのチェックを実行します。
+
*** xref:../rhel/index.adoc[Red Hat Enterprise Linux または CentOS をインストールします]
*** xref:../ubuntu/index.adoc[Ubuntu または Debian をインストールします]
*** xref:../vmware/index.adoc[VMware をインストールする]


** ノードが SG100 、 SG1000 、または SG6000 アプライアンスに設置されている場合は、 BMC を使用します。
** ノードが SG5600 アプライアンスまたは SG5700 アプライアンスにインストールされている場合は、 SANtricity System Manager を使用します。


. 必要に応じて、コンポーネントを交換します。使用しているアプライアンスの手順を参照してください。
+
** xref:../sg6000/index.adoc[SG6000 ストレージアプライアンス]
** xref:../sg5700/index.adoc[SG5700 ストレージアプライアンス]
** xref:../sg5600/index.adoc[SG5600 ストレージアプライアンス]






 a| 
テナントクォータの使用率が高い
 a| 
テナントクォータスペースの使用率が高くなっています。テナントのクォータを超えると、新しい取り込みは拒否されます。

* 注： * 多くの通知が生成される可能性があるため、このアラートルールはデフォルトで無効になっています。

. Grid Manager から * tenants * を選択します。
. テーブルを * クォータ使用率 * でソートします。
. クォータ使用率が 100% に近いテナントを選択します。
. 次のいずれか、または両方を実行します。
+
** 「 * Edit * 」を選択して、テナントのストレージ・クォータを増やします。
** クォータ使用率が高いことをテナントに通知します。






 a| 
ノードと通信できません
 a| 
1 つ以上のサービスが応答していないか、ノードに到達できません。

このアラートは、原因が不明でノードが切断されたことを示しています。たとえば、ノードのサービスが停止したり、電源障害や予期しない停止によってノードのネットワーク接続が失われたりする場合があります。

このアラートを監視して、問題 が自動的に解決するかどうかを確認します。問題 が維持される場合は、次の手順

. このノードに影響している別のアラートがないかを確認します。他のアラートを解決することで、このアラートが解決する可能性があります。
. このノードですべてのサービスが実行されていることを確認します。サービスが停止している場合は、開始してみてください。を参照してください xref:../maintain/index.adoc[リカバリとメンテナンスの手順]。
. ノードのホストの電源がオンになっていることを確認します。表示されない場合は、ホストを起動します。
+
* 注： * 複数のホストの電源がオフになっている場合は、を参照してください xref:../maintain/index.adoc[リカバリとメンテナンスの手順]。

. このノードと管理ノードの間にネットワーク接続問題 があるかどうかを確認します。
. このアラートを解決できない場合は、テクニカルサポートにお問い合わせください。




 a| 
予期しないノードのリブートです
 a| 
過去 24 時間以内にノードが予期せずリブートされました。

. このアラートを監視します。このアラートは 24 時間後にクリアされます。ただし、ノードが予期せずにリブートされた場合、このアラートは再度トリガーされます。
. アラートを解決できない場合は、ハードウェア障害が発生している可能性があります。テクニカルサポートにお問い合わせください。




 a| 
未識別の破損オブジェクトが検出されました
 a| 
レプリケートオブジェクトストレージにファイルが見つかりましたが、レプリケートオブジェクトとして識別できませんでした。

. ストレージノード上の基盤となるストレージに問題がないかどうかを確認します。たとえば、ハードウェア診断を実行するか、ファイルシステムチェックを実行します。
. ストレージの問題を解決したあと、 xref:verifying-object-integrity.adoc[オブジェクトの存在チェックを実行します] ILM ポリシーに定義されているレプリケートコピーがないかどうかを確認します。
. このアラートを監視します。このアラートは 24 時間後にクリアされますが、問題 が修正されていない場合は再度トリガーされます。
. このアラートを解決できない場合は、テクニカルサポートにお問い合わせください。


|===