---
permalink: monitor/logs-files-reference.html 
sidebar: sidebar 
keywords: log, logs, log files 
summary: StorageGRID には、イベント、診断メッセージ、およびエラー状態をキャプチャするために使用されるログが用意されています。テクニカルサポートにトラブルシューティングを依頼すると、ログファイルを収集して転送するように求められることがあります。 
---
= ログファイル参照
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID には、イベント、診断メッセージ、およびエラー状態をキャプチャするために使用されるログが用意されています。テクニカルサポートにトラブルシューティングを依頼すると、ログファイルを収集して転送するように求められることがあります。

ログは次のように分類されます。

* xref:storagegrid-software-logs.adoc[StorageGRID ソフトウェアのログ]
* xref:deployment-and-maintenance-logs.adoc[導入とメンテナンスのログ]
* xref:logs-for-third-party-software.adoc[サードパーティソフトウェアのログ]
* xref:about-bycast-log.adoc[bycast.log について]



IMPORTANT: 各ログタイプの詳細情報は参考用です。これらのログは、テクニカルサポートが高度なトラブルシューティングに使用することを目的としています。監査ログやアプリケーションログファイルを使用して問題の履歴を再構築する高度な手法については、この手順では説明していません。

ログにアクセスするには、 1 つ以上のノードからログファイルとシステムデータを単一のログファイルアーカイブとして収集します（ * support * > * Tools * > * Logs * ）。または、プライマリ管理ノードを使用できない場合や特定のノードに到達できない場合は、次の手順で各グリッドノードの個別のログファイルにアクセスできます。

. 次のコマンドを入力します。 ssh admin@grid_node_name
. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
. root に切り替えるには、次のコマンドを入力します
. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。


StorageGRID ログファイルアーカイブには、カテゴリごとに説明されているログ、およびメトリックと debug コマンドの出力が含まれている追加ファイルが含まれています。

[cols="1a,3a"]
|===
| アーカイブの場所 | 説明 


| 監査  a| 
通常のシステム動作中に生成される監査メッセージです。



| base-os-logs  a| 
StorageGRID イメージのバージョンなど、ベースとなるオペレーティングシステムの情報。



| バンドル  a| 
グローバル構成情報（バンドル）。



| Cassandra  a| 
Cassandra データベース情報と Reaper 修復ログ。



| EC  a| 
プロファイル ID に基づいて、現在のノードおよび EC グループの情報が VCS に表示されます。



| グリッド（ Grid ）  a| 
デバッグ (bycast.log) や「 servermanager 」ログを含む一般的なグリッドログ。



| grid.xml  a| 
グリッド構成ファイルをすべてのノードで共有



| シュラウド  a| 
ハイアベイラビリティグループの指標とログ。



| をインストールします  a| 
Gdu-server' ログとインストール・ログ



| lumberjack.log  a| 
ログ収集に関連するデバッグメッセージ。



| Lambda - アービトレータ  a| 
S3 Select プロキシ要求に関連するログです。



| 指標  a| 
Grafana 、 Jaeger 、ノードエクスポータ、および Prometheus のサービスログ。



| 計算ミス  a| 
Miscd アクセスログとエラーログ。



| MySQL  a| 
MariaDB データベースの設定と関連ログ。



| ネット  a| 
ネットワーク関連のスクリプトおよび Dyip サービスによって生成されるログ。



| nginx  a| 
ロードバランサの構成ファイルとログ：Grid Manager と Tenant Manager のトラフィックログも含まれます。



| nginx-gw と入力します  a| 
ロードバランサの構成ファイルとログ：



| NTP  a| 
NTP 構成ファイルとログ：



| OS  a| 
ノードおよびグリッドの状態ファイル（サービス「 pid 」を含む）



| その他  a| 
他のフォルダには収集されない '/var/local/log' の下にログ・ファイルが格納されます



| パフォーマンス  a| 
CPU 、ネットワーク、ディスク I/O のパフォーマンス情報



| prometheus-data  a| 
ログ収集に Prometheus データが含まれている場合、現在の Prometheus 指標。



| プロビジョニング  a| 
グリッドのプロビジョニングプロセスに関連するログです。



| ラフト  a| 
プラットフォームサービスで使用される Raft クラスタのログ。



| SNMP  a| 
SNMP エージェント設定およびアラーム許可 / 拒否リストは、 SNMP 通知の送信に使用されます。



| ソケット - データ  a| 
ネットワークデバッグ用のソケットデータ。



| system-commands.txt  a| 
StorageGRID コンテナコマンドの出力。ネットワークやディスクの使用状況などのシステム情報が含まれます。

|===
.関連情報
xref:collecting-log-files-and-system-data.adoc[ログファイルとシステムデータを収集]
