---
permalink: monitor/monitoring-load-balancing-operations.html 
sidebar: sidebar 
keywords: load balancing, monitoring 
summary: ロードバランサを使用して StorageGRID へのクライアント接続を管理している場合は、システムを最初に設定したあとと、設定を変更したり拡張を行ったあとに、ロードバランシング処理を監視する必要があります。 
---
= ロードバランシング処理を監視する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ロードバランサを使用して StorageGRID へのクライアント接続を管理している場合は、システムを最初に設定したあとと、設定を変更したり拡張を行ったあとに、ロードバランシング処理を監視する必要があります。

.必要なもの
* を使用して Grid Manager にサインインする必要があります xref:../admin/web-browser-requirements.adoc[サポートされている Web ブラウザ]。
* 特定のアクセス権限が必要です。


管理ノードまたはゲートウェイノード上のロードバランササービス、外部のサードパーティのロードバランサ、またはゲートウェイノード上の CLB サービスを使用して、複数のストレージノードにクライアント要求を分散することができます。


NOTE: CLB サービスは廃止されました。

ロードバランシングを設定したら、オブジェクトの取り込みと読み出しの処理がストレージノード間で均等に分散されていることを確認する必要があります。要求が均等に分散されるため、 StorageGRID は負荷がかかっているクライアント要求への応答性を維持し、クライアントのパフォーマンスを維持できます。

ゲートウェイノードまたは管理ノードのハイアベイラビリティ（ HA ）グループをアクティブ / バックアップモードで設定した場合、グループ内の 1 つのノードだけがクライアント要求をアクティブに分散します。

StorageGRID の管理手順のクライアント接続の設定に関するセクションを参照してください。

.手順
. S3 または Swift クライアントがロードバランササービスを使用して接続する場合は、管理ノードまたはゲートウェイノードが想定どおりにトラフィックをアクティブに分散していることを確認します。
+
.. [* nodes （ノード） ] を選択します
.. ゲートウェイノードまたは管理ノードを選択します。
.. 概要 * タブで、ノードインターフェイスが HA グループに含まれているかどうか、およびノードインターフェイスのロールがマスターであるかどうかを確認します。
+
マスターのロールがノードで、 HA グループにないノードがクライアントに要求をアクティブに分散している必要があります。

.. クライアント要求をアクティブに分散するノードごとに、 * ロードバランサ * タブを選択します。
.. 過去 1 週間のロードバランサ要求トラフィックのチャートを確認して、ノードが要求をアクティブに分散していることを確認します。
+
アクティブ / バックアップ HA グループのノードでは、 Backup ロールが随時割り当てられる場合があります。この間、ノードはクライアント要求を分散しません。

.. ノードのオブジェクトスループットを確認するには、過去 1 週間のロードバランサの受信要求速度のグラフを確認します。
.. StorageGRID システムの管理ノードまたはゲートウェイノードごとに上記の手順を繰り返します。
.. 任意で、トラフィック分類ポリシーを使用して、ロードバランササービスが処理するトラフィックの詳細な内訳を表示できます。


. S3 または Swift クライアントが CLB サービス（廃止）を使用して接続する場合は、次のチェックを実行します。
+
.. [* nodes （ノード） ] を選択します
.. ゲートウェイノードを選択します。
.. 概要 * タブで、ノードインターフェイスが HA グループに含まれているかどうか、およびノードインターフェイスのロールがマスターであるかどうかを確認します。
+
マスターのロールがノードで、 HA グループにないノードがクライアントに要求をアクティブに分散している必要があります。

.. クライアント要求をアクティブに分散するゲートウェイノードごとに、 * support * > * Tools * > * Grid Topology * を選択します。
.. [*_Gateway Node_*>*CLB*>*HTTP*>*Overview*>*Main*] を選択します。
.. ゲートウェイノードが要求をアクティブに処理していることを確認するために、受信セッション - ESTABLISHED * の数を確認します。


. これらの要求がストレージノードに均等に分散されていることを確認します。
+
.. 「 * _ ストレージノード _ * > * LDR * > * HTTP * 」を選択します。
.. 現在確立されている受信セッション数 * を確認します。
.. グリッド内のストレージノードごとにこの手順を繰り返します。
+
セッションの数はすべてのストレージノードでほぼ同じにします。





xref:../admin/index.adoc[StorageGRID の管理]

xref:viewing-load-balancer-tab.adoc[Load Balancer タブを表示します]
