---
permalink: monitor/set-up-snmp-alert-notifications.html 
sidebar: sidebar 
keywords: how to use snmp notifications for alerts 
summary: アラート発生時に StorageGRID から SNMP 通知を送信するには、 StorageGRID SNMP エージェントを有効にし、 1 つ以上のトラップ送信先を設定する必要があります。 
---
= アラートの SNMP 通知を設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アラート発生時に StorageGRID から SNMP 通知を送信するには、 StorageGRID SNMP エージェントを有効にし、 1 つ以上のトラップ送信先を設定する必要があります。

Grid Manager またはグリッド管理 API の SNMP エンドポイントで * configuration * > * Monitoring * > * SNMP エージェント * オプションを使用して、 StorageGRID SNMP エージェントを有効にして設定できます。SNMP エージェントは、 3 つのバージョンの SNMP プロトコルをすべてサポートします。

SNMP エージェントの設定方法については、を参照してください xref:using-snmp-monitoring.adoc[SNMP による監視を使用する]。

StorageGRID SNMP エージェントの設定後に、次の 2 種類のイベントベースの通知を送信できます。

* トラップは、 SNMP エージェントから送信される通知であり、管理システムによる確認応答は必要ありません。トラップは、アラートがトリガーされているなど、 StorageGRID 内で何らかの問題が発生したことを管理システムに通知するために使用されます。トラップは、 SNMP の 3 つのバージョンすべてでサポートされています。
* 通知はトラップと似ていますが、管理システムによる確認応答が必要です。SNMP エージェントが一定時間内に確認応答を受信しなかった場合、確認応答を受信するか、最大再試行値に達するまで、通知を再送信します。インフォームは SNMPv2c および SNMPv3 でサポートされます。


トラップ通知およびインフォーム通知は、デフォルトまたはカスタムアラートがいずれかの重大度レベルでトリガーされたときに送信されます。アラートの SNMP 通知を停止するには、アラートのサイレンスを設定する必要があります。を参照してください xref:silencing-alert-notifications.adoc[アラート通知をサイレント化する]。

アラート通知は、優先送信者として設定された管理ノードから送信されます。デフォルトでは、プライマリ管理ノードが選択されます。を参照してください xref:../admin/index.adoc[StorageGRID の管理手順]。


NOTE: トラップ通知およびインフォーム通知は、指定された重大度レベル以上で特定のアラーム（レガシーシステム）がトリガーされたときにも送信されますが、 SNMP 通知はすべてのアラームまたはすべてのアラーム重大度に対して送信されるわけではありません。を参照してください xref:alarms-that-generate-snmp-notifications.adoc[SNMP 通知を生成するアラーム（従来のシステム）]。
