---
permalink: monitor/using-snmp-monitoring.html 
sidebar: sidebar 
keywords: snmp, monitoring 
summary: 簡易ネットワーク管理プロトコル \ （ SNMP\ ）を使用して StorageGRID を監視する場合は、 StorageGRID に含まれる SNMP エージェントを設定する必要があります。 
---
= SNMP による監視を使用する
:icons: font
:imagesdir: ../media/


[role="lead"]
簡易ネットワーク管理プロトコル（ SNMP ）を使用して StorageGRID を監視する場合は、 StorageGRID に含まれる SNMP エージェントを設定する必要があります。

* xref:configuring-snmp-agent.adoc[SNMP エージェントを設定します]
* xref:updating-snmp-agent.adoc[SNMP エージェントを更新します]




== 機能

各 StorageGRID ノードは、管理情報ベース（ MIB ）を提供する SNMP エージェントまたはデーモンを実行します。StorageGRID の MIB には、アラートおよびアラームのテーブルおよび通知定義が含まれています。この MIB には、各ノードのプラットフォームやモデル番号など、システムの概要 情報も含まれています。各 StorageGRID ノードは MIB-II オブジェクトのサブセットもサポートしています。

最初は、すべてのノードで SNMP が無効になっています。SNMP エージェントを設定すると、すべての StorageGRID ノードに同じ設定が適用されます。

StorageGRID SNMP エージェントは、 3 つのバージョンの SNMP プロトコルをすべてサポートします。クエリに読み取り専用 MIB アクセスを提供し、次の 2 種類のイベントベース通知を管理システムに送信できます。

* * トラップ * は、管理システムによる確認応答を必要としない SNMP エージェントによって送信される通知です。トラップは、アラートがトリガーされているなど、 StorageGRID 内で何らかの問題が発生したことを管理システムに通知するために使用されます。
+
トラップは、 SNMP の 3 つのバージョンすべてでサポートされています。

* * informs * はトラップに似ていますが、管理システムからの確認応答が必要です。SNMP エージェントが一定時間内に確認応答を受信しなかった場合、確認応答を受信するか、最大再試行値に達するまで、通知を再送信します。
+
インフォームは SNMPv2c および SNMPv3 でサポートされます。



トラップ通知およびインフォーム通知は、次の場合に送信されます。

* デフォルトまたはカスタムのアラートはいずれかの重大度レベルでトリガーされます。アラートの SNMP 通知を停止するには、アラートのサイレンスを設定する必要があります。アラート通知は、優先送信者として設定された管理ノードから送信されます。
+
各アラートは、アラートの重大度レベルに基づいて、 activeMinorAlert 、 activeMagajorAlert 、および activeCriticalAlert の 3 つのトラップタイプのいずれかにマッピングされます。これらのトラップをトリガーできるアラートの説明については、を参照してください xref:alerts-reference.adoc[アラート一覧]。

* 特定のアラーム（従来型システム）は、指定した重大度レベル以上でトリガーされます。
+

NOTE: SNMP 通知は、すべてのアラームまたはすべてのアラーム重大度について送信されるわけではありません。





== SNMP バージョンサポート

次の表に、各 SNMP バージョンでサポートされる内容の概要を示します。

|===
|  | SNMPv1 | SNMPv2c の場合 | SNMPv3 


 a| 
クエリ
 a| 
読み取り専用 MIB クエリ
 a| 
読み取り専用 MIB クエリ
 a| 
読み取り専用 MIB クエリ



 a| 
クエリ認証
 a| 
コミュニティストリング
 a| 
コミュニティストリング
 a| 
ユーザベースのセキュリティモデル（ USM ）ユーザ



 a| 
通知
 a| 
トラップのみ
 a| 
トラップおよびインフォーム
 a| 
トラップおよびインフォーム



 a| 
通知認証
 a| 
トラップの送信先ごとに、デフォルトのトラップコミュニティまたはカスタムのコミュニティストリングを指定します
 a| 
トラップの送信先ごとに、デフォルトのトラップコミュニティまたはカスタムのコミュニティストリングを指定します
 a| 
トラップの送信先ごとの USM ユーザ

|===


== 制限

* StorageGRID は、読み取り専用 MIB アクセスをサポートしています。読み取り / 書き込みアクセスはサポートされていません。
* グリッド内のすべてのノードが同じ設定を受信します。
* SNMPv3 ： StorageGRID は TSM （ Transport Support Mode ）をサポートしていません。
* SNMPv3 ： SHA （ HMAC-SHA-96 ）だけがサポートされています。
* SNMPv3 ： AES のみがサポートされています。




== MIB にアクセスします

MIB 定義ファイルには、任意の StorageGRID ノードの次の場所からアクセスできます。

/usr/share/snmp/mibs/NetApp-STORAGEGRID - mib.txt です

.関連情報
* xref:alerts-reference.adoc[アラート一覧]
* xref:alarms-reference.adoc[アラーム一覧（従来のシステム）]
* xref:alarms-that-generate-snmp-notifications.adoc[SNMP 通知を生成するアラーム（従来のシステム）]
* xref:silencing-alert-notifications.adoc[アラート通知をサイレント化する]

