---
permalink: maintain/checking-data-repair-jobs.html 
sidebar: sidebar 
keywords: storagegrid, data repair 
summary: グリッドノードの運用を停止する前に、アクティブなデータ修復ジョブがないことを確認する必要があります。修復に失敗した場合は、手順 の運用を停止する前に、修復を再開し、完了させておく必要があります。 
---
= データ修復ジョブを確認します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッドノードの運用を停止する前に、アクティブなデータ修復ジョブがないことを確認する必要があります。修復に失敗した場合は、手順 の運用を停止する前に、修復を再開し、完了させておく必要があります。

切断されているストレージノードの運用を停止する必要がある場合は、手順 の運用停止が完了したあとに、データ修復ジョブが正常に完了するように、この手順も実行します。削除したノードにイレイジャーコーディングフラグメントがあった場合は、適切にリストアされたことを確認してください。

以下の手順は、イレイジャーコーディングオブジェクトがあるシステムにのみ適用されます。

. プライマリ管理ノードにログインします。
+
.. 次のコマンドを入力します。 ssh admin@_grid_node_name
+
root としてログインすると、プロンプトは「 $` 」から「 #」 に変わります。

.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
.. root に切り替えるには、次のコマンドを入力します
.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。


. 実行中の修復を確認します「 repair-data show-ec-repair-status 」
+
** データ修復ジョブを実行したことがない場合、出力は「ジョブが見つかりません」になります。修復ジョブを再開する必要はありません。
** データ修復ジョブを以前に実行したか、現在実行している場合は、出力には修復に関する情報が表示されます。各修復には、一意の修復 ID が割り当てられます。次の手順に進みます。


+
[listing]
----
root@DC1-ADM1:~ # repair-data show-ec-repair-status

Repair ID Scope Start Time End Time State Est/Affected Bytes Repaired Retry Repair
===================================================================================
949283 DC1-S-99-10(Volumes: 1,2) 2016-11-30T15:27:06.9 Success 17359 17359 No
949292 DC1-S-99-10(Volumes: 1,2) 2016-11-30T15:37:06.9 Failure 17359 0     Yes
949294 DC1-S-99-10(Volumes: 1,2) 2016-11-30T15:47:06.9 Failure 17359 0     Yes
949299 DC1-S-99-10(Volumes: 1,2) 2016-11-30T15:57:06.9 Failure 17359 0     Yes
----
. すべての修復の State が Success の場合は ' 修復ジョブを再開する必要はありません
. いずれかの修復の State が Failure の場合は ' その修復を再開する必要があります
+
.. 出力から、障害が発生した修復の修復 ID を取得します。
.. 「 repair-data start-ec-node-repair 」コマンドを実行します。
+
「 --repair-id 」オプションを使用して、修復 ID を指定します。たとえば、修復 ID が 949292 の修復を再試行する場合は、「 repair-data start-ec-node-repair --repair-id 949292` 」コマンドを実行します

.. すべての修復の State が Success になるまで、引き続き EC データの修復のステータスを追跡します。



