---
permalink: maintain/configuring-ip-addresses.html 
sidebar: sidebar 
keywords: storagegrid, ip address, configure ip address, configuring ip address, network configuration, network configure, network configuring 
summary: IP 変更ツールを使用してグリッドノードの IP アドレスを設定することで、ネットワーク設定を実行できます。 
---
= IP アドレスを設定する
:icons: font
:imagesdir: ../media/


[role="lead"]
IP 変更ツールを使用してグリッドノードの IP アドレスを設定することで、ネットワーク設定を実行できます。

グリッドの導入時に設定されたネットワーク設定を変更するには、ほとんどの場合、 IP 変更ツールを使用する必要があります。標準の Linux ネットワークコマンドおよびファイルを使用して手動で変更すると、すべての StorageGRID サービスに変更が反映されなかったり、アップグレード、リブート、ノードリカバリ手順の実行後に変更が失われたりすることがあります。


NOTE: グリッド内のすべてのノードのグリッドネットワーク IP アドレスを変更する場合は、を使用します xref:changing-ip-addresses-and-mtu-values-for-all-nodes-in-grid.adoc[グリッド全体で変更される特殊な手順]。


NOTE: グリッドネットワークサブネットリストのみを変更する場合は、グリッドマネージャを使用してネットワーク設定の追加または変更を行います。グリッドネットワーク設定問題 が原因でグリッドマネージャにアクセスできない場合、またはグリッドネットワークルーティングの変更とその他のネットワーク変更を同時に実行する場合は、 IP 変更ツールを使用します。


IMPORTANT: IP 変更手順 は、停止を伴う手順 の可能性があります。グリッドの一部は、新しい設定が適用されるまで使用できない場合があります。

* イーサネット・インターフェイス *

eth0 に割り当てられる IP アドレスは、常にグリッドノードのグリッドネットワーク IP アドレスになります。eth1 に割り当てられている IP アドレスは、常にグリッドノードの管理ネットワーク IP アドレスです。eth2 に割り当てられている IP アドレスは、常にグリッドノードのクライアントネットワーク IP アドレスです。

StorageGRID アプライアンスなどの一部のプラットフォームでは、 eth0 、 eth1 、 eth2 が、下位のブリッジで構成されるアグリゲートインターフェイスや物理 / VLAN インターフェイスのボンドである場合があります。これらのプラットフォームでは、 * ssm* > * Resources * タブに、 eth0 、 eth1 、 eth2 に加えて、他のインターフェイスに割り当てられているグリッドネットワーク、管理ネットワーク、およびクライアントネットワークの IP アドレスが表示されることがあります。

* DHCP *

DHCP は導入フェーズでのみ設定できます。設定時に DHCP を設定することはできません。グリッドノードの IP アドレス、サブネットマスク、およびデフォルトゲートウェイを変更する場合は、 IP アドレス変更手順を使用する必要があります。IP 変更ツールを使用すると、原因 の DHCP アドレスが静的アドレスになります。

* ハイアベイラビリティ（ HA ）グループ *

* クライアントネットワークインターフェイスが HA グループに含まれている場合、そのインターフェイスのクライアントネットワーク IP アドレスを、 HA グループに設定されているサブネットの外部にあるアドレスに変更することはできません。
* クライアントネットワーク IP アドレスを、クライアントネットワークインターフェイスで設定された HA グループに割り当てられた既存の仮想 IP アドレスの値に変更することはできません。
* グリッドネットワークインターフェイスが HA グループに含まれている場合、そのインターフェイスのグリッドネットワークの IP アドレスを、 HA グループに設定されているサブネットの外部にあるアドレスに変更することはできません。
* グリッドネットワークの IP アドレスを、グリッドネットワークのインターフェイスで設定された HA グループに割り当てられている既存の仮想 IP アドレスの値に変更することはできません。

