---
permalink: maintain/downloading-hotfix-file.html 
sidebar: sidebar 
keywords: storagegrid, hotfix, download 
summary: ホットフィックスを適用する前に、ホットフィックスファイルをダウンロードする必要があります。 
---
= ホットフィックスファイルをダウンロードします
:icons: font
:imagesdir: ../media/


[role="lead"]
ホットフィックスを適用する前に、ホットフィックスファイルをダウンロードする必要があります。

.手順
. ネットアップの StorageGRID ダウンロードページにアクセスします。
+
https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["ネットアップのダウンロード： StorageGRID"]

. [ 利用可能なソフトウェア ] の下にある下矢印をクリックすると、ダウンロード可能なホットフィックスのリストが表示されます。
+

NOTE: ホットフィックスファイルのバージョンの形式は 11.4_.x.y__ です。

. 更新に含まれている変更を確認します。
+

NOTE: プライマリ管理ノードをリカバリした直後でホットフィックスを適用する必要がある場合は、他のグリッドノードにインストールされているものと同じバージョンのホットフィックスを選択します。

+
.. ダウンロードするホットフィックスのバージョンを選択し、 * Go * を選択します。
.. ネットアップアカウントのユーザ名とパスワードを使用してサインインします。
.. エンドユーザライセンス契約を読んで同意します。
+
選択したバージョンのダウンロードページが表示されます。

.. 修正プログラムの Readme.txt ファイルをダウンロードして ' 修正プログラムに含まれる変更の概要を表示します


. ホットフィックスのダウンロードボタンを選択してファイルを保存します。
+

NOTE: このファイルの名前は変更しないでください。

+

NOTE: macOS デバイスを使用している場合、修正プログラムファイルは自動的に「 .txt 」ファイルとして保存されます。その場合は '.txt' 拡張子を付けずにファイルの名前を変更してください

. ダウンロードする場所を選択し、「 * 保存 * 」を選択します。


xref:configuring-replacement-primary-admin-node.adoc[交換用プライマリ管理ノードを設定]
