---
permalink: maintain/how-appliance-node-cloning-works.html 
sidebar: sidebar 
keywords: storagegrid, appliance node cloning, appliance node clone 
summary: アプライアンスノードのクローニングを使用すると、グリッド内の既存のアプライアンスノード（ソース）を、同じ論理 StorageGRID サイトに含まれる互換性のあるアプライアンス（ターゲット）に簡単に置き換えることができます。このプロセスでは、すべてのデータが新しいアプライアンスに転送され、古いアプライアンスノードを交換するためにアプライアンスが稼働中になり、古いアプライアンスは設置前の状態になります。 
---
= アプライアンスノードのクローニングの仕組み
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アプライアンスノードのクローニングを使用すると、グリッド内の既存のアプライアンスノード（ソース）を、同じ論理 StorageGRID サイトに含まれる互換性のあるアプライアンス（ターゲット）に簡単に置き換えることができます。このプロセスでは、すべてのデータが新しいアプライアンスに転送され、古いアプライアンスノードを交換するためにアプライアンスが稼働中になり、古いアプライアンスは設置前の状態になります。



== アプライアンスノードをクローニングする理由

アプライアンスノードは、次の処理が必要な場合にクローニングできます。

* 寿命が近づいているアプライアンスの交換
* 改善されたアプライアンステクノロジを活用するには、既存のノードをアップグレードしてください。
* StorageGRID システム内のストレージノードの数を変更することなく、グリッドのストレージ容量を拡張できます。
* RAID モードを DDP 8 から DDP 16 に変更する、 RAID 6 に変更するなどして、ストレージ効率を向上
* ノード暗号化を効率的に実装して、外部キー管理サーバ（ KMS ）を使用できるようにします。




== どの StorageGRID ネットワークが使用されていますか？

クローニングでは、 3 つの StorageGRID ネットワークのいずれかで、ソースノードからターゲットアプライアンスにデータが直接転送されます。グリッドネットワークは通常は使用されますが、ソースアプライアンスがこれらのネットワークに接続されている場合は、管理ネットワークまたはクライアントネットワークも使用できます。StorageGRID ネットワークのパフォーマンスやデータの可用性を低下させることなく、最高のデータ転送パフォーマンスを提供するトラフィックのクローニングに使用するネットワークを選択してください。

交換用アプライアンスを設置するときは、 StorageGRID 接続およびデータ転送用の一時的な IP アドレスを指定する必要があります。交換用アプライアンスは交換前のアプライアンスノードと同じネットワークに含まれるため、交換用アプライアンスでこれらのネットワークごとに一時 IP アドレスを指定する必要があります。



== ターゲットアプライアンスの互換性

交換用アプライアンスは、交換するソースノードと同じタイプで、両方が同じ論理 StorageGRID サイトに属している必要があります。

* 交換用サービスアプライアンスは、交換する管理ノードまたはゲートウェイノードとは異なる場合があります。
+
** SG1000 サービスのターゲットアプライアンスに SG100 ソースノードアプライアンスをクローニングして、管理ノードまたはゲートウェイノードの機能を強化できます。
** SG1000 ソースノードアプライアンスを SG100 サービスターゲットアプライアンスにクローニングして、要件の厳しいアプリケーション用に SG1000 を再導入することができます。
+
たとえば、 SG1000 ソースノードアプライアンスを管理ノードとして使用していて、専用のロードバランシングノードとして使用する場合などです。

** SG1000 ソースノードアプライアンスを SG100 サービスターゲットアプライアンスに交換すると、ネットワークポートの最大速度が 100GbE から 25GbE に減ります。
** SG100 と SG1000 アプライアンスでは、ネットワークコネクタが異なります。アプライアンスのタイプを変更する場合は、ケーブルまたは SFP モジュールの交換が必要になることがあります。


* 交換用ストレージアプライアンスには、交換するストレージノード以上の容量が必要です。
+
** ターゲットストレージアプライアンスのドライブ数がソースノードと同じである場合は、ターゲットアプライアンスのドライブの容量（TB）を増やす必要があります。
** ターゲットノードでソースノードと同じ RAID モードを使用する場合は、次の手順を実行します。 ストレージ効率に優れた RAID モード（ RAID 6 から DDP への切り替えなど）では、ターゲットアプライアンスのドライブはソースアプライアンスのドライブよりも大きく（ TB ）必要です。
** ターゲットストレージアプライアンスに設置されている標準ドライブ数がソースノードのドライブ数よりも少ない場合は、ソリッドステートドライブ（ SSD ）が設置されているため、ターゲットアプライアンスの標準ドライブの全体的なストレージ容量（ TB ）が表示されます。 ソースストレージノード内のすべてのドライブの機能的な合計ドライブ容量を満たしているか、超えている必要があります。
+
たとえば、60本のドライブを搭載したSG5660ソースストレージノードアプライアンスを、58標準ドライブを搭載したSG6060またはSG6060Xターゲットアプライアンスにクローニングする場合は、ストレージ容量を確保するために、クローニングを行う前にSG6060またはSG6060Xターゲットアプライアンスに大容量のドライブを設置する必要があります。（ターゲットアプライアンス内の SSD を含む 2 つのドライブスロットは、アプライアンスのストレージ容量の合計には含まれません）。

+
ただし、60ドライブSG5660ソースノードアプライアンスがSANtricity Dynamic Disk Pools DDP 8で構成されている場合は、ストレージ効率が向上しているため、SG6058ドライブの同じサイズドライブSG6060またはSG6060Xターゲットアプライアンスを有効なクローンターゲットにする可能性があります。

+
ソースアプライアンスノードの現在の RAID モードに関する情報は、 Grid Manager の * nodes * ページで確認できます。アプライアンスの [*Storage*] タブを選択します。







== クローニングされない情報

以下のアプライアンス設定は、クローニング中に交換用アプライアンスに転送されません。交換用アプライアンスの初期セットアップ時に設定する必要があります。

* BMC インターフェイス
* ネットワークリンク
* ノード暗号化ステータス
* SANtricity システムマネージャ（ストレージノード用）
* RAID モード（ストレージノード用）




== クローニングの妨げとなる問題

クローニング中に次のいずれかの問題が発生すると、クローニングプロセスが停止し、エラーメッセージが生成されます。

* ネットワーク設定が正しくありません
* ソースとターゲットのアプライアンス間の接続が確立されていません
* ソースとターゲットのアプライアンスに互換性がない
* ストレージノードの場合は、容量の不十分な交換用アプライアンス


続行するには、クローニングのために各問題 を解決する必要があります。
