---
permalink: maintain/linux-adding-trunk-or-access-interfaces-to-node.html 
sidebar: sidebar 
keywords: add extra interface to node, trunk interface, access interface 
summary: Linux ノードをインストールしたあとで、そのノードにトランクインターフェイスまたはアクセスインターフェイスを追加できます。追加したインターフェイスは、 VLAN インターフェイスのページと HA グループのページに表示されます。 
---
= Linux ：ノードにトランクインターフェイスまたはアクセスインターフェイスを追加します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Linux ノードをインストールしたあとで、そのノードにトランクインターフェイスまたはアクセスインターフェイスを追加できます。追加したインターフェイスは、 VLAN インターフェイスのページと HA グループのページに表示されます。

.必要なもの
* Linux プラットフォームへの StorageGRID のインストール手順を参照できるようにしておきます。
+
** xref:../rhel/index.adoc[Red Hat Enterprise Linux または CentOS をインストールします]
** xref:../ubuntu/index.adoc[Ubuntu または Debian をインストールします]


* 「 passwords.txt 」ファイルがあります。
* 特定のアクセス権限が必要です。



IMPORTANT: ソフトウェアのアップグレード、リカバリ手順 、または拡張手順 がアクティブな間は、ノードにインターフェイスを追加しないでください。

.このタスクについて
ノードのインストール後に Linux ノードに 1 つ以上のインターフェイスを追加するには、次の手順を実行します。たとえば、管理ノードまたはゲートウェイノードにトランクインターフェイスを追加して、 VLAN インターフェイスを使用して複数のアプリケーションまたはテナントに属するトラフィックを分離できます。または、ハイアベイラビリティ（ HA ）グループで使用するアクセスインターフェイスを追加することもできます。

トランクインターフェイスを追加する場合は、 StorageGRID で VLAN インターフェイスを設定する必要があります。アクセスインターフェイスを追加する場合は、 HA グループに直接追加できます。 VLAN インターフェイスを設定する必要はありません。

インターフェイスを追加するときは、ノードを一時的に使用できなくなります。この手順 は一度に 1 つのノードで実行する必要があります。

.手順
. ノードをホストしている Linux サーバにログインします。
. vim や pico などのテキストエディタを使用して、ノード構成ファイルを編集します。
+
/etc/storagegrid/nodes/ _node-name _.conf

. ファイルにエントリを追加して名前を指定し、必要に応じて、ノードに追加する各インターフェイスの概要 を指定します。次の形式を使用します。
+
`interfaces_target_nnnn = _value_`

+
_nnnnnn _ の場合、追加する「 interfaces_target 」エントリごとに一意の番号を指定します。

+
value _ には、ベアメタルホスト上の物理インターフェイスの名前を指定します。その後、必要に応じて、カンマを追加してインターフェイスの概要 を指定します。このインターフェイスは、 VLAN インターフェイスのページと HA グループのページに表示されます。

+
例：

+
`interfaces_target_01= ens256, Trunk`

+

IMPORTANT: 他のネットワークパラメータを指定しないでください。検証エラーが発生します。

. 次のコマンドを実行して、ノード構成ファイルに対する変更を検証します。
+
sudo StorageGRID node VALIDATE_NODE-NAME_`

+
エラーや警告がある場合は、次の手順に進む前に対処してください。

. 次のコマンドを実行して、ノードの設定を更新します。
+
sudo StorageGRID node reload_node-name_



.完了後
* トランクインターフェイスを追加した場合は、に進みます xref:../admin/configure-vlan-interfaces.html[VLAN インターフェイスを設定します] 新しい親インターフェイスごとに 1 つ以上の VLAN インターフェイスを設定します。
* アクセスインターフェイスを追加した場合は、に進みます xref:../admin/configure-high-availability-group.html[ハイアベイラビリティグループを設定する] 新しいインターフェイスを HA グループに直接追加する場合。

