---
permalink: maintain/powering-down-host.html 
sidebar: sidebar 
keywords: storagegrid, recover, stop services, power down host, power off host 
summary: ホストの電源をオフにする前に、そのホスト上のすべてのグリッドノードのサービスを停止する必要があります。 
---
= ホストの電源をオフにします
:icons: font
:imagesdir: ../media/


[role="lead"]
ホストの電源をオフにする前に、そのホスト上のすべてのグリッドノードのサービスを停止する必要があります。

.手順
. グリッドノードにログインします。
+
.. 次のコマンドを入力します。 ssh admin@_grid_node_name
.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
.. root に切り替えるには、次のコマンドを入力します
.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。


+
root としてログインすると、プロンプトは「 $` 」から「 #」 に変わります。

. ノード上で実行されているすべてのサービスを停止します :service servermanager stop
+
サービスのシャットダウンには最大 15 分かかる場合があります。リモートからシステムにログインしてシャットダウンプロセスを監視することもできます。

. ホストの各ノードについて、手順 1 と 2 を繰り返します。
. Linux ホストの場合：
+
.. ホストオペレーティングシステムにログインします。
.. ノードを停止します StorageGRID node stop
.. ホストオペレーティングシステムをシャットダウンします。


. ノードが VMware 仮想マシン上で実行されている場合、またはノードがアプライアンスノードである場合、問題 は shutdown コマンドを「 shutdown -h now 」と入力します
+
この手順は 'service servermanager stop コマンドの結果に関係なく実行します

+

NOTE: アプライアンス・ノードで shutdown -h now コマンドを実行した後問題 ' アプライアンスの電源を入れ直してノードを再起動する必要があります

+
アプライアンスの場合、このコマンドはコントローラをシャットダウンしますが、アプライアンスの電源はオンになったままです。次の手順を実行する必要があります。

. アプライアンスノードの電源をオフにする場合は、次の手順を実行します。
+
** SG100 または SG1000 サービスアプライアンスの場合
+
... アプライアンスの電源をオフにします。
... 青色の電源 LED が消灯するまで待ちます。


** SG6000 アプライアンスの場合
+
... ストレージコントローラの背面にある緑のキャッシュアクティブ LED が消灯するまで待ちます。
+
この LED は、キャッシュデータをドライブに書き込む必要があるときに点灯します。この LED が消灯するのを待ってから、電源をオフにする必要があります。

... アプライアンスの電源をオフにし、青色の電源 LED が消灯するまで待ちます。


** SG5700 アプライアンスの場合
+
... ストレージコントローラの背面にある緑のキャッシュアクティブ LED が消灯するまで待ちます。
+
この LED は、キャッシュデータをドライブに書き込む必要があるときに点灯します。この LED が消灯するのを待ってから、電源をオフにする必要があります。

... アプライアンスの電源をオフにし、すべての LED とデジタル表示ディスプレイの動作が停止するまで待ちます。




. コマンドシェルからログアウトします :exit


xref:../sg100-1000/index.adoc[SG100 および SG1000 サービスアプライアンス]

xref:../sg6000/index.adoc[SG6000 ストレージアプライアンス]

xref:../sg5700/index.adoc[SG5700 ストレージアプライアンス]
