---
permalink: maintain/preparing-appliance-for-reinstallation-platform-replacement-only.html 
sidebar: sidebar 
keywords: storagegrid, recover, appliance, reinstallation appliance, reinstall appliance 
summary: サービスアプライアンスでホストされていたグリッドノードをリカバリする場合は、最初に StorageGRID ソフトウェアを再インストールするアプライアンスを準備する必要があります。 
---
= 再インストールのためのアプライアンスの準備（プラットフォームの交換のみ）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
サービスアプライアンスでホストされていたグリッドノードをリカバリする場合は、最初に StorageGRID ソフトウェアを再インストールするアプライアンスを準備する必要があります。

この手順 は、サービスアプライアンスでホストされていた障害ノードを交換する場合にのみ実行してください。障害ノードが VMware または Linux ホストでホストされていた場合は実行しないでください。

. 障害が発生したグリッドノードにログインします。
+
.. 次のコマンドを入力します。 ssh admin@_grid_node_name
.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
.. root に切り替えるには、次のコマンドを入力します
.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。


+
root としてログインすると、プロンプトは「 $` 」から「 #」 に変わります。

. StorageGRID ソフトウェアをアプライアンスにインストールする準備をします。「 sgareinstall 」と入力します
. 続行するかどうかを確認するメッセージが表示されたら、「 y 」と入力します
+
アプライアンスがリブートされ、 SSH セッションが終了します。通常は 5 分程度で StorageGRID アプライアンスインストーラが使用可能になりますが、場合によっては最大で 30 分待つ必要があります。

+
サービスアプライアンスがリセットされ、グリッドノード上のデータにアクセスできなくなります。元のインストールプロセスで設定した IP アドレスはそのまま使用する必要がありますが、手順 の完了時に確認しておくことを推奨します。

+
「 sgareinstall 」コマンドを実行すると、 StorageGRID でプロビジョニングされたすべてのアカウント、パスワード、および SSH キーが削除され、新しいホストキーが生成されます。


