---
permalink: maintain/removing-port-remaps.html 
sidebar: sidebar 
keywords: storagegrid, recover, remove port remap, removing port remap, port remap 
summary: ロードバランササービスのエンドポイントを設定する場合、ポートの再マッピングのマッピング先ポートとしてすでに設定されているポートを使用するには、まず既存のポートの再マッピングを削除する必要があります。そうしないと、エンドポイントが有効になりません。ノードのすべてのポートの再マッピングを削除するには、再マッピングされたポートが競合している各管理ノードおよびゲートウェイノードでスクリプトを実行する必要があります。 
---
= ポートの再マッピングを削除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ロードバランササービスのエンドポイントを設定する場合、ポートの再マッピングのマッピング先ポートとしてすでに設定されているポートを使用するには、まず既存のポートの再マッピングを削除する必要があります。そうしないと、エンドポイントが有効になりません。ノードのすべてのポートの再マッピングを削除するには、再マッピングされたポートが競合している各管理ノードおよびゲートウェイノードでスクリプトを実行する必要があります。

.このタスクについて

CAUTION: この手順 は、ポートの再マッピングをすべて削除します。一部の再マッピングを保持する必要がある場合は、テクニカルサポートにお問い合わせください。

ロードバランサエンドポイントの設定については、 StorageGRID の管理手順を参照してください。


IMPORTANT: ポートの再マッピングでクライアントアクセスが提供される場合は、可能であればロードバランサエンドポイントとして設定した別のポートを使用するようにクライアントを再設定してください。そうしないと、ポートマッピングを削除してクライアントアクセスが失われるため、適切にスケジュールを設定する必要があります。


IMPORTANT: この手順 は、ベアメタルホスト上のコンテナとして導入した StorageGRID システムでは機能しません。の手順を参照してください xref:removing-port-remaps-on-bare-metal-hosts.adoc[ベアメタルホストでのポートの再マッピングの削除]。

.手順
. ノードにログインします。
+
.. 次のコマンドを入力します。「 ssh -p 8022 admin@node_ip 」
+
ポート 8022 はベース OS の SSH ポートで、ポート 22 は StorageGRID を実行しているコンテナエンジンの SSH ポートです。

.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
.. root に切り替えるには、次のコマンドを入力します
.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
+
root としてログインすると、プロンプトは「 $` 」から「 #」 に変わります。



. 次のスクリプトを実行します :`remove-port-remap.sh`
. ノードをリブートします。
+
の手順に従ってください xref:rebooting-grid-node.adoc[グリッドノードのリブート]。

. 再マッピングされたポートが競合している管理ノードおよびゲートウェイノードごとに上記の手順を繰り返します。


xref:../admin/index.adoc[StorageGRID の管理]
