---
permalink: maintain/replacing-failed-node-with-services-appliance.html 
sidebar: sidebar 
keywords: storagegrid, recover, replace failed node, services appliance 
summary: SG100 または SG1000 サービスアプライアンスを使用して、障害が発生したゲートウェイノード、障害が発生した非プライマリ管理ノード、または VMware 、 Linux ホスト、サービスアプライアンスでホストされていた障害が発生したプライマリ管理ノードをリカバリできます。この手順 は、グリッドノードのリカバリ手順 の 1 つのステップです。 
---
= 障害が発生したノードをサービスアプライアンスと交換します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SG100 または SG1000 サービスアプライアンスを使用して、障害が発生したゲートウェイノード、障害が発生した非プライマリ管理ノード、または VMware 、 Linux ホスト、サービスアプライアンスでホストされていた障害が発生したプライマリ管理ノードをリカバリできます。この手順 は、グリッドノードのリカバリ手順 の 1 つのステップです。

.必要なもの
* 次のいずれかの状況に該当することを確認しておく必要があります。
+
** ノードをホストしている仮想マシンをリストアできない。
** グリッドノードの物理 / 仮想 Linux ホストに障害が発生したため、交換する必要がある。
** グリッドノードをホストしているサービスアプライアンスを交換する必要があります。


* StorageGRID アプライアンスインストーラのバージョンを確認およびアップグレードするためのハードウェアの設置とメンテナンスの説明に従って、サービスアプライアンス上の StorageGRID アプライアンスインストーラのバージョンが StorageGRID システムのソフトウェアバージョンと一致していることを確認する必要があります。
+
xref:../sg100-1000/index.adoc[SG100 および SG1000 サービスアプライアンス]




IMPORTANT: SG100 と SG1000 サービスアプライアンスの両方を同じサイトに導入しないでください。パフォーマンスが予測不能になる可能性があります

次の場合は、 SG100 または SG1000 サービスアプライアンスを使用して、障害が発生したグリッドノードをリカバリできます。

* 障害ノードが VMware または Linux でホストされていた（プラットフォームの変更）
* 障害ノードがサービスアプライアンスでホストされていた（プラットフォームの交換）

