---
permalink: maintain/restoring-admin-node-database-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, restore admin node database, restore database, primary admin node 
summary: 障害が発生したプライマリ管理ノードの属性、アラーム、およびアラートの履歴情報を維持したい場合は、管理ノードデータベースをリストアします。このデータベースをリストアできるのは、 StorageGRID システムに別の管理ノードがある場合のみです。 
---
= プライマリ管理ノードをリカバリする際に管理ノードデータベースをリストアする
:icons: font
:imagesdir: ../media/


[role="lead"]
障害が発生したプライマリ管理ノードの属性、アラーム、およびアラートの履歴情報を維持したい場合は、管理ノードデータベースをリストアします。このデータベースをリストアできるのは、 StorageGRID システムに別の管理ノードがある場合のみです。

* リカバリした管理ノードをインストールして実行する必要があります。
* StorageGRID システムには管理ノードが少なくとも 2 つ必要です。
* 「 passwords.txt 」ファイルが必要です。
* プロビジョニングパスフレーズが必要です。


管理ノードで障害が発生すると、その管理ノードデータベースに格納されていた履歴情報が失われます。このデータベースには次の情報が含まれています。

* アラートの履歴
* アラームの履歴
* ヒストリカル属性データ。 * サポート * > * ツール * > * グリッドトポロジ * ページで使用できるチャートおよびテキストレポートで使用されます。


管理ノードをリカバリする際に、ソフトウェアのインストールプロセスによって、リカバリしたノードに空の管理ノードデータベースが作成されます。ただし、新しいデータベースには、現在システムに含まれているサーバとサービス、またはあとで追加されたサーバの情報だけが含まれます。

プライマリ管理ノードをリストアした StorageGRID システムに別の管理ノードがある場合は、プライマリでない管理ノード（ _source Admin Nod_ ）の管理ノードデータベースをリカバリしたプライマリ管理ノードにコピーすることで、履歴情報をリストアできます。システムにプライマリ管理ノードしかない場合は、管理ノードデータベースをリストアできません。


NOTE: 管理ノードデータベースのコピーには数時間かかることがあります。ソース管理ノードでサービスが停止している間は、グリッドマネージャの一部の機能が使用できなくなります。

. ソース管理ノードにログインします。
+
.. 次のコマンドを入力します。 ssh admin@_grid_node_name
.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
.. root に切り替えるには、次のコマンドを入力します
.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。


. ソース管理ノードから 'MI サービス 'service mi stop' を停止します
. ソース管理ノードから、 Management Application Program Interface （ mgmt-api ）サービス「 service mgmt-api stop 」を停止します
. リカバリした管理ノードで次の手順を実行します。
+
.. リカバリした管理ノードにログインします。
+
... 次のコマンドを入力します。 ssh admin@_grid_node_name
... 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
... root に切り替えるには、次のコマンドを入力します
... 「 passwords.txt 」ファイルに記載されたパスワードを入力します。


.. MI サービスを停止します : "service mi stop
.. mgmt-api サービス「 service mgmt-api stop 」を停止します
.. SSH エージェントに SSH 秘密鍵を追加します。「 ssh -add 」と入力します
.. 「 passwords.txt 」ファイルに記載された SSH アクセスパスワードを入力します。
.. ソース管理ノードからリカバリされた管理ノードにデータベースをコピーします :/usr/local/mi /bin/mi-clone-db.sh Source_Admin_Node_ip
.. プロンプトが表示されたら、リカバリした管理ノードで MI データベースを上書きすることを確定します。
+
データベースとその履歴データが、リカバリした管理ノードにコピーされます。コピー処理が完了すると、リカバリした管理ノードがスクリプトによって起動されます。

.. 他のサーバにパスワードなしでアクセスする必要がなくなった場合は、 SSH エージェントから秘密鍵を削除します。「 ssh -add-D`` 」と入力します


. ソース管理ノード上のサービスを再起動します :service servermanager start

