---
permalink: maintain/restoring-audit-log-on-recovered-non-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, restore audit log, non-primary admin node 
summary: 障害が発生した非プライマリ管理ノードから監査ログを保存できたために監査ログの履歴情報が保持されている場合は、リカバリする非プライマリ管理ノードにその情報をコピーできます。 
---
= リカバリ済み非プライマリ管理ノードで監査ログをリストアする
:icons: font
:imagesdir: ../media/


[role="lead"]
障害が発生した非プライマリ管理ノードから監査ログを保存できたために監査ログの履歴情報が保持されている場合は、リカバリする非プライマリ管理ノードにその情報をコピーできます。

* リカバリした管理ノードをインストールして実行する必要があります。
* 元の管理ノードで障害が発生したあとに、監査ログを別の場所にコピーしておく必要があります。


管理ノードで障害が発生すると、その管理ノードに保存された監査ログが失われる可能性があります。障害が発生した管理ノードから監査ログをコピーし、リカバリされた管理ノードにリストアすることで、データを損失から守ることができる場合があります。障害によっては、障害が発生した管理ノードから監査ログをコピーできない場合があります。その場合、管理ノードが複数ある環境ではすべての管理ノードに監査ログがレプリケートされるため、別の管理ノードから監査ログをリカバリできます。

管理ノードが 1 つしかない環境で障害ノードから監査ログをコピーできない場合は、リカバリされた管理ノードで、新規インストールの場合と同じように監査ログへのイベントの記録が開始されます。

ロギング機能を復旧させるために、管理ノードはできるだけ早くリカバリする必要があります。

[NOTE]
====
デフォルトでは、監査情報は管理ノードの監査ログに送信されます。次のいずれかに該当する場合は、これらの手順をスキップしてかまいません。

* 外部 syslog サーバを設定し、管理ノードではなく syslog サーバに監査ログを送信するようになりました。
* 監査メッセージを生成したローカルノードにのみ保存するように明示的に指定します。


を参照してください xref:../monitor/configure-audit-messages.adoc[監査メッセージとログの送信先を設定します] を参照してください。

====
.手順
. リカバリした管理ノードにログインします。
+
.. 次のコマンドを入力します。 +`ssh admin@recovery_Admin_Node_ip`
.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
.. root に切り替えるには、次のコマンドを入力します
.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。


+
root としてログインすると ' プロンプトが $` から #` に変わります

. 保持されている監査ファイルを確認します。
+
'cd /var/local/audit/export

. 保持されている監査ログファイルをリカバリされた管理ノードにコピーします。
+
「 scp admin@grid_node_name ： /var/local/tmp/saved-audit-logs/YYYY * 」

+
プロンプトが表示されたら、 admin のパスワードを入力します。

. セキュリティ上の理由により、監査ログがリカバリされた管理ノードにコピーされたことを確認したら、監査ログを障害グリッドノードから削除します。
. リカバリされた管理ノードで、監査ログファイルのユーザとグループの設定を更新します。
+
chown ams-user:bycast *

. root:exit としてログアウトします


監査共有への既存のクライアントアクセスもリストアする必要があります。詳細については、 StorageGRID の管理手順を参照してください。

xref:../admin/index.adoc[StorageGRID の管理]
