---
permalink: maintain/service-with-error-state.html 
sidebar: sidebar 
keywords: storagegrid, recover, service error state, error, error state 
summary: サービスがエラー状態になったことが検出された場合は、サービスの再開を試みてください。 
---
= エラー状態のサービス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
サービスがエラー状態になったことが検出された場合は、サービスの再開を試みてください。

「 passwords.txt 」ファイルが必要です。

Server Manager は、サービスを監視し、予期せず停止したサービスがあれば再起動します。サービスで障害が発生すると、 Server Manager はそのサービスの再起動を試行します。5 分以内にサービスの開始が 3 回失敗すると、サービスはエラー状態になります。Server Manager は再起動を試行しません。

.手順
. グリッドノードにログインします。
+
.. 次のコマンドを入力します。 ssh admin@_grid_node_name
.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
.. root に切り替えるには、次のコマンドを入力します
.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。


+
root としてログインすると、プロンプトは「 $` 」から「 #」 に変わります。

. サービスのエラー状態を確認します :'SERVICE_SERVICE_STATUS
+
例：

+
[listing]
----
service ldr status
----
+
サービスがエラー状態の場合は、次のメッセージが返されます。 `_servicename_in error state`例：

+
[listing]
----
ldr in error state
----
+

NOTE: サービスステータスが「 disabled 」の場合は、の手順を参照してください xref:removing-donotstart-file-for-service.adoc[サービスの DoNotStart ファイルを削除しています]。

. サービスを再起動してエラー状態を削除してみます :'SERVICE_SERVICE_Ename_restart
+
サービスを再開できない場合は、テクニカルサポートにお問い合わせください。

. コマンドシェルからログアウトします :exit

