---
permalink: maintain/shutting-down-grid-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, node shutdown, shut down node, node shut down 
summary: グリッドノードは、ノードのコマンドシェルからシャットダウンできます。 
---
= グリッドノードをシャットダウンします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッドノードは、ノードのコマンドシェルからシャットダウンできます。

.必要なもの
* 「 passwords.txt 」ファイルが必要です。


この手順 を実行する前に、次の考慮事項を確認してください。

* 通常は、業務の中断を避けるために、一度に複数のノードをシャットダウンすることは避けてください。
* ドキュメントまたはテクニカルサポートから指示があった場合を除き、メンテナンス手順 の実行中にノードをシャットダウンしないでください。
* シャットダウンプロセスは、ノードがインストールされている場所によって次のように異なります。
+
** VMware ノードをシャットダウンすると、仮想マシンがシャットダウンされます。
** Linux ノードをシャットダウンすると、コンテナがシャットダウンされます。
** StorageGRID アプライアンスノードをシャットダウンすると、コンピューティングコントローラがシャットダウンされます。


* サイトで複数のストレージノードをシャットダウンする場合は、ノードをシャットダウンする前に、そのサイトでのオブジェクトの取り込みを約1時間停止します。
+
いずれかのILMルールで* Dual commit *取り込みオプションを使用する場合（またはルールで* Balanced *オプションを使用するルールで必要なすべてのコピーをただちに作成できない場合）は、StorageGRID は、新たに取り込まれたオブジェクトをただちに同じサイトの2つのストレージノードにコミットしてあとでILMを評価します。サイトで複数のストレージノードがシャットダウンされている場合は、シャットダウン中に新たに取り込んだオブジェクトにアクセスできない可能性があります。使用可能なストレージノードがサイトで少なすぎる場合も、書き込み処理が失敗する可能性があります。



.手順
. グリッドノードにログインします。
+
.. 次のコマンドを入力します。 ssh admin@_grid_node_name
.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
.. root に切り替えるには、次のコマンドを入力します
.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。


+
root としてログインすると、プロンプトは「 $` 」から「 #」 に変わります。

. すべてのサービスを停止します :'service servermanager stop
+
サービスのシャットダウンには最大 15 分かかる場合があります。リモートからシステムにログインしてシャットダウンプロセスを監視することもできます。

. ノードが VMware 仮想マシン上で実行されている場合、またはノードがアプライアンスノードである場合、問題 は shutdown コマンドを「 shutdown -h now 」と入力します
+
この手順は 'service servermanager stop コマンドの結果に関係なく実行します

+

NOTE: アプライアンス・ノードで shutdown -h now コマンドを実行した後問題 ' アプライアンスの電源を入れ直してノードを再起動する必要があります

+
アプライアンスの場合、このコマンドはコントローラをシャットダウンしますが、アプライアンスの電源はオンになったままです。次の手順を実行する必要があります。

. アプライアンスノードの電源をオフにする場合は、次の手順を実行します。
+
** SG100 または SG1000 サービスアプライアンスの場合
+
... アプライアンスの電源をオフにします。
... 青色の電源 LED が消灯するまで待ちます。


** SG6000 アプライアンスの場合
+
... ストレージコントローラの背面にある緑のキャッシュアクティブ LED が消灯するまで待ちます。
+
この LED は、キャッシュデータをドライブに書き込む必要があるときに点灯します。この LED が消灯するのを待ってから、電源をオフにする必要があります。

... アプライアンスの電源をオフにし、青色の電源 LED が消灯するまで待ちます。


** SG5700 アプライアンスの場合
+
... ストレージコントローラの背面にある緑のキャッシュアクティブ LED が消灯するまで待ちます。
+
この LED は、キャッシュデータをドライブに書き込む必要があるときに点灯します。この LED が消灯するのを待ってから、電源をオフにする必要があります。

... アプライアンスの電源をオフにし、すべての LED とデジタル表示ディスプレイの動作が停止するまで待ちます。






xref:../admin/index.adoc[StorageGRID の管理]
