---
permalink: maintain/stopping-services-and-shutting-down-grid-nodes.html 
sidebar: sidebar 
keywords: storagegrid, recover, stop services, shut down nodes, node shutdown 
summary: StorageGRID システムの電源をオフにするには、各グリッドノードで実行されているすべてのサービスを停止してから、すべての VMware 仮想マシン、コンテナエンジン、および StorageGRID アプライアンスをシャットダウンする必要があります。 
---
= サービスを停止し、グリッドノードをシャットダウンします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID システムの電源をオフにするには、各グリッドノードで実行されているすべてのサービスを停止してから、すべての VMware 仮想マシン、コンテナエンジン、および StorageGRID アプライアンスをシャットダウンする必要があります。

.このタスクについて
最初に管理ノードと API ゲートウェイノードのサービスを停止してから、ストレージノードのサービスを停止します。

この方法なら、プライマリ管理ノードを使用して他のグリッドノードのステータスをできるだけ長く監視できます。


NOTE: 単一のホストに複数のグリッドノードが含まれている場合は、そのホスト上のすべてのノードを停止するまで、ホストをシャットダウンしないでください。ホストにプライマリ管理ノードが含まれている場合は、そのホストを最後にシャットダウンします。


NOTE: 必要に応じて、を実行できます xref:linux-migrating-grid-node-to-new-host.adoc[Linux ホスト間でのノードの移行] グリッドの機能や可用性に影響を与えずにホストのメンテナンスを実行するため。

.手順
. すべてのクライアントアプリケーションからグリッドへのアクセスを停止します。
. [[log_in_on_gn] ][ 各ゲートウェイノードにログインします。
+
.. 次のコマンドを入力します。 ssh admin@_grid_node_name
.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
.. root に切り替えるには、次のコマンドを入力します
.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
+
root としてログインすると、プロンプトは「 $` 」から「 #」 に変わります。



. [[stop_all_services] ノード上で実行されているすべてのサービスを停止します :'service servermanager stop`
+
サービスのシャットダウンには最大 15 分かかる場合があります。リモートからシステムにログインしてシャットダウンプロセスを監視することもできます。



. 上記の 2 つの手順を繰り返して、すべてのストレージノード、アーカイブノード、非プライマリ管理ノードのサービスを停止します。
+
これらのノードのサービスは、どの順序で停止してもかまいません。

+

NOTE: アプライアンス・ストレージ・ノード上のサービスを停止するために 'service servermanager stop コマンドを実行した場合問題 は ' アプライアンスの電源を再投入してノードを再起動する必要があります

. プライマリ管理ノードについて、の手順を繰り返します <<log_in_to_gn,ノードにログインします>> および <<stop_all_services,ノードのすべてのサービスを停止しています>>。
. Linux ホストで実行されているノードの場合：
+
.. ホストオペレーティングシステムにログインします。
.. ノードを停止します StorageGRID node stop
.. ホストオペレーティングシステムをシャットダウンします。


. VMware 仮想マシンで実行されているノードおよびアプライアンスストレージノードの場合、問題 the shutdown コマンド：「 shutdown -h now
+
この手順は 'service servermanager stop コマンドの結果に関係なく実行します

+
アプライアンスの場合、このコマンドはコンピューティングコントローラをシャットダウンしますが、アプライアンスの電源はオンになったままです。次の手順を実行する必要があります。

. アプライアンスノードがある場合：
+
** SG100 または SG1000 サービスアプライアンスの場合
+
... アプライアンスの電源をオフにします。
... 青色の電源 LED が消灯するまで待ちます。


** SG6000 アプライアンスの場合
+
... ストレージコントローラの背面にある緑のキャッシュアクティブ LED が消灯するまで待ちます。
+
この LED は、キャッシュデータをドライブに書き込む必要があるときに点灯します。この LED が消灯するのを待ってから、電源をオフにする必要があります。

... アプライアンスの電源をオフにし、青色の電源 LED が消灯するまで待ちます。


** SG5700 アプライアンスの場合
+
... ストレージコントローラの背面にある緑のキャッシュアクティブ LED が消灯するまで待ちます。
+
この LED は、キャッシュデータをドライブに書き込む必要があるときに点灯します。この LED が消灯するのを待ってから、電源をオフにする必要があります。

... アプライアンスの電源をオフにし、すべての LED とデジタル表示ディスプレイの動作が停止するまで待ちます。




. 必要に応じて、コマンドシェルからログアウトします。「 exit
+
これで、 StorageGRID グリッドのシャットダウンは完了です。



.関連情報
xref:../sg100-1000/index.adoc[SG100 および SG1000 サービスアプライアンス]

xref:../sg6000/index.adoc[SG6000 ストレージアプライアンス]

xref:../sg5700/index.adoc[SG5700 ストレージアプライアンス]
