---
permalink: maintain/understanding-adc-service-quorum.html 
sidebar: sidebar 
keywords: storagegrid, recover, adc, adc quorum 
summary: 運用停止後に残る Administrative Domain Controller （ ADC ）サービスが少なすぎる場合は、データセンターサイトの一部のストレージノードの運用を停止できないことがあります。一部のストレージノードで使用されるこのサービスは、グリッドトポロジ情報を保持し、設定サービスをグリッドに提供します。StorageGRID システムでは、各サイトで ADC サービスのクォーラムが常に利用可能である必要があります。 
---
= ADC クォーラムを把握します
:icons: font
:imagesdir: ../media/


[role="lead"]
運用停止後に残る Administrative Domain Controller （ ADC ）サービスが少なすぎる場合は、データセンターサイトの一部のストレージノードの運用を停止できないことがあります。一部のストレージノードで使用されるこのサービスは、グリッドトポロジ情報を保持し、設定サービスをグリッドに提供します。StorageGRID システムでは、各サイトで ADC サービスのクォーラムが常に利用可能である必要があります。

ストレージノードを削除すること原因 で ADC クォーラムが満たされなくなる場合は、そのノードの運用を停止することはできません。運用停止時に ADC クォーラムを満たすには、各データセンターサイトで少なくとも 3 つのストレージノードに ADC サービスが必要です。ADC サービスがあるストレージノードが 1 つのデータセンターサイトに 3 つ以上ある場合は、運用停止後もそれらのノードの過半数が利用可能な状態である必要があります（（ 0.5`_ADC があるストレージノード） +1 ）。

たとえば、 ADC サービスがあるストレージノードが 1 つのデータセンターサイトに 6 つあり、そのうちの 3 つの運用を停止するとします。ADC クォーラムの要件により、次の 2 つの運用停止手順を実行する必要があります。

* 手順 の最初の運用停止では、 ADC サービスがある 4 つのストレージノードが利用可能な状態で残るようにする必要があります（（ 0.5x6 ） +1 ）。そのため、最初に運用停止できるのは、 2 つのストレージノードのみです。
* 2 回目の手順 運用停止では、 3 つ目のストレージノードを削除できます。 ADC クォーラムの要件により、利用可能な状態で残す必要のある ADC サービスが 3 つになったためです（（ 0.5x4 ） +1 ）。


ストレージノードの運用を停止する必要があるものの、 ADC クォーラムの要件が原因で運用停止できない場合は、拡張の際に新しいストレージノードを追加し、そのノードに ADC サービスを配置するよう指定する必要があります。そのあと、既存のストレージノードの運用を停止できます。

xref:../expand/index.adoc[グリッドを展開します]
