---
permalink: maintain/viewing-server-manager-status-and-version.html 
sidebar: sidebar 
keywords: storagegrid, recover, server manager, status, version 
summary: グリッドノードごとに、そのグリッドノード上で実行されている Server Manager の現在のステータスとバージョンを表示できます。そのグリッドノード上で実行されているすべてのサービスの現在のステータスも取得できます。 
---
= Server Manager のステータスとバージョンを表示します
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッドノードごとに、そのグリッドノード上で実行されている Server Manager の現在のステータスとバージョンを表示できます。そのグリッドノード上で実行されているすべてのサービスの現在のステータスも取得できます。

「 passwords.txt 」ファイルが必要です。

.手順
. グリッドノードにログインします。
+
.. 次のコマンドを入力します。 ssh admin@_grid_node_name
.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
.. root に切り替えるには、次のコマンドを入力します
.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。


+
root としてログインすると、プロンプトは「 $` 」から「 #」 に変わります。

. Grid ノード上で実行されている Server Manager の現在のステータスを表示します：「 * service servermanager status *
+
グリッドノード上で実行されている Server Manager の現在のステータスが（実行中かどうかに関係なく）報告されます。Server Manager のステータスが「 running 」の場合は、最後に起動されてから実行されていた時刻が表示されます。例：

+
[listing]
----
servermanager running for 1d, 13h, 0m, 30s
----
. グリッドノード上で実行されている Server Manager の現在のバージョンを表示します。「 * service servermanager version *
+
現在のバージョンが表示されます。例：

+
[listing]
----
11.1.0-20180425.1905.39c9493
----
. コマンドシェルからログアウトします :`*exit*`

