---
permalink: primer/configuring-network-settings.html 
sidebar: sidebar 
keywords: network settings, configure, configuring, configuration, domain name, virtual hosted-style requests 
summary: グリッドマネージャからさまざまなネットワーク設定を行い、 StorageGRID システムの動作を微調整できます。 
---
= ネットワークの設定を行います
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッドマネージャからさまざまなネットワーク設定を行い、 StorageGRID システムの動作を微調整できます。



== ドメイン名

S3 仮想ホスト形式の要求をサポートする場合は、 S3 クライアントの接続先となるエンドポイントのドメイン名のリストを設定する必要があります。たとえば、「 s3.example.com 」、「 s3.example.co.uk 」、「 s3-east.example.com 」などです。

設定済みのサーバ証明書とエンドポイントのドメイン名が一致している必要があります。



== ハイアベイラビリティグループ

ハイアベイラビリティ（ HA ）グループを使用して、 S3 / Swift クライアントに可用性の高いデータ接続を提供したり、 Grid Manager および Tenant Manager への可用性の高い接続を提供したりできます。

HA グループを作成するときは、 1 つ以上のノードのネットワークインターフェイスを選択します。各 HA グループは、選択したノードの共有サービスへのアクセスを提供します。

* ゲートウェイノード、管理ノード、またはその両方のインターフェイスを含む HA グループは、 S3 / Swift クライアントに可用性の高いデータ接続を提供します。
* 管理ノード上のインターフェイスを含む HA グループは、 Grid Manager および Tenant Manager への可用性の高い接続のみを提供します。


インターフェイスは、グリッドネットワーク（ eth0 ）、クライアントネットワーク（ eth2 ）、または VLAN ネットワークに属することができます。

各 HA グループに最大 10 個の仮想 IP （ VIP ）アドレスを割り当てることができます。1 つのインターフェイスをプライマリインターフェイスに指定し、他のインターフェイスに優先順位を付けます。プライマリインターフェイスは、障害が発生しないかぎり、アクティブインターフェイスです。アクティブインターフェイスに障害が発生すると、 VIP アドレスはプライオリティ順に最初のバックアップインターフェイスに移動します。そのインターフェイスに障害が発生すると、 VIP アドレスは次のバックアップインターフェイスに移動します。



== リンクコスト

サイト間のレイテンシに合わせてリンクコストを調整できます。データセンターサイトが複数ある場合は、要求されたサービスを提供するデータセンターサイトの優先順位がリンクコストによって決まります。



== ロードバランサエンドポイント

ロードバランサを使用して、 S3 / Swift クライアントからの取り込み / 読み出しワークロードを処理できます。ロードバランシングは、複数のストレージノードにワークロードと接続を分散することで、速度と接続容量を最大化します。

管理ノードとゲートウェイノードに含まれる StorageGRID ロードバランササービスを使用する場合は、 1 つ以上のロードバランサエンドポイントを設定する必要があります。各エンドポイントは、ストレージノードへの S3 および Swift 要求に使用するゲートウェイノードまたは管理ノードポートを定義します。



== トラフィック分類

トラフィック分類ポリシーを作成して、特定のバケット、テナント、クライアントサブネット、またはロードバランサエンドポイントに関連するトラフィックなど、さまざまなタイプのネットワークトラフィックを識別して処理できます。これらのポリシーは、トラフィックの制限と監視に役立ちます。



== VLAN インターフェイス

仮想 LAN （ VLAN ）インターフェイスを作成してトラフィックを分離し、パーティションを作成することで、セキュリティ、柔軟性、パフォーマンスを向上させることができます。各 VLAN インターフェイスは、管理ノードおよびゲートウェイノード上の 1 つ以上の親インターフェイスに関連付けられます。HA グループでは VLAN インターフェイスを使用し、ロードバランサエンドポイントではクライアントトラフィックと管理トラフィックをアプリケーションまたはテナントごとに分離できます。

たとえば、ネットワークで FabricPool トラフィックに VLAN 100 を使用し、アーカイブアプリケーションに VLAN 200 を使用しているとします。

.関連情報
* xref:../admin/index.adoc[StorageGRID の管理]
* xref:managing-tenants-and-client-connections.adoc[テナントとクライアント接続を管理する]

