---
permalink: primer/controlling-storagegrid-access.html 
sidebar: sidebar 
keywords: grid manager, administrator access, single sign on, sso, users, groups, client certificates, passwords, passphrase 
summary: StorageGRID にアクセスできるユーザ、およびユーザが実行できるタスクを制御するには、グループとユーザを作成またはインポートし、各グループに権限を割り当てます。必要に応じて、シングルサインオン \ （ SSO \ ）を有効にしたり、クライアント証明書を作成したり、グリッドのパスワードを変更したりできます。 
---
= StorageGRID アクセスを制御します
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID にアクセスできるユーザ、およびユーザが実行できるタスクを制御するには、グループとユーザを作成またはインポートし、各グループに権限を割り当てます。必要に応じて、シングルサインオン（ SSO ）を有効にしたり、クライアント証明書を作成したり、グリッドのパスワードを変更したりできます。



== Grid Manager へのアクセスを制御

Grid Manager およびグリッド管理 API にアクセスできるユーザを指定するには、アイデンティティフェデレーションサービスからグループとユーザをインポートするか、またはローカルのグループおよびユーザを設定します。

アイデンティティフェデレーションを使用すると、グループやユーザを迅速に設定できます。また、ユーザは使い慣れたクレデンシャルを使用して StorageGRID にサインインできます。Active Directory 、 OpenLDAP 、または Oracle Directory Server を使用する場合は、アイデンティティフェデレーションを設定できます。


NOTE: 別の LDAP v3 サービスを使用する場合は、テクニカルサポートにお問い合わせください。

各ユーザが実行できるタスクを指定するには、各グループに異なる権限を割り当てます。たとえば、あるグループのユーザには ILM ルールを管理する権限を、別のグループのユーザにはメンテナンスタスクを実行する権限を与えることができます。システムにアクセスするには、ユーザが少なくとも 1 つのグループに属している必要があります。

必要に応じて、グループを読み取り専用に設定することができます。読み取り専用グループのユーザは、設定と機能のみを表示できます。Grid Manager API や Grid 管理 API で変更や処理を行うことはできません。



== シングルサインオンを有効にします

StorageGRID システムでは、 Security Assertion Markup Language 2.0 （ SAML 2.0 ）標準を使用したシングルサインオン（ SSO ）がサポートされます。SSO が有効な場合は、 Grid Manager 、 Tenant Manager 、 Grid 管理 API 、またはテナント管理 API にアクセスするすべてのユーザを外部のアイデンティティプロバイダによって認証する必要があります。ローカルユーザは StorageGRID にサインインできません。

SSO が有効な場合にユーザが StorageGRID にサインインすると、組織の SSO ページにリダイレクトされてクレデンシャルが検証されます。1 つの管理ノードからサインアウトしたユーザは、自動的にすべての管理ノードからサインアウトされます。



== Grid のパスワードを変更

プロビジョニングパスフレーズは、多くのインストールやメンテナンスの手順、および StorageGRID リカバリパッケージのダウンロードで必要になります。また、 StorageGRID システムのグリッドトポロジ情報と暗号化キーのバックアップをダウンロードする際にもパスフレーズが必要です。このパスフレーズは必要に応じて変更できます。

.関連情報
* xref:../admin/index.adoc[StorageGRID の管理]
* xref:../tenant/index.adoc[テナントアカウントを使用する]

