---
permalink: primer/using-snmp-monitoring.html 
sidebar: sidebar 
keywords: snmp, simple network management protocol, agent, trap, inform, mib 
summary: 簡易ネットワーク管理プロトコル（ SNMP ）を使用して StorageGRID を監視する場合は、グリッドマネージャを使用して SNMP エージェントを設定できます。 
---
= SNMP による監視を使用する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
簡易ネットワーク管理プロトコル（ SNMP ）を使用して StorageGRID を監視する場合は、グリッドマネージャを使用して SNMP エージェントを設定できます。

各 StorageGRID ノードは、管理情報ベース（ MIB ）を提供する SNMP エージェントまたはデーモンを実行します。StorageGRID の MIB には、アラートおよびアラームのテーブルおよび通知定義が含まれています。各 StorageGRID ノードは MIB-II オブジェクトのサブセットもサポートしています。

最初は、すべてのノードで SNMP が無効になっています。SNMP エージェントを設定すると、すべての StorageGRID ノードに同じ設定が適用されます。

StorageGRID SNMP エージェントは、 3 つのバージョンの SNMP プロトコルをすべてサポートします。エージェントは、クエリに対して読み取り専用 MIB アクセスを提供し、次の 2 種類のイベントベース通知を管理システムに送信できます。

* * トラップ * は、管理システムによる確認応答を必要としない SNMP エージェントによって送信される通知です。トラップは、アラートがトリガーされているなど、 StorageGRID 内で何らかの問題が発生したことを管理システムに通知するために使用されます。トラップは、 SNMP の 3 つのバージョンすべてでサポートされています。
* * informs * はトラップに似ていますが、管理システムからの確認応答が必要です。SNMP エージェントが一定時間内に確認応答を受信しなかった場合、確認応答を受信するか、最大再試行値に達するまで、通知を再送信します。インフォームは SNMPv2c および SNMPv3 でサポートされます。


トラップ通知およびインフォーム通知は、次の場合に送信されます。

* デフォルトまたはカスタムのアラートはいずれかの重大度レベルでトリガーされます。アラートの SNMP 通知を停止するには、アラートのサイレンスを設定する必要があります。アラート通知は、優先送信者として設定された管理ノードから送信されます。
* 特定のアラーム（従来型システム）は、指定した重大度レベル以上でトリガーされます。
+

NOTE: SNMP 通知は、すべてのアラームまたはすべてのアラーム重大度について送信されるわけではありません。



* 関連情報 *

* xref:../monitor/index.adoc[監視とトラブルシューティング]

