---
permalink: sg5700/gathering-installation-information-sg5700.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, install, information, site, pre-install, preparing, prepare, preinstall, info, preparation 
summary: StorageGRID アプライアンスを設置および設定する際に、イーサネットスイッチポート、 IP アドレス、およびポートとネットワークのボンディングモードについて決定し、関連情報を収集する必要があります。 
---
= インストール情報の収集（ SG5700 ）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID アプライアンスを設置および設定する際に、イーサネットスイッチポート、 IP アドレス、およびポートとネットワークのボンディングモードについて決定し、関連情報を収集する必要があります。

次の表を使用して、アプライアンスに接続する各ネットワークの必要な情報を記録できます。これらの値は、ハードウェアの設置と設定に必要です。



== E2800 コントローラの SANtricity System Manager に接続するために必要な情報

E2800 コントローラは、 SANtricity System Manager で使用する管理ネットワークに接続する必要があります。

|===
| 必要な情報 | あなたの価値 


 a| 
管理ポート 1 に接続するイーサネットスイッチポート
 a| 



 a| 
管理ポート 1 の MAC アドレス（ポート P1 のラベルに記載）
 a| 



 a| 
DHCP によって管理ポート 1 に割り当てられた IP アドレス（電源投入後に使用可能な場合）

* 注： * E2800 コントローラに接続するネットワークに DHCP サーバがある場合、ネットワーク管理者は MAC アドレスを使用して DHCP サーバによって割り当てられた IP アドレスを特定できます。
 a| 



 a| 
速度と二重モード

* 注： SANtricity システムマネージャ管理ネットワークのイーサネットスイッチが自動ネゴシエーションに設定されていることを確認してください。
 a| 
次の値でなければなりません

* Autonegotiate （デフォルト）




 a| 
IP アドレスの形式
 a| 
1 つ選択してください：

* IPv4
* IPv6




 a| 
管理ネットワークでアプライアンスに使用する静的 IP アドレス
 a| 
IPv4 の場合：

* IPv4 アドレス：
* サブネットマスク：
* ゲートウェイ


IPv6 の場合：

* IPv6 アドレス：
* ルーティング可能な IP アドレス：
* E2800 コントローラのルータ IP アドレス：


|===


== E5700SG コントローラを管理ネットワークに接続するために必要な情報

StorageGRID の管理ネットワークは、システムの管理とメンテナンスに使用するオプションのネットワークです。アプライアンスは、 E5700SG コントローラの 1GbE 管理ポートを使用して管理ネットワークに接続しています。

|===
| 必要な情報 | あなたの価値 


 a| 
管理ネットワークが有効になりました
 a| 
1 つ選択してください：

* いいえ
* ○（デフォルト）




 a| 
ネットワークボンディングモード
 a| 
1 つ選択してください：

* 独立
* アクティブ / バックアップ




 a| 
ポート 1 のスイッチポートを指定します
 a| 



 a| 
ポート 2 のスイッチポート（アクティブ / バックアップネットワークボンディングモードのみ）
 a| 



 a| 
DHCP によって管理ポート 1 に割り当てられた IP アドレス（電源投入後に使用可能な場合）

* 注：管理ネットワークに DHCP サーバが含まれている場合、 E5700SG コントローラのブート後のデジタル表示ディスプレイに、 DHCP によって割り当てられた IP アドレスが表示されます。DHCP によって割り当てられた IP アドレスは、 MAC アドレスを使用して IP アドレスを調べる方法でも確認できます。
 a| 
* IPv4 アドレス（ CIDR ）：
* ゲートウェイ




 a| 
管理ネットワークでアプライアンスストレージノードに使用する静的 IP アドレス

* 注： * ネットワークにゲートウェイがない場合は、同じ静的 IPv4 アドレスをゲートウェイに指定してください。
 a| 
* IPv4 アドレス（ CIDR ）：
* ゲートウェイ




 a| 
管理ネットワークのサブネット（ CIDR ）
 a| 

|===


== E5700SG コントローラの 10 / 25GbE ポートの接続と設定に必要な情報

E5700SG コントローラの 4 つの 10 / 25GbE ポートは、 StorageGRID のグリッドネットワークおよびクライアントネットワークに接続しています。


NOTE: これらのポートのオプションの詳細については、 E5700SG コントローラでの 10 / 25GbE ポート接続を参照してください。

|===
| 必要な情報 | あなたの価値 


 a| 
リンク速度

* 注： 25GbE を選択した場合は、 SPF28 トランシーバを取り付ける必要があります。自動ネゴシエーションはサポートされないため、 25GbE 用のポートおよび接続されたスイッチも設定する必要があります。
 a| 
1 つ選択してください：

* 10GbE （デフォルト）
* 25GbE




 a| 
ポートボンディングモード
 a| 
1 つ選択してください：

* Fixed （デフォルト）
* アグリゲート




 a| 
ポート 1 のスイッチポート（クライアントネットワーク）
 a| 



 a| 
ポート 2 のスイッチポート（グリッドネットワーク）
 a| 



 a| 
ポート 3 のスイッチポート（クライアントネットワーク）
 a| 



 a| 
ポート 4 のスイッチポート（グリッドネットワーク）
 a| 

|===


== E5700SG コントローラをグリッドネットワークに接続するために必要な情報

StorageGRID のグリッドネットワークは、内部のすべての StorageGRID トラフィックに使用される必須のネットワークです。アプライアンスは、 E5700SG コントローラの 10 / 25GbE ポートを使用してグリッドネットワークに接続しています。


NOTE: これらのポートのオプションの詳細については、 E5700SG コントローラでの 10 / 25GbE ポート接続を参照してください。

|===
| 必要な情報 | あなたの価値 


 a| 
ネットワークボンディングモード
 a| 
1 つ選択してください：

* Active-Backup （デフォルト）
* LACP （ 802.3ad ）




 a| 
VLAN タギングが有効です
 a| 
1 つ選択してください：

* いいえ（デフォルト）
* はい。




 a| 
VLAN タグ（ VLAN タギングが有効な場合）
 a| 
0~4095 の値を入力してください：



 a| 
電源投入後に使用可能な場合、 DHCP によってグリッドネットワークに割り当てられた IP アドレス

* 注： * グリッドネットワークに DHCP サーバがある場合、 E5700SG コントローラのブート後のデジタル表示ディスプレイに、 DHCP によって割り当てられたグリッドネットワークの IP アドレスが表示されます。
 a| 
* IPv4 アドレス（ CIDR ）：
* ゲートウェイ




 a| 
グリッドネットワークでアプライアンスストレージノードに使用する静的 IP アドレス

* 注： * ネットワークにゲートウェイがない場合は、同じ静的 IPv4 アドレスをゲートウェイに指定してください。
 a| 
* IPv4 アドレス（ CIDR ）：
* ゲートウェイ




 a| 
グリッドネットワークのサブネット（ CIDR ）

* 注： * クライアントネットワークが有効になっていない場合、コントローラのデフォルトルートではここで指定したゲートウェイが使用されます。
 a| 

|===


== E5700SG コントローラをクライアントネットワークに接続するために必要な情報

StorageGRID のクライアントネットワークは、一般にグリッドへのクライアントプロトコルアクセスを可能にするために使用する、オプションのネットワークです。アプライアンスは、 E5700SG コントローラの 10 / 25GbE ポートを使用してクライアントネットワークに接続しています。


NOTE: これらのポートのオプションの詳細については、 E5700SG コントローラでの 10 / 25GbE ポート接続を参照してください。

|===
| 必要な情報 | あなたの価値 


 a| 
クライアントネットワークが有効になりました
 a| 
1 つ選択してください：

* いいえ（デフォルト）
* はい。




 a| 
ネットワークボンディングモード
 a| 
1 つ選択してください：

* Active-Backup （デフォルト）
* LACP （ 802.3ad ）




 a| 
VLAN タギングが有効です
 a| 
1 つ選択してください：

* いいえ（デフォルト）
* はい。




 a| 
VLAN タグ

（ VLAN タギングが有効な場合）
 a| 
0~4095 の値を入力してください：



 a| 
電源投入後に DHCP によってクライアントネットワークに割り当てられた IP アドレスがある場合は
 a| 
* IPv4 アドレス（ CIDR ）：
* ゲートウェイ




 a| 
クライアントネットワークでアプライアンスストレージノードに使用する静的 IP アドレス

* 注： * クライアントネットワークが有効になっている場合、コントローラのデフォルトルートではここで指定したゲートウェイが使用されます。
 a| 
* IPv4 アドレス（ CIDR ）：
* ゲートウェイ


|===
xref:reviewing-appliance-network-connections-sg5700.adoc[アプライアンスのネットワーク接続を確認する（ SG5700 ）]

xref:port-bond-modes-for-e5700sg-controller-ports.adoc[E5700SG コントローラポートのポートボンディングモード]

xref:configuring-hardware-sg5712-60.adoc[ハードウェアの構成（ SG5700 ）]
