---
permalink: sg5700/hardware-setup-appears-to-hang.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, troubleshoot, troubleshooting, hardware, setup, hang, hangs, fails, failure, stop, terminate, terminates, stuck 
summary: ハードウェア障害やケーブル接続エラーによって E5700SG コントローラのブート処理が完了しなかった場合、 StorageGRID アプライアンスインストーラを使用できないことがあります。 
---
= ハードウェアのセットアップがハングしたように見える（ SG5700 ）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ハードウェア障害やケーブル接続エラーによって E5700SG コントローラのブート処理が完了しなかった場合、 StorageGRID アプライアンスインストーラを使用できないことがあります。

.手順
. デジタル表示ディスプレイのコードを監視します。
+
電源投入時にハードウェアが初期化される際に、 2 つのデジタル表示ディスプレイに一連のコードが表示されます。ハードウェアが正常にブートされると、各コントローラのデジタル表示ディスプレイに異なるコードが表示されます。

. E5700SG コントローラのデジタル表示ディスプレイのコードを確認してください。
+

NOTE: インストールとプロビジョニングには時間がかかります。フェーズによっては、 StorageGRID アプライアンスインストーラの更新が数分間報告されないこともあります。

+
エラーが発生すると、デジタル表示ディスプレイに HE などの一連のコードが点滅します。

. これらのコードの意味については、次のリソースを参照してください。
+
|===
| コントローラ | 参照 


 a| 
E5700SG コントローラのものです
 a| 
** E5700SG コントローラのステータス・インジケータ
** "`he error:Error synchronizing with SANtricity OS Software`" （エラー： OS ソフトウェアとの同期エラー）




 a| 
E2800 コントローラ
 a| 
E5700 and E2800 System Monitoring Guide 』を参照してください

* 注： * E シリーズ E5700 コントローラに関するコードは、アプライアンスの E5700SG コントローラには適用されません。

|===
. この方法で問題 が解決しない場合は、テクニカルサポートにお問い合わせください。


.関連情報
xref:status-indicators-on-e5700sg-controller.adoc[E5700SG コントローラのステータスインジケータ]

xref:he-error-error-synchronizing-with-santricity-os-software.adoc[HE エラー： SANtricity OS ソフトウェアとの同期エラー]

http://mysupport.netapp.com/info/web/ECMP1658252.html["NetApp E シリーズシステムのドキュメントのサイト"^]
