---
permalink: sg5700/optional-changing-raid-mode-sg5760-only.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, raid, raid mode, change, changing, modify, DDP, ddp16, raid6 
summary: 60 本のドライブを搭載した SG5760 では、ストレージとリカバリの要件に対応するために、別の RAID モードに変更できます。モードを変更できるのは、 StorageGRID アプライアンスストレージノードを導入する前だけです。 
---
= オプション： RAID モードの変更（ SG5760 のみ）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
60 本のドライブを搭載した SG5760 では、ストレージとリカバリの要件に対応するために、別の RAID モードに変更できます。モードを変更できるのは、 StorageGRID アプライアンスストレージノードを導入する前だけです。

.必要なもの
* SG5760 を使用します。SG5712 がある場合は、 DDP モードを使用する必要があります。
* StorageGRID に接続できるクライアントを使用している必要があります。
* クライアントにはがあります xref:../admin/web-browser-requirements.adoc[サポートされている Web ブラウザ]。


.このタスクについて
SG5760 アプライアンスをストレージノードとして導入する前に、次のいずれかのボリューム構成オプションを選択できます。

* * DDP * ：データドライブ 8 本につきパリティドライブを 2 本使用します。すべてのアプライアンスに推奨されるデフォルトのモードです。RAID6 よりもシステムパフォーマンスに優れ、ドライブ障害が発生したあとのリビルド時間も短く、管理も簡単です。また、 60 ドライブアプライアンスをドロワー損失から保護します。
* * DDP16 * ：このモードはデータドライブ 16 本につきパリティドライブを 2 本使用するため、 DDP よりもストレージ効率が高くなります。RAID6 よりもシステムパフォーマンスに優れ、ドライブ障害が発生したあとのリビルド時間も短く、管理も簡単です。ストレージ効率は RAID6 と同等です。DDP16 モードを使用するには、構成にドライブが 20 本以上含まれている必要があります。ドロワー損失からの保護は提供しません。
* *RAID6 *: このモードは 16 台以上のデータドライブごとに 2 本のパリティドライブを使用します。RAID 6 モードを使用するには、構成にドライブが 20 本以上含まれている必要があります。DDP よりもアプライアンスのストレージ効率を上げることができますが、ほとんどの StorageGRID 環境では推奨されません。



IMPORTANT: ボリュームがすでに構成されている場合や StorageGRID が事前にインストールされている場合に RAID モードを変更すると、ボリュームが削除されて置き換えられます。対象となったボリュームのデータはすべて失われます。

.手順
. サービスラップトップを使用して Web ブラウザを開き、 StorageGRID アプライアンスインストーラ +`*https://_E5700SG_Controller_IP_:8443*` にアクセスします
+
ここで '_E5700SG コントローラの IP アドレスのいずれかは '_E5700SG コントローラの IP アドレスです

. 「 * アドバンスト * 」 > 「 * RAID モード * 」の順に選択します。
. [Configure RAID Mode*] ページで、 [Mode] ドロップダウンリストから目的の RAID モードを選択します。
. [ 保存（ Save ） ] をクリックします。


.関連情報
http://["NetApp E シリーズシステムのドキュメントのサイト"^]
