---
permalink: sg5700/troubleshooting-connection-issues.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, troubleshoot, troubleshooting, connection 
summary: StorageGRID アプライアンスのインストール時に接続の問題が発生した場合は、以下に記載する対処策を実施する必要があります。 
---
= 接続の問題のトラブルシューティング（ SG5700 ）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID アプライアンスのインストール時に接続の問題が発生した場合は、以下に記載する対処策を実施する必要があります。



== アプライアンスに接続できません

アプライアンスに接続できない場合は、ネットワーク問題 があるか、またはハードウェアの設置が正常に完了していない可能性があります。

.手順
. SANtricity システムマネージャに接続できない場合は、次の手順を実行します。
+
.. SANtricity システムマネージャの管理ネットワークにある E2800 コントローラの IP アドレスを使用してアプライアンスに ping を送信します。 +`*ping_E28P_Controller_IP_*`
.. ping からの応答がない場合は、正しい IP アドレスを使用していることを確認します。
+
E2800 コントローラの管理ポート 1 の IP アドレスを使用します。

.. IP アドレスが正しい場合は、アプライアンスのケーブル接続とネットワークのセットアップを確認します。
+
この手順で問題 が解決しない場合は、テクニカルサポートにお問い合わせください。

.. ping が成功した場合は、 Web ブラウザを開きます。
.. SANtricity System Manager:+`*https://_E2800_Controller_IP_*` の URL を入力します
+
SANtricity System Manager のログインページが表示されます。



. E5700SG コントローラに接続できない場合は、次の手順を実行してください。
+
.. E5700SG コントローラの IP アドレスを使用してアプライアンスに ping を実行してください。 +`*ping_E5700SG _Controller_IP_*`
.. ping からの応答がない場合は、正しい IP アドレスを使用していることを確認します。
+
グリッドネットワーク、管理ネットワーク、またはクライアントネットワークでのアプライアンスの IP アドレスを使用できます。

.. IP アドレスが正しい場合は、アプライアンスのケーブル接続、 SFP トランシーバ、およびネットワークのセットアップを確認します。
+
この手順で問題 が解決しない場合は、テクニカルサポートにお問い合わせください。

.. ping が成功した場合は、 Web ブラウザを開きます。
.. StorageGRID アプライアンスインストーラの URL を入力します :+`*https://_E5700SG_Controller_IP_:8443*`
+
ホームページが表示されます。




