---
permalink: expand/adding-grid-nodes-to-add-capabilities.html 
sidebar: sidebar 
keywords: grid nodes, expand, expansion, site, add 
summary: 既存のサイトに新しいグリッドノードを追加することで、 StorageGRID システムに冗長性を追加したり機能を追加したりできます。 
---
= システムの機能を追加するには、グリッドノードを追加してください
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
既存のサイトに新しいグリッドノードを追加することで、 StorageGRID システムに冗長性を追加したり機能を追加したりできます。

たとえば、ゲートウェイノードのハイアベイラビリティグループの作成をサポートするゲートウェイノードを追加したり、ローカルノードを使用した監視を許可する管理ノードをリモートサイトに追加したりできます。

次のタイプの 1 つ以上のノードを、 1 回の拡張処理で 1 つ以上の既存のサイトに追加することができます。

* 非プライマリ管理ノード
* ストレージノード
* ゲートウェイノード
* アーカイブノード


グリッドノードを追加する場合は、次の制限事項に注意してください。

* プライマリ管理ノードは最初のインストール時に導入されます。プライマリ管理ノードを拡張時に追加することはできません。
* 同じ拡張内でストレージノードとその他のタイプのノードを追加できます。
* ストレージノードを追加するときは、新しいノードの数と場所を慎重に計画する必要があります。を参照してください xref:../expand/guidelines-for-adding-object-capacity.adoc[オブジェクト容量を追加する場合のガイドラインを次に示します]。
* アーカイブノードを追加する場合は、 Tivoli Storage Manager （ TSM ）ミドルウェア経由のテープのみが各アーカイブノードでサポートされます。
* [ 信頼されていないクライアントネットワーク ] ページで [ 新しいノードのクライアントネットワークのデフォルト * ] オプションが [ 信頼されていない * ] に設定されている場合、クライアントネットワークを使用して拡張ノードに接続するクライアントアプリケーションは、ロードバランサエンドポイントポート（ * 構成 * > * ネットワーク * > 信頼されていないクライアントネットワーク * ）を使用して接続する必要の手順を参照してください xref:../admin/index.adoc[StorageGRID の管理] 新しいノードの設定を変更し、ロードバランサエンドポイントを設定する。

