---
permalink: expand/adding-new-site.html 
sidebar: sidebar 
keywords: expand, expansion, new site, add site, guidelines 
summary: 新しいサイトを追加して StorageGRID システムを拡張することができます。 
---
= 新しいサイトを追加します
:icons: font
:imagesdir: ../media/


[role="lead"]
新しいサイトを追加して StorageGRID システムを拡張することができます。



== サイトの追加に関するガイドライン

サイトを追加する前に、次の要件および制限事項を確認してください。

* 拡張処理で追加できるサイトは 1 つだけです。
* 同じ拡張の一環として既存のサイトにグリッドノードを追加することはできません。
* すべてのサイトに少なくとも 3 つのストレージノードが含まれている必要があります。
* 新しいサイトを追加しても、格納できるオブジェクトの数は自動的に増えません。グリッドの合計オブジェクト容量は、使用可能なストレージの量、 ILM ポリシー、および各サイトのメタデータ容量によって異なります。
* 新しいサイトのサイジングを行うときは、十分なメタデータ容量が確保されている必要があります。
+
StorageGRID は、すべてのオブジェクトメタデータのコピーをすべてのサイトで保持します。新しいサイトを追加するときは、既存のオブジェクトメタデータ用の十分なメタデータ容量と、拡張に対応できる十分なメタデータ容量が追加されている必要があります。

+
詳細については、次を参照してください。

+
** xref:../admin/managing-object-metadata-storage.adoc[オブジェクトメタデータストレージを管理する]
** xref:../monitor/monitoring-storage-capacity.adoc#monitor-object-metadata-capacity-for-each-storage-node[各ストレージノードのオブジェクトメタデータ容量を監視します]


* サイト間の使用可能なネットワーク帯域幅およびネットワークレイテンシのレベルを考慮する必要があります。すべてのオブジェクトが取り込まれたサイトにのみ格納されている場合でも、メタデータの更新はサイト間で継続的にレプリケートされます。
* StorageGRID システムは拡張時も動作し続けるため、拡張手順 を開始する前に ILM ルールを確認し、拡張手順 が完了するまではオブジェクトコピーが新しいサイトに格納されないようにする必要があります。
+
たとえば、拡張を開始する前に、デフォルトのストレージプール（すべてのストレージノード）を使用するルールがないかを確認します。その場合は、既存のストレージノードを含む新しいストレージプールを作成し、新しいストレージプールを使用するように ILM ルールを更新する必要があります。そうしないと、そのサイトの最初のノードがアクティブになるとすぐに新しいサイトにオブジェクトがコピーされます。

+
新しいサイトを追加する際の ILM の変更の詳細については、の手順で ILM ポリシーの変更例を参照してください xref:../ilm/index.adoc[ILM によるオブジェクトの管理]。


