---
permalink: expand/adding-storage-capacity-for-replicated-objects.html 
sidebar: sidebar 
keywords: replication, replicated, copies, capacity, storage nodes, expand, expansion 
summary: 環境の情報ライフサイクル管理ポリシーにオブジェクトのレプリケートコピーを作成するルールが含まれている場合は、追加するストレージの量と新しいストレージボリュームまたはストレージノードの追加先を検討する必要があります。 
---
= レプリケートオブジェクトのストレージ容量を追加します
:icons: font
:imagesdir: ../media/


[role="lead"]
環境の情報ライフサイクル管理（ ILM ）ポリシーに、オブジェクトのレプリケートコピーを作成するルールが含まれている場合は、追加するストレージの量と、新しいストレージボリュームまたはストレージノードの追加先を検討する必要があります。

ストレージを追加する場所については、レプリケートコピーを作成する ILM ルールを確認してください。ILM ルールで複数のオブジェクトコピーが作成される場合は、オブジェクトコピーが作成されるそれぞれの場所にストレージを追加することを検討してください。単純な例として、 2 サイトグリッドがあり、各サイトにオブジェクトコピーを 1 つ作成する ILM ルールがある場合は、グリッドの全体的なオブジェクト容量を増やすために各サイトにストレージを追加する必要があります。の手順を参照してください xref:../ilm/index.adoc[情報ライフサイクル管理によるオブジェクトの管理]。

パフォーマンス上の理由から、サイト間でストレージ容量と処理能力のバランスを維持することをお勧めします。そのため、この例では、各サイトに同じ数のストレージノードを追加するか、各サイトにストレージボリュームを追加する必要があります。

より複雑な ILM ポリシーで、バケット名などの条件に基づいてオブジェクトを別々の場所に配置するルールや、オブジェクトの場所を一定期間変更するルールが含まれている場合は、拡張に必要なストレージについての分析も似ていますが、より複雑です。

全体的なストレージ容量がどれだけ早く消費されるかを記録しておくと、拡張に必要なストレージ容量や、追加のストレージ容量が必要になる時期を把握するのに役立ちます。グリッドマネージャを使用して、の手順に従ってストレージ容量を監視し、グラフ化することができます xref:../monitor/index.adoc[StorageGRID の監視とトラブルシューティング]。

拡張をいつ実施するかを計画するときは、追加のストレージを調達して設置するのにどれくらいの時間がかかるかを考慮する必要があります。
