---
permalink: expand/copying-audit-logs.html 
sidebar: sidebar 
keywords: copy audit log, Admin Node expansion, 
summary: 拡張手順 を使用して新しい管理ノードを追加した場合、その AMS サービスでログに記録されるのは、システムへの追加後に発生したイベントと処理のみになります。必要に応じて、先にインストールされていた管理ノードから新しい拡張管理ノードに監査ログをコピーして、残りの StorageGRID システムと同期されるようにすることができます。 
---
= 監査ログをコピーする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
拡張手順 を使用して新しい管理ノードを追加した場合、その AMS サービスでログに記録されるのは、システムへの追加後に発生したイベントと処理のみになります。必要に応じて、先にインストールされていた管理ノードから新しい拡張管理ノードに監査ログをコピーして、残りの StorageGRID システムと同期されるようにすることができます。

.必要なもの
* 管理ノードを追加する拡張手順が完了している必要があります。
* 「 passwords.txt 」ファイルがあります。


.このタスクについて
新しい管理ノードで監査メッセージの履歴を確認できるようにするには、既存の管理ノードから拡張管理ノードに監査ログファイルを手動でコピーする必要があります。

[NOTE]
====
デフォルトでは、監査情報は管理ノードの監査ログに送信されます。次のいずれかに該当する場合は、これらの手順をスキップしてかまいません。

* 外部 syslog サーバを設定し、管理ノードではなく syslog サーバに監査ログを送信するようになりました。
* 監査メッセージを生成したローカルノードにのみ保存するように明示的に指定します。


を参照してください xref:../monitor/configure-audit-messages.adoc[監査メッセージとログの送信先を設定します] を参照してください。

====
.手順
. プライマリ管理ノードにログインします。
+
.. 次のコマンドを入力します。「 ssh_admin@_primary_Admin_Node_IP_`
.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
.. root に切り替えるには、次のコマンドを入力します
.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
+
root としてログインすると、プロンプトは「 $` 」から「 #」 に変わります。



. AMS サービスを停止して、新しいファイル「 service AMS stop 」が作成されないようにします
. 「 audit.log 」ファイルの名前を変更して、コピー先の拡張管理ノードでファイルが上書きされないようにします。
+
cd /var/local/audit/export `+`ls -l`+mv audit.log _new_name_txt`

. すべての監査ログファイルを拡張管理ノードにコピーします。
+
`scp-p *_IP_address_:/var/local/audit/export`

. 「 /root/.ssh/id_rsa 」のパスフレーズを入力するように求められた場合は、「 passwords.txt 」ファイルにリストされているプライマリ管理ノードの SSH アクセスパスワードを入力します。
. 元の「 audit.log 」ファイルを復元します。
+
mv _new_name_.txt audit.log

. AMS サービスを開始します。
+
'service AMS start

. サーバからログアウトします。
+
「 exit

. 拡張管理ノードにログインします。
+
.. 次のコマンドを入力します。 ssh admin@_expansion_Admin_Node_IP_`
.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
.. root に切り替えるには、次のコマンドを入力します
.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
+
root としてログインすると、プロンプトは「 $` 」から「 #」 に変わります。



. 監査ログファイルのユーザとグループの設定を更新します。
+
'cd /var/local/audit/export'+'chown ams-user:bycast*

. サーバからログアウトします。
+
「 exit


