---
permalink: expand/copying-admin-node-database.html 
sidebar: sidebar 
keywords: copy Admin Node database, alert history, Admin Node expansion 
summary: 拡張手順 を使用して管理ノードを追加する場合は、必要に応じてプライマリ管理ノードから新しい管理ノードにデータベースをコピーできます。データベースをコピーすると、属性、アラート、およびアラートに関する履歴情報を保持できます。 
---
= 管理ノードデータベースをコピーする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
拡張手順 を使用して管理ノードを追加する場合は、必要に応じてプライマリ管理ノードから新しい管理ノードにデータベースをコピーできます。データベースをコピーすると、属性、アラート、およびアラートに関する履歴情報を保持できます。

.必要なもの
* 管理ノードを追加する拡張手順が完了している必要があります。
* 「 passwords.txt 」ファイルがあります。
* プロビジョニングパスフレーズを用意します。


.このタスクについて
拡張管理ノードには、 StorageGRID ソフトウェアのアクティブ化プロセスによって NMS サービス用の空のデータベースが作成されます。拡張管理ノードで NMS サービスが開始されると、システムに現在追加されているか以降に追加されたサーバとサービスに関する情報が記録されます。この管理ノードデータベースには次の情報が含まれています。

* アラートの履歴
* アラームの履歴
* ヒストリカル属性データ。 * サポート * > * ツール * > * グリッドトポロジ * ページで使用できるチャートおよびテキストレポートで使用されます


ノード間で管理ノードデータベースの整合性を確保するには、プライマリ管理ノードから拡張管理ノードにデータベースをコピーします。


NOTE: プライマリ管理ノード（ __ ソース管理ノード __ ）から拡張管理ノードへのデータベースのコピーは、完了までに数時間かかる場合があります。この間は Grid Manager にアクセスできません。

次の手順に従って、プライマリ管理ノードと拡張管理ノードの両方で MI サービスと管理 API サービスを停止してからデータベースをコピーします。

.手順
. プライマリ管理ノードで次の手順を実行します。
+
.. 管理ノードにログインします。
+
... 次のコマンドを入力します。 ssh admin@_grid_node_name
... 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
... root に切り替えるには、次のコマンドを入力します
... 「 passwords.txt 」ファイルに記載されたパスワードを入力します。


.. 「 recover-access-points 」コマンドを実行します
.. プロビジョニングパスフレーズを入力します。
.. MI サービスを停止します : "service mi stop
.. Management Application Program Interface (mgmt-api) サービス「 service mgmt-api stop 」を停止します


. 拡張管理ノードで次の手順を実行します。
+
.. 拡張管理ノードにログインします。
+
... 次のコマンドを入力します。 ssh admin@_grid_node_name
... 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
... root に切り替えるには、次のコマンドを入力します
... 「 passwords.txt 」ファイルに記載されたパスワードを入力します。


.. MI サービスを停止します : "service mi stop
.. mgmt-api サービス「 service mgmt-api stop 」を停止します
.. SSH エージェントに SSH 秘密鍵を追加します。「 ssh -add 」と入力します
.. 「 passwords.txt 」ファイルに記載された SSH アクセスパスワードを入力します。
.. ソース管理ノードから拡張管理ノードにデータベースをコピーします :/usr/local/mi /bin/mi-clone-db.sh _Source_Admin_Node_IP_`
.. プロンプトが表示されたら、拡張管理ノードで MI データベースを上書きすることを確定します。
+
データベースとその履歴データが拡張管理ノードにコピーされます。コピー処理が完了すると、拡張管理ノードがスクリプトによって起動されます。

.. 他のサーバにパスワードなしでアクセスする必要がなくなった場合は、 SSH エージェントから秘密鍵を削除します。「 ssh -add-D`` 」と入力します


. プライマリ管理ノード上のサービスを再起動します :service servermanager start

