---
permalink: expand/gather-required-materials.html 
sidebar: sidebar 
keywords: expand, expansion, planning, storagrid files 
summary: 拡張処理を実行する前に、機器を揃え、新しいハードウェアとネットワークの設置と設定を行ってください。 
---
= 必要なデータや機器を揃えます
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
拡張処理を実行する前に、機器を揃え、新しいハードウェアとネットワークの設置と設定を行ってください。

[cols="1a,2a"]
|===
| 項目 | 注： 


 a| 
StorageGRID インストールアーカイブ
 a| 
新しいグリッドノードや新しいサイトを追加する場合は、 StorageGRID インストールアーカイブをダウンロードして展開する必要があります。グリッドで現在実行されているバージョンと同じバージョンを使用する必要があります。

詳細については、の手順を参照してください ,StorageGRID インストールファイルのダウンロードと展開。

* 注：既存のストレージノードに新しいストレージボリュームを追加する場合や新しい StorageGRID アプライアンスをインストールする場合、ファイルをダウンロードする必要はありません。



 a| 
サービスラップトップ
 a| 
サービスラップトップには次のものがあります。

* ネットワークポート
* SSH クライアント（ PuTTY など）
* xref:../admin/web-browser-requirements.adoc[サポートされている Web ブラウザ]




 a| 
「 passwords.txt 」ファイル
 a| 
コマンドラインでグリッドノードにアクセスするために必要なパスワードが含まれています。リカバリパッケージに含まれています。



 a| 
プロビジョニングパスフレーズ
 a| 
このパスフレーズは、 StorageGRID システムが最初にインストールされるときに作成されて文書化されます。プロビジョニングパスフレーズは 'passwords.txt ファイルには含まれていません



 a| 
StorageGRID のドキュメント
 a| 
* xref:../admin/index.adoc[StorageGRID の管理]
* xref:../release-notes/index.adoc[リリースノート]
* 使用しているプラットフォームに対応したインストール手順
+
** xref:../rhel/index.adoc[Red Hat Enterprise Linux または CentOS をインストールします]
** xref:../ubuntu/index.adoc[Ubuntu または Debian をインストールします]
** xref:../vmware/index.adoc[VMware をインストールする]






 a| 
ご使用のプラットフォームの最新ドキュメント
 a| 
サポートされるバージョンについては、を参照してください https://mysupport.netapp.com/matrix["互換性マトリックス"^]。

|===


== StorageGRID インストールファイルをダウンロードして展開します

新しいグリッドノードや新しいサイトを追加する前に、適切な StorageGRID インストールアーカイブをダウンロードし、ファイルを展開する必要があります。

拡張処理は、グリッドで現在実行されているバージョンの StorageGRID を使用して実行する必要があります。

.手順
. ネットアップの StorageGRID ダウンロードページにアクセスします。
+
https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["ネットアップのダウンロード： StorageGRID"^]

. グリッドで現在実行されている StorageGRID のバージョンを選択します。
. ネットアップアカウントのユーザ名とパスワードを使用してサインインします。
. エンドユーザライセンス契約を読み、チェックボックスをオンにして、「 * 同意して続行 * 」を選択します。
. ダウンロード・ページの ［ StorageGRID のインストール ］ 列で ' 使用するプラットフォームに対応する tgz または .zip ファイルを選択します
+
インストールアーカイブファイルに表示されるバージョンは、現在インストールされているソフトウェアのバージョンと一致している必要があります。

+
サービスラップトップで Windows を実行している場合は '.zip ファイルを使用します

+
[cols="1a,2a"]
|===
| プラットフォーム | インストールアーカイブ 


 a| 
Red Hat Enterprise Linux または CentOS
| 「 StorageGRIDWebscale--_version__ RPM --_uniqueID_.zip 」「 StorageGRID Webscale --_version_-RPM -- _uniqueID_tgz 」 


 a| 
Ubuntu 、 Debian 、またはアプライアンス
| `StorageGRIDWebscale--_version_-bDEB -- _uniqueID_.zip `StorageGRID -_version_-bDEB -- _uniqueID_.tgz ` 


 a| 
VMware
| 「 StorageGRIDWebscale--_version__ vmware --uniqueID_.zip 」「 StorageGRID Webscale --_version_ -vmware -- _uniqueID_tgz 」 


 a| 
OpenStack / その他のハイパーバイザー
 a| 
OpenStack の既存の環境を拡張する場合は、上記のサポートされている Linux ディストリビューションのいずれかを実行する仮想マシンを導入し、 Linux に関する適切な手順に従う必要があります。

|===
. アーカイブファイルをダウンロードして展開します。
. プラットフォームに応じた手順に従って、プラットフォーム、計画したグリッドトポロジ、および StorageGRID システムの拡張方法に基づいて、必要なファイルを選択します。
+
各プラットフォームの手順に記載されているパスは、アーカイブファイルによってインストールされた最上位ディレクトリに対する相対パスです。

. Red Hat Enterprise Linux または CentOS のシステムを拡張する場合は、該当するファイルを選択します。


[cols="1a,1a"]
|===
| パスとファイル名 | 説明 


| ./rps/README  a| 
StorageGRID ダウンロードファイルに含まれているすべてのファイルについて説明するテキストファイル。



| ./rps/NLF000000.txt  a| 
製品サポートのない無償ライセンス。



| ./rps/StorageGRID-Webscale-Images-_version_-SHA.rpm  a| 
RHEL ホストまたは CentOS ホストに StorageGRID ノードイメージをインストールするための RPM パッケージ。



| ./rps/StorageGRID-Webscale-Service-_version_-SHA.rpm  a| 
RHEL ホストまたは CentOS ホストに StorageGRID ホストサービスをインストールするための RPM パッケージ。



| 導入スクリプトツール | 説明 


| ./rps/configure-storagegrid.py  a| 
StorageGRID システムの設定を自動化するための Python スクリプト。



| ./rps/configure-sga.py  a| 
StorageGRID アプライアンスの設定を自動化するための Python スクリプト。



| ./rpms/configure -storagegrid-sample.json  a| 
configure -storagegrid.py スクリプトで使用される設定ファイルの例。



| ./rps/storagegrid-ssoauth.py  a| 
シングルサインオンが有効な場合にグリッド管理 API にサインインするために使用できる Python スクリプトの例。



| ./rpms/configure -storagegridBlank.json （ StorageGRID を構成する  a| 
configure -storagegrid.py スクリプトで使用する空の構成ファイル。



| ./rps/extra/Ansible と入力します  a| 
StorageGRID コンテナ導入用の RHEL ホストまたは CentOS ホストを設定するためのサンプルの Ansible のロールとプレイブック。必要に応じて、ロールまたはプレイブックをカスタマイズできます。



| ./rpms/extra/api-schemas  a| 
StorageGRID の API スキーマ

* 注 * ：アップグレードを実行する前に、これらのスキーマを使用して、 StorageGRID 管理 API を使用するように記述したコードが、アップグレード互換性テスト用の非本番環境の StorageGRID 環境を持たない場合、新しい StorageGRID リリースと互換性があることを確認できます。

|===
. Ubuntu または Debian システムを拡張する場合は、適切なファイルを選択します。


[cols="1a,1a"]
|===
| パスとファイル名 | 説明 


| ./debs/README  a| 
StorageGRID ダウンロードファイルに含まれているすべてのファイルについて説明するテキストファイル。



| ./debs/NLF000000.txt  a| 
テスト環境およびコンセプトの実証環境に使用できる、非本番環境のネットアップライセンスファイル。



| ./debs/storagegrid-webscale-images-version-SHA.deb  a| 
Ubuntu ホストまたは Debian ホストに StorageGRID ノードイメージをインストールするための DEB パッケージ。



| ./debs/storagegrid-webscale-images-version-SHA.deb.md5  a| 
ファイル「 /debs/storagegrid-webscale-images-version-SHA.deb` 」の MD5 チェックサム。



| ./debs/storagegrid-webscale-service-version-SHA.deb  a| 
Ubuntu ホストまたは Debian ホストに StorageGRID ホストサービスをインストールするための DEB パッケージ。



| 導入スクリプトツール | 説明 


| ./debs/configure-storagegrid.py  a| 
StorageGRID システムの設定を自動化するための Python スクリプト。



| ./debs/configure-sga.py  a| 
StorageGRID アプライアンスの設定を自動化するための Python スクリプト。



| ./debs/storagegrid-ssoauth.py  a| 
シングルサインオンが有効な場合にグリッド管理 API にサインインするために使用できる Python スクリプトの例。



| ./debs/configure -storagegrid-sample.json という形式で指定します  a| 
configure -storagegrid.py スクリプトで使用される設定ファイルの例。



| ./debs/configure -storagegrid-bank.json という形式で実行します  a| 
configure -storagegrid.py スクリプトで使用する空の構成ファイル。



| ./debs/extras /Ansible を実行します  a| 
StorageGRID コンテナ導入用の Ubuntu ホストまたは Debian ホストを設定するためのサンプルの Ansible のロールとプレイブック。必要に応じて、ロールまたはプレイブックをカスタマイズできます。



| ./debs/extra/api-schemas  a| 
StorageGRID の API スキーマ

* 注 * ：アップグレードを実行する前に、これらのスキーマを使用して、 StorageGRID 管理 API を使用するように記述したコードが、アップグレード互換性テスト用の非本番環境の StorageGRID 環境を持たない場合、新しい StorageGRID リリースと互換性があることを確認できます。

|===
. VMware システムを拡張する場合は、適切なファイルを選択します。


[cols="1a,1a"]
|===
| パスとファイル名 | 説明 


| ./vsphere/README （ ./vsphere/README  a| 
StorageGRID ダウンロードファイルに含まれているすべてのファイルについて説明するテキストファイル。



| ./vsphere/NLF000000.txt にアクセスします  a| 
製品サポートのない無償ライセンス。



| ./vsphere/NetApp-SG-version-sha.vmdk  a| 
グリッドノード仮想マシンを作成するためのテンプレートとして使用される仮想マシンディスクファイル。



| ./vsphere/vsphere-primary-admin.ovf ./vsphere-primary-admin.mf  a| 
プライマリ管理ノードを導入するための Open Virtualization Format テンプレートファイル (`.ovf ') およびマニフェストファイル (`.mf ') 。



| ./vsphere/vsphere-non-primary-admin.ovf ./vsphere/vsphere-non-primary-admin.mf  a| 
非プライマリ管理ノードを導入するためのテンプレートファイル (`.ovf ') およびマニフェストファイル (`.mf ') 。



| ./vsphere/vsphere-archive.ovf ./vsphere-archive.mf  a| 
アーカイブノードを導入するためのテンプレートファイル (`.ovf ') およびマニフェストファイル (`.mf ')



| ./vsphere/vsphere-gateway.ovf ./vsphere/vsphere-gateway.mf  a| 
ゲートウェイノードを導入するためのテンプレートファイル (`.ovf ') およびマニフェストファイル (`.mf ') 。



| ./vsphere/vsphere-storage.OVF ./vsphere/vsphere-storage.mf  a| 
仮想マシンベースのストレージノードを導入するためのテンプレートファイル (`.ovf ') およびマニフェストファイル (`.mf ') 。



| 導入スクリプトツール | 説明 


| ./vsphere/deploy-vsphere-ovftool.sh にアクセスします  a| 
仮想グリッドノードの導入を自動化するための Bash シェルスクリプト。



| ./vsphere/deploy-vsphere-ovftool-sample.ini にアクセスします  a| 
「 deploy-vsphere-ovftool.sh 」スクリプトで使用する構成ファイルの例。



| ./vsphere/configure-storagegrid.py にアクセスします  a| 
StorageGRID システムの設定を自動化するための Python スクリプト。



| ./vsphere/configure-sga.py にアクセスします  a| 
StorageGRID アプライアンスの設定を自動化するための Python スクリプト。



| ./vsphere/storagegrid-ssoauth.py にアクセスします  a| 
シングルサインオンが有効な場合にグリッド管理 API にサインインするために使用できる Python スクリプトの例。



| ./vsphere/configure -storagegrid-sample.json という形式で実行します  a| 
configure -storagegrid.py スクリプトで使用される設定ファイルの例。



| ./vsphere/configure -storagegrid-bank.json （ページ構成  a| 
configure -storagegrid.py スクリプトで使用する空の構成ファイル。



| ./vsphere/extra/api-schemas  a| 
StorageGRID の API スキーマ

* 注 * ：アップグレードを実行する前に、これらのスキーマを使用して、 StorageGRID 管理 API を使用するように記述したコードが、アップグレード互換性テスト用の非本番環境の StorageGRID 環境を持たない場合、新しい StorageGRID リリースと互換性があることを確認できます。

|===
. StorageGRID アプライアンスベースのシステムを拡張する場合は、該当するファイルを選択してください。


[cols="1a,1a"]
|===
| パスとファイル名 | 説明 


| ./debs/storagegrid-webscale-images-version-SHA.deb  a| 
アプライアンスに StorageGRID ノードイメージをインストールするための DEB パッケージ。



| ./debs/storagegrid-webscale-images-version-SHA.deb.md5  a| 
DEB インストールパッケージのチェックサム。アップロード後にパッケージに変更が加えられていないことを確認するために StorageGRID アプライアンスインストーラで使用されます。

|===

NOTE: アプライアンスのインストールの場合、これらのファイルが必要になるのは、ネットワークトラフィックを回避する必要がある場合だけです。アプライアンスは、プライマリ管理ノードから必要なファイルをダウンロードできます。



== ハードウェアとネットワークの確認

StorageGRID システムの拡張を開始する前に、次の点を確認してください。

* 新しいグリッドノードまたは新しいサイトをサポートするために必要なハードウェアを設置して設定しておきます。
* すべての新しいノードに、既存および新規のすべてのノードへの双方向通信パスがある（グリッドネットワークの要件）。
* プライマリ管理ノードは、 StorageGRID システムをホストするすべての拡張サーバと通信できます。
* 新しいノードのいずれかでグリッドネットワークの IP アドレスが使用されていないサブネットにある場合は、すでに完了している xref:updating-subnets-for-grid-network.adoc[新しいサブネットが追加されました] をクリックしてください。それ以外の場合は、拡張をキャンセルし、新しいサブネットを追加してから、手順 をもう一度開始する必要があります。
* グリッドノード間または StorageGRID サイト間のグリッドネットワークでネットワークアドレス変換（ NAT ）を使用しない。グリッドネットワークにプライベート IPv4 アドレスを使用する場合は、使用するアドレスに各サイトのすべてのグリッドノードから直接ルーティングできる必要があります。NAT を使用してパブリックネットワークセグメント全体にグリッドネットワークをブリッジする方法は、グリッド内のすべてのノードに対して透過的なトンネリングアプリケーションを使用する場合、つまりグリッドノードがパブリック IP アドレスを認識する必要がない場合にのみサポートされます。
+
この NAT の制限は、グリッドノードとグリッドネットワークに固有のものです。必要に応じて、ゲートウェイノードにパブリック IP アドレスを指定する場合など、外部クライアントとグリッドノードの間で NAT を使用できます。


