---
permalink: expand/rebalancing-erasure-coded-data-after-adding-storage-nodes.html 
sidebar: sidebar 
keywords: erasure coding, EC, rebalancing, site rebalance procedure 
summary: 場合によっては、新しいストレージノードを追加したあとにイレイジャーコーディングデータのリバランシングが必要になることがあります。 
---
= ストレージノードの追加後にイレイジャーコーディングデータをリバランシングします
:icons: font
:imagesdir: ../media/


[role="lead"]
場合によっては、新しいストレージノードを追加したあとにイレイジャーコーディングデータのリバランシングが必要になることがあります。

.必要なもの
* 新しいストレージノードを追加する拡張手順が完了している。
* を確認しておきます xref:considerations-for-rebalancing-erasure-coded-data.adoc[イレイジャーコーディングデータのリバランシングに関する考慮事項]。
+

IMPORTANT: この手順 は、サイトの 1 つ以上のストレージノードに対して * Low Object Storage * アラートがトリガーされ、推奨数の新しいストレージノードを追加できなかった場合にのみ実行してください。

* レプリケートされたオブジェクトデータがこの手順 によって移動されることはなく、イレイジャーコーディングデータの移動先を特定する際に、 EC 手順 が各ストレージノードでレプリケートされたデータの使用量を考慮しないことを理解しておきます。
* 「 passwords.txt 」ファイルがあります。


EC のリバランシング手順 が実行されている場合、 ILM 処理と S3 および Swift クライアント処理のパフォーマンスに影響する可能性があります。そのため、この手順 は限られた場合にのみ実行してください。


NOTE: EC のリバランシングによって、手順 が一時的に大量のストレージをリザーブします。ストレージアラートがトリガーされる場合がありますが、リバランシングが完了すると解決します。予約に十分なストレージがない場合、 EC のリバランシング手順 は失敗します。ストレージ予約は、手順 が失敗したか成功したかに関係なく、 EC のリバランシング手順 が完了したときに解放されます。

[NOTE]
====
オブジェクト（またはオブジェクトパーツ）をアップロードするために S3 および Swift API 処理を実行すると、 EC のリバランシング中に 24 時間以上かかる場合に手順 のリバランシングが失敗することがあります。該当する ILM ルールの取り込みに Strict または Balanced 配置が使用されている場合、長時間の PUT 処理は失敗します。次のエラーが報告されます。

500 Internal Server Error( 内部サーバエラー

====
.手順
. [[review_object_storage] ] リバランシングするサイトの現在のオブジェクトストレージの詳細を確認します。
+
.. [* nodes （ノード） ] を選択します
.. サイトで最初のストレージノードを選択します。
.. [ * ストレージ * ] タブを選択します。
.. Storage Used - Object Data チャートにカーソルを合わせて、ストレージノード上のレプリケートデータとイレイジャーコーディングデータの現在の量を表示します。
.. 同じ手順を繰り返して、サイトの他のストレージノードを表示します。


. プライマリ管理ノードにログインします。
+
.. 次のコマンドを入力します。 ssh admin@_primary_Admin_Node_IP_`
.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
.. root に切り替えるには、次のコマンドを入力します
.. 「 passwords.txt 」ファイルに記載されたパスワードを入力します。
+
root としてログインすると、プロンプトは「 $` 」から「 #」 に変わります。



. 次のコマンドを入力します。
+
rebalance -datastart --site "_site -name_

+
「 _site name _ 」には、新しいストレージ・ノードを追加した最初のサイトを指定します。「 site-name 」は引用符で囲みます。

+
EC Rebalance 手順 が開始され、ジョブ ID が返されます。

. ジョブ ID をコピーします。
. EC Rebalance 手順 のステータスを監視します。
+
** 単一の EC Rebalance 手順 のステータスを表示するには、次の手順を実行します
+
rebalance -datastatus -- job-id_job-id_`

+
`_job-id_` には、手順 の起動時に返された ID を指定します。

** 現在の EC Rebalance 手順 と、以前に完了した手順のステータスを表示するには、次の手順を実行します。
+
「 rebalance - data status 」

+
[NOTE]
====
rebalance -dataコマンド のヘルプを表示するには、次の手順を実行します。

「 rebalance -data--help 」

====
** 現在のジョブの完了までの推定時間と完了率を表示するには、 *support*>*Tools*>*Metrics* を選択します。次に、 Grafana のセクションで * EC Overview * を選択します。グリッド EC ジョブの完了予想時間 * ダッシュボードと * グリッド EC ジョブの完了率 * ダッシュボードを確認します。


. 返されたステータスに基づいて、追加の手順を実行します。
+
** ステータスが「進行中」の場合、 EC の再バランス操作はまだ実行中です。手順 は、完了するまで定期的に監視する必要があります。
** ステータスが [Failure] の場合は、を実行します <<rebalance_fail,失敗の手順>>。
** ステータスが「 Success 」の場合は、を実行します <<rebalance_succeed,成功のステップ>>。


. EC Rebalance 手順 によって大量の負荷が生成されている（取り込み処理に影響があるなど）場合は、手順 を一時停止します。
+
rebalance -datapause -- job-id_job-id_`

. EC のリバランシング手順 を終了する必要がある場合（ StorageGRID ソフトウェアのアップグレードを実行できるようにする場合など）は、次のように入力します。
+
rebalance -dataterminate -- job-id_job-id_`

+

NOTE: EC のリバランシング手順 を終了すると、移動済みのデータフラグメントは新しい場所に残ります。データは元の場所に戻されません。

. [[rebalance _fail]] EC rebalance 手順 のステータスが「 Failure 」の場合は、次の手順を実行します。
+
.. サイトのすべてのストレージノードがグリッドに接続されていることを確認します。
.. これらのストレージノードに影響している可能性があるアラートがないかどうかを確認し、解決してください。
+
特定のアラートの詳細については、監視とトラブルシューティングの手順を参照してください。

.. EC rebalance 手順 ： +`rebalance -datastart – job-id_job-id_` を再起動します
.. EC Rebalance 手順 のステータスがまだ Failure の場合は、テクニカル・サポートに連絡してください。


. [[rebalance _cuccess] 手順 のステータスが「 Success 」の場合は、オプションで <<review_object_storage,オブジェクトストレージを確認する>> をクリックすると、サイトの最新の詳細が表示されます。
+
イレイジャーコーディングされたデータをサイトのストレージノード間でより均等に配置します。

. 複数のサイトでイレイジャーコーディングを使用している場合は、影響を受ける他のすべてのサイトに対してこの手順 を実行します。

