---
permalink: ilm/advantages-disadvantages-of-ingest-options.html 
sidebar: sidebar 
keywords: ingest options, balance ingest, strict ingest, dual commit ingest 
summary: 取り込み時にデータを保護するための 3 つのオプション（ Balanced 、 Strict 、 Dual commit ）のそれぞれのメリットとデメリットを理解すると、 ILM ルールに選択するオプションを決定する際に役立ちます。 
---
= データ保護オプションのメリット、デメリット、および制限事項
:icons: font
:imagesdir: ../media/


[role="lead"]
取り込み時にデータを保護するための 3 つのオプション（ Balanced 、 Strict 、 Dual commit ）のそれぞれのメリットとデメリットを理解することは、 ILM ルールに選択するオプションを決定する際に役立ちます。



== Balanced オプションと Strict オプションのメリット

取り込み時に中間コピーを作成する Dual commit と比較すると、 2 つの同期配置オプションには次のメリットがあります。

* * Better データ セキュリティ * ：オブジェクトデータは、 ILM ルールの配置手順に従ってただちに保護されます。配置手順は、複数の格納場所の障害など、さまざまな障害状況からオブジェクトを保護するように設定できます。Dual commit で保護できるのは、単一のローカルコピーの損失のみです。
* * グリッド処理の効率化 * ：各オブジェクトは、取り込み時に 1 回だけ処理されます。StorageGRID システムで中間コピーを追跡または削除する必要がないため、処理の負荷が軽減され、消費されるデータベーススペースも少なくてすみます。
* * （ Balanced ） Recommended * ： Balanced オプションは、最適な ILM 効率を実現します。Strict 取り込み動作が必要であるか、グリッドが Dual commit に使用するためのすべての条件を満たしていないかぎり、 Balanced オプションを使用することを推奨します。
* * （ Strict ）オブジェクトの場所が明らか * ： Strict オプションは、 ILM ルールの配置手順に従ってオブジェクトがただちに格納されることを保証します。




== Balanced オプションと Strict オプションのデメリット

Dual commit と比較すると、 Balanced オプションと Strict オプションにはいくつかのデメリットがあります。

* * クライアントの取り込み時間が長くなる * ：クライアントの取り込みレイテンシが長くなる可能性があります。Balanced オプションと Strict オプションを使用する場合、すべてのイレイジャーコーディングフラグメントまたはレプリケートコピーが作成されて格納されるまで、「 ingest successful 」メッセージはクライアントに返されません。しかし、ほとんどの場合、オブジェクトデータは最終的な配置までの時間をはるかに短縮できます。
* * （ Strict ）取り込みエラーの増加 * ： Strict オプションでは、 StorageGRID が ILM ルールに指定されたすべてのコピーをただちに作成できないと取り込みが失敗します。必要なストレージの場所が一時的にオフラインになっている場合や、ネットワークでサイト間のオブジェクトコピーが原因 で遅延している場合には、取り込みに失敗する可能性が高くなります。
* * （ Strict ） S3 マルチパートアップロードでは、状況によっては想定どおりに配置されない可能性がある * ： Strict では、オブジェクトが ILM ルールの指定どおりに配置されるか、あるいは取り込みが失敗するかのどちらかの結果が想定されます。ところが、 S3 マルチパートアップロードの場合、オブジェクトの各パートの取り込み時に ILM が評価され、マルチパートアップロードが完了した時点でオブジェクト全体に対して ILM が評価されます。そのため、次の状況では想定どおりに配置されないことがあります。
+
** * S3 マルチパートアップロードの実行中に ILM が変更された場合 * ：各パートはその取り込み時にアクティブなルールに従って配置されるため、マルチパートアップロードが完了した時点でオブジェクトの一部のパートが現在の ILM 要件を満たしていない可能性があります。この場合、オブジェクトの取り込みは失敗しません。代わりに、正しく配置されていないパートは ILM ルールによる再評価の対象としてキューに登録され、あとで正しい場所に移動されます。
** * ILM ルールがサイズでフィルタリングする場合 * ：パーツに対して ILM を評価する際、 StorageGRID はオブジェクトのサイズではなくパーツのサイズでフィルタリングします。つまり、オブジェクト全体としては ILM 要件を満たしていない場所にオブジェクトのパーツが格納される可能性があります。たとえば、 10GB 以上のオブジェクトをすべて DC1 に格納し、それより小さいオブジェクトをすべて DC2 に格納するルールの場合、 10 パートからなるマルチパートアップロードの 1GB の各パートは取り込み時に DC2 に格納されます。オブジェクトに対して ILM が評価されると、オブジェクトのすべてのパートが DC1 に移動されます。


* * （ Strict ）オブジェクトタグまたはメタデータが更新され、新たに必要となった配置を実行できなくても取り込みが失敗しない * ： Strict では、オブジェクトが ILM ルールの指定どおりに配置されるか、あるいは取り込みが失敗するかのどちらかの結果が想定されます。ただし、グリッドにすでに格納されているオブジェクトのメタデータまたはタグを更新しても、オブジェクトは再取り込みされません。そのため、更新によってトリガーされるオブジェクト配置の変更は、すぐには実行されず、通常のバックグラウンド ILM プロセスで ILM が再評価されると、配置変更が行われます。必要な配置変更を行えない場合（新たに必要となった場所が使用できない場合など）は、更新されたオブジェクトは配置変更が可能になるまで現在の場所に残ります。




== Balanced オプションと Strict オプションを使用したオブジェクトの配置に関する制限事項

次のいずれかの配置手順を含む ILM ルールには、 Balanced オプションまたは Strict オプションを使用できません。

* クラウドストレージプールへの配置： 0 日目
* アーカイブノードへの配置： 0 日目
* ルールの参照時間としてユーザ定義の作成時間が設定されている場合のクラウドストレージプールまたはアーカイブノードでの配置


StorageGRID ではクラウドストレージプールまたはアーカイブノードにコピーを同期的に作成できず、ユーザ定義の作成時間が現在の状態に解決される場合があるため、このような制限があります。



== ILM ルールと整合性制御がデータ保護に与える影響

ILM ルールと選択した整合性制御は、どちらもオブジェクトの保護方法に影響します。これらの設定は対話的に操作できます。

たとえば、 ILM ルールに対して選択した取り込み動作はオブジェクトコピーの初期配置に影響し、オブジェクトの格納時に使用される整合性制御はオブジェクトメタデータの初期配置に影響します。StorageGRID では、クライアント要求に対応するためにオブジェクトのメタデータとそのデータの両方にアクセスする必要があるため、整合性レベルと取り込み動作に一致する保護レベルを選択することで、より適切な初期データ保護と予測可能なシステム応答を実現できます。

StorageGRID で使用できる整合性制御の概要を以下に示します。

* * all * ：すべてのノードが即座にオブジェクトメタデータを受け取り、受け取れない場合は要求が失敗します。
* * strong-global * ：オブジェクトのメタデータがすべてのサイトにただちに分散されます。すべてのサイトのすべてのクライアント要求について、リードアフターライト整合性が保証されます。
* * strong-site * ：オブジェクトのメタデータがただちにサイトの他のノードに分散されます。1 つのサイト内のすべてのクライアント要求について、リードアフターライト整合性が保証されます。
* * read-after-new-write * ：新規オブジェクトについてはリードアフターライト整合性が提供され、オブジェクトの更新については結果整合性が提供されます。高可用性が確保され、データ保護が保証されます。
* * available * （ HEAD オペレーションについては結果整合性）：「 read-after-new-write 」整合性レベルと動作は同じですが、 HEAD オペレーションについては結果整合性のみを提供します。



NOTE: 整合性レベルを選択する前に、の手順に記載されている整合性制御の完全な概要 をお読みください xref:../s3/consistency-controls.adoc[S3] または xref:../swift/storagegrid-swift-rest-api-operations.adoc[Swift] クライアントアプリケーション：デフォルト値を変更する前に、利点と制限事項を理解しておく必要があります。



== 整合性制御と ILM ルールの連動の例

次の ILM ルールと次の整合性レベル設定の 2 サイトグリッドがあるとします。

* * ILM ルール * ：ローカルサイトとリモートサイトに 1 つずつ、 2 つのオブジェクトコピーを作成します。Strict 取り込み動作が選択されています。
* * 整合性レベル *:"Strong-GLOBAL" ( オブジェクトメタデータはすべてのサイトにただちに分散されます )


クライアントがオブジェクトをグリッドに格納すると、 StorageGRID は両方のオブジェクトをコピーし、両方のサイトにメタデータを分散してからクライアントに成功を返します。

オブジェクトは、取り込みが成功したことを示すメッセージが表示された時点で損失から完全に保護されます。たとえば、取り込み直後にローカルサイトが失われた場合、オブジェクトデータとオブジェクトメタデータの両方のコピーがリモートサイトに残っています。オブジェクトを完全に読み出し可能にしている。

代わりに同じ ILM ルールと「 strong-site 」整合性レベルを使用する場合は、オブジェクトデータがリモートサイトにレプリケートされたあとで、オブジェクトメタデータがそこに分散される前に、クライアントに成功メッセージが送信される可能性があります。この場合、オブジェクトメタデータの保護レベルがオブジェクトデータの保護レベルと一致しません。取り込み直後にローカルサイトが失われると、オブジェクトメタデータが失われます。オブジェクトを読み出すことができません。

整合性レベルと ILM ルールの間の関係は複雑になる可能性があります。サポートが必要な場合は、ネットアップにお問い合わせください。

.関連情報
* xref:example-5-ilm-rules-and-policy-for-strict-ingest-behavior.adoc[例 5 ：取り込み動作が Strict の場合の ILM ルールとポリシー]

