---
permalink: ilm/considerations-for-cloud-storage-pools.html 
sidebar: sidebar 
keywords: what is a cloud storage pool, considerations for a cloud storage pool 
summary: クラウドストレージプールを使用して StorageGRID システムからオブジェクトを移動する場合は、クラウドストレージプールの設定と使用に関する考慮事項を確認しておく必要があります。 
---
= クラウドストレージプールに関する考慮事項
:icons: font
:imagesdir: ../media/


[role="lead"]
クラウドストレージプールを使用して StorageGRID システムからオブジェクトを移動する場合は、クラウドストレージプールの設定と使用に関する考慮事項を確認しておく必要があります。



== 一般的な考慮事項

* 一般に、 Amazon S3 Glacier や Azure BLOB ストレージなどのクラウドアーカイブストレージにはオブジェクトデータを低コストで格納することができます。ただし、クラウドアーカイブストレージからデータを読み出すコストは比較的高くなります。全体的なコストを最小限に抑えるには、クラウドストレージプール内のオブジェクトにアクセスするタイミングと頻度を考慮する必要があります。クラウドストレージプールの使用は、アクセス頻度の低いコンテンツにのみ推奨されます。
* Swift クライアントによって取り込まれたオブジェクトには、クラウドストレージプールを使用しないでください。Swift では POST Object restore 要求がサポートされないため、 StorageGRID は S3 Glacier ストレージや Azure BLOB ストレージのアーカイブ層に移行された Swift オブジェクトを読み出せません。これらのオブジェクトを読み出す Swift GET object 要求は失敗します（ 403 Forbidden ）。
* クラウドストレージプールターゲットからオブジェクトを読み出すレイテンシが増加しているため、 FabricPool でクラウドストレージプールを使用することはサポートされていません。




== クラウドストレージプールの作成に必要な情報

クラウドストレージプールを作成する前に、クラウドストレージプールに使用する外部の S3 バケットまたは Azure BLOB ストレージコンテナを作成する必要があります。その後、 StorageGRID でクラウドストレージプールを作成する際に、次の情報を指定する必要があります。

* プロバイダタイプ： Amazon S3 または Azure BLOB ストレージ。
* Amazon S3 を選択した場合は、クラウドストレージプールが AWS Secret Region （ * CAP （ C2S Access Portal ） * ）で使用するかどうかを示します。
* バケットまたはコンテナの正確な名前。
* バケットまたはコンテナへのアクセスに必要なサービスエンドポイント。
* バケットまたはコンテナへのアクセスに必要な認証。
+
** * S3 * ：必要に応じて、アクセスキー ID とシークレットアクセスキー。
** *C2S * ： CAP サーバから一時的なクレデンシャルを取得するための完全な URL 。サーバ CA 証明書、クライアント証明書、クライアント証明書の秘密鍵、および秘密鍵が暗号化されている場合は復号化するためのパスフレーズ。
** *Azure BLOB ストレージ * ：アカウント名とアカウントキー。これらのクレデンシャルにはコンテナに対する完全な権限が必要です。


* 必要に応じて、バケットまたはコンテナへの TLS 接続を検証するカスタム CA 証明書を指定します。




== クラウドストレージプールに使用するポートに関する考慮事項

指定したクラウドストレージプールとの間でオブジェクトを ILM ルールによって移動できるようにするには、システムのストレージノードが含まれるネットワークを設定する必要があります。次のポートがクラウドストレージプールと通信できることを確認してください。

デフォルトでは、クラウドストレージプールは次のポートを使用します。

* *80* ：エンドポイント URI が http で始まる場合
* *442* ： https で始まるエンドポイント URI の場合


クラウドストレージプールを作成または編集するときに、別のポートを指定できます。

非透過型プロキシサーバを使用する場合は、も使用する必要があります xref:../admin/configuring-storage-proxy-settings.adoc[ストレージプロキシを設定する] インターネット上のエンドポイントなどの外部エンドポイントへのメッセージの送信を許可します。



== コストに関する考慮事項

クラウドストレージプールを使用してクラウド内のストレージにアクセスするには、クラウドへのネットワーク接続が必要です。クラウドストレージプールを使用して StorageGRID とクラウドの間で移動するデータ量の予測に基づいて、クラウドへのアクセスに使用するネットワークインフラのコストを考慮し、適切にプロビジョニングする必要があります。

StorageGRID が外部のクラウドストレージプールエンドポイントに接続すると、さまざまな要求を実行して接続を監視し、必要な処理を確実に実行できるようにします。これらの要求には追加コストが伴いますが、クラウドストレージプールの監視にかかるコストは、 S3 または Azure にオブジェクトを格納する場合の全体的なコストのごくわずかです。

外部クラウドストレージプールのエンドポイントから StorageGRID にオブジェクトを戻す必要がある場合、より大きなコストが発生する可能性があります。次のいずれかの場合、オブジェクトが StorageGRID に戻ることがあります。

* オブジェクトの唯一のコピーがクラウドストレージプールにあり、オブジェクトを StorageGRID に格納することにした場合。その場合は、 ILM ルールとポリシーを再設定するだけです。ILM 評価が実行されると、 StorageGRID はクラウドストレージプールからオブジェクトを読み出す要求を複数実行します。次に、 StorageGRID は指定された数のレプリケートコピーまたはイレイジャーコーディングコピーをローカルに作成します。オブジェクトが StorageGRID に戻ると、クラウドストレージプール内のコピーは削除されます。
* ストレージノードの障害が原因でオブジェクトが失われた場合。オブジェクトのコピーがクラウドストレージプールにしか残っていない場合、 StorageGRID はオブジェクトを一時的にリストアして、リカバリされたストレージノードに新しいコピーを作成します。



IMPORTANT: オブジェクトがクラウドストレージプールから StorageGRID に戻ると、 StorageGRID は各オブジェクトに対してクラウドストレージプールエンドポイントに対して複数の要求を実行します。大量のオブジェクトを移動する場合は、事前にテクニカルサポートに問い合わせて、期間と関連コストの見積もりを依頼してください。



== S3 ：クラウドストレージプールバケットに必要な権限

クラウドストレージプールに使用される外部の S3 バケットポリシーで、バケットへのオブジェクトの移動、オブジェクトのステータスの取得、必要に応じた Glacier ストレージからのオブジェクトのリストアなどを行うために、 StorageGRID 権限を付与する必要があります。理想的には、 StorageGRID にはバケット（「 s3 ： * 」）へのフルコントロールアクセス権が必要ですが、フルコントロールアクセスができない場合は、バケットポリシーで StorageGRID に次の S3 権限を付与する必要があります。

* `s3: AbortMultipartUpload`
* `s3: DeleteObject`
* `s3: GetObject`
* `s3:ListBucket`
* s3 ： ListBucketMultipartUploads
* `s3:ListMultipartUploadParts`
* `s3:PutObject`
* `s3: RestoreObject`




== S3 ：外部バケットのライフサイクルに関する考慮事項

StorageGRID とクラウドストレージプールに指定された外部の S3 バケット間のオブジェクトの移動は、 StorageGRID の ILM ルールとアクティブな ILM ポリシーによって制御されます。一方、クラウドストレージプールに指定された外部の S3 バケットから Amazon S3 Glacier または S3 Glacier Deep Archive （あるいは Glacier ストレージクラスを実装するストレージ解決策 ）へのオブジェクトの移行は、そのバケットのライフサイクル設定によって制御されます。

クラウドストレージプールからオブジェクトを移行する場合は、外部の S3 バケットに適切なライフサイクル設定を作成する必要があります。また、 Glacier ストレージクラスを実装し、かつ S3 POST Object restore API をサポートするストレージ解決策 を使用する必要があります。

たとえば、 StorageGRID からクラウドストレージプールに移動されたすべてのオブジェクトをすぐに Amazon S3 Glacier ストレージに移行するとします。この場合、単一のアクション（ * Transition * ）を指定する外部の S3 バケットでライフサイクル設定を次のように作成します。

[listing]
----
<LifecycleConfiguration>
  <Rule>
    <ID>Transition Rule</ID>
    <Filter>
       <Prefix></Prefix>
    </Filter>
    <Status>Enabled</Status>
    <Transition>
      <Days>0</Days>
      <StorageClass>GLACIER</StorageClass>
    </Transition>
  </Rule>
</LifecycleConfiguration>
----
このルールは、すべてのバケットオブジェクトを作成された日（ StorageGRID からクラウドストレージプールに移動された日）に Amazon S3 Glacier に移行します。


IMPORTANT: 外部バケットのライフサイクルを設定する場合、 * Expiration * アクションを使用してオブジェクトの期限を定義しないでください。Expiration アクション期限切れのオブジェクトを削除するために、外部ストレージシステムを原因 します。期限切れのオブジェクトにあとで StorageGRID からアクセスしようとしても、削除されたオブジェクトは見つかりません。

クラウドストレージプール内のオブジェクトを（ Amazon S3 Glacier ではなく） S3 Glacier Deep Archive に移行する場合は、バケットライフサイクルに「 <StorageClass> DEEP_ARCHIVE </StorageClass> 」と指定します。ただし、「 Expedited 」階層を使用して S3 Glacier Deep Archive からオブジェクトをリストアすることはできません。



== Azure ：アクセス層に関する考慮事項

Azure ストレージアカウントを設定する場合は、デフォルトのアクセス層をホットまたはクールに設定できます。クラウドストレージプールで使用するストレージアカウントを作成する場合は、デフォルト階層としてホット階層を使用する必要があります。StorageGRID はオブジェクトをクラウドストレージプールに移動するとすぐに階層をアーカイブに設定しますが、デフォルト設定をホットにしておくことで、最低期間の 30 日前にクール階層から削除されたオブジェクトに対する早期削除料金が発生しません。



== Azure ：ライフサイクル管理はサポートされていません

クラウドストレージプールで使用するコンテナには Azure BLOB ストレージのライフサイクル管理を使用しないでください。ライフサイクル処理が Cloud Storage Pool の処理の妨げになることがあります。

.関連情報
* xref:creating-cloud-storage-pool.adoc[クラウドストレージプールを作成]
* xref:s3-authentication-details-for-cloud-storage-pool.adoc[S3 ：クラウドストレージプールの認証情報を指定します]
* xref:c2s-s3-authentication-details-for-cloud-storage-pool.adoc[C2S S3 ：クラウドストレージプールの認証情報を指定します]
* xref:azure-authentication-details-for-cloud-storage-pool.adoc[Azure ：クラウドストレージプールの認証情報を指定します]

