---
permalink: ilm/creating-ilm-policy.html 
sidebar: sidebar 
keywords: create ILM policy, information lifecycle policy considerations 
summary: ILM ポリシーを作成するには、最初に ILM ルールを選択して配置します。次に、以前に取り込まれたオブジェクトに対してドラフトポリシーをシミュレートし、その動作を確認します。ドラフトポリシーが意図したとおりに機能していることを確認したら、そのポリシーをアクティブ化してアクティブポリシーを作成できます。 
---
= Create ILM policy ：概要
:icons: font
:imagesdir: ../media/


[role="lead"]
ILM ポリシーを作成するには、最初に ILM ルールを選択して配置します。次に、以前に取り込まれたオブジェクトに対してドラフトポリシーをシミュレートし、その動作を確認します。ドラフトポリシーが意図したとおりに機能していることを確認したら、そのポリシーをアクティブ化してアクティブポリシーを作成できます。


CAUTION: ILM ポリシーが正しく設定されていないと、リカバリできないデータ損失が発生する可能性があります。ILM ポリシーをアクティブ化する前に、 ILM ポリシーおよびその ILM ルールを慎重に確認し、次に ILM ポリシーをシミュレートします。ILM ポリシーが意図したとおりに機能することを必ず確認してください。



== ILM ポリシーの作成に関する考慮事項

* システムに組み込まれているポリシーである Baseline 2 Copies Policy をテストシステムでのみ使用します。このポリシーの Make 2 Copies ルールは、すべてのサイトを含む All Storage Nodes ストレージプールを使用します。StorageGRID システムに複数のサイトがある場合は、 1 つのオブジェクトのコピーが同じサイトに 2 つ配置される可能性があります。
* 新しいポリシーを設計する際には、グリッドに取り込まれる可能性のあるさまざまなタイプのオブジェクトをすべて考慮してください。それらのオブジェクトに一致し、必要に応じて配置するルールがポリシーに含まれていることを確認してください。
* ILM ポリシーはできるだけシンプルにします。これにより、時間が経って StorageGRID システムに変更が加えられ、オブジェクトデータが意図したとおりに保護されないという危険な状況を回避できます。
* ポリシー内のルールの順序が正しいことを確認してください。ポリシーをアクティブ化すると、新規および既存のオブジェクトがリスト内の順にルールによって評価されます。たとえば、ポリシー内の最初のルールがオブジェクトに一致する場合、そのルールは他のルールによって評価されません。
* すべての ILM ポリシーの最後のルールはデフォルトの ILM ルールであり、フィルタを使用することはできません。オブジェクトが別のルールに一致していない場合は、デフォルトルールによって、そのオブジェクトの配置場所と保持期間が制御されます。
* 新しいポリシーをアクティブ化する前に、ポリシーによって既存のオブジェクトの配置が変更されていないかどうかを確認します。既存のオブジェクトの場所を変更すると、新しい配置が評価されて実装される際に一時的なリソースの問題が発生する可能性があります。

