---
permalink: ilm/editing-storage-pool.html 
sidebar: sidebar 
keywords: edit storage pool 
summary: ストレージプールを編集して、名前を変更したり、サイトやストレージグレードを更新したりできます。 
---
= ストレージプールを編集します
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージプールを編集して、名前を変更したり、サイトやストレージグレードを更新したりできます。

.必要なもの
* を使用して Grid Manager にサインインします xref:../admin/web-browser-requirements.adoc[サポートされている Web ブラウザ]。
* 特定のアクセス権限が必要です。
* ストレージプールの作成に関するガイドラインを確認しておく必要があります。
* アクティブな ILM ポリシーのルールで使用されているストレージプールを編集する場合は、変更がオブジェクトデータの配置にどのように影響するかを検討しておく必要があります。


アクティブな ILM ポリシーで使用されているストレージプールに新しいストレージグレードを追加する場合は、新しいストレージグレードのストレージノードが自動的には使用されないことに注意してください。StorageGRID で新しいストレージグレードを強制的に使用するには、編集したストレージプールを保存したあとに新しい ILM ポリシーをアクティブ化する必要があります。

.手順
. ILM * > * Storage pools * を選択します
+
Storage Pools （ストレージプール）ページが表示されます。

. 編集するストレージプールのラジオボタンを選択します。
+
All Storage Nodes ストレージプールは編集できません。

. 「 * 編集 * 」を選択します。
. 必要に応じて、ストレージプール名を変更します。
. 必要に応じて、他のサイトとストレージグレードを選択します。
+

NOTE: ストレージプール原因 がイレイジャーコーディングプロファイルで使用されている場合や、イレイジャーコーディングスキームを無効に変更する場合、サイトまたはストレージグレードを変更することはできません。たとえば、イレイジャーコーディングプロファイルで使用されているストレージプールにサイトが 1 つしかないストレージグレードが含まれている場合、サイトが 2 つのストレージグレードを使用することはできません。これは、変更によってイレイジャーコーディングスキームが無効になるためです。

. [ 保存（ Save ） ] を選択します。


アクティブな ILM ポリシーで使用されているストレージプールに新しいストレージグレードを追加した場合は、新しい ILM ポリシーをアクティブ化して StorageGRID に新しいストレージグレードを強制的に使用させます。たとえば、既存の ILM ポリシーのクローンを作成し、そのクローンをアクティブ化します。
