---
permalink: ilm/guidelines-for-creating-storage-pools.html 
sidebar: sidebar 
keywords: storage pool guidelines 
summary: ストレージプールを設定して使用する場合は、次のガイドラインに従ってください。 
---
= ストレージプールの作成に関するガイドラインを次に示します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージプールを設定して使用する場合は、次のガイドラインに従ってください。



== すべてのストレージプールのガイドライン

* StorageGRID には、デフォルトのストレージプールとすべてのストレージノードが含まれ、デフォルトサイト、すべてのサイト、およびデフォルトのストレージグレードであるすべてのストレージノードが使用されます。新しいデータセンターサイトを追加するたびに、 All Storage Nodes ストレージプールが自動的に更新されます。
+

NOTE: All Storage Nodes ストレージプールまたはすべてのサイトサイトサイトは、拡張に追加する新しいサイトが自動的に更新されて追加されるため、推奨されません。これは動作ではない可能性があります。All Storage Nodes ストレージプールまたはデフォルトサイトを使用する前に、レプリケートコピーとイレイジャーコーディングコピーに関するガイドラインをよく確認してください。

* ストレージプールの設定は可能なかぎりシンプルにします。必要以上に多くのストレージプールを作成しないでください。
* できるだけ多くのノードを含むストレージプールを作成します。各ストレージプールには 2 つ以上のノードを含める必要があります。ノードが不十分なストレージプールでは、ノードが使用できなくなった場合に原因 ILM バックログが発生する可能性があります。
* 重複する（ 1 つ以上の同じノードを含む）ストレージプールを作成または使用することは避けてください。ストレージプールが重複していると、オブジェクトデータの複数のコピーが同じノードに保存される可能性があります。




== レプリケートコピーに使用するストレージプールのガイドライン

* サイトごとに異なるストレージプールを作成します。次に、ルールごとに配置手順でサイト固有のストレージプールを 1 つ以上指定します。各サイトにストレージプールを使用すると、レプリケートされたオブジェクトコピーが想定どおりに配置されるようになります（たとえば、サイト障害から保護するために、各サイトのすべてのオブジェクトのコピーが 1 つずつ）。
* 拡張でサイトを追加する場合は、新しいサイト用の新しいストレージプールを作成します。次に、新しいサイトに格納するオブジェクトを制御するために ILM ルールを更新します。
* 通常は、デフォルトのストレージプール、すべてのストレージノード、またはデフォルトサイトであるすべてのサイトを含むストレージプールを使用しないでください。




== イレイジャーコーディングされたコピーに使用するストレージプールのガイドラインを次に示します

* イレイジャーコーディングデータ用にアーカイブノードを使用することはできません。
* ストレージプールに含まれるストレージノードとサイトの数によって、使用できるイレイジャーコーディングスキームが決まります。
* ストレージプールにサイトが 2 つしかない場合、そのストレージプールをイレイジャーコーディングに使用することはできません。2 つのサイトを含むストレージプールではイレイジャーコーディングスキームを使用できません。
* 通常は、デフォルトのストレージプール、すべてのストレージノード、またはデフォルトサイトを含むすべてのサイトのいずれかのイレイジャーコーディングプロファイル内のストレージプールを使用しないでください。
+

NOTE: グリッドにサイトが 1 つしかない場合、イレイジャーコーディングプロファイルに「すべてのストレージノード」ストレージプールまたは「すべてのサイト」デフォルトサイトを使用することはできません。これにより、 2 つ目のサイトが追加された場合にイレイジャーコーディングプロファイルが無効になるのを防ぐことができます。

* 高スループットが必要な場合、サイト間のネットワークレイテンシが 100 ミリ秒を超える状況では、複数のサイトを含むストレージプールを作成することは推奨されません。レイテンシが上昇すると TCP ネットワークのスループットが低下するため、 StorageGRID がオブジェクトフラグメントを作成、配置、読み出す速度は大幅に低下します。スループットの低下は、オブジェクトの取り込みと読み出しの達成可能な最大速度に影響する（ Strict または Balanced が取り込み動作として選択されている場合）か、 ILM キューのバックログが発生する可能性があります（ Dual Commit が取り込み動作として選択されている場合）。
* 可能であれば、選択するイレイジャーコーディングスキームに必要な最小数よりも多くのストレージノードをストレージプールに含めてください。たとえば、 6+3 のイレイジャーコーディングスキームを使用する場合は、 9 個以上のストレージノードが必要です。ただし、サイトごとに少なくとも 1 つのストレージノードを追加することを推奨します。
* ストレージノードはサイト間にできるだけ均等に分散します。たとえば、 6+3 のイレイジャーコーディングスキームをサポートするには、 3 つのサイトにそれぞれ 1 つ以上のストレージノードを含むストレージプールを設定します。




== アーカイブされたコピーに使用するストレージプールのガイドラインを次に示します

* ストレージノードとアーカイブノードの両方を含むストレージプールは作成できません。アーカイブされたコピーには、アーカイブノードのみを含むストレージプールが必要です。
* アーカイブノードが含まれたストレージプールを使用する場合は、ストレージノードが含まれたストレージプール上に、 1 つ以上のレプリケートコピーまたはイレイジャーコーディングコピーを保持する必要もあります。
* グローバルな S3 オブジェクトロック設定が有効になっていて準拠 ILM ルールを作成する場合は、アーカイブノードが含まれたストレージプールを使用できません。S3 オブジェクトロックを使用してオブジェクトを管理する手順を参照してください。
* アーカイブノードの Target Type が「 Cloud Tiering - Simple Storage Service （ S3 ）」の場合、そのアーカイブノードは自身のストレージプールに含まれている必要があります。を参照してください xref:../admin/index.adoc[StorageGRID の管理]。


.関連情報
* xref:what-replication-is.adoc[レプリケーションとは]
* xref:what-erasure-coding-is.adoc[イレイジャーコーディングとは]
* xref:what-erasure-coding-schemes-are.adoc[イレイジャーコーディングスキームとは]
* xref:using-multiple-storage-pools-for-cross-site-replication.adoc[複数のストレージプールを使用してサイト間レプリケーションを行う]

