---
permalink: ilm/using-last-access-time-in-ilm-rules.html 
sidebar: sidebar 
keywords: last access time, ilm rule reference time 
summary: 最終アクセス時間を ILM ルールの参照時間として使用できます。たとえば、過去 3 カ月間に表示されたオブジェクトをローカルストレージノードに残しておき、最近表示されていないオブジェクトをオフサイトの場所に移動することができます。特定の日付に最後にアクセスされたオブジェクトにのみ ILM ルールを適用する場合は、高度なフィルタとして最終アクセス時間を使用することもできます。 
---
= ILM ルールで最終アクセス時間を使用します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
最終アクセス時間を ILM ルールの参照時間として使用できます。たとえば、過去 3 カ月間に表示されたオブジェクトをローカルストレージノードに残しておき、最近表示されていないオブジェクトをオフサイトの場所に移動することができます。特定の日付に最後にアクセスされたオブジェクトにのみ ILM ルールを適用する場合は、高度なフィルタとして最終アクセス時間を使用することもできます。

ILM ルールで最終アクセス日時を使用する前に、次の考慮事項を確認してください。

* 参照時間として最終アクセス時間を使用する場合、オブジェクトの最終アクセス時間を変更しても ILM 評価はすぐには開始されない点に注意してください。オブジェクトの配置が評価され、バックグラウンド ILM がオブジェクトを評価したときに必要に応じてオブジェクトが移動されます。この処理には、オブジェクトがアクセスされてから 2 週間以上かかる場合があります。
+
最終アクセス時間に基づいて ILM ルールを作成する際には、このレイテンシを考慮し、短い期間（ 1 カ月未満）を使用する配置は避けてください。

* 高度なフィルタまたは参照時間として最終アクセス時間を使用する場合は、 S3 バケットに対して最終アクセス時間の更新を有効にしておく必要があります。Tenant Manager またはテナント管理 API を使用できます。
+

NOTE: 最終アクセス時間の更新は Swift コンテナでは常に有効ですが、 S3 バケットではデフォルトで無効になっています。

+

IMPORTANT: 最終アクセス時間の更新を有効にすると、特に小さなオブジェクトを含むシステムのパフォーマンスが低下する可能性があります。これは、オブジェクトが読み出されるたびに StorageGRID が新しいタイムスタンプでオブジェクトを更新する必要があるためです。



次の表に、バケット内のすべてのオブジェクトについて、さまざまなタイプの要求について最終アクセス時間が更新されるかどうかを示します。

[cols="1a,1a,1a"]
|===
| 要求のタイプ | 最終アクセス時間の更新が無効になったときに最終アクセス時間を更新するかどうか | 最終アクセス時間の更新が有効になったときに最終アクセス時間を更新するかどうか 


 a| 
オブジェクト、そのアクセス制御リスト、またはメタデータの読み出し要求
 a| 
いいえ
 a| 
はい。



 a| 
オブジェクトメタデータの更新要求
 a| 
はい。
 a| 
はい。



 a| 
バケット間でのオブジェクトのコピー要求
 a| 
* ソースコピーに対しては、「いいえ」と指定します
* デスティネーションコピーについては、はい

 a| 
* ソースコピーについては、はい
* デスティネーションコピーについては、はい




 a| 
マルチパートアップロードの完了要求
 a| 
はい、アセンブルされたオブジェクトの場合
 a| 
はい、アセンブルされたオブジェクトの場合

|===
.関連情報
* xref:../s3/index.adoc[S3 を使用する]
* xref:../tenant/index.adoc[テナントアカウントを使用する]

