---
permalink: ilm/what-cloud-storage-pool-is.html 
sidebar: sidebar 
keywords: what is a cloud storage pool 
summary: クラウドストレージプールでは、 ILM を使用して StorageGRID システムの外部にオブジェクトデータを移動できます。たとえば、 Amazon S3 Glacier 、 S3 Glacier Deep Archive 、 Microsoft Azure Blob Storage のアーカイブアクセス階層など、アクセス頻度の低いオブジェクトを低コストのクラウドストレージに移動できます。または、 StorageGRID オブジェクトのクラウドバックアップを保持して、ディザスタリカバリを強化することもできます。 
---
= クラウドストレージプールとは
:icons: font
:imagesdir: ../media/


[role="lead"]
クラウドストレージプールでは、 ILM を使用して StorageGRID システムの外部にオブジェクトデータを移動できます。たとえば、 Amazon S3 Glacier 、 S3 Glacier Deep Archive 、 Microsoft Azure Blob Storage のアーカイブアクセス階層など、アクセス頻度の低いオブジェクトを低コストのクラウドストレージに移動できます。または、 StorageGRID オブジェクトのクラウドバックアップを保持して、ディザスタリカバリを強化することもできます。

ILM から見た場合、クラウドストレージプールはストレージプールに似ています。どちらの場所にオブジェクトを格納する場合も、 ILM ルールの配置手順の作成時にプールを選択します。ただし、ストレージプールは StorageGRID システム内のストレージノードまたはアーカイブノードで構成されますが、クラウドストレージプールは外部のバケット（ S3 ）またはコンテナ（ Azure BLOB ストレージ）で構成されます。

次の表に、ストレージプールとクラウドストレージプールの比較と、類似点と相違点を示します。

[cols="1a,2a,2a"]
|===
|  | ストレージプール | クラウドストレージプール 


 a| 
作成方法
 a| 
Grid Manager で * ILM * > * ストレージプール * オプションを使用している。

ストレージプールを作成する前に、ストレージグレードをセットアップする必要があります。
 a| 
Grid Manager で * ILM * > * ストレージプール * オプションを使用している。

クラウドストレージプールを作成する前に、外部のバケットまたはコンテナをセットアップする必要があります。



 a| 
作成できるプール数
 a| 
無制限。
 a| 
最大 10 個。



 a| 
オブジェクトの格納先
 a| 
StorageGRID 内の 1 つ以上のストレージノードまたはアーカイブノード。
 a| 
StorageGRID システムの外部にある Amazon S3 バケットまたは Azure BLOB ストレージコンテナ。

クラウドストレージプールが Amazon S3 バケットの場合：

* 必要に応じて、 Amazon S3 Glacier や S3 Glacier Deep Archive などの低コストの長期保存用ストレージにオブジェクトを移行するようにバケットライフサイクルを設定できます。外部ストレージシステムが Glacier ストレージクラスと S3 POST Object restore API をサポートしている必要があります。
* AWS Commercial クラウド サービス （ C2S ）で使用するクラウドストレージプールを作成できます。 C2S は AWS Secret Region をサポートします。


クラウドストレージプールが Azure BLOB ストレージコンテナの場合、 StorageGRID はオブジェクトをアーカイブ層に移行します。

* 注：一般に、クラウドストレージプールに使用するコンテナには Azure Blob Storage のライフサイクル管理を設定しないでください。クラウドストレージプール内のオブジェクトに対する POST Object restore 処理が、設定されたライフサイクルの影響を受ける可能性があります。



 a| 
オブジェクトの配置を制御する要素
 a| 
アクティブな ILM ポリシーの ILM ルール。
 a| 
アクティブな ILM ポリシーの ILM ルール。



 a| 
使用されるデータ保護方法
 a| 
レプリケーションまたはイレイジャーコーディング。
 a| 
レプリケーション：



 a| 
各オブジェクトに許可されるコピー数
 a| 
複数。
 a| 
クラウドストレージプールに 1 つ、また必要に応じて StorageGRID に 1 つ以上のコピーを作成します。

* 注： * 1 つのオブジェクトを複数のクラウドストレージプールに一度に格納することはできません。



 a| 
利点は何ですか？
 a| 
オブジェクトにいつでもすばやくアクセスできる。
 a| 
低コストのストレージ。

|===