---
permalink: ilm/what-erasure-coding-schemes-are.html 
sidebar: sidebar 
keywords: erasure coding scheme 
summary: ILM ルールにイレイジャーコーディングプロファイルを設定する場合は、使用するストレージプールを構成するストレージノードとサイトの数に基づいて、使用可能なイレイジャーコーディングスキームを選択します。イレイジャーコーディングスキームは、各オブジェクト用に作成されるデータフラグメントとパリティフラグメントの数を制御します。 
---
= イレイジャーコーディングスキームとは
:icons: font
:imagesdir: ../media/


[role="lead"]
ILM ルールにイレイジャーコーディングプロファイルを設定する場合は、使用するストレージプールを構成するストレージノードとサイトの数に基づいて、使用可能なイレイジャーコーディングスキームを選択します。イレイジャーコーディングスキームは、各オブジェクト用に作成されるデータフラグメントとパリティフラグメントの数を制御します。

StorageGRID システムは、 Reed-Solomon イレイジャーコーディングアルゴリズムを使用します。このアルゴリズムは、オブジェクトを k 個のデータフラグメントに分割して、 m 個のパリティフラグメントを計算します。k + m = n 個のフラグメントが n 個のストレージノードに分散され、データ保護を提供します。失われたフラグメントまたは破損したフラグメントは、オブジェクトが保持できる最大 m 個です。k 個のフラグメントがオブジェクトの読み出しまたは修復に必要です。

イレイジャーコーディングプロファイルを設定する場合は、ストレージプールについて次のガイドラインに従ってください。

* ストレージプールには 3 つ以上のサイト、または 1 つのサイトだけが含まれている必要があります。
+

NOTE: ストレージプールにサイトが 2 つ含まれている場合、イレイジャーコーディングプロファイルは設定できません。

+
** <<Erasure-coding schemes for storage pools containing three or more sites,3 つ以上のサイトを含むストレージプールのイレイジャーコーディングスキーム>>
** <<Erasure-coding schemes for one-site storage pools,1 サイトのストレージプールのイレイジャーコーディングスキーム>>


* デフォルトのストレージプール、すべてのストレージノード、またはデフォルトサイトであるすべてのサイトを含むストレージプールは使用しないでください。
* ストレージプールには少なくとも _k + m_+1 ストレージノードを含める必要があります。
+
必要なストレージノードの最小数は、 _ k + m_. です。ただし、必要なストレージノードが一時的に使用できない場合に、少なくとも 1 つのストレージノードを追加することで、取り込みエラーや ILM バックログが発生するのを防ぐことができます。



イレイジャーコーディングスキームのストレージオーバーヘッドは、パリティフラグメントの数（ _m_） をデータフラグメントの数（ _k_ ）で割ることによって計算されます。ストレージオーバーヘッドを使用して、各イレイジャーコーディングオブジェクトに必要なディスクスペースを計算できます。

`_disk space_=_object size_+(_object size_*_storage overhead _)`

たとえば、 4+2 スキームを使用して 10MB のオブジェクト（ストレージオーバーヘッドが 50% ）を格納すると、そのオブジェクトが消費するグリッドストレージは 15MB です。6+3 のストレージオーバーヘッドを含む 6+2 スキームを使用して同じ 10MB のオブジェクトを格納すると、オブジェクトが消費するサイズは約 13.3 MB になります。

合計値が最も小さいイレイジャーコーディングスキーム（ _k + m_that ）をニーズに合わせて選択します。フラグメント数が少ないイレイジャーコーディングスキームは全体的に計算効率が高く、 1 つのオブジェクトに作成されて分散（または取得）されるフラグメント数が少なくて済むため、フラグメントサイズが大きいためパフォーマンスが向上し、ストレージの追加が必要になった場合に拡張時に必要なノード数が少なくて済みます。（ストレージ拡張の計画については、 StorageGRID の拡張手順を参照してください）。



== 3 つ以上のサイトを含むストレージプールのイレイジャーコーディングスキーム

次の表に、 3 つ以上のサイトを含むストレージプールについて、 StorageGRID で現在サポートされているイレイジャーコーディングスキームを示します。これらの方式はいずれもサイト障害からの保護を提供します。1 つのサイトが失われてもオブジェクトには引き続きアクセスできます。

サイト損失の保護を提供するイレイジャーコーディングスキームの場合、ストレージプールに推奨されるストレージノードの数は各サイトに少なくとも 3 つのストレージノードが必要なため _ k + m_+1 を超えています。

[cols="1a,1a,1a,1a,1a,1a"]
|===
| イレイジャーコーディングスキーム（ _k + m_） | サイトの最小数 | 各サイトで推奨されるストレージノードの数 | 推奨されるストレージノードの総数 | サイト障害からの保護 | ストレージオーバーヘッド 


 a| 
4+2
 a| 
3.
 a| 
3.
 a| 
9.
 a| 
はい。
 a| 
50%



 a| 
6+2
 a| 
4.
 a| 
3.
 a| 
12.
 a| 
はい。
 a| 
33%



 a| 
8+2
 a| 
5.
 a| 
3.
 a| 
15
 a| 
はい。
 a| 
25%



 a| 
6 + 3
 a| 
3.
 a| 
4.
 a| 
12.
 a| 
はい。
 a| 
50%



 a| 
9 + 3
 a| 
4.
 a| 
4.
 a| 
16
 a| 
はい。
 a| 
33%



 a| 
2+1
 a| 
3.
 a| 
3.
 a| 
9.
 a| 
はい。
 a| 
50%



 a| 
4+1
 a| 
5.
 a| 
3.
 a| 
15
 a| 
はい。
 a| 
25%



 a| 
6+1
 a| 
7.
 a| 
3.
 a| 
21
 a| 
はい。
 a| 
17%



 a| 
7+5
 a| 
3.
 a| 
5.
 a| 
15
 a| 
はい。
 a| 
71%

|===

NOTE: StorageGRID では、サイトごとに少なくとも 3 つのストレージノードが必要です。7+5 スキームを使用するには、各サイトに少なくとも 4 つのストレージノードが必要。サイトごとに 5 つのストレージノードを使用することを推奨します。

サイト保護を提供するイレイジャーコーディングスキームを選択する場合は、次の要素の相対的な重要性を調整します。

* * フラグメント数 * ：フラグメントの総数が少ないほど、一般にパフォーマンスと拡張の柔軟性が向上します。
* * フォールトトレランス * ：パリティセグメントの数を増やすことでフォールトトレランスが向上します（ _m_の 値が大きい場合）。
* * ネットワーク・トラフィック *: 障害から回復する場合、フラグメント数の多いスキーム（つまり、 _k + m_） を使用すると、より多くのネットワーク・トラフィックが生成されます。
* * ストレージ・オーバーヘッド * ：オーバーヘッドの大きいスキームでは、オブジェクトごとにより多くのストレージ・スペースが必要です。


たとえば、 4+2 と 6+3 のどちらかのスキーム（どちらも 50% のストレージオーバーヘッドがある）を選ぶ場合、フォールトトレランスをさらに高める必要がある場合は 6+3 のスキームを選択します。ネットワークリソースが制限されている場合は、 4+2 のスキームを選択します。他のすべての要素が等しい場合は、フラグメントの合計数が少ないため、 4+2 を選択します。


NOTE: 使用するスキームが不明な場合は、 4+2 または 6+3 を選択するか、テクニカルサポートにお問い合わせください。



== 1 サイトのストレージプールのイレイジャーコーディングスキーム

1 サイトのストレージプールでは、サイトに十分な数のストレージノードがある場合、 3 つ以上のサイト用に定義されたすべてのイレイジャーコーディングスキームがサポートされます。

必要なストレージノードの最小数は _k + m_1 ですが、 _k + m_+1 ストレージノードを含むストレージプールを推奨します。たとえば、 2+1 イレイジャーコーディングスキームには少なくとも 3 つのストレージノードからなるストレージプールが必要ですが、推奨されるストレージノード数は 4 つです。

[cols="1a,1a,1a,1a"]
|===
| イレイジャーコーディングスキーム（ _k + m_） | ストレージノードの最小数 | 推奨されるストレージノードの数 | ストレージオーバーヘッド 


 a| 
4+2
 a| 
6.
 a| 
7.
 a| 
50%



 a| 
6+2
 a| 
8.
 a| 
9.
 a| 
33%



 a| 
8+2
 a| 
10.
 a| 
11.
 a| 
25%



 a| 
6 + 3
 a| 
9.
 a| 
10.
 a| 
50%



 a| 
9 + 3
 a| 
12.
 a| 
13
 a| 
33%



 a| 
2+1
 a| 
3.
 a| 
4.
 a| 
50%



 a| 
4+1
 a| 
5.
 a| 
6.
 a| 
25%



 a| 
6+1
 a| 
7.
 a| 
8.
 a| 
17%



 a| 
7+5
 a| 
12.
 a| 
13
 a| 
71%

|===
xref:../expand/index.adoc[グリッドを展開します]
