---
permalink: fabricpool/creating-ha-group-for-fabricpool.html 
sidebar: sidebar 
keywords: fabricPool, high availability group, HA group, create, creating, virtual IP, VIP, preferred master, backup interface 
summary: FabricPool で使用するように StorageGRID を設定する場合は、必要に応じて 1 つ以上のハイアベイラビリティ（ HA\ ）グループを作成できます。HA グループは、管理ノード、ゲートウェイノード、またはその両方の 1 つ以上のネットワークインターフェイスで構成されます。 
---
= FabricPool のハイアベイラビリティ（ HA ）グループを作成します
:icons: font
:imagesdir: ../media/


[role="lead"]
FabricPool で使用するように StorageGRID を設定する場合は、必要に応じて 1 つ以上のハイアベイラビリティ（ HA ）グループを作成できます。HA グループは、管理ノード、ゲートウェイノード、またはその両方の 1 つ以上のネットワークインターフェイスで構成されます。

.必要なもの
* を使用して Grid Manager にサインインします xref:../admin/web-browser-requirements.adoc[サポートされている Web ブラウザ]。
* Root Access 権限が必要です。
* VLAN を使用する場合は、 VLAN インターフェイスを作成しておきます。を参照してください xref:../admin/configure-vlan-interfaces.adoc[VLAN インターフェイスを設定します]。


各 HA グループは、仮想 IP アドレス（ VIP ）を使用して、関連付けられたノード上の共有サービスへの可用性の高いアクセスを提供します。

このタスクの詳細については、を参照してください xref:../admin/managing-high-availability-groups.adoc[ハイアベイラビリティグループを管理します]。

.手順
. 構成 * > * ネットワーク * > * ハイアベイラビリティグループ * を選択します。
. 「 * Create * 」を選択します。
. 一意の名前を入力し、必要に応じて概要 を入力します。
. この HA グループに追加するインターフェイスを 1 つ以上選択してください。
+
列ヘッダーを使用して行をソートするか、検索キーワードを入力してインターフェイスをより迅速に検索します。

. この HA グループのプライマリインターフェイスとバックアップインターフェイスを特定します。
+
行をドラッグアンドドロップして、 * 優先順位 * 列の値を変更します。

+
リストの最初のインターフェイスはプライマリインターフェイスです。プライマリインターフェイスは、障害が発生しないかぎり、アクティブインターフェイスです。

+
HA グループに複数のインターフェイスが含まれている場合にアクティブインターフェイスで障害が発生すると、 VIP アドレスは優先順位に従って最初のバックアップインターフェイスに移動します。そのインターフェイスに障害が発生すると、 VIP アドレスは次のバックアップインターフェイスに移動します。障害が解決されると、 VIP アドレスは利用可能な最優先インターフェイスに戻ります。

. VIP サブネットを CIDR 表記で指定します。 IPv4 アドレスのあとにスラッシュとサブネットの長さ（ 0 ～ 32 ）を付けます。
+
ネットワークアドレスにホストビットを設定しないでください。たとえば '192.160.0/22' のようになります

. 必要に応じて、 StorageGRID へのアクセスに使用する ONTAP IP アドレスが StorageGRID VIP アドレスと同じサブネット上にない場合は、 StorageGRID VIP ローカルゲートウェイ IP アドレスを入力します。ローカルゲートウェイの IP アドレスは VIP サブネット内にある必要があります。
. HA グループの仮想 IP アドレスを 1 つ以上入力します。IP アドレスは 10 個まで追加できます。VIP はすべて VIP サブネット内に設定する必要があります。
+
IPv4 アドレスを少なくとも 1 つ指定する必要があります。必要に応じて、追加の IPv4 アドレスと IPv6 アドレスを指定できます。

. HA グループの作成 * を選択し、完了 * を選択します。

