---
permalink: fabricpool/using-storagegrid-ilm-with-fabricpool-data.html 
sidebar: sidebar 
keywords: FabricPool, requirements, ILM, information lifecycle management, ILM rule, ILM rules, ILM policy, erasure-coding, replication, cloud storage pool, glacier 
summary: FabricPool を使用して StorageGRID にデータを階層化する場合は、 StorageGRID 情報ライフサイクル管理（ ILM ）ルールおよび FabricPool データを管理するための ILM ポリシーの作成に関する要件を理解しておく必要があります。FabricPool データに適用される ILM ルールがシステム停止を伴わないようにする必要があります。 
---
= StorageGRID の情報ライフサイクル管理と FabricPool のデータを使用できます
:icons: font
:imagesdir: ../media/


[role="lead"]
FabricPool を使用して StorageGRID にデータを階層化する場合は、 StorageGRID 情報ライフサイクル管理（ ILM ）ルールの作成要件と、 FabricPool データを管理するための ILM ポリシーの作成要件を理解しておく必要があります。FabricPool データに適用される ILM ルールがシステム停止を伴わないようにする必要があります。


IMPORTANT: FabricPool は、 StorageGRID の ILM ルールやポリシーを認識しません。StorageGRID の ILM ポリシーの設定ミスが原因でデータが失われる可能性があります。を参照してください xref:../ilm/index.adoc[ILM を使用してオブジェクトを管理する] を参照してください。

以下のガイドラインを確認し、 ILM ルールと ILM ポリシーが FabricPool データとビジネス要件に適していることを確認してください。すでに StorageGRID ILM を使用している場合は、次のガイドラインに従って、アクティブな ILM ポリシーの更新が必要になることがあります。

* レプリケーションルールとイレイジャーコーディングルールを任意に組み合わせて、クラウド階層のデータを保護できます。
+
コスト効率に優れたデータ保護を実現するために、サイト内で 2+1 のイレイジャーコーディングを使用することを推奨します。イレイジャーコーディングは CPU 使用率は高くなりますが、レプリケーションよりもストレージ容量が大幅に少なくなります。4+1 スキームと 6+1 スキームは 2+1 スキームよりも容量が少ないただし、グリッドの拡張時にストレージノードを追加する必要がある場合、 4+1 スキームと 6+1 スキームの柔軟性は低くなります。詳細については、を参照してください xref:../expand/adding-storage-capacity-for-erasure-coded-objects.adoc[イレイジャーコーディングオブジェクトのストレージ容量を追加します]。

* FabricPool データに適用するルールは、イレイジャーコーディングを使用するか、少なくとも 2 つのレプリケートコピーを作成する必要があります。
+

IMPORTANT: ある期間にレプリケートコピーを 1 つしか作成しない ILM ルールには、データが永続的に失われるリスクがあります。オブジェクトのレプリケートコピーが 1 つしかない場合、ストレージノードに障害が発生したり、重大なエラーが発生すると、そのオブジェクトは失われます。また、アップグレードなどのメンテナンス作業中は、オブジェクトへのアクセスが一時的に失われます。

* FabricPool クラウド階層のデータが期限切れになる、または削除される ILM ルールは使用しないでください。StorageGRID ILM によって FabricPool オブジェクトが削除されないように、各 ILM ルールの保持期間を「 forever 」に設定します。
* FabricPool クラウド階層のデータをバケットから別の場所に移動するルールは作成しないでください。ILM ルールを使用して、アーカイブノードを使用して FabricPool データをテープにアーカイブしたり、クラウドストレージプールを使用して FabricPool データを別のオブジェクトストアに移動したりすることはできません。
+

NOTE: クラウドストレージプールターゲットからオブジェクトを読み出すレイテンシが増加しているため、 FabricPool でクラウドストレージプールを使用することはサポートされていません。

* ONTAP 9.8 以降では、オプションでオブジェクトタグを作成して階層化データを分類およびソートし、管理を容易にすることができます。たとえば、タグを設定できるのは、 StorageGRID に接続されている FabricPool ボリュームのみです。次に、 StorageGRID で ILM ルールを作成する際に、高度なフィルタ「オブジェクトタグ」を使用してこのデータを選択し、配置します。




== FabricPool データ用の ILM ポリシーの例

以下に記載するシンプルなポリシーの例をベースに、独自の ILM ルールとポリシーを作成します。

この例では、コロラド州デンバーの 1 つのデータセンターに 4 つのストレージノードがある StorageGRID システムの ILM ルールと ILM ポリシーを設計していることを前提としています。この例の FabricPool データでは、「 fabricpool-bucket 」という名前のバケットが使用されています。


CAUTION: 以下の ILM ルールとポリシーは一例にすぎません。ILM ルールを設定する方法は多数あります。新しいポリシーをアクティブ化する前に、ドラフトポリシーをシミュレートして、コンテンツの損失を防ぐためにドラフトポリシーが想定どおりに機能することを確認してください。詳細については、を参照してください xref:../ilm/index.adoc[ILM を使用してオブジェクトを管理する]。

.手順
. *Den という名前のストレージプールを作成します。Denver サイトを選択します。
. 2 plus 1 * という名前のイレイジャーコーディングプロファイルを作成します。2+1 イレイジャーコーディングスキームと *Den * ストレージプールを選択します。
. fabricpool-bucket 内のデータにのみ適用される ILM ルールを作成します次のルール例では、イレイジャーコーディングコピーを作成します。
+
[cols="1a,2a"]
|===
| ルール定義 | 値の例 


 a| 
ルール名
 a| 
FabricPool データ用の 2+1 のイレイジャーコーディング



 a| 
バケット名
 a| 
fabricpool-bucket

FabricPool テナントアカウントでフィルタリングすることもできます。



 a| 
高度なフィルタリング
 a| 
オブジェクトサイズ（ MB ）が 0.2 MB を超えています。

* 注： * FabricPool は 4MB のオブジェクトのみを書き込みますが、このルールではイレイジャーコーディングを使用するため、オブジェクトサイズフィルタを追加する必要があります。



 a| 
参照時間
 a| 
取り込み時間



 a| 
配置
 a| 
0 日目のストアから永遠に



 a| 
を入力します
 a| 
イレイジャーコーディング



 a| 
場所
 a| 
デン (2 プラス 1)



 a| 
取り込み動作
 a| 
中間（ Balanced ）

|===
. 最初のルールに一致しないオブジェクトのレプリケートコピーを 2 つ作成する ILM ルールを作成します。基本フィルタ（テナントアカウントまたはバケット名）や高度なフィルタは選択しないでください。
+
[cols="1a,2a"]
|===
| ルール定義 | 値の例 


 a| 
ルール名
 a| 
2 つのレプリケートコピー



 a| 
バケット名
 a| 
_ なし _



 a| 
高度なフィルタリング
 a| 
_ なし _



 a| 
参照時間
 a| 
取り込み時間



 a| 
配置
 a| 
0 日目のストアから永遠に



 a| 
を入力します
 a| 
レプリケート



 a| 
場所
 a| 
デン



 a| 
コピー
 a| 
2.



 a| 
取り込み動作
 a| 
中間（ Balanced ）

|===
. ドラフトの ILM ポリシーを作成して 2 つのルールを選択レプリケーションルールではフィルタを使用しないため、ポリシーのデフォルト（最後の）ルールを使用できます。
. テストオブジェクトをグリッドに取り込みます。
. ポリシーをテストオブジェクトでシミュレートして動作を確認します。
. ポリシーをアクティブ化する。


このポリシーをアクティブ化すると、 StorageGRID はオブジェクトデータを次のように配置します。

* 「 fabricpool-bucket 」内の FabricPool から階層化されたデータは、 2+1 イレイジャーコーディングスキームを使用してイレイジャーコーディングされます。2 つのデータフラグメントと 1 つのパリティフラグメントが 3 つの異なるストレージノードに配置されます。
* 他のすべてのバケット内のオブジェクトがレプリケートされます。2 つのコピーが作成され、 2 つの異なるストレージノードに配置されます。
* イレイジャーコーディングコピーとレプリケートコピーは、 S3 クライアントによって削除されるまで StorageGRID に保持されます。StorageGRID ILM によってこれらの項目が削除されることはありません。

